### ISSUE TITLE
Saving recompiled binaries

### ISSUE THREAD

**Issue by alsldlflglhljlk** [ptitSeb/box64#1000]
As far as I know (correct me if I'm wrong), Box86/64 takes the target binary and recompiles it to the target architecture (armhf/64). Is it possible to save the recompiled binary to a file?

This would be useful for debugging purposes and would improve runtime speed.

**Comment by ptitSeb** [comment]
It's not possible for now.
1. Only used code is compiled, it's not a static recompilation of the whole binary/libs (it's a JIT)
2. Relocation are tricky and need to be taken into account when doing save

There might be an AOT compiler at some point, but not in the immadiate (less immediate) future.

**Comment by alsldlflglhljlk** [comment]
Good to know, though kind of disappointing :( I'll close this issue for now...

**Comment by ptitSeb** [comment]
I think it would make more sense to have this as a Discussion instead of an Issue.
