### ISSUE TITLE
Unsupported Syscall 0x50h (80)

### ISSUE THREAD

**Issue by AmateurECE** [ptitSeb/box64#1006]
Hey, there!

While attempting to run TeamViewer QuickSupport under box64, I get an unsupported syscall:

```
Running on Icestorm-M1-Pro Firestorm-M1-Pro with 10 Cores
Params database has 21 entries
Box64 v0.2.2 nogit built on Oct  2 2023 12:09:22
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 76 Env var
Looking for ./teamviewerqs/teamviewer
Rename process to "teamviewer"
Error: Unsupported Syscall 0x50h (80)
```

Obviously, I am running on an M1 Pro and I have enabled the `M1` CMake option, in case that's relevant here. Thanks for your help!

**Comment by ptitSeb** [comment]
Your box64 is very old. This syscall is supported with current version, so you should update your box64 version.

(also, note that statically linked binary, i.e. the one that doesn't use libc.so and friends, are not really supported on box64)
