### ISSUE TITLE
Emuelec SDL 2.28.4 Shovelknight segfault SIGSEGV @0x7fa997ac44 (???(/usr/lib/libc.so.6+0x7fa997ac44)) 

### ISSUE THREAD

**Issue by Kelvfimer** [ptitSeb/box64#1011]
Hello

I'm member of the EMUELEC testing community and we are upgrading the system. 

I notice when upgrading from SDL2 2.24.2 to SDL 2.28.4 in any commit (I tested even in the latest one available this morning [c904a9af1ca653443988ee698dec4670d4b32f88](https://github.com/ptitSeb/box64/commit/c904a9af1ca653443988ee698dec4670d4b32f88) Shovel knight crashes . If I keep SDL2 2.24.2 it works.

The platform used is odroid n2+ . BOX64 has been built using Ubuntu 22.04 WSL2 gcc 12.1, cmake 3.27.5 Emuelec Toolchain for amlogic-ng

The settings set up for running the game is the following sh

#!/bin/bash

cd /storage/roms/ports/shovelknight/64

export LIBGL_NOBANNER=1
export LIBGL_ES=2
export LIBGL_GL=21
export LIBGL_FB=4
export BOX64_LOG=1
export BOX64_LD_LIBRARY_PATH=/emuelec/bin/box64/lib/
export BOX64_DYNAREC=1
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/emuelec/bin/box64/lib/
fbfix
/emuelec/bin/box64/box64 ShovelKnight

and the crash dump is the attached file
[emuelec.log](https://github.com/ptitSeb/box64/files/12822262/emuelec.log)

[?25lGL Version: 2.10
7824|SIGSEGV @0x7fa997ac44 (???(/usr/lib/libc.so.6+0x7fa997ac44)) (x64pc=0x90073/???:"???", rsp=0x101fff908, stack=0x101800000:0x102000000 own=(nil) fp=0x65073aa0), for accessing 0x1e90 (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000000101fff910 RSP-0x18:0x0000000101ff7830 RSP-0x10:0x0000000064746a80 RSP-0x08:0x0000000000000005
RSP+0x00:0x00000001028d5bcf RSP+0x08:0x0000000102b07602 RSP+0x10:0x0000000102b07601 RSP+0x18:0x0000000102b07600
RAX:0x000000000000084e RCX:0x0000000102b07607 RDX:0x0000000102b07609 RBX:0x00000000650742ee 
RSP:0x0000000101fff908 RBP:0x0000000065073aa0 RSI:0x0000000102b07606 RDI:0x00000001028f713e 
 R8:0x0000000102b075fd  R9:0x0000000000002000 R10:0x0000000000e99d00 R11:0x00000000a1f17f00 
R12:0x0000000102b07060 R13:0x0000000102b07604 R14:0x0000000102b07603 R15:0x0000000102b07605 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053 
/emuelec/bin/shovelknight.sh: line 14:  7824 Segmentation fault      /emuelec/bin/box64/box64 ShovelKnight

Please can you help us?

I can provide a custom image to debug. 

thx
KR

**Comment by ptitSeb** [comment]
I suppose ShovelKnight use some functions from SDL 2.28 that is not wrapped. Is there some mention of a missing wrapper of some `SDL_xxxx` function before the crash?

**Comment by Kelvfimer** [comment]
done :) thx for the prompt answer

here you are the new log file
[emuelec.log](https://github.com/ptitSeb/box64/files/12822624/emuelec.log)

let me know if you need more info.

**Comment by ptitSeb** [comment]
Ok thanks. Strange, it's a `glXGetProcAddress` call that crashes. That's odd. Does other OpenGL games run with the new SDL2?

Also, can you run with `BOX64_DLSYM_ERROR=1` so we'll see what kind of gl function its getting the address of.

**Comment by Kelvfimer** [comment]
[emuelec.log](https://github.com/ptitSeb/box64/files/12822845/emuelec.log)

This is the new log. 

@ptitSeb  To be frank yes there is other game Tortugas ninja that is crashing with this call stack 

that is similar to yours 

    0x5589e6e9d8 - mono :
        0x5589e6ece4 - mono :
        0x5589e26b18 - mono :
        0x5589defa08 - mono :
        0x7fb05c9670 - linux-vdso.so.1 : kernel_rt_sigreturn
        0x7fb00bac44 - /usr/lib/libc.so.6 :
        0x7fb00787f4 - /usr/lib/libc.so.6 : gsignal
        0x7fa5fd43e8 - /usr/lib/libSDL2-2.0.so.0 :
        0x7fb05c9670 - linux-vdso.so.1 : kernel_rt_sigreturn
        0x7f95dcdd4c - Unknown

so it coudl be that the issue is pure SDL2 . Let me know which function is and maybe we can address it to SDL2 team. 

thx for helping me in this one.

**Comment by ptitSeb** [comment]
Mmm, I don't see the detail I'm supposed to see. Strange. Anyway, does this SDL2 have been built with OpenGL support?

**Comment by Kelvfimer** [comment]
Sure I think so

PKG_CMAKE_OPTS_HOST="-DSDL_MALI=OFF -DSDL_KMSDRM=OFF"

PKG_CMAKE_OPTS_TARGET="-DSDL_STATIC=OFF \
                       -DSDL_LIBC=ON \
                       -DSDL_GCC_ATOMICS=ON \
                       -DSDL_ALTIVEC=OFF \
                       -DSDL_OSS=OFF \
                       -DSDL_ALSA=ON \
                       -DSDL_ALSA_SHARED=ON \
                       -DSDL_JACK=OFF \
                       -DSDL_JACK_SHARED=OFF \
                       -DSDL_ESD=OFF \
                       -DSDL_ESD_SHARED=OFF \
                       -DSDL_ARTS=OFF \
                       -DSDL_ARTS_SHARED=OFF \
                       -DSDL_NAS=OFF \
                       -DSDL_NAS_SHARED=OFF \
                       -DSDL_LIBSAMPLERATE=OFF \
                       -DSDL_LIBSAMPLERATE_SHARED=OFF \
                       -DSDL_SNDIO=OFF \
                       -DSDL_DISKAUDIO=OFF \
                       -DSDL_DUMMYAUDIO=OFF \
                       -DSDL_DUMMYVIDEO=OFF \
                       -DSDL_WAYLAND=OFF \
                       -DSDL_WAYLAND_QT_TOUCH=ON \
                       -DSDL_WAYLAND_SHARED=OFF \
                       -DSDL_COCOA=OFF \
                       -DSDL_DIRECTFB=OFF \
                       -DSDL_VIVANTE=OFF \
                       -DSDL_DIRECTFB_SHARED=OFF \
                       -DSDL_FUSIONSOUND=OFF \
                       -DSDL_FUSIONSOUND_SHARED=OFF \
                       -DSDL_PTHREADS=ON \
                       -DSDL_PTHREADS_SEM=ON \
                       -DSDL_DIRECTX=OFF \
                       -DSDL_CLOCK_GETTIME=OFF \
                       -DSDL_RPATH=OFF \
                       -DSDL_RENDER_D3D=OFF \
                       -DSDL_X11=OFF \
                       -DSDL_OPENGLES=ON \
                       -DSDL_VULKAN=OFF \
                       -DSDL_PULSEAUDIO=ON \
                       -DSDL_HIDAPI_JOYSTICK=OFF"

case "${DEVICE}" in
  'Amlogic-ng'|'Amlogic-old')  # We should've used PROJECT=Amlogic-ce logically, but using these two device names here saves a comparasion (only device needs to be compared)
    PKG_PATCH_DIRS="Amlogic"
    PKG_CMAKE_OPTS_TARGET+=" -DSDL_MALI=ON -DSDL_KMSDRM=OFF"

**Comment by Kelvfimer** [comment]
@ptitSeb added this flag -DSDL_OPENGL=ON \ and same behaviour

**Comment by ptitSeb** [comment]
That still seems suspicious. Can you check `ldd /PATH/TO/libSDL2-2.0.so.0` to see when libs are linked (is there libGLES2 hard linked there for example, that would be bad).

**Comment by Kelvfimer** [comment]
@ptitSeb 

This is the output

EMUELEC:~ # ldd /usr/lib/libSDL2-2.0.so.0
ldd: warning: you do not have execution permission for `/usr/lib/libSDL2-2.0.so.0'
        linux-vdso.so.1 => linux-vdso.so.1 (0x0000007f8b531000)
        libm.so.6 => /usr/lib/libm.so.6 (0x0000007f8b2f0000)
        libasound.so.2 => /usr/lib/libasound.so.2 (0x0000007f8b1e0000)
        libc.so.6 => /usr/lib/libc.so.6 (0x0000007f8b050000)
        /usr/lib/ld-linux-aarch64.so.1 => /usr/lib/ld-linux-aarch64.so.1 (0x0000007f8b4f4000)

I wait for you

**Comment by Kelvfimer** [comment]
I was troubkeshooting SDL2 I found the failing commit

https://github.com/libsdl-org/SDL/issues/8363#issuecomment-1751547935

It is related to them.

**Comment by ptitSeb** [comment]
Oh, ok. interesting. To Be Continued... :)

**Comment by Kelvfimer** [comment]
Yah let's see :)

**Comment by Kelvfimer** [comment]
Thx for ur support @ptitSeb I'm closing this one as I did a patch in Sdl2 and it's super clear is an SDL2 issue. But I found a another one due that I need to check if it's Box64 or SDL2.

Kind regards!!
