### ISSUE TITLE
[32BITS] DA opcodes unimplemented in dynarec

### ISSUE THREAD

**Issue by AndreRH** [ptitSeb/box64#1012]
Hi,

Found with Project Hangover running VARA.exe.

0024:err:box64dynarec:dynarec64_000 00000000734902C8: Dynarec stopped because of 32bits Opcode DA 4D 0C 89 45 0C DA 75 0C EB CE 55 8B EC 8B
0024:err:box64dynarec:dynarec64_000 0000000073490310: Dynarec stopped because of 32bits Opcode DA 4D 0C 89 45 0C DA 75 0C EB CD 55 8B EC 8B
0024:err:box64dynarec:dynarec64_000 00000000734901BD: Dynarec stopped because of 32bits Opcode DA 75 0C 0F BF 00 89 45 0C DA 45 0C EB CE 55
0024:err:box64dynarec:dynarec64_000 0000000073490204: Dynarec stopped because of 32bits Opcode DA 75 0C 0F BF 40 04 89 45 0C DA 45 0C EB CD
0024:err:box64dynarec:dynarec64_000 000000007349038C: Dynarec stopped because of 32bits Opcode DA 75 0C EB D7 55 8B EC D9 45 0C 51 D9 1C 24
0024:err:box64dynarec:dynarec64_000 0000000073490351: Dynarec stopped because of 32bits Opcode DA 75 0C EB D7 55 8B EC 8B 45 08 F6 40 10 01

**Comment by ptitSeb** [comment]
Ok, I have added all the DA opcode to arm64 dynarec.

**Comment by AndreRH** [comment]
Thanks, that part works, just Vara in wow64 Mode (hangover) doesn't yet :(
