### ISSUE TITLE
Cannot dlopen d3dadapter9

### ISSUE THREAD

**Issue by Pipetto-crypto** [ptitSeb/box64#1016]
When I was trying to use Gallium Nine, I encountered a very strange issue. It is very easy to trigger, at least on my part:

Load native arm64 d3dadapter9.so through the use of D3D_MODULE_PATH

Using BOX64_DUMP=1 and BOX64_DLSYM_ERROR=1, it seems to fail like this:

Call to dlopen("/data/data/com.termux/files/usr/glibc/lib/d3dadapter9.so"/0x1edac0, 102)

Trying to Get "/data/data/com.termux/files/usr/glibc/lib/d3dadapter9.so" to maplib

Trying to add "/data/data/com.termux/files/usr/glibc/lib/d3dadapter9.so" to maplib

Trying to load "/data/data/com.termux/files/usr/glibc/lib/d3dadapter9.so"

Simplified name is "d3dadapter9.so"

Faillure to create lib => fail

Warning: Cannot dlopen("/data/data/com.termux/files/usr/glibc/lib/d3dadapter9.so")

I had tried a few months ago from a prooted environment and it failed as well, even when not using the D3D_MODULE_PATH

**Comment by ptitSeb** [comment]
Do you have the native version of d3dadapter9 on your system? This libs can only be loaded as native, and is a bit tricky to build and load.

**Comment by Pipetto-crypto** [comment]
Yes, I have compiled it myself from mesa following the instructions on the Gallium Nine mesa page.

**Comment by ptitSeb** [comment]
Look at ` wrappedlibdl.c` lines 102-106. https://github.com/ptitSeb/box64/blob/main/src/wrapped/wrappedlibdl.c#L102

You see that the detection of the d3dadapter is very basic, but should work if you leave the default system (so don't set ` D3D_MODULE_PATH`). And make sure the actual ` d3dadapter9.so.1`  is accessible for `dlopen(...)` (so should be in the ` LD_LIBRARY_PATH` or regular system libs path)

**Comment by Pipetto-crypto** [comment]
Thx, I will close this
