### ISSUE TITLE
Support musl libc

### ISSUE THREAD

**Issue by gamecss** [ptitSeb/box64#1027]
I've done something [here](https://github.com/gamecss/box64/tree/musl)
Seem able to compile on x86_64 and aarch64 alpine edge. Now I defining `box_malloc` as `malloc` in `src/include/debug.h`, but it stucks at first `box_malloc` now.
I'm a complete noob in C language..... I really need some suggestions :(
I have tried in defining something like `box_malloc` as `__libc_malloc`. With some hack, I'm able to link `__libc_*` without `__libc_realloc` then it stucks at `box_realloc'.

**Comment by ptitSeb** [comment]
You need to use the ANDROID code path for everything malloc related.

**Comment by gamecss** [comment]
Thanks! now it don't stucks at `box_malloc` any more, but I encountered another problem, seem`src/box64context.c:initAllHelpers` isn't called, so no `init_pthread_helper` and `pthread_key_create` called, then with a `pthread_getspecific` call, I get a SIGSEGV. However, I cannot search any refer to `initAllHelpers`. What should I do?

**Comment by paulwratt** [comment]
@gamecss you only get notifications for _posting_ not _editing_

> ~~However, I cannot search any refer to `initAllHelpers`. What should I do?~~ Sorry. I missed collapsed content.
I moved initAllHelpers(context); below init_custommem_helper(context); to create pthread key before NewLibrarian. Is that ok?

**Comment by gamecss** [comment]
@ptitSeb Hello, developer! 😉 Is that ok?

**Comment by paulwratt** [comment]
@gamecss while you are waiting for a reply, you might want to re-read my post (sorry) i edited it :)

**Comment by paulwratt** [comment]
@gamecss I just read through the [diff of your commits](https://github.com/ptitSeb/box64/compare/main...gamecss:box64:musl), and mostly it seems like you are on the right track, except in **src/libtools/signals.c line 16** - that does not look right, and neither does line 1348

**Comment by gamecss** [comment]
oops, they're typos
Should be `#if !defined(ANDROID) && !defined(MUSL)`

**Comment by paulwratt** [comment]
@gamecss  overall I think you need to cleanup:
`#if !defined(MUSL) && !defined(MUSL)`
and change the use of:
 `#if !defined(ANDROID) && !defined(MUSL)`
to 
 `#ifndef (ANDROID || MUSL)`

_AND_ remember you are dealing with a _library change_ not and _OS change_ , so you probably shoud _not_ be adding `ifndef MUSL` and `ifdef MUSL` at _exactly_ the same places that the `ANDROID` path is

**Comment by paulwratt** [comment]
@gamecss does Musl really not have / use `_pthread_unwind` ? PThread is a seperate library, so it should be the same, and where these are unset (at lines 66 & 84 in src/libtools/threads.c) they are Kernel calls if I am not mistaken.

**Comment by gamecss** [comment]
🤔 Seem functions like `pthread_unwind_next` implemented only in glibc

**Comment by ptitSeb** [comment]
ok, it really depend what you want to do:
If you want to run glibc x86_64 binary on musl aarch64, you need to code wrappers for missing glibc funciton in musl, because x86_64 program will use them.
If you want to run musl x86_64 program on musl aarch64, you can `#ifdef` out the missing functions (and you might need to add a couple of musl-exclusive ones).

Also, note that I have just changed a bit the "pthread cancel" handling. If you want to use glibc program, the current new method should work plug'n play, becasue it only use posix function now to emulated the glibc mecanism. If you want to run musl x86_64 program, you might have to create new wrapper to handle `pthread_cleanup_push` and `pthread_cleanup_pop`, as I assume those are actual function on musl and not macro like in glibc (that uses `pthread_register_cancel`, `pthread_unregister_cancel` and `pthread_unwind_next`).

**Comment by gamecss** [comment]
That's a weird thing.... In `library_t *NewLibrary`, through `lib->type = LIB_UNNKNOW`, still trigger SIGSEGV when trying print it as `%s`

**Comment by ptitSeb** [comment]
> That's a weird thing.... In `library_t *NewLibrary`, through `lib->type = LIB_UNNKNOW`, still trigger SIGSEGV when trying print it as `%s`

I don't undersand what you are trying to do. `LIB_UNKNOWN` is an integer, it should not be printed as %s (or `lib->type` in fact), or you'll sure get a SEGFAULT there.

**Comment by gamecss** [comment]
oops sorry

**Comment by gamecss** [comment]
Thanks for your help! but I still have a little questions.
> I moved `initAllHelpers(context);` below `init_custommem_helper(context);` to create pthread key before `NewLibrarian`.

Will this cause some problem?
> .... as I assume those are actual function on musl and not macro like in glibc (that uses `pthread_register_cancel`, `pthread_unregister_cancel` and `pthread_unwind_next`).

In [musl's `pthread.h`](https://github.com/bminor/musl/blob/79bdacff83a6bd5b70ff5ae5eb8b6de82c2f7c30/include/pthread.h#L212-L216), `pthread_cleanup_push(f, x)` and `pthread_cleanup_pop(r)` are implemented as macro, too. But I couldn't found something like `pthread_unwind_next` and `pthread_cond_clockwait`. Should I just ignore them when compiling with `MUSL`?

Now I'm able to run some bascially command in busybox like `ls` and `echo` on sd625, but other commands often cause `Error: Unsupported Syscall` and crashes. Should I implement them?
(I couldn't run `busybox ls` though box64 on `x86_64` platform. Got SIGSEGV after lots of symbol not found:
```
Error: Global Symbol ns_initparse not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5560 (0) in /bin/busybox
Error: Global Symbol res_mkquery not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5660 (0) in /bin/busybox
Error: Global Symbol ns_name_uncompress not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5670 (0) in /bin/busybox
Error: Global Symbol pivot_root not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5758 (0) in /bin/busybox
Error: Global Symbol ns_parserr not found, cannot apply R_X86_64_GLOB_DAT @0x1000c57a8 (0) in /bin/busybox
Error: Global Symbol ns_get32 not found, cannot apply R_X86_64_GLOB_DAT @0x1000c57e0 (0) in /bin/busybox
Error: Global Symbol ether_hostton not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5870 (0) in /bin/busybox
Error: Global Symbol swapoff not found, cannot apply R_X86_64_GLOB_DAT @0x1000c59e0 (0) in /bin/busybox
Error: Global Symbol crypt not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5b18 (0) in /bin/busybox
Error: Global Symbol swapon not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5ce0 (0) in /bin/busybox
Error: Global Symbol ether_aton_r not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5d20 (0) in /bin/busybox
Error: Global Symbol scanf not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5d40 (0) in /bin/busybox
Error: Global Symbol ns_get16 not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5e20 (0) in /bin/busybox
3464746|SIGSEGV @0x34e94d48 (???(./box64+0x34e94d48)) (x64pc=0x76322/???:"???", rsp=0x7f7fd8aa1c08), for accessing 0x76322 (code=1)
```

**Comment by gamecss** [comment]
Ok... I think it's really a disturb. giving up

**Comment by gamecss** [comment]
:( I'm so sorry

**Comment by ptitSeb** [comment]
sorry for what? there is no issue in trying things :)

**Comment by paulwratt** [comment]
> Thanks for your help! but I still have a little questions.
> 
> > I moved `initAllHelpers(context);` below `init_custommem_helper(context);` to create pthread key before `NewLibrarian`.
> 
> Will this cause some problem?
> 
> > .... as I assume those are actual function on musl and not macro like in glibc (that uses `pthread_register_cancel`, `pthread_unregister_cancel` and `pthread_unwind_next`).
> 
> In [musl's `pthread.h`](https://github.com/bminor/musl/blob/79bdacff83a6bd5b70ff5ae5eb8b6de82c2f7c30/include/pthread.h#L212-L216), `pthread_cleanup_push(f, x)` and `pthread_cleanup_pop(r)` are implemented as macro, too. But I couldn't found something like `pthread_unwind_next` and `pthread_cond_clockwait`. Should I just ignore them when compiling with `MUSL`?
> 
> Now I'm able to run some bascially command in busybox like `ls` and `echo` on sd625, but other commands often cause `Error: Unsupported Syscall` and crashes. Should I implement them? (I couldn't run `busybox ls` though box64 on `x86_64` platform. Got SIGSEGV after lots of symbol not found:
> 
> ```
> Error: Global Symbol ns_initparse not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5560 (0) in /bin/busybox
> Error: Global Symbol res_mkquery not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5660 (0) in /bin/busybox
> Error: Global Symbol ns_name_uncompress not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5670 (0) in /bin/busybox
> Error: Global Symbol pivot_root not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5758 (0) in /bin/busybox
> Error: Global Symbol ns_parserr not found, cannot apply R_X86_64_GLOB_DAT @0x1000c57a8 (0) in /bin/busybox
> Error: Global Symbol ns_get32 not found, cannot apply R_X86_64_GLOB_DAT @0x1000c57e0 (0) in /bin/busybox
> Error: Global Symbol ether_hostton not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5870 (0) in /bin/busybox
> Error: Global Symbol swapoff not found, cannot apply R_X86_64_GLOB_DAT @0x1000c59e0 (0) in /bin/busybox
> Error: Global Symbol crypt not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5b18 (0) in /bin/busybox
> Error: Global Symbol swapon not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5ce0 (0) in /bin/busybox
> Error: Global Symbol ether_aton_r not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5d20 (0) in /bin/busybox
> Error: Global Symbol scanf not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5d40 (0) in /bin/busybox
> Error: Global Symbol ns_get16 not found, cannot apply R_X86_64_GLOB_DAT @0x1000c5e20 (0) in /bin/busybox
> 3464746|SIGSEGV @0x34e94d48 (???(./box64+0x34e94d48)) (x64pc=0x76322/???:"???", rsp=0x7f7fd8aa1c08), for accessing 0x76322 (code=1)
> ```

> Ok... I think it's really a disturb. giving up

Like I said earlier, _"How are you testing you changes / fixes"_ - start simple. If you really want to use BusyBox on Alpine to start out, then make sure you compile BusyBox `--with-standalone` (or whatever switch compiles all BusyBox binaries as stand alone modues).

why do I say this: things like `ether_aton_r`, `swapon`, `crypt` and `swapoff` are not part of a _normal_ `ls` commad process

you end up overloading yourself with required fixes that are totally unrelated to what you are testing.

**Comment by gamecss** [comment]
I really thanks for your reply! About `ether_aton_r`, `swapon`, `crypt` and `swapoff` -- They're actually a part of musl, I can grep them in `ld-musl-x86_64.so.1`. About `Error: Global Symbol` error, I can think out only three reasons:
- These symbol doesn't linked, so box64 cannot find them
- Missing some `EXPORT sth my_something` function
- Missing some `GO(sth, ......)`

For the first possible reason, `-lc` linking options is already applied. But for the second and third possible reason, I can't do anything useful.
- What does the second paramater of GOs like `GO(...., pFp_t)` means?
- When and how should I write them?
And is the really reason in these reasons?

These are lots of problems. I can't find documents about how to do. Of course, I'm able to test if they're works, but first I need to write some code. That's why I cannot do anything and have to give up. These should be done by someone knows a lot about musl & box64 & c, but not me. However, thank you very much for your help! :)
