### ISSUE TITLE
Bug: Steam's launcher not launching even though login into a user thats not root (GNOME Edition)

### ISSUE THREAD

**Issue by BBCByComcast** [ptitSeb/box64#1038]
Steam's launcher not launching even though login into a user thats not root
i cant launch steam launcher as i was trying to test if steam even runs and works properly but it just says that it cant run as root user even though i login into a user thats not root
-Run the steam launcher
-Get error "cannot run as root user"
-Switch to a user
-Run the steam launcher
-Get the same error even though not being in the root user.
giving me the "cannot run as root user" even though i am not in the root user
![Picsart_23-10-23_11-30-45-322](https://github.com/ptitSeb/box64/assets/137778363/5a642e5a-d717-4edc-b65a-374203c7857c)

**Comment by ptitSeb** [comment]
You probably still have a use that is root there. Steam is an hybid 32bits/64bits app. Not sure how you handled 32bits process, but something makes the user a superuser
It's not really a box issue (also, most probably it should be on box86 as steam is a 32bits apps with a 64bits server in the background).

**Comment by BBCByComcast** [comment]
> You probably still have a use that is root there. Steam is an hybid 32bits/64bits app. Not sure how you handled 32bits process, but something makes the user a superuser It's not really a box issue (also, most probably it should be on box86 as steam is a 32bits apps with a 64bits server in the background).

Sir, That a Redesign, Not a Just Issues, Btw, My a Way, Let Me Install Windows 11 in Termux with Ubuntu 23.10 Excusing Android 13, Just Redesign

**Comment by ptitSeb** [comment]
> Sir, That a Redesign, Not a Just Issues, Btw, My a Way, Let Me Install Windows 11 in Termux with Ubuntu 23.10 Excusing Android 13, Just Redesign

I don't understand what you are trying to do.

**Comment by BBCByComcast** [comment]
> > Sir, That a Redesign, Not a Just Issues, Btw, My a Way, Let Me Install Windows 11 in Termux with Ubuntu 23.10 Excusing Android 13, Just Redesign
> 
> I don't understand what you are trying to do.

NVR, Let Me Close This Issue for Some Reason
