### ISSUE TITLE
Valheim Dedicated Server - Unimplemented Opcode (D9) FE 97 60 02 40 F9 77 D9 FE 97 05 FF FF 17 1F

### ISSUE THREAD

**Issue by highland-joe** [ptitSeb/box64#105]
Running Valheim Dedicated Server on Ubuntu 20.04 (server) on aarch64, Raspberry Pi 4 (8GB)
Box64 with Dynarec v0.1.3 39f2b50 built on Aug 26 2021 10:33:55
Using Valheim Dedicated Server for Linux downloaded via steamcmd

Good news is, I got it to work, played successfully over one hour with two players on the server.

However, the server ist not stable. After several hours idle, I cannot re-connect and have to restart the server. Restart fails in about 7 of 10 attempts with the following "Unimplemented Opcode Message":

_Aug 26 10:39:00 raspi4 vstart.sh[13078]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
Aug 26 10:39:00 raspi4 vstart.sh[13078]: 08/26/2021 10:39:00: Game server connected
Aug 26 10:39:00 raspi4 vstart.sh[13078]:
Aug 26 10:39:00 raspi4 vstart.sh[13078]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
Aug 26 10:39:01 raspi4 vstart.sh[13078]: TYPE: 31
Aug 26 10:39:01 raspi4 vstart.sh[13078]: * Assertion at mini-amd64.c:209, condition `amd64_is_imm32 (disp)' not met
Aug 26 10:39:01 raspi4 vstart.sh[13078]: Warning, jumping to a no-block address 0x6490a5c0 from 0xffff78032770 (db=0xa0c7ca70, x64addr=0xffff8cfa9b7c)
Aug 26 10:39:01 raspi4 vstart.sh[13078]: 13078|0x6490a5ae: Unimplemented Opcode (D9) FE 97 60 02 40 F9 77 D9 FE 97 05 FF FF 17 1F
Aug 26 10:39:02 raspi4 vstart.sh[13077]: /home/valheim/Valheim/vstart.sh: line 12: 13078 Aborted                 (core dumped)_

I'll attach the complete server log. Hope you can help me with this, thanks in advance.
[Server Log Valheim Dedicated Server on Raspi4.txt](https://github.com/ptitSeb/box64/files/7059385/Server.Log.Valheim.Dedicated.Server.on.Raspi4.txt)

**Comment by thorkseng** [comment]
I am having the same issue, in my case in the start of the server. I was playing some hours without issues (even if the server was online during hours without players) but the error appears when I restart it (randomly).

**Comment by thorkseng** [comment]
I don't know if this can help but when I got the error I got this message:

```
TYPE: 31
* Assertion at mini-amd64.c:209, condition `amd64_is_imm32 (disp)' not met

Stacktrace:

/proc/self/maps:
0000007fa7ec6040-0000007fa7ec6238 rw-p 0000000000000040 00:22 2264383 /root/valheim_server/valheim_server.x86_64

0000007fa7ec6238-0000007fa7ec6254 rwxp 0000000000000238 00:22 2264383 /root/valheim_server/valheim_server.x86_64

0000007fa7ec6000-0000007fa7ec6954 r-xp 0000000000000000 00:22 2264383 /root/valheim_server/valheim_server.x86_64

0000007fa80c6d88-0000007fa80c7030 r-xp 0000000000000d88 00:22 2264383 /root/valheim_server/valheim_server.x86_64

0000007fa80c6da0-0000007fa80c6fe0 -w-p 0000000000000da0 00:22 2264383 /root/valheim_server/valheim_server.x86_64

0000007fa7ec6254-0000007fa7ec6298 r--p 0000000000000254 00:22 2264383 /root/valheim_server/valheim_server.x86_64

0000007fa7ec6810-0000007fa7ec684c ---p 0000000000000810 00:22 2264383 /root/valheim_server/valheim_server.x86_64

0000007fa80c6d88-0000007fa80c7000 -w-p 0000000000000d88 00:22 2264383 /root/valheim_server/valheim_server.x86_64


Native stacktrace:

        (null)

Debug info from gdb:

src/tier1/fileio.cpp (5131) : Assertion Failed: m_vecRegisteredWriters.Count() == 0
src/tier1/fileio.cpp (5131) : Assertion Failed: m_vecRegisteredWriters.Count() == 0
```

Thanks a lot!

Regards,
Tranko.

**Comment by ptitSeb** [comment]
Yes, that's an assert in 64bits mono that happens when a value is not 32bits. I have fixed some of them, but not all it seems (and I'm not sure how those other occurence happens...).
I know I have to fix that eventualy.

**Comment by thorkseng** [comment]
First of all: Thanks a lot for your effort!!!!!

Today I rebuild everything from the github code with the last version. 
I got the previous error sometimes and sometimes (lees) I got this one too:

```
TYPE: 31
* Assertion at mini-amd64.c:209, condition `amd64_is_imm32 (disp)' not met

Stacktrace:

* Assertion: should not be reached at interp-stubs.c:105
```

But I am not if this can help you.

Regards,
Tranko.

**Comment by thorkseng** [comment]
Hello,

With the last compilation I am getting this error:

```
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Threading.WaitHandle.Wait_internal (intptr*,int,bool,int) [0x0000b] in <b6074dacdf2142f38da4050b03a225bb>:0
  at System.Threading.WaitHandle.WaitOneNative (System.Runtime.InteropServices.SafeHandle,uint,bool,bool) [0x00019] in <b6074dacdf2142f38da4050b03a225bb>:0
  at System.Threading.WaitHandle.InternalWaitOne (System.Runtime.InteropServices.SafeHandle,long,bool,bool) [0x00014] in <b6074dacdf2142f38da4050b03a225bb>:0
  at System.Threading.WaitHandle.WaitOne (long,bool) [0x00000] in <b6074dacdf2142f38da4050b03a225bb>:0
  at System.Threading.WaitHandle.WaitOne (int,bool) [0x00019] in <b6074dacdf2142f38da4050b03a225bb>:0
  at System.Threading.WaitHandle.WaitOne () [0x00000] in <b6074dacdf2142f38da4050b03a225bb>:0
  at HeightmapBuilder.RequestTerrain (UnityEngine.Vector3,int,single,bool,WorldGenerator) [0x00000] in <e394723aae704d74a059e2274ad0bdb2>:0
  at HeightmapBuilder.RequestTerrainSync (UnityEngine.Vector3,int,single,bool,WorldGenerator) [0x00000] in <e394723aae704d74a059e2274ad0bdb2>:0
  at Heightmap.Generate () [0x0008e] in <e394723aae704d74a059e2274ad0bdb2>:0
  at Heightmap.Regenerate () [0x00013] in <e394723aae704d74a059e2274ad0bdb2>:0
  at Heightmap.OnEnable () [0x00018] in <e394723aae704d74a059e2274ad0bdb2>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x0001e] in <b6074dacdf2142f38da4050b03a225bb>:0
/proc/self/maps:
0000007f8b8ee040-0000007f8b8ee238 rw-p 0000000000000040 00:21 6816804 /root/valheim_server/valheim_server.x86_64
0000007f8b8ee238-0000007f8b8ee254 rwxp 0000000000000238 00:21 6816804 /root/valheim_server/valheim_server.x86_64
0000007f8b8ee000-0000007f8b8ee954 r-xp 0000000000000000 00:21 6816804 /root/valheim_server/valheim_server.x86_64
0000007f8baeed88-0000007f8baef030 r-xp 0000000000000d88 00:21 6816804 /root/valheim_server/valheim_server.x86_64
0000007f8baeeda0-0000007f8baeefe0 -w-p 0000000000000da0 00:21 6816804 /root/valheim_server/valheim_server.x86_64
0000007f8b8ee254-0000007f8b8ee298 r--p 0000000000000254 00:21 6816804 /root/valheim_server/valheim_server.x86_64
0000007f8b8ee810-0000007f8b8ee84c ---p 0000000000000810 00:21 6816804 /root/valheim_server/valheim_server.x86_64
0000007f8baeed88-0000007f8baef000 -w-p 0000000000000d88 00:21 6816804 /root/valheim_server/valheim_server.x86_64

Native stacktrace:

        (null)

Debug info from gdb:

mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
src/tier1/fileio.cpp (5131) : Assertion Failed: m_vecRegisteredWriters.Count() == 0
src/tier1/fileio.cpp (5131) : Assertion Failed: m_vecRegisteredWriters.Count() == 0
```

Regards,
Alvaro.

**Comment by thorkseng** [comment]
I tested yesterday in the night to build and run and I got the same error:

```
TYPE: 31
* Assertion at mini-amd64.c:209, condition `amd64_is_imm32 (disp)' not met

Stacktrace:

* Assertion: should not be reached at interp-stubs.c:105
```

@mogery How I can help to bring you more information?

**Comment by mogery** [comment]
Seems to work for me locally just fine. I got to `Generating locations`.

Could you maybe re-clone the repo with my edits and try building it again? Just to make sure.

```bash
git clone -b memory-map-fix https://github.com/mogery/box64 box64-memory-patch
cd box64-memory-patch
# repeat build instructions
```

**Comment by thorkseng** [comment]
> Seems to work for me locally just fine. I got to `Generating locations`.
> 
> Could you maybe re-clone the repo with my edits and try building it again? Just to make sure.
> 
> ```shell
> git clone -b memory-map-fix https://github.com/mogery/box64 box64-memory-patch
> cd box64-memory-patch
> # repeat build instructions
> ```

Yeah, I was doing something wrong. I rebuild the container with your version and it works. At least I have tried to start the server several times and it goes correctly all the times. As it's a random issue it's difficult to determinate that is fixed, but I think so.

I think that maybe can be merged the fix to the main repository?

Thanks so much!

**Comment by highland-joe** [comment]
I just rebuit and was able to start the Valheim Dedicated Server in 1st attempt. Will keep trying to see if it runs stable.
