### ISSUE TITLE
Build Error on Ubuntu 22.04

### ISSUE THREAD

**Issue by xboxones1** [ptitSeb/box64#1050]
Build log: [box64.log](https://github.com/ptitSeb/box64/files/13265064/box64.log)

**Comment by Sirox228** [comment]
which arguments and compiler do you use for it? for me it compiles fine with gcc-12 and SAVE_MEM argument

**Comment by ptitSeb** [comment]
Are you building an ARM64 version on a x86_64 machine?

**Comment by xboxones1** [comment]
raspberry pi 4

**Comment by ptitSeb** [comment]
> raspberry pi 4 Ubuntu arm64

Ok, but do you have `build-essentials` installed? or did you just built `box86` before and have not installed anything else maybe?

**Comment by xboxones1** [comment]
All the necessary dependencies are installed, I just installed the operating system today, apparently something went wrong. box86 did not assemble and did not even add the armhf architecture itself. I will reinstall os

**Comment by xboxones1** [comment]
I reinstalled the system and nothing changed, same error. I don't have any armhf package. I also have the `proposed` repository connected. How to diagnose the problem?

**Comment by ptitSeb** [comment]
Waht does `gcc --version` gives you?

**Comment by xboxones1** [comment]
```
gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
uname -a
Linux mate 5.15.0-1042-raspi #45-Ubuntu SMP PREEMPT Thu Oct 12 09:20:16 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by ptitSeb** [comment]
and what about`
```bash
uname -i
```
and
```bash
file `which gcc-11`
```
?

**Comment by xboxones1** [comment]
```
uname -i
aarch64
```
```
file `which gcc-11`
/usr/bin/gcc-11: symbolic link to aarch64-linux-gnu-gcc-11
```

**Comment by ptitSeb** [comment]
looks good. what about
```bash
file `which gcc`
echo $CC
```

Also, can you put the whole log of the config part of box64?

**Comment by xboxones1** [comment]
```
file `which gcc`
/usr/bin/gcc: symbolic link to gcc-11
```
`echo $CC

`

**Comment by ptitSeb** [comment]
I checked on my ubuntu 22.04, and the symbol `HWCAP_CRC32` (and all the other) are defined in ` /usr/include/aarch64-linux-gnu/asm/hwcap.h`
Can you check that file on your system?

**Comment by xboxones1** [comment]
Thanks for the help. I found what the problem was, in one of the PPAs the `linux-libc-dev` package was not build correctly, and it overwrote the necessary files.
