### ISSUE TITLE
box64 hates gcc-13 builds

### ISSUE THREAD

**Issue by mcagabe19** [ptitSeb/box64#1052]
Termux PRoot with Ubuntu Mantic

[log.txt](https://github.com/ptitSeb/box64/files/13282895/log.txt)

and ptitSeb if you have discord add me if you wanna I use box64 everyday (username mc.9)

**Comment by ptitSeb** [comment]
I see nothing special in this log, execpt a missing function: `__isoc23_strtoul` that I'll added later.

Is that box64 that is build with gcc-13 or is it wine?

**Comment by mcagabe19** [comment]
> Is that box64 that is build with gcc-13 or is it wine?

The application builded at gcc-13 not box64 or nor wine
