### ISSUE TITLE
Error: PltResolver: Symbol curl_multi_poll(ver 21: curl_multi_poll@CURL_OPENSSL_4) not found, cannot apply R_X86_64_JUMP_SLOT 0x107b5d198 (0x107701626) in /home/container/bedrock_server

### ISSUE THREAD

**Issue by Notacod3r** [ptitSeb/box64#1053]
Hi, Hope you're doing well!

I run a Minecraft Bedrock server on an Oracle Cloud Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-1047-oracle aarch64)

And I get this error running my server through box64: 
`[2023-11-08 23:40:25:814 INFO] Opening level 'worlds/Bedrock level/db'`
`[2023-11-08 23:40:30:164 INFO] IPv4 supported, port: 19132: Used for gameplay and LAN discovery`
`[2023-11-08 23:40:30:164 INFO] IPv6 supported, port: 19133: Used for gameplay`
`[2023-11-08 23:40:30:271 INFO] Server started.`
`Error: PltResolver: Symbol curl_multi_poll(ver 21: curl_multi_poll@CURL_OPENSSL_4) not found, cannot apply R_X86_64_JUMP_SLOT 0x107b5d198 (0x107701626) in /home/container/bedrock_server`

This error is exclusive to the most recent versions of the official Minecraft server releases. With this error, the server is actually not functional and players are not able to connect any longer. 

Can this be fixed? Let me know if more info is needed.

**Comment by ptitSeb** [comment]
I have added that wrapped function.
Note that this function has been introduced with curl v7.66.0.

**Comment by QuintenQVD0** [comment]
> Thank you so much! Do these changes apply right away? or is it only on a specific day of the week an update is pushed?
> 
> One more quick question, there is this warning that also showed up a long time ago, but the game functions fine with it so I never bothered to reach out. `Warning: Global Symbol _ZTHN11ChunkSource17gPerfIsClientSideE not found, cannot apply R_X86_64_GLOB_DAT @0x107732260 ((nil)) in /home/container/bedrock_server` Do you know if this is an egg, or box64 or Pterodactyl issue?

We at pterodactyl just run a docker container with box64 installed. This can not be an issue pterodactyl.

**Comment by ptitSeb** [comment]
> Thank you so much! Do these changes apply right away? or is it only on a specific day of the week an update is pushed?
> 
> One more quick question, there is this warning that also showed up a long time ago, but the game functions fine with it so I never bothered to reach out. `Warning: Global Symbol _ZTHN11ChunkSource17gPerfIsClientSideE not found, cannot apply R_X86_64_GLOB_DAT @0x107732260 ((nil)) in /home/container/bedrock_server` Do you know if this is an egg, or box64 or Pterodactyl issue?

Note that I only provide sources for box64. It seems you are using a precompile version, and I cannot tell when a new build will be done as it's not handle by me.

About the Warning, that's just warning, don't worry about it.

**Comment by Notacod3r** [comment]
I appreciate it! 

Looks like there will be a new build on Monday. If everything is good, I'll close this issue afterward. Thank you!
