### ISSUE TITLE
[RV64] Cannot MMap/load elf /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 inspite of it existing

### ISSUE THREAD

**Issue by Vixea** [ptitSeb/box64#1057]
[logs.txt](https://github.com/ptitSeb/box64/files/13326539/logs.txt)

HW:
[hwinfo.txt](https://github.com/ptitSeb/box64/files/13326564/hwinfo.txt)
Distro:
Debian(RevyOS)

This happens with any program, and box64 was self compiled.
Thank you for your time. You do amazing work!

**Comment by Vixea** [comment]
Oh and here's the output of ls
```
XXXXXXXX@lpi4a:~/Documents$ ls /usr/lib/x86_64-linux-gnu/
libcrypto.so.1.1  libpng12.so.0  libstdc++.so.5
libgcc_s.so.1     libssl.so.1.1  libstdc++.so.6
```

**Comment by ksco** [comment]
Please paste the whole log so we know which version (commit) of box64 are you using.

**Comment by Vixea** [comment]
[full_log.txt](https://github.com/ptitSeb/box64/files/13327591/full_log.txt)

**Comment by ksco** [comment]
So you're not using the latest tree, please `git pull` and rebuild.

**Comment by Vixea** [comment]
```
sipeed@lpi4a:/media/sipeed/167c8b5c-c517-4ec3-835b-5ef977851fc9/projects/box64$ git pull
Updating 70e4bd41..62634c6e
Fast-forward
 src/dynarec/arm64/dynarec_arm64_00.c | 52 ++++++++++++++++++++----------------
 1 file changed, 29 insertions(+), 23 deletions(-)
```
this is the only change so I doubt it would matter

**Comment by ksco** [comment]
Looking at the log you pasted:

```
Box64 with Dynarec v0.2.5 936fa209 built on Oct 31 2023 20:56:46
```

https://github.com/ptitSeb/box64/commit/936fa209 was committed 2 weeks ago. Maybe you forgot to install it after the build?

**Comment by Vixea** [comment]
possibly

**Comment by Vixea** [comment]
[new_log.txt](https://github.com/ptitSeb/box64/files/13327620/new_log.txt)
progress I thought I had a updated version.... shrug

**Comment by ksco** [comment]
I submitted a fix above.

**Comment by ksco** [comment]
Also, if you have GPU issues, you might want to use the latest RevyOS image from https://mirror.iscas.ac.cn/revyos/extra/images/lpi4a/20231026/, where you can `sudo switch-gl gl4es` to turn on gl4es support and `sudo switch-gl mesa` to turn off.

**Comment by Vixea** [comment]
Here's the thing I did

**Comment by Vixea** [comment]
yep that indeed fixed it. Thanks!

**Comment by Vixea** [comment]
[crash_log.txt](https://github.com/ptitSeb/box64/files/13327758/crash_log.txt)

**Comment by ksco** [comment]
This is a different issue than what suggested in the title, so can you submit a new issue so we can track it there?

(And Unity games are not expected to work on RISC-V hardwares due to the lack of OpenGL support (gl4es is not enough for it).)

**Comment by Vixea** [comment]
ahh fair enough, eh I'll just close it and if I can get it working with zink that would be cool but not something that's an box64
