### ISSUE TITLE
Factorio Headless Server - Unimplemented Opcode (EA) 66 0F 3A 22 D8 03 49 8D 40 03 66 0F 7F 5C 24

### ISSUE THREAD

**Issue by dn9uyen** [ptitSeb/box64#106]
I am trying to run a headless factorio server on ubuntu 20.04 but it crashed on an unimplemented opcode.
Compiled box64 using https://github.com/ptitSeb/box64/commit/e10a78d67112b10806825732f4122d8ade9e6b4e
Dynarec is enabled.

3999|0x1ee5843: Unimplemented Opcode (EA) 66 0F 3A 22 D8 03 49 8D 40 03 66 0F 7F 5C 24
Stop waiting for remaining thread 4002
Stop waiting for remaining thread 4003
Stop waiting for remaining thread 4010
Stop waiting for remaining thread 4011
Stop waiting for remaining thread 4012
Stop waiting for remaining thread 4014
Stop waiting for remaining thread 4015
4003|SIGSEGV @0x648ffeac (???(/usr/local/bin/box64/0x648ffeac)) (x64pc=0xa4a4f033/???:"???", rsp=0xffff7da1bb38, stack=0xffff7d81d000:0xffff7da1d000 own=0xffff7d81d000 fp=0xa6354f80), for accessing 0x48 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=0xd7d6c0
4011|Double SIGSEGV (code=1, pc=0x648ffeac, addr=0x48)!
4010|Double SIGSEGV (code=1, pc=0x648ffeac, addr=0x48)!

Full server log
[factorio-current.log](https://github.com/ptitSeb/box64/files/7079220/factorio-current.log)

Edit: It seems to be working properly now after I reinstalled the server files. I have no idea why it didn't work before.

**Comment by ptitSeb** [comment]
Did you retry after update box64?

**Comment by dn9uyen** [comment]
Yes it's working now.
