### ISSUE TITLE
Box64 + x86_64 Reaper (Cockos) - DAW 

### ISSUE THREAD

**Issue by antisaint81** [ptitSeb/box64#1063]
Hello, 

I'm attempting to run the x86-64 version of the Reaper DAW on the Radxa Rock 5B 16GB with the hopes of using yabridge to run Windows VSTs within the program. X86-64 reaper does not boot, I'm getting the following error: 

antisaint@ROCK5B:~/Downloads/REAPER$ box64 ./reaper
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Cortex-A55 Cortex-A76 with 8 Cores
Params database has 32 entries
Box64 with Dynarec v0.2.5 b82d9d15 built on Nov 10 2023 21:06:02
Counted 31 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/
Looking for ./reaper
Rename process to "reaper"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libasound.so.2
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /home/antisaint/Downloads/REAPER/libSwell.so
Using native(wrapped) libX11.so.6
Using native(wrapped) libXi.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libgdk-3.so.0
Using native(wrapped) libgobject-2.0.so.0Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0Using native(wrapped) libgdk_pixbuf-2.0.so.0
Error: PltResolver: Symbol FT_Init_FreeType(ver 0: FT_Init_FreeType) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff022b62c8 (0x7fff02009e36) in /home/antisaint/Downloads/REAPER/libSwell.so

**Comment by ptitSeb** [comment]
Ok, it would be better now.

**Comment by antisaint81** [comment]
Thank  you! -- that one cleared but now I have this one 

Error: PltResolver: Symbol gdk_screen_get_monitor_workarea(ver 0: gdk_screen_get_monitor_workarea) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff022b6178 (0x7fff02009b96) in /home/antisaint/Downloads/REAPER/libSwell.so

**Comment by LukeShortCloud** [comment]
The `gdk_screen_get_monitor_workarea` function has now been wrapped:

https://github.com/search?q=repo%3AptitSeb%2Fbox64%20gdk_screen_get_monitor_workarea&type=code

Closing as complete.
