### ISSUE TITLE
A question about rv64_lock

### ISSUE THREAD

**Issue by factfinding** [ptitSeb/box64#1068]
Sorry to bother you. When I'm trying to read box64's code, I find that in src/dynarec/native_lock.h, the rv64_lock_cas_d and rv64_lock_cas_dd functions compare the values of (A) and tmpcas, but in the rv64_lock_cas_b and rv64_lock_cas_h functions, the value of the tmpcas is abandoned. As shown in the figure, is that correct?
<img width="491" alt="image" src="https://github.com/ptitSeb/box64/assets/25546853/8c9d3e19-c2ef-49a1-93a5-412a1d8c0a74">
<img width="148" alt="image" src="https://github.com/ptitSeb/box64/assets/25546853/b3d15361-a4cc-4f18-9e81-6493e552560c">
The value of ref is useless?
<img width="470" alt="image" src="https://github.com/ptitSeb/box64/assets/25546853/642da3df-90e2-428f-bbe8-bd7e3fae379e">

**Comment by ptitSeb** [comment]
Mmmm, yeah, that seems a bit strange. I'll try to have another look at those functions.

The lack of byte atomic function is anoying.

**Comment by factfinding** [comment]
In addition, is it possible that just comparing values can lead to ABA problems? In arm64, the LDAXR/STLXR instruction pair will fail when value has been changed, even value is changed to the same value. But CAS will not fail when value is changed to the same value by the other thread. Can this difference cause some problems?

**Comment by ptitSeb** [comment]
> In addition, is it possible that just comparing values can lead to ABA problems? In arm64, the LDAXR/STLXR instruction pair will fail when value has been changed, even value is changed to the same value. But CAS will not fail when value is changed to the same value by the other thread. Can this difference cause some problems?

I don't see this can cause an issue. Writing the same value should be equivalent to no writing at all in this case.
