### ISSUE TITLE
Warning: Unsupported libc Syscall 0x1C1 (449)

### ISSUE THREAD

**Issue by KhanhNguyen9872** [ptitSeb/box64#1070]
i found that when running wine proton x86_64 on box64 and wine x86 on box86

can you add this syscall? i will rebuild and test it

**Comment by ptitSeb** [comment]
It's already present. This syscall is recent and not all kernel have it. Wine test if the syscall is supported and don't use it if it's not, so don't worry about this one.

**Comment by KhanhNguyen9872** [comment]
> It's already present. This syscall is recent and not all kernel have it. Wine test if the syscall is supported and don't use it if it's not, so don't worry about this one.

got it! thanks
