### ISSUE TITLE
gtk_scrollable_get_type not found

### ISSUE THREAD

**Issue by Pet0203** [ptitSeb/box64#1077]
Hi!

I'm running a build from the repo on arm64. Getting this issue when running a binary and I have no idea where to turn. Any ideas? All libs are loading fine.

`Error: PltResolver: Symbol gtk_scrollable_get_type(ver 1: gtk_scrollable_get_type) not found, cannot apply R_X86_64_JUMP_SLOT 0x10ac030 (0x42e096)`

**Comment by LukeShortCloud** [comment]
The requested function has been wrapped. Closing as resolved.
