### ISSUE TITLE
Error loading one of needed lib

### ISSUE THREAD

**Issue by SahajJain01** [ptitSeb/box64#1079]
Hi, I am very new to this so I just needed a little guidance on how I can resolve the following issues regarding Error loading libs
Sorry if this is answered already, I have spent last 3 hours finding something on this but was unable to.

```shell

Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Neoverse-N1 with 4 Cores
Params database has 32 entries
Box64 with Dynarec v0.2.5 4c7ac85a built on Nov 21 2023 18:51:49
BOX64: Detected 48bits at least of address space
Counted 6 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/
Looking for ./nodeserver
argv[1]="-i"
argv[2]="999.3.1.1"
Warning, PreInit Array (size=8) present and ignored!
Rename process to "nodeserver"
Redirecting overridden malloc from symtab function for /app/nodeserver
Error loading needed lib libasan.so.5
Using native(wrapped) librt.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Error loading needed lib libpython2.7.so.1.0
Using native(wrapped) liblzma.so.5
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Error loading one of needed lib
Error: loading needed libs in elf /app/nodeserver
```

**Comment by gongchunye** [comment]
> You need the x86_64 lib named libpython2.7.so.1.0 . You can find it from your amd64 Linux GNU computer if your computer have installed python2.7 . Or u can cross-complie the source of python2.7 to get this .so file.Then move this lib to /usr/lib/x86_64-linux-gnu .

how to do this? please

**Comment by LukeShortCloud** [comment]
@gongchunye Here's how you can do this:

- Find a package that provides `libpython2.7.so.1.0` that is x86_64.
- Extract it (depends on the package format).
- Move the `usr/lib64/` files into `/usr/lib/x86_64-linux-gnu/`.
- Set this environment variable: `export BOX64_LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu"`.
- Run `box64` again.

We'll be automating this process soon. Since the original issue should be resolved by adding the missing library, closing as resolved.
