### ISSUE TITLE
Compiling Box64 in Termux.

### ISSUE THREAD

**Issue by BloodANGELdb** [ptitSeb/box64#1108]
Compiling Box64 in Termux produces the following errors.  What am I doing wrong and how can I solve this problem? ![Screenshot_2023-12-04-09-33-59-077_com.termux.jpg](https://github.com/ptitSeb/box64/assets/44096076/e47f571a-9c36-4b2f-b1af-fa72fc917a7c)

**Comment by mcagabe19** [comment]
try ``cmake .. -DTERMUX=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-17 -DARM_DYNAREC=ON`` (not in chroot/proot)

**Comment by BloodANGELdb** [comment]
> @BloodANGELdb install `libandroid-spawn` and recompile

Thanks, it worked to compile, but there are still a lot of warnings...

**Comment by mcagabe19** [comment]
> Thanks, it worked to compile, but there are still a lot of warnings...

it's due box(64/86) writen for gcc and clang is different

**Comment by mcagabe19** [comment]
@RajDave-Dev you not have `libandroid-sysv-semaphore` installed

**Comment by RajDave-Dev** [comment]
> @RajDave-Dev you not have `libandroid-sysv-semaphore` installed

It worked after installation. Thanks
