### ISSUE TITLE
Plexamp: Unimplemented Opcode (FE) 66 0F 7C C0 F2 0F 10 0D 9E 7E F7 FE F2 0F 5E

### ISSUE THREAD

**Issue by hakmo** [ptitSeb/box64#111]
Running from console:

$ box64 plexamp
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.5 4a9b012 built on Sep  8 2021 11:43:16
BOX64_LD_LIBRARY_PATH: /home/pi/Downloads/x64_libs/
Using default BOX64_PATH: ./:bin/
Counted 46 Env var
Looking for plexamp
Using emulated libffmpeg.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/pi/Downloads/x64_libs/libgobject-2.0.so.0
Using emulated /home/pi/Downloads/x64_libs/libglib-2.0.so.0
Using emulated /home/pi/Downloads/x64_libs/libxshmfence.so.1
Using emulated /home/pi/Downloads/x64_libs/libgio-2.0.so.0
Using emulated /home/pi/Downloads/x64_libs/libnss3.so
Using emulated /home/pi/Downloads/x64_libs/libnssutil3.so
Using emulated /home/pi/Downloads/x64_libs/libsmime3.so
Using emulated /home/pi/Downloads/x64_libs/libnspr4.so
Using native(wrapped) libatk-1.0.so.0
Using native(wrapped) libatk-bridge-2.0.so.0
Using native(wrapped) libSM.so.6
Using native(wrapped) libICE.so.6
Using native(wrapped) libXau.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libdbus-1.so.3
Using emulated /home/pi/Downloads/x64_libs/libdrm.so.2
Using emulated /home/pi/Downloads/x64_libs/libgdk_pixbuf-2.0.so.0
Using emulated /home/pi/Downloads/x64_libs/libgtk-3.so.0
Using emulated /home/pi/Downloads/x64_libs/libgdk-3.so.0
Using native(wrapped) libpango-1.0.so.0
Using emulated /home/pi/Downloads/x64_libs/libffi.so.8
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpcre.so.3
Using native(wrapped) libm.so.6
Using native(wrapped) libcairo.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXdamage.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXrender.so.1
Using native(wrapped) libexpat.so.1
Using native(wrapped) libxkbcommon.so.0
Using emulated /home/pi/Downloads/x64_libs/libgbm.so.1
Using native(wrapped) libasound.so.2
Using native(wrapped) libcups.so.2
Using native(wrapped) libatspi.so.0
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /home/pi/Downloads/x64_libs/libgmodule-2.0.so.0
Using native(wrapped) libz.so.1
Using emulated /home/pi/Downloads/x64_libs/libmount.so.1
Using emulated /home/pi/Downloads/x64_libs/libselinux.so.1
Using native(wrapped) libresolv.so.2
Using emulated /home/pi/Downloads/x64_libs/libblkid.so.1
Using emulated /home/pi/Downloads/x64_libs/libpcre2-8.so.0
Using emulated /home/pi/Downloads/x64_libs/libplc4.so
Using emulated /home/pi/Downloads/x64_libs/libplds4.so
Warning, function gettid not found in lib libc.so.6
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libXi.so.6
Using emulated /home/pi/Downloads/x64_libs/libcairo-gobject.so.2
Using emulated /home/pi/Downloads/x64_libs/libepoxy.so.0
Using emulated /home/pi/Downloads/x64_libs/libfribidi.so.0
Using native(wrapped) libpangoft2-1.0.so.0
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using emulated /home/pi/Downloads/x64_libs/libharfbuzz.so.0
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXcursor.so.1
Using emulated /home/pi/Downloads/x64_libs/libwayland-cursor.so.0
Using emulated /home/pi/Downloads/x64_libs/libwayland-egl.so.1
Using emulated /home/pi/Downloads/x64_libs/libwayland-client.so.0
Using emulated /home/pi/Downloads/x64_libs/libgraphite2.so.3
Using emulated /home/pi/Downloads/x64_libs/libwayland-server.so.0
Error: Global Symbol OPENSSL_memory_alloc not found, cannot apply R_X86_64_GLOB_DAT @0x7f7f005020 ((nil)) in /home/pi/Downloads/squashfs-root/plexamp
Error: Global Symbol OPENSSL_memory_free not found, cannot apply R_X86_64_GLOB_DAT @0x7f7f005028 ((nil)) in /home/pi/Downloads/squashfs-root/plexamp
Error: Global Symbol OPENSSL_memory_get_size not found, cannot apply R_X86_64_GLOB_DAT @0x7f7f005038 ((nil)) in /home/pi/Downloads/squashfs-root/plexamp
Error: Global Symbol sdallocx not found, cannot apply R_X86_64_GLOB_DAT @0x7f7f005030 ((nil)) in /home/pi/Downloads/squashfs-root/plexamp
0963|0x7f78fefd06: Unimplemented Opcode (FE) 66 0F 7C C0 F2 0F 10 0D 9E 7E F7 FE F2 0F 5E

And it just hangs at that point.

**Comment by ptitSeb** [comment]
Did you retried with an updated box64?

**Comment by rajdakin** [comment]
Closing now (no reply since last request).
