### ISSUE TITLE
Elden ring crash after White screen

### ISSUE THREAD

**Issue by DrSay123** [ptitSeb/box64#1114]
Elden ring crashes after White screen. Tried changing wine, vkd3d-proton, dyncfg - but nothing helped
Here few examples of log file
[mobox_log.txt](https://github.com/ptitSeb/box64/files/13549723/mobox_log.txt)
[mobox_log(1).txt](https://github.com/ptitSeb/box64/files/13549729/mobox_log.1.txt)

[mobox_log3.txt](https://github.com/ptitSeb/box64/files/13549731/mobox_log3.txt)

**Comment by LukeShortCloud** [comment]
Elden Ring has been reported to work now.

https://www.reddit.com/r/EmulationOnAndroid/comments/196ql4e/elden_ring_running_on_android_with_mobox_emulator/?rdt=44882

Let us know if you encounter any further issues. Closing as resolved.
