### ISSUE TITLE
Unimplemented Opcode (41 0F A4 D2) 17 41 5A 66 41 F7 C0 4D 13 44 3B F1 48 63 C9

### ISSUE THREAD

**Issue by strongtz** [ptitSeb/box64#1116]
when launching Genshin Impact with GE-Proton8-23

**Comment by ptitSeb** [comment]
That's not a correct opcode. It seems the 17 bellong to the previous opcode (`41 0F A4 D2 17: shld r10d, edx, 0x17`) but I don't see in the code why the 17 would not be fetched in the previous opcode.

You are using latest box64?

**Comment by strongtz** [comment]
Yeah I'm using latest box64 (1b7b361b305ed9867e76d420e139e7f33a577bb3)

**Comment by shenmo7192** [comment]
> Yeah I'm using latest box64 ([1b7b361](https://github.com/ptitSeb/box64/commit/1b7b361b305ed9867e76d420e139e7f33a577bb3))

Nice furina avatar. I comment here to get noticed by mail. Will help test if necessary
