### ISSUE TITLE
Symbol `gtk_progress_bar_set_show_text` and `gdk_threads_add_idle` not found

### ISSUE THREAD

**Issue by Maxython** [ptitSeb/box64#1120]
I tried to run `minecraft-launcher` on Termux, but I ended up getting the following error:
![Screenshot_20231207-000859_Termux](https://github.com/ptitSeb/box64/assets/60917834/127741f1-8b79-43ad-a8c7-4a42029e7260)
I note that this box64 is based on `glibc` and not on `bionic` from android.

**Comment by mcagabe19** [comment]
is that mean u're in chroot/proot?

**Comment by mcagabe19** [comment]
@ptitSeb some missing `gtk` and `gdk` wrapped symbols im box64 I guess

**Comment by Maxython** [comment]
@ptitSeb, if it's not a secret, but how are new symbols added to `box64`?

**Comment by iamcxds** [comment]
> > @ptitSeb, if it's not a secret, but how are new symbols added to `box64`?
> 
> It's not secret at all. I check the signature on the official doc and add the wrapping in the `XXXX_private.h` file (and int the .c if the function has a callback or some special needs).
> 
> There is an old blog entry there https://box86.org/2021/08/a-deep-dive-into-library-wrapping/ with some details.

Maybe you can make a tutorial on this? I found missing symbols are the most common problems which seem "easy" to solve. If it is possible to solve by ourselves and contribute to the project?

**Comment by LukeShortCloud** [comment]
The requested functions have been wrapped and a guide on how to do wrapping has been created:

https://box86.org/2024/02/how-to-create-a-wrapping/

Closing as resolved.
