### ISSUE TITLE
Can't start wineserver on Box64/Wine64, Asahi Linux + Arch ARM?

### ISSUE THREAD

**Issue by Ruby-Enthusiast** [ptitSeb/box64#1139]
Hello, I recently installed Box64/Wine64 on Asahi Linux - Arch Linux ARM deployed on M1 Mac.

At first, It seems to work.

[alarm@alarm bin]$ wine64
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT PageSize:16384 Running on Unknown CPU with 8 Cores
Params database has 38 entries
Box64 with Dynarec v0.2.5 6ecfe5e1 built on Dec 15 2023 05:09:15
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
BOX64: Detected 48bits at least of address space
Counted 50 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/usr/local/sbin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
Looking for /root/wine64/bin/wine64
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /root/wine64/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Usage: wine PROGRAM [ARGUMENTS...]   Run the specified program
       wine --help                   Display this help and exit
       wine --version                Output version information and exit

But whenever I try to run something, wineserver doesn't actually start. I used 64-bit Notepad++ installer for testing.

[alarm@alarm Downloads]$ wine64 npp.8.6.Installer.x64.exe
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT PageSize:16384 Running on Unknown CPU with 8 Cores
Params database has 38 entries
Box64 with Dynarec v0.2.5 6ecfe5e1 built on Dec 15 2023 05:09:15
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
BOX64: Detected 48bits at least of address space
Counted 50 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/usr/local/sbin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
Looking for /root/wine64/bin/wine64
argv[1]="npp.8.6.Installer.x64.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /root/wine64/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT PageSize:16384 Running on Unknown CPU with 8 Cores
Params database has 38 entries
Box64 with Dynarec v0.2.5 6ecfe5e1 built on Dec 15 2023 05:09:15
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
BOX64: Detected 48bits at least of address space
Counted 52 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/usr/local/sbin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
Looking for /root/wine64/bin/wine64
argv[1]="npp.8.6.Installer.x64.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /root/wine64/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT PageSize:16384 Running on Unknown CPU with 8 Cores
Params database has 38 entries
Box64 with Dynarec v0.2.5 6ecfe5e1 built on Dec 15 2023 05:09:15
BOX64: Detected 48bits at least of address space
Counted 52 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/usr/local/sbin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
Looking for /root/wine64/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /root/wine64/lib/wine/x86_64-unix/libwine.so.1
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b
[alarm@alarm Downloads]$ 

I just followed this instruction to install :  https://github.com/ptitSeb/box64/blob/main/docs/X64WINE.md

How can I solve this problem? I tried re-installing, downgrading, upgrading, but every method didn't work.

Thanks.

**Comment by ptitSeb** [comment]
Wine currently doesn't work with 16K pagesize. I might try some things leter to make it work, but for now, it will just not work.

**Comment by Ruby-Enthusiast** [comment]
Oh, It was fundamentally impossible then. Kinda sad, but Thanks for reply.

**Comment by ptitSeb** [comment]
PE file, like ELF, have section with alignment, and all PE are setup to load on a system with 4k pagesize (because it's the only thing that exist in x86 world)....
