### ISSUE TITLE
Box64, 86

### ISSUE THREAD

**Issue by BloodANGELdb** [ptitSeb/box64#1144]
help me please.  I want to create my own Linux prefix in Termux and I want to make it as light as possible.  Can I get a complete list of dependencies for Box86 Box64?  For example, if there is no libFLAC.so.8, then the games will not start.  what libraries are needed for maximum compatibility?

**Comment by ptitSeb** [comment]
box86/box64 themself only need glibc. It's the games that use the libs.

Look at `library_list.h`  for the complete list of libs actually wrapped. That the maximum armhf/arm64 libs box can use. Ohter needed libs would have to be x86/x86_64 ones.

**Comment by BloodANGELdb** [comment]
ticket closed
