### ISSUE TITLE
Wine 9.0: Failed to start explorer

### ISSUE THREAD

**Issue by Pipetto-crypto** [ptitSeb/box64#1147]
Whenever I try to launch any graphical application with wine 9.0, box64/box86 and an odd Termux setup, it fails with the two following errors:

0294:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0294:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."

I tried with a few logging options but none showed anything apart from WINEDEBUG=+seh:

029c:trace:seh:handle_syscall_fault code=c0000005 flags=0 addr=0x3f000390ed ip=3f000390ed tid=029c
029c:trace:seh:handle_syscall_fault  info[0]=0000000000000000
029c:trace:seh:handle_syscall_fault  info[1]=ffffffffffffffff
029c:trace:seh:handle_syscall_fault  rax=ffffffffffffffff rbx=0000003f00085920 rcx=000000007ffc0000 rdx=0000000000000001
029c:trace:seh:handle_syscall_fault  rsi=0000000000000000 rdi=0000000000000000 rbp=0000007ffe0ff9c8 rsp=0000007ffe0ff558
029c:trace:seh:handle_syscall_fault   r8=ffffffffffffffff  r9=0000007fffcbce80 r10=0000007ffe0ff9e0 r11=ffffffffffffffff
029c:trace:seh:handle_syscall_fault  r12=0000000000000000 r13=0000000000000001 r14=0000000000000000 r15=0000000000000000
029c:trace:seh:handle_syscall_fault returning to user mode ip=0000007ffe94bb04 ret=c0000005

**Comment by Pipetto-crypto** [comment]
The issue is not on box64 side but on wine side.

**Comment by ptitSeb** [comment]
> The issue is not on box64 side but on wine side, so closing this.

Is it? Do you have a wine ticket for that?
