### ISSUE TITLE
*Box64 Excuse me. Please answer

### ISSUE THREAD

**Issue by zanfan12** [ptitSeb/box64#1171]
Excuse me. Please answer my question. In box64droid Wine version shows cpu status?. It's not zero cpu status. Please tell me which version.

**Comment by ptitSeb** [comment]
Sorry but I didn't understood the question.

**Comment by LukeShortCloud** [comment]
We recommend using the latest Wine WoW64 build for the best results. You can get builds from here:

https://github.com/Kron4ek/Wine-Builds/releases

Feel free to re-open this with more exact details if you need helping with anything.
