### ISSUE TITLE
Error: PltResolver: Symbol bsd_signal(ver 2: bsd_signal@GLIBC_2.2.5) not found

### ISSUE THREAD

**Issue by Bukayoooo** [ptitSeb/box64#1208]
Hello, I'm running speccpu in box64, and encountered the below error:
Error: PltResolver: Symbol bsd_signal(ver 2: bsd_signal@GLIBC_2.2.5) not found, cannot apply R_X86_64_JUMP_SLOT 0x6315e0 (0x40545e) in /home/wh/soft/cpu2017_install/bin/specmake
is it a error because of box64, and how to fix it? Looking forward to replying!

**Comment by ptitSeb** [comment]
It's a box64 issue. I'll add wrapping to this function soon.

**Comment by ptitSeb** [comment]
Ok, this function has been added. You can update box64 and try again.

**Comment by ptitSeb** [comment]
Can you check please @Bukayoooo so the ticket be closed.
