### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by Vixeliz** [ptitSeb/box64#122]
Hello I was wondering if there was any way to run build systems such as gradle with box64? I was wondering if one way you could do this was make it when u do "box64 <command>" instead of just trying to run the initial command through box64 it runs every future command spawned by the original as well through box64 would this work?

**Comment by ptitSeb** [comment]
You want to build box64 on Android? It will not work without changes. Android doesn't use libc but musl, and it's not 100% compatible with linux.

**Comment by Vixeliz** [comment]
I kind of want it on android? I was more of asking though if there is a way to run the gradle build system using box64? As for the environment I'm using I am running box64 in a proot through termux and it seems to work fine for things other then gradle

**Comment by artdeell** [comment]
You can use binfmt support to always run box64 with x86_64 tools. I think
you can setup it on proot

ср, 29 сент. 2021 г., 20:37 Vixeliz ***@***.***>:
