### ISSUE TITLE
tcmalloc cannot allocate some internal data (regression)

### ISSUE THREAD

**Issue by Coreforge** [ptitSeb/box64#1249]
Since https://github.com/ptitSeb/box64/commit/1344b1837909da6d91153cf686557a4a10bcb468, steamwebhelper fails to run properly and steam displays the "steamwebhelper is not working" message. In `steamwebhelper.log`, there is the error
```
../../third_party/tcmalloc/chromium/src/page_heap_allocator.h:74] FATAL ERROR: Out of memory trying to allocate internal tcmalloc data (bytes, object-size) 131072 48 
```
https://github.com/ptitSeb/box64/commit/1deec05f3dfaa93b034d0bb7cf00b0f9d73d4016 still works fine.  
I didn't see any relevant log output (with `BOX64_LOG=2` set for steamwebhelper)

**Comment by ptitSeb** [comment]
Thanks you for the bisection. I'll take a look into this. I don't see any direct relationship here, but there must be something.

**Comment by ptitSeb** [comment]
Ok, this should be fixed now. Can you try again with latest sources?

**Comment by Coreforge** [comment]
Steam runs fine again. Thank you very much!
