### ISSUE TITLE
Symbol g_type_add_instance_private not found

### ISSUE THREAD

**Issue by avently** [ptitSeb/box64#125]
Hello, @ptitSeb. Thank you for your hard work! I'm trying to run Anydesk (because it's not available on Arm64). I copied libs one by one from Ubuntu x64 to Ubuntu arm64. The last unsolved thing is this error:

```
sudo ./anydesk --get-status
...
Error: PltResolver: Symbol g_type_add_instance_private(ver 0: g_type_add_instance_private) not found, cannot apply R_X86_64_JUMP_SLOT 0x12be740 (0x412466) in ./anydesk
``` 

Maybe more such errors will be printed after this one is solved, I don't know. Could you please take a look and maybe to wrap this function too? I tried to use emulated libgobject-2.0.so.0 but have another errors which I don't know how to solve.

Attaching archive with Anydesk & libs I copied from Ubuntu x64:
[anydesk.tar.gz](https://github.com/ptitSeb/box64/files/7308192/anydesk.tar.gz)

Let me know if I need to do something more in order to get this binary working.

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
This function has been wrapped:

https://github.com/search?q=repo%3AptitSeb%2Fbox64%20g_type_add_instance_private&type=code

Closing as resolved.
