### ISSUE TITLE
Help me with raspberry pi 3 and bricksync

### ISSUE THREAD

**Issue by Yayaa10** [ptitSeb/box64#1255]
Hi, I'm looking for use the bricksync program, where he is compile from C language in 64 bits.
He is in open source in http://www.bricksync.net/ and a git repo is available in https://github.com/ZZJHONS/Bricksync

1. I have try to compile un 32 bits direct via the raspberry pi but so issues with the arm... and I think with the gcc version.
    Try to compile with my laptop and a VM with raspOS installed ==> not work
    Try to compile with my laptop and a VM with Ubuntu 32bits installed ==> not work again....

2. Try to use the box64 emulator (other way to use the program finally !) and I have this error:
`yaya@raspberrypi:~/bricksync-linux64 $ box86 sh /home/pi/bricksync-linux64/bricksync 
Box86 with Dynarec v0.3.5 eaeacc67 built on Feb  2 2024 19:05:16
Error: reading elf header of /usr/bin/dash, trying to launch natively instead
/home/pi/bricksync-linux64/bricksync: 1: Syntax error: ")" unexpected
`
Is it a syntaxe error when I try to use box64 or the programm doesn't work ?
Can someone explain me the issue ?

**Comment by hisham2630** [comment]
i see that you're using box86?

**Comment by Yayaa10** [comment]
![image](https://github.com/ptitSeb/box64/assets/21086212/32c74489-94ca-4ab3-af7f-6af90fb3e71e)

**Comment by ptitSeb** [comment]
there is a version of libssl for x86_64 in the box64 repo. It should be picked up if it was installed correctly (but maybe I miss a symlink between `libssl.so.1.1` and `libssl.so.1`, I need to check. same for libcrypto)

**Comment by Yayaa10** [comment]
I have install a old version of box64 but I can maybe upgrade it.

**Comment by Yayaa10** [comment]
Hi @ptitSeb is there any way to add the ssl additions?

**Comment by ptitSeb** [comment]
> Hi @ptitSeb is there any way to add the ssl additions?

No. They are not in the lib.

Use the Emulated version of them, it's better for libssl / libcrypto

**Comment by Yayaa10** [comment]
How can I do it ? I'm sorry but I'm not sure to understand

**Comment by Yayaa10** [comment]
@ptitSeb I have try to reinstall from scratch, compile directly on the rasp and same issue:
![image](https://github.com/ptitSeb/box64/assets/21086212/1be6c2cf-3fe3-4be7-9dae-d60193f591d1)
![image](https://github.com/ptitSeb/box64/assets/21086212/1d3a694a-5808-4034-85fa-941674a100f8)

**Comment by Yayaa10** [comment]
Finally I got it by recompile a fresh version of my program. And it works, it was an old version of my compiled program which have an issue.
