### ISSUE TITLE
Problems with Vulkan with latest Wine dev branch

### ISSUE THREAD

**Issue by airidosas252** [ptitSeb/box64#1256]
Hey, this is just merely a suggestion.

Could you try compiling or running latest Wine 9.2?
I'm trying to figure the cause for Vulkan being broken. There are these three peculiar commits (related to Vulkan header updates and new extensions), which after reverting fixed Vulkan fully.

These are the commits on Wine dev branch:
05a0da8ab98af4ae0290643d42c5251a73f886a5
ea890c4733db5119fdb63b900bb7e5c8d04b5245
db03d2be88d80195635188cb51507f4c2d9c2b13

Running with them included I get this error:

```012c:err:msvcrt:_wassert (L"!status",L"../dlls/winevulkan/loader.c",271)``` 

I wanna find out what caused this big regression and I don't even know where to begin. Is it Box64, is it Wine or is it Mesa even?

Thank you once again.

**Comment by ptitSeb** [comment]
It might be missing vulkan extension in the vulkan wrapper. In that case, you should see some message from box64 about missing vrapper for some `vkXxxx` symbols.

**Comment by airidosas252** [comment]
Weirdly, box64 didn't spit any message about any missing vulkan symbol. This is why it's so weird.
Lemme enable more detailed logs and see through it.

**Comment by ptitSeb** [comment]
Odd, that's usualy what's happening: supporting new vulkan extension, exposed by the driver, but not yet wrapped in box64. That usualy lead to crash or issue with initializations.

**Comment by Manorhos** [comment]
I'm getting the same on a Pi 5 with Mesa 24.0.1, but I get this message before the assertion failure:
`Warning, no wrapper for vkGetPhysicalDeviceCalibrateableTimeDomainsKHR`

**Comment by ptitSeb** [comment]
That's an extension not wrpped on box64. I'll add it soon.

**Comment by airidosas252** [comment]
This very well might be why Vulkan isn't working. 
Weird how Box64 in my case was totally quiet.

**Comment by ptitSeb** [comment]
Ok, I have added that extension (VK_KHR_calibrated_timestamps, same as VK_EXT_calibrated_timestamps that was already there)

**Comment by airidosas252** [comment]
![Screenshot_20240224_110149_TermuxX11](https://github.com/ptitSeb/box64/assets/4144830/1aa6edb3-bc34-4e43-8391-751116180941)

So apparently that extension addition is all that was needed for Vulkan to work!

Thanks! Closing this issue.
