### ISSUE TITLE
space engine on wine: can't initialise opengl

### ISSUE THREAD

**Issue by Sirox228** [ptitSeb/box64#1268]
i'm trying to run space engine under wine 8-18. when running it, this pop-up window appears

![Screenshot_2024-02-16-11-19-17-872_com termux x11](https://github.com/ptitSeb/box64/assets/71220271/aa376988-dc3e-46fb-af88-e9ea0884f9ef)

log:
[mobox_log.txt](https://github.com/ptitSeb/box64/files/14309215/mobox_log.txt)

**Comment by hisham2630** [comment]
it's mobox problem.
try to running these commands in termux:
apt install glibc-repo -y
apt install alsa-lib-glibc libglvnd-glibc -y

then run the game

**Comment by Sirox228** [comment]
that didn't help

**Comment by hisham2630** [comment]
> that didn't help, it seems thats a problem with wgl
> 
> ```
> 019c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 0000007FFECFFE10
> 0198:fixme:system:EnableNonClientDpiScaling (0000000000020142): stub
> 0198:fixme:wgl:X11DRV_wglChoosePixelFormatARB unused pfAttribFList
> 0198:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 0000007FFE1FFD70
> ```

Run this in termux before starting mobox:
```export force_gl_vendor=X.Org
```

**Comment by Sirox228** [comment]
didn't work, error is the still the same, log too

**Comment by hisham2630** [comment]
> > that didn't help, it seems thats a problem with wgl
> > ```
> > 019c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 0000007FFECFFE10
> > 0198:fixme:system:EnableNonClientDpiScaling (0000000000020142): stub
> > 0198:fixme:wgl:X11DRV_wglChoosePixelFormatARB unused pfAttribFList
> > 0198:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 0000007FFE1FFD70
> > ```
> 
> Run this in termux before starting mobox:
> 
> ```
> export force_gl_vendor=X.Org
> ```

run these too:
```
export MESA_LOADER_DRIVER_OVERRIDE=zink
export ZINK_CONTEXT_THREADED=true
export ZINK_DESCRIPTORS=lazy
export MESA_SHADER_CACHE_DISABLE=false
```

**Comment by Sirox228** [comment]
thanks, works now

**Comment by hisham2630** [comment]
you are welcome
case can be closed
