### ISSUE TITLE
Error FARA64 Linux libgtk

### ISSUE THREAD

**Issue by alvinhanaji** [ptitSeb/box64#128]
Error loading needed lib libgtk-3.so.0
Error loading one of needed lib
Error: loading needed libs in elf ./FARA

Running FARA x64 Linux and can't run with this error, running Debian on RK3399.

**Comment by ptitSeb** [comment]
GTK 3 is not wrapped yet on box64. It's planned for this version, but not yet there.

**Comment by Wooty-B** [comment]
Looking forward to this addition! Is there any guides tor info on library wrapping? I'd like to get involved but not sure where I would begin. Thanks again!

**Comment by brad** [comment]
gtk3 is now wrapped in version 0.2.0. This issue can be closed

**Comment by rajdakin** [comment]
@alvinhanaji Can you confirm that this is fixed now?

**Comment by LukeShortCloud** [comment]
The `libgtk-3.so.0` library from GTK 3 has been wrapped and should be working. @alvinhanaji If you're having any further issues, please let us know. Closing as resolved.
