### ISSUE TITLE
OpenTTD Linux errors

### ISSUE THREAD

**Issue by alvinhanaji** [ptitSeb/box64#129]
Using emulated /home/cpi/Games/openttd/lib/libgomp.so.1
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58600 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58c70 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58ca0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59550 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58610 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58780 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58830 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b588e0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58900 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58a50 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58b00 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58bb0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58c80 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58f00 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58f70 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58ff0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59070 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b590d0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59130 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59190 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b591f0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59250 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b592c0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59310 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b593f0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59440 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59490 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b594f0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59640 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59690 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59750 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59810 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b598d0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59950 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b599d0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59a80 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59af0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59b70 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59bd0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59c30 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59c90 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59cf0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59d50 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59dc0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59e10 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b58660 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b586b0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b586c8 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b586e8 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b586f0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b586f8 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b58700 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b58708 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b58740 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b58748 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b58758 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b58760 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b58768 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b58de0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b590b0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b592a8 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b592b0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b592b8 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b592f0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b595b0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b59670 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b59bb0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b59da8 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b59db0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b59db8 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __cxa_pure_virtual not found, cannot apply R_X86_64_64 @0xffffa2b59df0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv121__vmi_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58cc0 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv121__vmi_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58d00 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv121__vmi_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b58d40 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv121__vmi_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59380 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv121__vmi_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2b59560 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol __gxx_personality_v0 not found, cannot apply R_X86_64_64 @0xffffa2b5a078 ((nil)) in /home/cpi/Games/openttd/lib/libicule.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2d65b60 ((nil)) in /home/cpi/Games/openttd/lib/libiculx.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2d65b80 ((nil)) in /home/cpi/Games/openttd/lib/libiculx.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2d65ba0 ((nil)) in /home/cpi/Games/openttd/lib/libiculx.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2d65c70 ((nil)) in /home/cpi/Games/openttd/lib/libiculx.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2d65c90 ((nil)) in /home/cpi/Games/openttd/lib/libiculx.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2d65cb0 ((nil)) in /home/cpi/Games/openttd/lib/libiculx.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2d65cd0 ((nil)) in /home/cpi/Games/openttd/lib/libiculx.so.50
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0xffffa2d65e00 ((nil)) in /home/cpi/Games/openttd/lib/libiculx.so.50
Error: Symbol __gxx_personality_v0 not found, cannot apply R_X86_64_64 @0xffffa2d66148 ((nil)) in /home/cpi/Games/openttd/lib/libiculx.so.50
Using native(wrapped) libGL.so.1
Error: PltResolver: Symbol FcNameParse(ver 0: FcNameParse) not found, cannot apply R_X86_64_JUMP_SLOT 0x9de5f0 (0x4b2be6) in ./openttd

**Comment by QuintenQVD0** [comment]
I try to start it the server and I get 

```logs
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.9 40fa336 built on Sep 25 2022 06:46:35
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 19 Env var
Looking for ./openttd
Rename process to "openttd"
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libpng16.so.16
Using native(wrapped) libz.so.1
Using native(wrapped) liblzma.so.5
Error loading needed lib liblzo2.so.2
Error loading one of needed lib
Error: loading needed libs in elf 
```

and liblzo2-dev liblzo2-2 are installed.

I hope that It is not a problem that I post at a older issue

**Comment by QuintenQVD0** [comment]
I have added some .so files:
![afbeelding](https://user-images.githubusercontent.com/67589015/192346123-fa44ed5b-90bf-42cc-b421-04e89f7441b1.png)

```terminal logs
:/home/container$ box64 ./openttd -D
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.9 4f18bd6 built on Sep 26 2022 07:10:41
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 25 Env var
Looking for ./openttd
argv[1]="-D"
Rename process to "openttd"
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libpng16.so.16
Using native(wrapped) libz.so.1
Using native(wrapped) liblzma.so.5
Using emulated liblzo2.so.2
Using emulated libfluidsynth.so.1
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libm.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated libiculx.so.60
Using emulated libicu-le-hb.so.0
Using emulated libicuuc.so.60
Using emulated libicui18n.so.60
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libglib-2.0.so.0
Using emulated libjack.so.0
Using native(wrapped) libasound.so.2
Using native(wrapped) libpulse-simple.so.0
Using native(wrapped) libpulse.so.0
Using native(wrapped) libsndfile.so.1
Using emulated libreadline.so.7
Using emulated libdb-5.3.so
Error initializing native libtinfo.so.5 (last dlerror is libtinfo.so.5: cannot open shared object file: No such file or directory)
Using emulated libtinfo.so.5
Error loading needed lib libicudata.so.60
Error loading one of needed lib
Error initializing needed lib libicuuc.so.60
Error loading one of needed lib
Error initializing needed lib libiculx.so.60
Error loading one of needed lib
Error: loading needed libs in elf /home/container/openttd
```

wy do I get this error if I proved the .so?
Error initializing native libtinfo.so.5 (last dlerror is libtinfo.so.5: cannot open shared object file: No such file or directory)

**Comment by ptitSeb** [comment]
`libtinfo.so.5` is part of libncurses5. Install that (this one is wrapped and box64 will pick it)

**Comment by QuintenQVD0** [comment]
I got it to start but it instandly crashes with the following error:

```error
:/home/container$ box64 ./openttd -D
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.9 4f18bd6 built on Sep 26 2022 07:10:41
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 25 Env var
Looking for ./openttd
argv[1]="-D"
Rename process to "openttd"
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libpng16.so.16
Using native(wrapped) libz.so.1
Using native(wrapped) liblzma.so.5
Using emulated liblzo2.so.2
Using emulated libfluidsynth.so.1
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libm.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated libiculx.so.60
Using emulated libicu-le-hb.so.0
Using emulated libicuuc.so.60
Using emulated libicui18n.so.60
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libglib-2.0.so.0
Using emulated libjack.so.0
Using native(wrapped) libasound.so.2
Using native(wrapped) libpulse-simple.so.0
Using native(wrapped) libpulse.so.0
Using native(wrapped) libsndfile.so.1
Using emulated libreadline.so.7
Using emulated libdb-5.3.so
Using native(wrapped) libtinfo.so.5
Using emulated libicudata.so.60
Using emulated libharfbuzz.so.0
Using emulated libgraphite2.so.3
dbg: [net] Starting dedicated server, version 12.2
dbg: [net] Starting network
dbg: [net] Initializing UDP listeners
dbg: [net] Network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net]   0) 172.18.255.255
Error: PltResolver: Symbol lzma_auto_decoder(ver 13: lzma_auto_decoder@XZ_5.0) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fa2190108 (0x7fa19560f6) in /home/container/openttd
```

**Comment by ptitSeb** [comment]
I need to add lzma_auto_decoder``  symbol to liblzma wrapping. I'll do it later.

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
I recently tested OpenTTD and did not come across any issues. This should be fixed now. If there are any new issues with OpenTTD, please open a new GitHub Issue. Closing as complete.
