### ISSUE TITLE
Newest git version unuseable - high cpu usage on RPI 5 ARM64

### ISSUE THREAD

**Issue by thaihugo** [ptitSeb/box64#1301]
Hi,

I have a surprisingly big performance issue with latest git versions. I cannot pinpoint which ones, but I'm working everyday on 0.2.6, and I started having the issue compiling newer git version by the end of January.

My report is with today's git version.

Problem: 
- Using Box64 version 0.2.6 is normal. For example, dwarf fortress 0.51 loads in 5 seconds. 
- Using the result of the compilation from git (29/02/2024) on the same setup is very very slow. Processor runs at 70% and the game takes 30s- 1m to launch. After that the game is still slow. Anything is 3-4 times slower than normal.
- vulkan games tend to not to load/be too slow for me to wait for them. Art of Rally is buggy on vulkan version with 0.2.6, but does not load ( after 5 minutes) on latest git. Most vulkan version of games have problem on RPI5, but for example, you can launch Fort Triumph on vulkan but not in opengl even if it crashes after a few moves. It does not launch on latest git.

Technical info:
- Rpi5 8 GB
- official Raspberry OS lite, Wayland, fully patched
- Kernel8.img with 4096 Kb pages. Box versions compiled accordingly.

As the program function normally except for the slow behavior, I'm not sure if there is any log I can provide, but I'm ready to test any simple or advanced procedures.

Thanks

**Comment by ptitSeb** [comment]
I have not experienced this behaviour on my side.
If you can do `sudo perf top` it would be interesting to see what takes time at the loading.

**Comment by ptitSeb** [comment]
Also, if you can do a bisect between v0.2.6 and now to see when this behaviour started, that would be very helpfull.

**Comment by ptitSeb** [comment]
Mmmm, just troed on my side (not on a Pi5, I don't have access to that) and the loading of the classic version 50.11 was instantaneous. Not sure if we are talking about the same program tho.
Check that your build is still DYNAREC enabled. simply use `box64 --version` to check

**Comment by thaihugo** [comment]
DYNAREC is indeed not enabled in the git version. I'm going to check my compilation, but I select the RPI5ARM64 option in ccmake.

**Comment by thaihugo** [comment]
I can confirm that ccmake does not enable the ARM64_dynarec parameter by default, while cmake enables it.

Thanks for helping me finding my mistake. I now have git DYNAREC builds.

**Comment by ptitSeb** [comment]
Glad it work now. Enjoy fast loading times :)
