### ISSUE TITLE
hackmud fails to launch sometimes, failed assertion in Mono

### ISSUE THREAD

**Issue by mogery** [ptitSeb/box64#131]
I get the same message as in #105, except I don't get any error messages about opcodes.

```
TYPE: 31
* Assertion at mini-amd64.c:209, condition 'amd64_is_imm32 (disp)' not met

Stacktrace:

* Assertion: should not be reached at interp-stubs.c:105
```

Here are the following links to source code on GitHub with the exact lines:
[mini-amd64.c](https://github.com/Unity-Technologies/mono/blob/2019.4.9f1/mono/mini/mini-amd64.c#L209)
[interp-stubs.c](https://github.com/Unity-Technologies/mono/blob/2019.4.9f1/mono/mini/interp-stubs.c#L105)

**Comment by ptitSeb** [comment]
Yes, I still don't know why some pointer are not 32bits.

**Comment by ptitSeb** [comment]
Oh, wow, well done!

Do you know if there is other function called, other than `fmod` and `fmodf`?
