### ISSUE TITLE
[LA64] Elf loading error: Cannot create memory map

### ISSUE THREAD

**Issue by ksco** [ptitSeb/box64#1318]
Sample:
[sample-elf-loading-error.zip](https://github.com/ptitSeb/box64/files/14472648/sample-elf-loading-error.zip)

Error:
```
Looking for /path/to/sample-elf-loading-error
Cannot create memory map (@0x10000d000 0x6000/0xfff) for elf "/path/to/sample-elf-loading-error" error=22/Invalid argument
Error: Loading elf /path/to/sample-elf-loading-error
```

**Comment by ptitSeb** [comment]
This is fixed now and the ticket can be closed right?

**Comment by ksco** [comment]
Hmm not sure, but will check tomorrow.

**Comment by ksco** [comment]
Sorry but since when this is fixed?

**Comment by ptitSeb** [comment]
This 3d211143e062566d55be50972e5f7dc6a2bfe820 should have fixed it
