### ISSUE TITLE
MangoHUD

### ISSUE THREAD

**Issue by BloodANGELdb** [ptitSeb/box64#1333]
Hello, can I use MangoHUD in conjunction with box64?

**Comment by BloodANGELdb** [comment]
> Yes, you can, but for opengl things, you need to use `--dlsym` parameter (so, something like `mangohud --dlsym ./my_game`)

One more question, should I compile MangoHUD for Arm or can I use x64?

**Comment by ptitSeb** [comment]
ARM version is better.
