### ISSUE TITLE
Minecraft bedrock server not lan-discoverable

### ISSUE THREAD

**Issue by rcmoody** [ptitSeb/box64#1343]
When running minecraft's official bedrock server for linux on raspberry pi (I'm using specifically the pi 4 model b) through box64, the server is not discoverable by clients under the friends tab.

It does appear however if I run natively on x64 hardware or if I use an alternative bedrock server such as nukkit, leading me to conclude this is an issue with box64.

I am able to connect to the server directly, it just doesn't appear under LAN worlds. Is it possible that box64 is not handling multicast packets properly?

**Comment by ptitSeb** [comment]
Box64 should support it, but there might be some missing wrapped function or some struture needed some alignment between arm64 and x86_64 world.

Do you have more details on how bedrock server is doing it's network request?

**Comment by rcmoody** [comment]
It looks like minecraft bedrock uses the [RakNet](https://wiki.vg/Raknet_Protocol) protocol. It looks like the client is the one that broadcasts a message and the server responds to it. However in this case the server simply isn't responding, I checked via wireshark.

**Comment by rcmoody** [comment]
I ended up discovering that the reason my server was not discoverable under the friends tab was because I had already setup a direction connection under the servers tab which apparently precludes the former.
