### ISSUE TITLE
Unimplemented 32bits Opcode (00 00 EB 09) 64 67 8F 06 00 00 83 C4 24 EB 1B 01 48 60 2C

### ISSUE THREAD

**Issue by skydark719** [ptitSeb/box64#1347]
Some RPG Maker VX Ace games refuses to run on box64 with wine wow64, showing this opcode error (game tested: Aria's Story) on Tegra X1:

```
0034:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
0024:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXfixes.so.3
Using emulated /opt/wine-9.3/lib/wine/x86_64-unix/ws2_32.so
4062|0x102c611e: Unimplemented 32bits Opcode (00 00 EB 09) 64 67 8F 06 00 00 83 C4 24 EB 1B 01 48 60 2C
Sigfault/Segbus while quitting, exiting silently
```

**Comment by ptitSeb** [comment]
Ok, I added that opcode, you can update and try again.

**Comment by skydark719** [comment]
The opcode is fixed on both games, but now there's a new error appearing:
`0024:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.`

**Comment by ptitSeb** [comment]
Does one of the game is free to download somewhere? I need to test localy, this kind of error is difficult to fix without some debugging.

**Comment by skydark719** [comment]
Yes, both games are totally free and are lightweight to download. As I added on the previous message as an edit: If dynarec is off, it shows another opcode error.

**Comment by ptitSeb** [comment]
Ok, so games now start without Dynarec (but of course, is super slow).
Need to find what wrong when dynarec is on...

**Comment by skydark719** [comment]
Ok, now it works without any issues, thanks!
