### ISSUE TITLE
Unimplemented Opcode (B0 FF FF FF) 64 66 0F 6F 24 25 80 FF FF FF 64 66 0F 6F 1C

### ISSUE THREAD

**Issue by jh1950** [ptitSeb/box64#1349]
Hi, I ran Longvinter Server with box64. but I saw an error.

```
0112|0x2498bd3: Unimplemented Opcode (B0 FF FF FF) 64 66 0F 6F 24 25 80 FF FF FF 64 66 0F 6F 1C
```

**Comment by ptitSeb** [comment]
Opcode has been added, you can update box64 and try again.

**Comment by jh1950** [comment]
`64 66 0F 6F` in my log, but `66 64 0F 6F` in commit message.

The positions `64` and `66` have changed, does it matter?

**Comment by jh1950** [comment]
Thanks! I'll try again later
