### ISSUE TITLE
I cant run a java project

### ISSUE THREAD

**Issue by RoySalgadoM** [ptitSeb/box64#1357]
When i execute

java -jar myjar.jar

I get: Error: PltResolver: Symbol gdk_threads_add_idle_full(ver 0: gdk_threads_add_idle_fukk) not found, cannot apply R_X86_64_JUMO_SLOT in libglassgtk2.so

Can you help with that please

**Comment by LukeShortCloud** [comment]
This function has now been wrapped:

https://github.com/search?q=repo%3AptitSeb%2Fbox64%20gdk_threads_add_idle_full&type=code

Closing as resolved.
