### ISSUE TITLE
Box64 new version bugs

### ISSUE THREAD

**Issue by BloodANGELdb** [ptitSeb/box64#1364]
Hi, I compiled Box64 last time at the beginning of the month and everything worked fine.  Today I decided to update to the current version, and was faced with the fact that wine takes longer to load, and terrible graphics bugs with OpenGL, I returned to the old version and everything is fine.  Well, what could be the problem?

**Comment by nqtal** [comment]
The breakdown occurred earlier, on March 11th. Many games stopped working or had graphical bugs.

**Comment by BloodANGELdb** [comment]
> The breakdown occurred earlier, on March 11th. Many games stopped working or had graphical bugs.
> 

Is it possible to somehow assemble a version valid for example on March 8?

**Comment by ptitSeb** [comment]
I would need a a more precise dichotomy for this. ` git bisect` is a pretty powerfull tool for that.

**Comment by nqtal** [comment]
> > The breakdown occurred earlier, on March 11th. Many games stopped working or had graphical bugs.
> 
> Is it possible to somehow assemble a version valid for example on March 8?

Download from: 
https://github.com/Pi-Apps-Coders/box64-debs/commit/76149402124b8276324b47186a07814adb93af36#diff-e249003a5c099c2ebc568a7d175c6655dfcd665c11bf5a959c4925ec2814ed90

Then install: 
sudo dpkg -i box64-tegrax1_0.2.7+20240229T063446.6a98369-1_arm64.deb

**Comment by BloodANGELdb** [comment]
> > > The breakdown occurred earlier, on March 11th. Many games stopped working or had graphical bugs.
> > 
> > Is it possible to somehow assemble a version valid for example on March 8?
> 
> Download from: 
> https://github.com/Pi-Apps-Coders/box64-debs/commit/76149402124b8276324b47186a07814adb93af36#diff-e249003a5c099c2ebc568a7d175c6655dfcd665c11bf5a959c4925ec2814ed90
> 
> Then install: 
> sudo dpkg -i box64-tegrax1_0.2.7+20240229T063446.6a98369-1_arm64.deb

the problem is that I need the source code to be compiled manually under glibc Termux-Pacman, since proot-distro is much inferior in performance.

**Comment by BloodANGELdb** [comment]
https://github.com/ptitSeb/box64/issues/1366#issuecomment-2007148999

**Comment by LukeShortCloud** [comment]
All of the issues mentioned here have been resolved in newer Box64 releases. Closing as resolved.
