### ISSUE TITLE
Graphic glitches in Warcraft 3 1.26

### ISSUE THREAD

**Issue by askorbinovaya-kislota** [ptitSeb/box64#1366]
bisected the issue to this commit: a5a7d9382ec09c89779ae66f3af2ca2255ea3003

glitches look like this:
<details>

![Screenshot_2024-03-16-22-29-05-965_com termux x11](https://github.com/ptitSeb/box64/assets/105155938/31a4acbb-0b10-4b36-9d8e-dbd29f30863b)
![Screenshot_2024-03-16-22-29-12-182_com termux x11](https://github.com/ptitSeb/box64/assets/105155938/ae54124d-f716-4dfb-84d1-b50246617397)
</details>

and that's how the game menu should look like:
<details>
<summary>BOX64_DYNAREC=0</summary>

![Screenshot_2024-03-16-22-30-39-539_com termux x11](https://github.com/ptitSeb/box64/assets/105155938/536daec4-0d56-4fdd-a5e8-cbc83056966b)
![Screenshot_2024-03-16-22-30-43-050_com termux x11](https://github.com/ptitSeb/box64/assets/105155938/0a0fb808-b03e-4d90-9b63-ba91af38298d)
</details>

simply disabling bigblock (i thought that commit referenced something about it) partially fixes the glitches, but cripples the menu even further:
<details>
<summary>BOX64_DYNAREC_BIGBLOCK=0</summary>

![Screenshot_2024-03-16-22-34-45-678_com termux x11](https://github.com/ptitSeb/box64/assets/105155938/625007c2-c087-4541-b9d1-4e1a4c428889)
![Screenshot_2024-03-16-22-33-33-530_com termux x11](https://github.com/ptitSeb/box64/assets/105155938/a297327f-046b-4f91-b89c-1a496cdab59d)
</details>

and with the safest dynarec options, the menu is almost fine, with a different glitch affecting the water (x87double fixed the menu):
<details>
<summary>BOX64_DYNAREC_BIGBLOCK=0 BOX64_DYNAREC_SAFEFLAGS=2 BOX64_DYNAREC_STRONGMEM=2 BOX64_DYNAREC_FASTROUND=0 BOX64_DYNAREC_FASTNAN=0 BOX64_DYNAREC_X87DOUBLE=1</summary>

![Screenshot_2024-03-16-22-38-54-458_com termux x11](https://github.com/ptitSeb/box64/assets/105155938/13e7d952-5d4b-498d-a5a8-997f0a2a636a)
</details>
none of those issues appeared on bc770d908af3c310e2e0cd9e1fdc7ca6e0e80fb3 (a5a7d9382ec09c89779ae66f3af2ca2255ea3003 - 1).
i've checked the issues, and it seems that no one reported exactly those glitches, but a comment at #1364 states that many games are broken on a version after march 11; the commit after which the issue happened was made on march 10, so i think they had exactly the same problem

i'm testing on android and my cpu is snapdragon 750G

**Comment by ptitSeb** [comment]
That commit? This is really stronge. I reproduce the inssue on my side, and confirm your result. I'll work on that to see what's wrong (but it maign take time as I'm not home and will have little time this week for box64 dev.)

**Comment by ptitSeb** [comment]
I pushed something, it should be better now, if you can update and test.

**Comment by askorbinovaya-kislota** [comment]
no glitches on latest commit, works fine now

**Comment by BloodANGELdb** [comment]
> I pushed something, it should be better now, if you can update and test.

I confirm that there are no more graphical bugs.  But there is one significant mistake left?  on versions from the beginning of the month everything worked perfectly, the wine prefix loaded in a second, Now if you enable "WINEESYNC=1, WINEESYNC_TERMUX=1" the prefix will load in 30-60 seconds

**Comment by airidosas252** [comment]
https://github.com/ptitSeb/box64/commit/33846405d8e0af86bb5cfb9dab4ea5026fadb614

This commit actually causes Wine to start up very slowly. It also causes two winedevice.exe instances to appear. After reverting this - everything goes back to normal.

It also caused Mass Effect Andromeda to hang while trying to launch it.

**Comment by askorbinovaya-kislota** [comment]
i also encountered freezes (in warcraft 3) on new version, but i thought it was wine issue...

> After reverting this - everything goes back to normal.

i'll try reverting to see if freezes go away

**Comment by askorbinovaya-kislota** [comment]
> i'll try reverting to see if freezes go away

can confirm, no freezes if i revert that commit

**Comment by ptitSeb** [comment]
This commit is important. I'll try to check later why it cause some regressions.

**Comment by LukeShortCloud** [comment]
@askorbinovaya-kislota This should be resolved now. Feel free to re-open this GitHub Issue if you're still encountering issues. Closing as resolved.
