### ISSUE TITLE
Steam on Raspberry Pi 5 with Raspberry Pi OS

### ISSUE THREAD

**Issue by addohm** [ptitSeb/box64#1369]
I've been unsuccessful in actually running steam on the desktop of a Pi5.  Ive ran the install script but when I run steam its as if I never ran the install script.  I even went through and manually made sure all the associated packages were installed, but nothing.

Apologies for the screenshot but at the moment Im remote.

<img width="354" alt="image" src="https://github.com/ptitSeb/box64/assets/25333107/22b2928f-5e2d-44db-a4bf-599a1a2ddd47">

**Comment by ptitSeb** [comment]
I suggest you use the "install_script.sh" script from box86 repo.
Also, make sure you run 4K pagesize kernel, the default 16K pagesize will not work for now.

**Comment by addohm** [comment]
> I suggest you use the "install_script.sh" script from box86 repo. Also, make sure you run 4K pagesize kernel, the default 16K pagesize will not work for now.

That's the script I ran that produced these results.

**Comment by ptitSeb** [comment]
you should also use the "steam" script shell created in `/usr/local/bin/steam` then. All the message of missing libc and stuff should go away.

**Comment by LukeShortCloud** [comment]
@addohm If you have any issues with `/usr/local/bin/steam` from Box86, please feel free to re-open this GitHub issue.
