### ISSUE TITLE
Format the code

### ISSUE THREAD

**Issue by f1yby** [ptitSeb/box64#1386]
Some of the code follow the format rule described in ./.clang-format, but others are not. Would you mind if I format the code, or should I submit a PR?

**Comment by ptitSeb** [comment]
I'm not a big fan of automatic code formating tbh. I find it sometimes ruins manual formating done on purpose.

So you can create a PR, but not sure I'll accept it if I find it makes things less readable.

**Comment by f1yby** [comment]
[PR](https://github.com/ptitSeb/box64/pull/1387#issue-2211737684).
Note: The macro _DOIT defined in `src/wrapped/wrappedlib_init.h` use `#`, and the formation of the macro cause extra space around `/` and cause error when the macro is expanded, so I turned off the formation at this line.
