### ISSUE TITLE
Box64+Box86 Steam Unsupported Architecture aarch64

### ISSUE THREAD

**Issue by nitram166** [ptitSeb/box64#1394]
Didn't find a similar open issue, so I figured I would open one.

When trying to launch a lot of linux games on Steam I get the error "unsupported architecture aarch64" in terminal.
There are others that work fine, but I wonder why these do not play nice with Box64.
For example I tried "The Whispered World Special Edition".

Raspberry Pi 5
OS: Ubuntu 23.10
Built and installed Box64, Box86, and Steam.sh from github.

**Comment by ptitSeb** [comment]
You probably need to setup `BOX64_BASH` env. var. This needs to point to a x86-64 version of bash. There is one copy inside the `tests` folder of box64 repo. This allows running bash script in box64 environnement and should fix those issues.

**Comment by nitram166** [comment]
I added "export BOX64_BASH=~/box64/tests/bash" at the bottom my /etc/bash.bashrc and restarted Ubuntu.
Then I reran the game and it worked perfectly, thank you!

And since I saw there was a BOX86_BASH too, I added "export BOX86_BASH=~/box86/tests/bash" to bashrc as well.

**Comment by ptitSeb** [comment]
You shouldn't need the box86 one, box86 will recognise the BOX64_BASH and will use it anyway.
