### ISSUE TITLE
missing symbols for Gstreamer

### ISSUE THREAD

**Issue by hisham2630** [ptitSeb/box64#1397]
hello
when i try to run a video inside palemoon browser or some games, those missing symbols will popup.
due to trace is too long i share it as file.
[trace-24056-1.txt](https://github.com/ptitSeb/box64/files/14828513/trace-24056-1.txt)

**Comment by hisham2630** [comment]
thanks  for adding those missing symbols, but there's still some missing symbols
also i don't know why some libraries failed to load 
[trace-14213-1.txt](https://github.com/ptitSeb/box64/files/14865350/trace-14213-1.txt)

**Comment by ptitSeb** [comment]
Can this ticket be closed now?

**Comment by hisham2630** [comment]
> Can this ticket be closed now?
there's a missing symbol:
```
Using native(wrapped) libgstreamer-1.0.so.0
Error initializing native libgtk-3.so.0 (last dlerror is /data/data/com.darkos.x11/files/usr/glibc/lib/libpangoft2-1.0.so.0: undefined symbol: hb_ft_face_create)
Error loading needed lib libgtk-3.so.0
Error: loading a needed libs in elf libgstreamer-1.0.so.0
```
the ```hb_ft_face_create``` is available in the native lib

**Comment by hisham2630** [comment]
it was libharfbuzz issue, thank you

**Comment by hisham2630** [comment]
it was libharfbuzz issue, thank you
