### ISSUE TITLE
Unsupported Syscall

### ISSUE THREAD

**Issue by chills340** [ptitSeb/box64#14]
On my pinephone when trying to run Doom RougeLike x64 ( https://drl.chaosforge.org/downloads ) I receive an error Unsupported Syscall 0x4Fh (79).  You stated syscall 79 is sys_getcwd. making the ticket as requested.

Thanks

**Comment by chills340** [comment]
I updated BOX64 and now I receive another syscall for this game. Syscall 0x29h (41)

**Comment by chills340** [comment]
And another one: Syscall 0x2Ch (44)

**Comment by chills340** [comment]
And: Syscall 0x2Dh (45)

sorry

**Comment by chills340** [comment]
Syscall 0x2Ah (42)

**Comment by chills340** [comment]
recompiled and then received 2 missing lib errors. grabbed `libsdl1.2debian` and `libglu1-mesa` then got another syscall 0x49h (73)

**Comment by chills340** [comment]
Progress it seemed to want to launch after grabbing libsdl-image1.2 but now I get a sigbus and sigsevs

![box64sigsev](https://user-images.githubusercontent.com/77407293/124492580-4945ec80-dd7a-11eb-8cd7-69a3cb89a17b.png)

**Comment by chills340** [comment]
Update it ran after i grabbed libsdl-mixer1.2 however controls locked up during gameplay of normal mode for some reason.

![doomrunning](https://user-images.githubusercontent.com/77407293/124654478-34458800-de64-11eb-9399-9321f744ec3b.png)

when attempting challenge mode i received another syscall and now can't launch the game.

![doom](https://user-images.githubusercontent.com/77407293/124654652-6e168e80-de64-11eb-8855-31b88c72b749.png)

**Comment by chills340** [comment]
The game is now working and playable. I will close this ticket and open another if there are anymore issues. Thanks

**Comment by Izaic** [comment]
Awesome work @ptitSeb ! <3

**Comment by zhangjing-GitHub-Code** [comment]
Hi ptitSeb
I'm running Koishi(a bot framework) x64 AppImage on arm64 armbian s905l3a(soc) as it only officialy supported x64 appimage on linux or you will kicked from qq group.
now I run it with box64, it can run and shows log, but
```
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Error: Unsupported Syscall 0xA0h (160)
```
(a part of log)
So might you add this syscall?
thank you.

**Comment by ptitSeb** [comment]
I have added the syscall @zhangjing-GitHub-Code . But why did you use this very old ticket and not created a new one for this?

**Comment by zhangjing-GitHub-Code** [comment]
Just searched with Bing and viewed down, and think it is better to request this syscall in the context(

**Comment by zhangjing-GitHub-Code** [comment]
```
0000|2023-08-02 21:18:05 [I] launcher Error: Unsupported Syscall 0x3Bh (59)
```
Maybe another one?
~and it uses go, saying errorno 2 when reading not existed files~
The program will segment fault/exit and when i run it repeatly it final shows file read err, will it exit too fast by processing by box64?

Just Another syscall failure: 
`Error: Unsupported Syscall 0x10Ch (268)`

**Comment by ptitSeb** [comment]
please create a new ticket. This one is closed, and I suspect you will need more.
