### ISSUE TITLE
HollowKnight not launching on Pinebook Pro

### ISSUE THREAD

**Issue by Idah00** [ptitSeb/box64#141]
I recently installed the box64 package from AUR on my Manjaro Pinebook Pro and I wanted to try out the capabilities of the software with HollowKnight which seems to wokr on other platforms but it doesnt seem to be able to start on the Pinebook Pro.

I am using;
Box64 with Dynarec v0.1.5 289deb3 built on Oct 10 2021 17:09:09
Mesa 21.2.3-1
Linux Kernel 5.14.12-1
Latest HollowKnight version from GOG
The hardware I'm using is a Pinebook Pro

Here is the log I get zhen I launch the game:
[box64.log](https://github.com/ptitSeb/box64/files/7384274/box64.log)

Then here is the log I get when I launch the game with BOX64_LOG=2:
[box64_log2.log](https://github.com/ptitSeb/box64/files/7384282/box64_log2.log)

And finally here are the Unity player logs:
[Unity_Player.log](https://github.com/ptitSeb/box64/files/7384286/Unity_Player.log)

I hope my issue can help improve this fantastic software, if you need me to do more test don't hesitate to ask me.

**Comment by ptitSeb** [comment]
Can this ticket be closed?

**Comment by Idah00** [comment]
Hmmm, mesa has gotten an update recently but I haven't had the time to check if it changes anything, can you give me a day or two to update stuff and test things out?

**Comment by ptitSeb** [comment]
Sure, no pb.

**Comment by Idah00** [comment]
I have updated mesa and box64 and the game now loads but the window does not appear, tho I can see the game appearing in the taskbar its window doesnt seem to render :/

**Comment by ptitSeb** [comment]
I see an xcb issue. I know it happens sometimes, and you just have to try again. I don't know the root cause of this.

I also see it's trying to use Vulkan. Not sure it's a good idea on Panfrost for now. I think there is an env. var. somewhere with a funny name to enable it, but I don't know if it will work. You can force the use of opengl using `-force-glcore` argument.

**Comment by Idah00** [comment]
Welp, using -force-glcore did not change a thing, I dont have much free time these days anyway so you can close the issue, I'll reopen one if I ever get in trouble again, hopefully when I get back to this the bugs will be ironed out or I'll have switched to debian because it supports multiarch ^^
