### ISSUE TITLE
Warning, of_unconvert(...) left over 0x8000, converted 0x8402 when running box64 on RISC-V

### ISSUE THREAD

**Issue by lukaszsobala** [ptitSeb/box64#1432]
Hello,

My box64 version is:
```
Dynarec for RISC-V With extension: I M A F D C PageSize:4096 Running on unknown riscv64 cpu with 4 Cores
Will use Hardware counter measured at 10.0 MHz emulating 640 MHz
Params database has 61 entries
Box64 with Dynarec v0.2.7 db355427 built on Apr 10 2024 14:42:28
```
When I use it to run an amd64 version of bash, I get this at startup:
```
bash: eval: line 31: syntax error near unexpected token `('
bash: eval: line 31: `Warning, of_unconvert(...) left over 0x8000, converted 0x8000'
Warning, of_unconvert(...) left over 0x8000, converted 0x8402
Warning, of_unconvert(...) left over 0x8000, converted 0x8402
```
and then at the end of every output, there is this line:
`Warning, of_unconvert(...) left over 0x8000, converted 0x8402`

Is this expected or a bug? I just checked and it happens for other programs as well.

**Comment by ksco** [comment]
It's just a warning, if your programs run okay, it can be ignored.

**Comment by lukaszsobala** [comment]
Thanks. What is the meaning of this?

**Comment by ksco** [comment]
It means the x86_64 program uses some file flag we cannot find an equivalent in RISC-V, maybe it’s just some obsolete flag we don't care about.
