### ISSUE TITLE
Providing a Native GNU/Linux Environment for Android Users

### ISSUE THREAD

**Issue by nooob-developer** [ptitSeb/box64#1437]
Dear Developers of box64

I am writing to you with a constructive suggestion regarding the approach taken by your software solutions. While the ability to run Windows applications on Android devices through emulation is certainly valuable, I believe there is a missed opportunity in not providing users with a native GNU/Linux environment.

The core issue I see is that by focusing solely on running Windows applications via Wine, you are depriving users of access to the vast ecosystem of native Linux software. Programs like Blender, Steam, and many others have robust Linux versions that could provide a superior experience compared to their Windows counterparts running under emulation.

Furthermore, for certain performance-intensive applications, such as Team Fortress 2 or Dota 2, a native Linux environment could offer significantly better performance than the emulated Windows versions.

I would encourage you to consider expanding your offerings to include a full-fledged GNU/Linux distribution, in addition to the Windows emulation capabilities. This would allow users to access both the Windows software they need, as well as the rich selection of native Linux applications, all while potentially benefiting from improved performance in certain scenarios.

By taking this approach, you would be providing Android users with a truly comprehensive solution that caters to their diverse software requirements, without compromising on the quality and performance of the user experience.

I believe this would be a valuable addition to your product lineup and would make a significant contribution to the Android ecosystem. I am happy to discuss this further or provide any additional feedback that may assist in the development of this enhanced offering.

Thank you for your consideration, and I look forward to seeing the continued evolution of your products.

**Comment by Hacker1245** [comment]
You do realize the point of box64 is not to provide a complete Linux environment, but a emulation layer right?

**Comment by nooob-developer** [comment]
I wanted to share a constructive suggestion for the future development of your software.
The core of my idea is to expand Box64 beyond just Windows emulation. I think you should look into enabling users to seamlessly run native Linux software on their Android devices as well. Programs like Blender, Steam, and many others have native Linux versions that could potentially provide a better experience than their Windows counterparts running under emulation.

Plus, for certain high-performance apps like games (think Team Fortress 2 or Dota 2), a native Linux environment could offer significantly better performance than the emulated Windows versions. That could be a game-changer for users who need that extra horsepower on the go.

By incorporating support for a full-fledged Linux distro, alongside the existing Windows emulation, Box64 could become an even more versatile and comprehensive solution. Users would be able to access both the Windows apps they need, as well as the vast library of native Linux programs - all while potentially benefiting from improved performance in certain scenarios.

I reckon this expanded approach would make Box64 an even more valuable tool for Android users. It would allow you to cater to their diverse software needs without compromising on quality or performance.

**Comment by ptitSeb** [comment]
I don't think you nderstand what box64 really is, but it is already what you ask for. It always to run Linux x86_64 games on ARM64 linux. Also, Wine is a Linux application.
I think you are mystaken because box64 on Android, as found in Box64Droid, Box4Droid, Winlater, Mobox or just built on Termux, all focuses on Wine. But that's not a box64 constraint actually.

**Comment by Hacker1245** [comment]
> I don't think you understand what box64 really is, but it is already what you ask for. It always to run Linux x86_64 games on ARM64 linux. Also, Wine is a Linux application. I think you are mystaken because box64 on Android, as found in Box64Droid, Box4Droid, Winlater, Mobox or just built on Termux, all focuses on Wine. But that's not a box64 constraint actually.

you know, I think it's either a bot or they are using ChatGPT to write these replies...

**Comment by ptitSeb** [comment]
> > I don't think you understand what box64 really is, but it is already what you ask for. It always to run Linux x86_64 games on ARM64 linux. Also, Wine is a Linux application. I think you are mystaken because box64 on Android, as found in Box64Droid, Box4Droid, Winlater, Mobox or just built on Termux, all focuses on Wine. But that's not a box64 constraint actually.
> 
> you know, I think it's either a bot or they are using ChatGPT to write these replies...

Yes, it looks like AI generated question. But there is still a legitimate question behind the AI one I guess. And that's what I'm trying to answer.

**Comment by nooob-developer** [comment]
I'm sorry, I thought my speech would be more understandable with the help of Ai

thanks for your answering

This [link](https://github.com/ptitSeb/box64/blob/main/docs/X64WINE.md) helps me how to install wine64

How can I access glib etc. to install Steam Linux with the help of box64?

**Comment by m1m1k4tz** [comment]
https://box64droid.com/running-steam-games-on-box64droid/

https://www.youtube.com/watch?v=AsOcUtbRuQ4

I hope this solves your issue!

**Comment by nooob-developer** [comment]
thanks
