### ISSUE TITLE
Compile statically

### ISSUE THREAD

**Issue by DUOLabs333** [ptitSeb/box64#146]
I want to use this in a chroot, but this requires that the interpreter is statically linked inside the executable

**Comment by DUOLabs333** [comment]
That may be a problem -- alternatively, does box64 has some sort of overlay, so programs can access both libraries? For example, trying to run x86_64 bash gives me 
```
Error: Global Symbol tfind not found, cannot apply R_X86_64_GLOB_DAT @0xffff9cc151e8 ((nil)) in /home/system/Downloads/WINE/lib/libncursesw.so.6
```

**Comment by wuzw10** [comment]
Still failed to statically compile box64 (v0.2.8).

**Comment by ptitSeb** [comment]
> Still failed to statically compile box64 (v0.2.8), my cmake options is `STATIC_BUILD=ON`.

And what are you errors?

**Comment by wuzw10** [comment]
> > Still failed to statically compile box64 (v0.2.8), my cmake options is `STATIC_BUILD=ON`.
> 
> And what are you errors?

Here is the error report:
```
/root/box64-0.2.8/src/wrapped/wrappedlibbsd_private.h:5:4: error: ‘arc4random’ undeclared here (not in a function); did you mean ‘srandom’?
    5 | GO(arc4random, uFv)
      |    ^~~~~~~~~~
/root/box64-0.2.8/src/wrapped/wrappedlib_init.h:48:30: note: in definition of macro ‘GO’
   48 | #define GO(N, W) {#N, W, 0, &N},
      |                              ^
/root/box64-0.2.8/src/wrapped/wrappedlibbsd_private.h:7:4: error: ‘arc4random_buf’ undeclared here (not in a function); did you mean ‘arc4random_stir’?
    7 | GO(arc4random_buf, vFpL)
      |    ^~~~~~~~~~~~~~
/root/box64-0.2.8/src/wrapped/wrappedlib_init.h:48:30: note: in definition of macro ‘GO’
   48 | #define GO(N, W) {#N, W, 0, &N},
      |                              ^
/root/box64-0.2.8/src/wrapped/wrappedlibbsd_private.h:9:4: error: ‘arc4random_uniform’ undeclared here (not in a function); did you mean ‘arc4random_stir’?
    9 | GO(arc4random_uniform, uFu)
      |    ^~~~~~~~~~~~~~~~~~
/root/box64-0.2.8/src/wrapped/wrappedlib_init.h:48:30: note: in definition of macro ‘GO’
   48 | #define GO(N, W) {#N, W, 0, &N},
      |                              ^
make[2]: *** [CMakeFiles/box64.dir/build.make:764: CMakeFiles/box64.dir/src/wrapped/wrappedlibbsd.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:342: CMakeFiles/box64.dir/all] Error 2
```
Many thanks!

**Comment by ptitSeb** [comment]
That arc4random has been an issue for some time now. With recent glibc, lib bsd (and many other  libs) are all fused into libc, and some recent build of libstdc++ now use some of those function (and so link will fail if this function is not present). But on older glibc, lib bsd is seperate and barrely used...
Maybe I should just exclude the lib bsd for the statiic build? but I fear it might just fail to load basic stuff in that case...
