### ISSUE TITLE
Anydesk: error initializing needed lib

### ISSUE THREAD

**Issue by dxwil** [ptitSeb/box64#1501]
I added some x86 binaries that were originally not wrapped and needed to be emulated, but I still can't launch anydesk.

[dxwil@asahi ~]$ anydesk
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT PageSize:16384 Running on Icestorm-M1 Firestorm-M1 with 8 Cores
Will use Hardware counter measured at 24.0 MHz emulating 3.0 GHz
Params database has 68 entries
Box64 with Dynarec v0.2.7 85458d1f built on May  2 2024 17:31:47
BOX64: Detected 48bits at least of address space
Counted 60 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/home/dxwil/.local/bin/:/home/dxwil/bin/:/usr/local/bin/:/usr/bin/:/usr/local/sbin/:/usr/sbin/
Looking for /home/dxwil/.local/bin/anydesk
Rename process to "anydesk"
Using native(wrapped) libgtk-x11-2.0.so.0
Using native(wrapped) libgdk-x11-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libatk-1.0.so.0
Using native(wrapped) libcairo.so.2
Using native(wrapped) libpangoft2-1.0.so.0
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libexpat.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using emulated /lib/x86_64-linux-gnu/libpolkit-gobject-1.so.0
Using native(wrapped) libXrender.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libxcb-shm.so.0
Using native(wrapped) libpthread.so.0
Using native(wrapped) libXi.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXtst.so.6
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXdamage.so.1
Using emulated /lib/x86_64-linux-gnu/libxkbfile.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libGLU.so.1
Using native(wrapped) libresolv.so.2
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) libbsd.so.0
Error: Symbol XkbAddGeomColor not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025b88 (0x40a0) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAddGeomKey not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025ba0 (0x40d0) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAddGeomRow not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025bf8 (0x4180) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAllocClientMap not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025c00 (0x4190) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAddGeomSection not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025c08 (0x41a0) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbGetCompatMap not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025c38 (0x4200) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAddGeomProperty not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025c58 (0x4240) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAddGeomOverlayRow not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025c60 (0x4250) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAddGeomDoodad not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025cb0 (0x42f0) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbSetIndicatorMap not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025ce0 (0x4350) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbGetIndicatorMap not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025da0 (0x44d0) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbSetGeometry not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025de0 (0x4550) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAddGeomOutline not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025e00 (0x4590) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbGetGeometry not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025e48 (0x4620) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAddGeomOverlay not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025ea8 (0x46e0) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAddGeomShape not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025ec0 (0x4710) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAllocGeometry not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025ec8 (0x4720) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: Symbol XkbAllocServerMap not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff01025ee8 (0x4760) in /lib/x86_64-linux-gnu/libxkbfile.so.1
Error: relocating Plt symbols in elf libxkbfile.so.1
Error initializing needed lib libpango-1.0.so.0
Using emulated /lib/x86_64-linux-gnu/libsystemd.so.0
Using native(wrapped) libcap.so.2
Using emulated /lib/x86_64-linux-gnu/liblz4.so.1
Using native(wrapped) liblzma.so.5
Using emulated /lib/x86_64-linux-gnu/libzstd.so.1
Warning: Weak Symbol ZSTD_trace_decompress_end not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff060bdc68 (0x40a0)
Warning: Weak Symbol ZSTD_trace_compress_begin not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff060bdcd8 (0x4180)
Warning: Weak Symbol ZSTD_trace_compress_end not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff060bdd98 (0x4300)
Warning: Weak Symbol ZSTD_trace_decompress_begin not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff060bdf50 (0x4670)
Warning: Weak Symbol mempool_enabled not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff040eb260 (0x10400)
Error: Symbol cap_get_flag not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff040eb2d0 (0x104e0) in /lib/x86_64-linux-gnu/libsystemd.so.0
Error: Symbol __readlinkat_chk not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff040eb398 (0x10670) in /lib/x86_64-linux-gnu/libsystemd.so.0
Error: Symbol mallinfo2 not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff040eb7d8 (0x10ef0) in /lib/x86_64-linux-gnu/libsystemd.so.0
Error: Symbol __isoc23_strtoull not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff040eb930 (0x111a0) in /lib/x86_64-linux-gnu/libsystemd.so.0
Error: Symbol __isoc23_strtoll not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff040eb960 (0x11200) in /lib/x86_64-linux-gnu/libsystemd.so.0
Error: Symbol epoll_pwait2 not found, cannot apply R_X86_64_JUMP_SLOT @0x7fff040ebdf8 (0x11b30) in /lib/x86_64-linux-gnu/libsystemd.so.0
Error: relocating Plt symbols in elf libsystemd.so.0
Error initializing needed lib libgobject-2.0.so.0
Error loading one of needed lib
Error initializing needed lib libxcb-shm.so.0
Error loading one of needed lib
Error: Loading needed libs in elf /home/dxwil/.local/bin/anydesk

**Comment by dxwil** [comment]
Would it be possible to add these symbols or needed libs?

**Comment by LukeShortCloud** [comment]
The zstandard library is very complex and hard to wrap. We're aiming to ship the required x86_64 library file in the next release of Box64 which should fix your issue.
