### ISSUE TITLE
Installing box64rc configurations

### ISSUE THREAD

**Issue by spwly** [ptitSeb/box64#1502]
Hello, I'm having trouble installing the box64rc file. I understood the explanation in the readme as copying the file from /system to /etc, but don't think the settings are taking. Is there a different procedure here I'm missing? Apologies as I am still learning Linux and github.

**Comment by ptitSeb** [comment]
If `/etc/box64.box64rc` exist, box64 will read it. This file should be copied automatically when ypu do `sudo make install`

Note that there is also this file that is used: `~/.box64rc` This file is in your home (that's what `~` means) and can be writen without sudo. Box64 will read first the one from etc, than the one from your home (and if a program is in both file, only the settings from the home one will be applied).

**Comment by spwly** [comment]
Thanks - renaming the home file box64.box64rc to just ".box64rc" solved my issue. The configurations are now showing in the terminal when I run my program!
