### ISSUE TITLE
Wine on an M1 doesn’t show the toolbar

### ISSUE THREAD

**Issue by m1m1k4tz** [ptitSeb/box64#1509]

**Comment by ptitSeb** [comment]
you are using krun or some way to have 4k pagesize I suppose?

**Comment by m1m1k4tz** [comment]
Yeah, I’m using krun from this guide but I didn’t do fex emu https://gist.github.com/teohhanhui/042a395010d9946ceee14768736e3780

**Comment by m1m1k4tz** [comment]
I don’t think this is a box64 bug
