### ISSUE TITLE
Right clicking in the wine registry editor is broken on m1

### ISSUE THREAD

**Issue by m1m1k4tz** [ptitSeb/box64#1510]
Also, the same thing happens when trying my to change the windows version but the workaround is to use arrow keys buttons are glitchy as well

**Comment by ptitSeb** [comment]
Are you sure those issues are related to box64?

**Comment by m1m1k4tz** [comment]
I’m not sure if it happens in fex too because I’ve never actually installed it

**Comment by ptitSeb** [comment]
I mean, it might be a 4k pagesize emulation issue, or some side effect of it. Maybe you should also open a ticket in the krun project too?

**Comment by m1m1k4tz** [comment]
@teohhanhui could you test this in fed and see if it happens there too?

**Comment by m1m1k4tz** [comment]
Okay I just tried and this happens in hangover too so I reported it in krun

**Comment by LukeShortCloud** [comment]
This appears to be an issue outside of Box64. Closing.
