### ISSUE TITLE
Mouse not working when using keyboard when using apple silicon 

### ISSUE THREAD

**Issue by m1m1k4tz** [ptitSeb/box64#1515]
Not sure if this is a krun issue or box64 but it works fine on x86_64

**Comment by m1m1k4tz** [comment]
Once hangover gets 64 bit support all these wine issues might not even matter it would just be specific to games

**Comment by m1m1k4tz** [comment]
But for sure this one only happens when using box64 I’ve seen asahi Lina play games fine on fex emu

**Comment by ptitSeb** [comment]
I don't understand how box64 could introduce lag. I'll have to test myself. Was the game tested the same you tested yourself?

**Comment by m1m1k4tz** [comment]
No and it was also using proton so it wasn’t the new wow64 mode but on native wine it works fine so I’m thinking it can’t be krun or wine

**Comment by m1m1k4tz** [comment]
Also I’m not sure the steam app works without dxvk thru wine with the new wow64 mode

**Comment by ptitSeb** [comment]
32bits on Wow64 with OpenGL (and so with wined3d) will be slow for now. That may be the source of the lag.

**Comment by m1m1k4tz** [comment]
It was weird because it felt fast when moving with the keyboard but the mouse felt laggy not sure why

**Comment by m1m1k4tz** [comment]
I tried to test a controller but it’s broken with krun

**Comment by m1m1k4tz** [comment]
The game was fallout 3 but it was kinda janky to get working without steam btw the steam app on x86 works fine for me natively on wine

**Comment by m1m1k4tz** [comment]
This was a missing gstreamer plugin issue my bad

**Comment by m1m1k4tz** [comment]
Nevermind that was the fix on hangover but not boxwine

**Comment by m1m1k4tz** [comment]
[box64.txt](https://github.com/ptitSeb/box64/files/15506166/box64.txt)

**Comment by m1m1k4tz** [comment]
@teohhanhui this might be related to the pulse audio issue as there’s a bunch of quartz errors is there any guide for getting it working?

**Comment by m1m1k4tz** [comment]
Never mind even with the audio working I get quartz errors had to re follow your guide for sound

**Comment by m1m1k4tz** [comment]
Okayyy it’s actually that the mouse works fine until you use the keyboard for some reason

**Comment by m1m1k4tz** [comment]
Just tried in half life 1 and the same thing happens the mouse won’t work if you use keyboard

**Comment by ptitSeb** [comment]
I am pretty sure this is not a box64 issue.

**Comment by m1m1k4tz** [comment]
Im not sure yet bc krunvm works fine for other people with fex emu 🤔

**Comment by m1m1k4tz** [comment]
I dont get it though what could make it disable the mouse while using the keyboard

**Comment by ptitSeb** [comment]
> Im not sure yet bc krunvm works fine for other people with fex emu 🤔

With the same Wine? because box64 need new Wow64 while FEX does not.

**Comment by ptitSeb** [comment]
If you meant the touchpad, I think that's by-design, to avoid  unvolontary mouse move while typing.

**Comment by m1m1k4tz** [comment]
I think I remember this being a KDE thing I wasn’t sure because I just switched to try it out
