### ISSUE TITLE
[Steam] Games with native linux and proton support don't work

### ISSUE THREAD

**Issue by aleytus** [ptitSeb/box64#1516]
https://youtu.be/qy-LxhjDteM
The distro was customized https://github.com/waydroid/waydroid/issues/1206#issuecomment-2041641964

**Comment by ptitSeb** [comment]
It looks working, mostly, to me.

You might need to create `~/.box64rc` to setup custom parameters from some of those of game.
Like Subnautica, you might need to strongmem (when game freeze, you need to use BOX64_DYNAREC_STRONGMEM=1` or 2 if needed.

Some game just don't work yet.

And please, I cannot use a video to debug things. I need logs.

**Comment by aleytus** [comment]
Standard linux games don't work here https://github.com/ptitSeb/box64/issues/1388 also mentions this

**Comment by aleytus** [comment]
Maybe I'll give you access to vnc!?

**Comment by ptitSeb** [comment]
> Standard linux games don't work here #1388 also mentions this

This ticket is specific to CS2.

I do play a lot of game from Steam on my side, but I can confirm some game just don't work yet. But many do works actually.

**Comment by aleytus** [comment]
OK Subnautica is up and running
Is there any way to run skyrim and games for linux?

**Comment by aleytus** [comment]
> And please, I cannot use a video to debug things. I need logs.

There are instructions on how to get the log?
