### ISSUE TITLE
Error compiling box64 0.2.8 with GCC 13.3.0 within Buildroot

### ISSUE THREAD

**Issue by rtissera** [ptitSeb/box64#1551]
Target : AArch64 generic , RPI5ARM64, others...

Box64 0.2.6 compiles just fine in the same environment.
Box64 0.2.8 errors on custommem.c :

Building C object CMakeFiles/box64.dir/src/custommem.c.o
{standard input}: Assembler messages:
{standard input}:7113: Error: symbol `mmap64' is already defined
make[3]: *** [CMakeFiles/box64.dir/build.make:439: CMakeFiles/box64.dir/src/custommem.c.o] Error 1

Any idea ?

**Comment by ptitSeb** [comment]
`custommem.c` define a overloaded `mmap64` symbol, over libc one. It's important for the `BOX64_MMAP32=1` handling. If it doesn't work for you, you can comment lines 1720-1740 of that file, but then this function will not work...

**Comment by ptitSeb** [comment]
Never seen this issue before. And overloading function is pretty common...
Maybe those 2 function (mmap and munmap) should be moved to a separate file, with limited include file to avoid declaration of libc mmap64?

**Comment by jserv** [comment]
Should this issue be closed?
