### ISSUE TITLE
Witcher 3 unimplemented opcode

### ISSUE THREAD

**Issue by Heasterian** [ptitSeb/box64#156]
I'm trying to start it with Proton 5.9 GE

Here is opcode.

```
410104|0x14002720d: Unimplemented Opcode (8B) CE E8 0D 42 E5 00 48 89 B7 30 18 01 00 48 8B
```

**Comment by ptitSeb** [comment]
The "CE" opcode is not a correct one. but 8B CE is. I suppose one of the previous opcode decode incorectly, but it's not on the minidump.

**Comment by Heasterian** [comment]
It's hard to navigate on that small screen so I'm leaving here whole dump for now. [Witcher3_dump.zip](https://github.com/ptitSeb/box64/files/7486860/Witcher3_dump.zip)

**Comment by LukeShortCloud** [comment]
This game has been working on Arm for awhile now. As of this year, it even works on RISC-V.

https://box86.org/2024/08/box64-and-risc-v-in-2024/

Closing as resolved.
