### ISSUE TITLE
When using the fallout 3 launcher the program exits instead of launching fallout 

### ISSUE THREAD

**Issue by m1m1k4tz** [ptitSeb/box64#1565]
Hardware is m1 using krun

**Comment by m1m1k4tz** [comment]
You need a registry hack to get this working so I would just get it going thru steam first

**Comment by ptitSeb** [comment]
I have ran Fallout4 Steam and GOG version on a Ampere machine and an X13s. Not sure the issue is from box64. I may need to try with latest box64 version in case I introduced a regression.

**Comment by m1m1k4tz** [comment]
This is fallout 3 which is older and I’m using krun with the m1

**Comment by m1m1k4tz** [comment]
I don’t think this is a box64 issue
