### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by AndreySV** [ptitSeb/box64#157]
I see that only X11 libraries are wrapped. It'd be nice to get wayland support as well.

**Comment by rajdakin** [comment]
Please provide the required functions. Most (if not all) functions supported by box are functions which are used by games or other programs, which are then added after trying to start the program and looking at the list of unsupported functions.
If you want to add them then do a PR to box (and have sufficient programming knowledge, which consists of knowing how to read a function signature), [I have written a "tutorial"/how-to guide on box86.org](https://box86.org/2024/02/how-to-create-a-wrapping/).

**Comment by ptitSeb** [comment]
Also, Wayland support has been added in box64 lately. Enough to launch wine-wayland.
