### ISSUE TITLE
Precompiled builds no longer work. 

### ISSUE THREAD

**Issue by rom4ster** [ptitSeb/box64#1576]
The instructions for ryanfortner precomp builds result in "Unable to locate package". 

Probably has to do with him redirecting his domain or something. 

Could I suggest making a pipeline or something for precompiled builds. I really dont want to have to compile anything on my raspberry pi because it takes forever.

**Comment by ptitSeb** [comment]
Cab you open a ticket at ryanfortne repo about this?

About the pipeline, you want to do a PR bout it?

**Comment by rom4ster** [comment]
I dont know how. I cant even get this to work on my local PI .

**Comment by m1m1k4tz** [comment]
It is kinda weird how the artifacts don’t get uploaded I checked the release.yml and I can’t figure out why. Unable to locate package sounds like an apt issue though are you using the correct distribution and are 32 bit packages enabled?
