### ISSUE TITLE
Valheim Dedicated Server - Unimplemented Opcode (E5) FE 97 60 02 40 F9 64 E3 FE 97 E0 FF FF 17 1F

### ISSUE THREAD

**Issue by highland-joe** [ptitSeb/box64#158]
I am running Valheim Dedicated Server on Raspberry Pi 4 (8MB)
- Raspberry Pi OS 11 64bit (bullseye)
- Box64 with Dynarec v0.1.5 f73e419 built on Nov  6 2021 19:34:36

Recently I ran into these errors, both referencing the same "Unimplemented Opcode"

> Nov 07 14:51:41 raspi4 vstart.sh[463]: 11/07/2021 14:51:41: clone 2195
Nov 07 14:51:41 raspi4 vstart.sh[463]:
Nov 07 14:51:41 raspi4 vstart.sh[463]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
Nov 07 14:51:43 raspi4 vstart.sh[463]: * Assertion at class.c:8919, condition `ac->rank' not met
Nov 07 14:51:43 raspi4 vstart.sh[463]: * Assertion at class.c:8919, condition `ac->rank' not met
Nov 07 14:51:43 raspi4 vstart.sh[463]: 0463|0x64956d7a: Unimplemented Opcode (E5) FE 97 60 02 40 F9 64 E3 FE 97 E0 FF FF 17 1F
Nov 07 14:51:43 raspi4 vstart.sh[430]: /home/valheim/Valheim/vstart.sh: line 12:   463 Aborted
--------------------------------------
> Nov 08 07:08:21 raspi4 vstart.sh[2694]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
Nov 08 07:08:23 raspi4 vstart.sh[2694]: ghashtable.c:236: assertion 'hash != NULL' failed
Nov 08 07:08:23 raspi4 vstart.sh[2694]: * Assertion at boehm-gc.c:1686, condition `GC_base (obj) == (char*)obj - offset' not met
Nov 08 07:08:23 raspi4 vstart.sh[2694]: 2694|0x64956d7a: Unimplemented Opcode (E5) FE 97 60 02 40 F9 64 E3 FE 97 E0 FF FF 17 1F
Nov 08 07:08:23 raspi4 vstart.sh[2693]: /home/valheim/Valheim/vstart.sh: line 12:  2694 Aborted

Can you please help me with this?

**Comment by highland-joe** [comment]
Still experiencing this frequently, this time with another "Unimplemented Opcode". 

`Nov 14 16:18:49 raspi4 vstart.sh[13537]: Unloading 24 unused Assets to reduce memory usage. Loaded Objects now: 1121610.
Nov 14 16:18:49 raspi4 vstart.sh[13537]: Total: 2798.544943 ms (FindLiveObjects: 411.538759 ms CreateObjectMapping: 90.065148 ms MarkObjects: 2293.256313 ms  DeleteObjects: 3.681148 ms)
Nov 14 16:18:53 raspi4 vstart.sh[13537]: 11/14/2021 16:18:53: clone 4284
Nov 14 16:18:53 raspi4 vstart.sh[13537]:
Nov 14 16:18:53 raspi4 vstart.sh[13537]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
Nov 14 16:18:58 raspi4 vstart.sh[13537]: * Assertion at class.c:8919, condition ``ac->rank' not met
Nov 14 16:18:58 raspi4 vstart.sh[13537]: 13713|0x64956d88: Unimplemented Opcode (F9) 2E E5 FE 97 60 02 40 F9 60 E3 FE 97 E0 FF FF
Nov 14 16:18:59 raspi4 vstart.sh[13536]: /home/valheim/Valheim/vstart.sh: line 12: 13537 Aborted`

**Comment by ptitSeb** [comment]
The unimplemented opcode is probably just an consequence of the assert.
I'll try investigate that assert.

**Comment by highland-joe** [comment]
I have another error leading to the same Unimplemented Opcode:

`Nov 16 20:09:57 raspi4 vstart.sh[13726]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
Nov 16 20:09:59 raspi4 vstart.sh[13726]: * Assertion: should not be reached at class-accessors.c:73 
Nov 16 20:09:59 raspi4 vstart.sh[13726]: 13726|0x64956d88: Unimplemented Opcode (F9) 2E E5 FE 97 60 02 40 F9 60 E3 FE 97 E0 FF FF
Nov 16 20:09:59 raspi4 vstart.sh[13725]: /home/valheim/Valheim/vstart.sh: line 12: 13726  #Aborted`

I agree that it's probably consquence of the assertion errors.

**Comment by ptitSeb** [comment]
Can you retry now?

**Comment by highland-joe** [comment]
Running `Box64 with Dynarec v0.1.6 1874c57 built on Nov 21 2021 15:31:45` since sunday, no more crashes. Seems to run quite stable now. I would keep it runnintg and see what happens, before I switch to the latest build.

**Comment by highland-joe** [comment]
no more crashes, I updated today to:
`Box64 with Dynarec v0.1.7 40c5824 built on Nov 25 2021 13:05:27`
`Valheim Dedicated Server 0.205.5`
I will see, if it's still stable and eventually close the issue.

**Comment by highland-joe** [comment]
Congrats, server is running stable for over a week now running box64 v0.1.7, issue can be closed, thanks for the great support
