### ISSUE TITLE
Error loading needed lib UnityPlayer.so

### ISSUE THREAD

**Issue by tmahlstrom** [ptitSeb/box64#1580]
I'm trying to run my own Unity game on my Pi 4. It looks like it's not able to find UnityPlayer.so. 

Is that something I need to install separately? Apologies as I'm new to many of these things. 

[user]@ledpi:~/Documents $ ./test_linux_1.x86_64 
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 25 entries
Box64 with Dynarec v0.2.4 45c4117a built on Jun 12 2024 10:33:04
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 36 Env var
Looking for ./test_linux_1.x86_64
Rename process to "test_linux_1.x86_64"
Error loading needed lib UnityPlayer.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Error loading one of needed lib
Error: loading needed libs in elf /home/[user]/Documents/test_linux_1.x86_64

**Comment by ptitSeb** [comment]
is this lib `UnitPlayer.so` present?

**Comment by tmahlstrom** [comment]
I can't find it. Tried `ldconfig -p | grep UnityPlayer.so`. 

Again, total linux amateur here. Is there a simple way to install it? sudo apt install doesn't work. Should I have to do this, or is it fishy that I would have to do this at all? 

Very much appreciate the help.

**Comment by tmahlstrom** [comment]
Welp, UnityPlayer.so is created by Unity when it builds Linux games. I just wasn't carrying that over to the Pi.

Thanks.
