### ISSUE TITLE
Error during linking in build

### ISSUE THREAD

**Issue by theofficialgman** [ptitSeb/box64#1586]
https://github.com/Pi-Apps-Coders/box64-debs/actions/runs/9511573266/job/26217953856#step:7:916

```
[100%] Linking C executable box64
CMakeFiles/box64.dir/src/tools/my_cpuid.c.o: In function `helper_getcpu':
/__w/box64-debs/box64-debs/box64/src/tools/my_cpuid.c:475: undefined reference to `getcpu'
collect2: error: ld returned 1 exit status
make[2]: *** [box64] Error 1
CMakeFiles/box64.dir/build.make:5253: recipe for target 'box64' failed
make[1]: *** [CMakeFiles/box64.dir/all] Error 2
CMakeFiles/Makefile2:341: recipe for target 'CMakeFiles/box64.dir/all' failed
Makefile:165: recipe for target 'all' failed
Failed to run make.
make: *** [all] Error 2
```

**Comment by ptitSeb** [comment]
What target is that? TEGRAX?

**Comment by theofficialgman** [comment]
It fails on the first loop of the ci. So -DARM64=1

**Comment by theofficialgman** [comment]
@ptitSeb getcpu was not added until glibc 2.29 https://man7.org/linux/man-pages/man2/getcpu.2.html

**Comment by theofficialgman** [comment]
Example of a compatible implementation for such systems https://github.com/ggerganov/llama.cpp/blob/21be9cab94e0b5b53cb6edeeebf8c8c799baad03/ggml.c#L2961-L2969

**Comment by ptitSeb** [comment]
Oh, ok, thanks. I remove the getcpu call for old glibc, and kept the "0" in that case that was present before.
