### ISSUE TITLE
‘__int128’ is not supported on this target

### ISSUE THREAD

**Issue by GuckTubeYT** [ptitSeb/box64#159]
So, before i got this error = `uint128_t does not name a type`
and then, when i add
`typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;`
in `src/include/regs.h`
i got this error = `__int128 is not supported on this target`

My phone using arm64
and i run in Termux armv8l Debian armhf
is __int128 is not support for arm?

Sorry if my grammar is bad

**Comment by ptitSeb** [comment]
what is your compiler?

**Comment by GuckTubeYT** [comment]
> 
> 
> what is your compiler?

gcc version 8.3.0

**Comment by GuckTubeYT** [comment]
oh, i just solve the problem

the problem is = because i am using Debian armhf (in termux), when i install userland, and i choose Debian, and the debian is arm64 (not debian armhf), when i try to build on Debian arm64, its work

Because my termux is already armv8l, so i cant install Debian arm64 in termux, thats why i install userland

Sorry for bad grammar
