### ISSUE TITLE
Error initializing native libglib-2.0.so.0 (last dlerror is libglib-2.0.so.0: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by GuckTubeYT** [ptitSeb/box64#160]
So, before i got this error = `Error loading needed lib libpng12.so.0`
And then i download the libpng12.so.0 and i put near Packet Tracer
And then, i got this error = `Error initializing native libglib-2.0.so.0 (last dlerror is libglib-2.0.so.0: cannot open shared object file: No such file or directory)`

Logs
`
Box64 v0.1.5  built on Nov 11 2021 23:40:11
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 17 Env var
Looking for PacketTracer7
Using native(wrapped) libcrypto.so.1
Using emulated libQt5WebKitWidgets.so.5
Using emulated libQt5WebKit.so.5
Using emulated libQt5Multimedia.so.5
Using emulated libQt5PrintSupport.so.5
Using emulated libQt5Svg.so.5
Using emulated libQt5Widgets.so.5
Using emulated libQt5Gui.so.5
Using emulated libQt5Network.so.5
Using emulated libQt5Xml.so.5
Using emulated libQt5Script.so.5
Using emulated libQt5ScriptTools.so.5
Using emulated libQt5Sql.so.5
Using emulated libQt5Core.so.5
Using native(wrapped) libpthread.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated libQt5Sensors.so.5
Using emulated libQt5MultimediaWidgets.so.5
Using emulated libpng12.so.0
Using native(wrapped) libz.so.1
Using emulated libicui18n.so.52
Using emulated libicuuc.so.52
Using native(wrapped) libdl.so.2
Error initializing native libglib-2.0.so.0 (last dlerror is libglib-2.0.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libglib-2.0.so.0
Error loading one of needed lib
Error initializing needed lib libQt5Core.so.5
Error loading one of needed lib
Error initializing needed lib libQt5Gui.so.5
Error loading one of needed lib
Error initializing needed lib libQt5Widgets.so.5
Error loading one of needed lib
Error initializing needed lib libQt5WebKitWidgets.so.5
Error loading one of needed lib
Error: loading needed libs in elf /home/gucktubeyt/pt/bin/PacketTracer7
`

**Comment by GuckTubeYT** [comment]
Should i download `libglib-2.0.so.0` and put near PacketTracer7 like libpng?

**Comment by ptitSeb** [comment]
`libglib2-0.so.0` is wrapped in box86. You probably need to install the arm64 version of it (it's part if gtk) using your distrib package manager.

**Comment by GuckTubeYT** [comment]
Hmmmmm... i just download and put the libglib near packet tracer, but i still get this error
`
Error initializing native libglib-2.0.so.0 (last dlerror is libglib-2.0.so.0: cannot open shared object file: No such file or directory)
`
But i get this message = `Using emulated libglib-2.0.so.0`
So, is it success?

**Comment by ptitSeb** [comment]
Why don't you install it? On Debian/Ubuntu it's `sudo apt install libglib2.0-0`. because glibc is not alone, there will be a few other libs needed, better try to use the native version first.

**Comment by GuckTubeYT** [comment]
> 
> 
> Why don't you install it? On Debian/Ubuntu it's `sudo apt install libglib2.0-0`. because glibc is not alone, there will be a few other libs needed, better try to use the native version first.
> 
> (but yeah, it means it's success: it tried to load the native version first, failed, and falled back to the emulated one wich was found)

but its arm64 lib, is it work? or i should use add architecture i386?

**Comment by GuckTubeYT** [comment]
btw, about libglib is done, now the problem is `Cannot dlopen("Xcursor"/0x66cb5778,1)`
should i install xcursor lib?

**Comment by GuckTubeYT** [comment]
sorry if i am disturbing you

**Comment by GuckTubeYT** [comment]
Thanks, its work

**Comment by ptitSeb** [comment]
Box64 "wraps" some of the system libraries, so ARM64 one can be used instead of x86_64 version. This is what makes box64 (and box86) unique.

So yes, glibc2 from ARM4 will be used for this x86_64 application.

Glad you made it work.
