### ISSUE TITLE
Steam on raspberry pi 5

### ISSUE THREAD

**Issue by JustSomeMagic404** [ptitSeb/box64#1603]
Hello guys. Im totally green in Linux and raspberry pi. I wanted to tinker a bit to learn it and i get a challenge from my friend to install steam on raspberry pi 5 as he said he tried in the last version and failed. 

I followed this guide:  https://www.xda-developers.com/install-steam-on-raspberry-pi/
I am using exactly the same system (Ubuntu 23.10)
I went through all the steps and didnt receive a single error, everything went slowly but smoothly.

When i try to launch steam i am getting this error

> kuba@kuba-desktop:~$ steam
steam.sh[2663]: Running Steam on ubuntu 23.10 64-bit
steam.sh[2663]: STEAM_RUNTIME is enabled by the user
setup.sh[2727]: Steam runtime environment up-to-date!
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Warning, unsupported BOX64_RESERVE_HIGH=1 for [kingdom rush origins] in /etc/box64.box64rc
Params database has 74 entries
Box64 with Dynarec v0.2.9 263e79be built on Jun 18 2024 06:21:17
BOX64: Detected 48bits at least of address space
Counted 62 Env var
BOX64 LIB PATH: /home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/:/lib/aarch64-linux-gnu/:/lib/arm-linux-gnueabihf/:/usr/local/lib/:/lib/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/lib/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/:./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/bin/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/:/home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/usr/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/:/snap/bin/
Looking for /home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger
argv[1]="--exec-fallback"
argv[2]="--filename=console-linux.txt"
argv[3]="-t"
argv[4]="steam"
Rename process to "srt-logger"
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Error: PltResolver: Symbol  g_log_writer_is_journald(ver 0: g_log_writer_is_journald) not found, cannot apply R_X86_64_JUMP_SLOT 0x617128 (0x404326) in /home/kuba/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger (local_maplib=(nil), global maplib=0x3fc2e170, deepbind=0)
kuba

>

Did i do something wrong on the steps or whats wrong? Please help me guys as i cannot loose the challenge :D 

If You need any additional info please let me know as i am green like i said and i dont know how i can help locate th eissue better.

Thank You very much in advance <3

**Comment by ptitSeb** [comment]
I think you have 2 box64 binary on your system. One that you build from sources, and another one that got launched there and that is older (because it complains of BOX64_RESERVE_HIGH unsupported)

**Comment by ptitSeb** [comment]
But there are some issues with latest steam version anyway, I'm working on it.

**Comment by ptitSeb** [comment]
Ok, it's fixed now, but you need both latest box64 and box86 version.

**Comment by LukeShortCloud** [comment]
Closing as complete.
