### ISSUE TITLE
Missing symbol in Packet Tracer

### ISSUE THREAD

**Issue by GuckTubeYT** [ptitSeb/box64#161]
After i install all requirement on Packet Tracer, and then i got PltResolver Error = `Error: PltResolver: Symbol xcb_shape_query_version(ver 0: xcb_shape_query_version) not found, cannot apply R_X86_64_JUMP_SLOT 0x77689f1410 (0x776890a776) in libQt5XcbQ$
32004|SIGSEGV @0x776ad911f0 (???(0x776ad911f0)) (x64pc=0x3cd53/???:"???", rsp=0x77677cdf38), for accessing 0x776ad911f0 (code=1)`

Packet Tracer Version = 7.2.1 64 Bit (x86_64)

**Comment by ptitSeb** [comment]
Ok, I'll add this wrapped function later.

(wrapping libaries is not 100% magic, I need to declare the function signature for each wrapped function for all wrapped libs. Sometimes, I need to add a new one)

**Comment by GuckTubeYT** [comment]
> 
> 
> Ok, I'll add this wrapped function later.
> 
> (wrapping libaries is not 100% magic, I need to declare the function signature for each wrapped function for all wrapped libs. Sometimes, I need to add a new one)

thanks

**Comment by GuckTubeYT** [comment]
btw, can you teach me how to add symbol?

**Comment by ptitSeb** [comment]
Well, look at the commit I pushed: only `wrappedxcbshape_private.h` was touched, the other files were changed automatically.
Check there https://box86.org/2021/08/a-deep-dive-into-library-wrapping/ for more details on the library wrapping.

**Comment by GuckTubeYT** [comment]
`
Error: Global Symbol xmlIsDigitGroup not found, cannot apply R_X86_64_GLOB_DAT @0x759ab9ae40 ((nil)) in libxslt.so.1
Error: Global Symbol xmlStringText not found, cannot apply R_X86_64_GLOB_DAT @0x759ab9ae88 ((nil)) in libxslt.so.1
Error: Global Symbol xmlIsCombiningGroup not found, cannot apply R_X86_64_GLOB_DAT @0x759ab9aeb0 ((nil)) in libxslt.so.1
Error: Global Symbol xmlStringTextNoenc not found, cannot apply R_X86_64_GLOB_DAT @0x759ab9af08 ((nil)) in libxslt.so.1
Error: Global Symbol xmlIsExtenderGroup not found, cannot apply R_X86_64_GLOB_DAT @0x759ab9af50 ((nil)) in libxslt.so.1
Error: Global Symbol xmlIsBaseCharGroup not found, cannot apply R_X86_64_GLOB_DAT @0x759ab9afa8 ((nil)) in libxslt.so.1
`
Can you add this symbol?

**Comment by ptitSeb** [comment]
I will later.

**Comment by ptitSeb** [comment]
I have added the symbols, but it would be probably better to wrap libxslt.so.1 instead.
But I checked, there is quite a lot of symbol there, so not sure when I'll do that.

**Comment by GuckTubeYT** [comment]
> I have added the symbols, but it would be probably better to wrap libxslt.so.1 instead. But I checked, there is quite a lot of symbol there, so not sure when I'll do that.

Oh, sorry, i didnt know that

**Comment by GuckTubeYT** [comment]
Btw, thanks for add the symbol

**Comment by GuckTubeYT** [comment]
why i got this error = `6699|SIGSEGV @(nil) (???((nil))) (x64pc=0x233d3/???:"???", rsp=0x7766c01938), fo                                                                                        r accessing (nil) (code=1)`

**Comment by GuckTubeYT** [comment]
i install libssl by doing = `sudo apt install libssl-dev`
but i still get this warning message = `Warning, function SSLv23_server_method not found in lib libssl.so.1`

Sorry if my grammar is bad

**Comment by ptitSeb** [comment]
libssl and libcrypto are tricky. The version have changed a lot and the wrapping not always possible. Try to get the x86_64 version of them and put them in the current folder, the x86_64 will be used in priority if they are found.

**Comment by GuckTubeYT** [comment]
> 
> 
> libssl and libcrypto are tricky. The version have changed a lot and the wrapping not always possible. Try to get the x86_64 version of them and put them in the current folder, the x86_64 will be used in priority if they are found.

i got libssl, but its named `libssl.so.1.0.0` not `libssl.so.1`

**Comment by ptitSeb** [comment]
Rename it to the expected name. Same for libcrypto.

**Comment by GuckTubeYT** [comment]
> 
> 
> Rename it to the expected name. Same for libcrypto.

yeah, i try to rename `libssl.so.1.0.0` into `libssl.so.1` but its still doesnt work

**Comment by GuckTubeYT** [comment]
Btw, before i got warning message libssl
![image](https://user-images.githubusercontent.com/56192597/141614516-c21b6a91-b9e6-4282-b85f-dffad330db7c.png)
should i put libssl into /root/pt?

**Comment by GuckTubeYT** [comment]
hmmmmm, when i delete libssl near PacketTracer7, i got message this = `Using native(wrapped) libssl.so.1` and that lib still arm64, not amd64

is it should amd64?

**Comment by GuckTubeYT** [comment]
ah finally, it opened, i just delete the libssl, and then its work

**Comment by GuckTubeYT** [comment]
can you add this symbol = xcb_shape_get_rectangles

**Comment by GuckTubeYT** [comment]
Thanks for add the symbol

**Comment by GuckTubeYT** [comment]
If i get error symbol not found, i will open this issue again

**Comment by GuckTubeYT** [comment]
If i get error symbol not found, i will open this issue again
