### ISSUE TITLE
Help anyone?! When I install Steam on a clean ubunto jammy install  I get this error when I load up steam.

### ISSUE THREAD

**Issue by gelodrizz** [ptitSeb/box64#1610]
steamwebhelper requires the Sniper steam runtime.  Not found at /home/gelo/.local/share/Steam/ubuntu12_64/steam-runtime-sniper, there is a problem with your installation, aborting.

**Comment by ptitSeb** [comment]
diplaicate with #1612  (more detail on this one)

**Comment by Botspot** [comment]
This issue is now solved. Please update Pi-Apps.
