### ISSUE TITLE
steamwebhelper requires the Sniper steam runtime. Not found at /home/paul/.local/share/Steam/ubuntu12_64/steam-runtime-sniper, there is a problem with your installation, aborting.

### ISSUE THREAD

**Issue by gelodrizz** [ptitSeb/box64#1615]
steamwebhelper requires the Sniper steam runtime. Not found at /home/paul/.local/share/Steam/ubuntu12_64/steam-runtime-sniper, there is a problem with your installation, aborting.

**Comment by ptitSeb** [comment]
It's still a dupplicate of #1612 so Im' closing this one again. I don't need 10 copies of the same issue.

**Comment by Botspot** [comment]
This issue is now solved. Please update Pi-Apps.
