### ISSUE TITLE
Error: PltResolver: Symbol cupsSetPasswordCB2 trying to wipe a drive with Active KillDisk

### ISSUE THREAD

**Issue by musiconwax** [ptitSeb/box64#1629]
As the title says, I'm getting an error when I try to wipe a drive with KillDisk. The second I click on the "Erase Drive" button at the top the program closes. Below is the console output from the crash. Any help or direction would be appreciated.

Error: PltResolver: Symbol  cupsSetPasswordCB2(ver 0: cupsSetPasswordCB2) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fff22213400 (0x7fff22006c66) in /opt/lsoft/KillDisk/plugins/printsupport/libcupsprintersupport.so (local_maplib=0x582881e0, global maplib=0x5730e270, deepbind=0)
BreakPad crash
2971|Double SIGSEGV (code=1, pc=0xffff7282c118, addr=0x70, prot=00)!
Sigfault/Segbus while quitting, exiting silently

**Comment by ptitSeb** [comment]
It's a missing symbol, I'll add it soon.

**Comment by ptitSeb** [comment]
Ok, I have added that symbol, it should go farther now.

**Comment by ptitSeb** [comment]
@musiconwax is it fixed now?

**Comment by musiconwax** [comment]
@ptitSeb I have been away on business this week without my macbook. I will be back home Monday and will report.

**Comment by ptitSeb** [comment]
Ok, no problem, thanks!

**Comment by musiconwax** [comment]
Everything works as expected. You are an amazing individual.
