### ISSUE TITLE
Can a host binary file be generated

### ISSUE THREAD

**Issue by sammyzhoumhhh** [ptitSeb/box64#163]
I tried to use thebox64 to successfully run the example“hello x86 world!”, but I didn't see arm binary or intermediate files being generated. I can see that x86 binary files can be run directly on aarch64 architecture. Can I choose to generate binary files? Can one translation be reused?
Did I miss any information? Thanks a lot to help!

**Comment by ptitSeb** [comment]
You need to build box64. Read `docs/COMPILE.md` for more detail.

**Comment by netthier** [comment]
https://stackoverflow.com/questions/11215689/why-does-emulation-have-to-be-done-in-real-time/32202886

**Comment by ptitSeb** [comment]
Oh, ok.
So no, box86 doesn't generate arm intermediary binary.
It's not currently planned to have anything like that.

Also, just to note, many game nowaday use Unity3D/C# (among other things). Those engines generate code on the fly, making static compilation only scenario irrelevent.

**Comment by sammyzhoumhhh** [comment]
> 哦好的。 所以不，box86 不会生成 arm 中间二进制文件。 目前没有计划有这样的事情。
> 
> 另外，请注意，当今许多游戏都使用 Unity3D/C#（除其他外）。这些引擎动态生成代码，使静态编译仅适用
