### ISSUE TITLE
Support `sys_getpgrp` & `sys_getgpid`

### ISSUE THREAD

**Issue by Coekjan** [ptitSeb/box64#1636]
These days I have some x64 applications relying on `sys_getpgrp` & `sys_getgpid`, but current `x64Syscall()` does not implement them.

I am not sure if they should be wrapped or emulated, but if I just wrapped them, my applications seemed working.

**Comment by rajdakin** [comment]
As a quick rule of thumb, if your program doesn't crash, you've probably implemented enough things correctly. Please do a PR (and if what you've done is not good enough, someone will tell you).

Also, this doesn't look like an issue, just a statement. What is/are the question(s)? (There is none in your comment above.)
