### ISSUE TITLE
Symbol __isoc99_scanf(ver 4: __isoc99_scanf@GLIBC_2.7) not found

### ISSUE THREAD

**Issue by huy-nh2x** [ptitSeb/box64#164]
I got this error when ran a program 
`┌──(kali㉿kali)-[~/Desktop]
└─$ ./babyrev_level12_testing1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.5 841003b built on Nov  5 2021 22:51:58
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 57 Env var
Looking for ./babyrev_level12_testing1
argv[1]="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
Using native(wrapped) libcrypto.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
###
###

This license verifier software will allow you to read the flag.
However, before you can do so, you must verify that you are licensed to read flag files!
This program consumes a license key over some communication channel that you must figure out.
You must also figure out (by reverse engineering this program) what that license key is.
Providing the correct license key will net you the flag!
Unfortunately for you, the license key cannot be reversed. You'll have to crack this program.
Changing byte 1/1.
Offset (hex) to change:
Error: PltResolver: Symbol __isoc99_scanf(ver 4: __isoc99_scanf@GLIBC_2.7) not found, cannot apply R_X86_64_JUMP_SLOT 0xffff9ee59fc0 (0xffff9ee570f0) in ./babyrev_level12_testing1
`
I don't know why and how to fix it. Can you guys help me with this issue?

**Comment by ptitSeb** [comment]
Can you retry now?

**Comment by rajdakin** [comment]
Closing now (no reply since last request).
