### ISSUE TITLE
Unimplemented 32bits Opcode (00 00 00 00) 64 66 8D 80 00 00 00 00 0F 10 04 08 0F 10 4C

### ISSUE THREAD

**Issue by KodinGuy08** [ptitSeb/box64#1646]
I am trying to run Supremo on box64. I keep on getting: `6714|0x407798: Unimplemented 32bits Opcode (00 00 00 00) 64 66 8D 80 00 00 00 00 0F 10 04 08 0F 10 4C.
`

I am using Raspbian Bookworm with wine 9.3
Here is the full log with BOX64_LOG=1: [log.txt](https://github.com/user-attachments/files/16110415/log.txt)

Here is without: 
[log-without-log-argument.txt](https://github.com/user-attachments/files/16110443/log-without-log-argument.txt)

Thank you in advanced :)

**Comment by rajdakin** [comment]
Can this issue be closed now?

**Comment by KodinGuy08** [comment]
Yeah, sorry
