### ISSUE TITLE
`BOX64_DYNAREC_TEST` on RISC-V is Failing

### ISSUE THREAD

**Issue by Coekjan** [ptitSeb/box64#1649]
### Description

I used `BOX64_DYNAREC_TEST` to test box64. And I saw that box64 must have some issues about this flag on RISC-V (it is good on ARM though). Many crashes I met, seems that RISC-V `BOX64_DYNAREC_TEST` cannot correctly handle the programs with PLT Callings. A hello-world program can reproduce the issue.

```console
$ cat hello.c
#include <stdio.h>

int main() {
    puts("Hello World");
    return 0;
}
$ x86_64-linux-gnu-gcc hello.c -o hello
$ BOX64_DYNAREC_TEST=1 box64 ./hello  # here `box64` is running on risc-v.
(( !crash! ))
```

Due to this issue, I cannot move my work forward nearly at all. _Hope we can solve this issue as soon as possible..._

**Comment by ksco** [comment]
Maybe this is a regression. I haven't used `BOX64_DYNAREC_TEST` for a while now. Busy with other things for now, I can check this later if no one fixes it by then.

**Comment by ksco** [comment]
So I found the issue, submitted a PR above.

**Comment by ksco** [comment]
By the way, currently for RISC-V we don't run tests with cosim in CI, otherwise, this should be caught... The reason for that is some features of x87 are incomplete on RISC-V so cosim complains. And I totally forgot about this... Anyway will do it maybe tomorrow.

**Comment by Coekjan** [comment]
Thanks very very much!! You really save my life.

**Comment by ksco** [comment]
lol, happy to hear that. Out of curiosity, you're doing some research projects related to box64?

**Comment by Coekjan** [comment]
> Out of curiosity, you're doing some research projects related to box64?

Yes. Something about dynamic binary translation.

**Comment by Coekjan** [comment]
Honestly, I have investigated this issue for 2 days. I saw something wrong about test pc, but could not find out how to solve it. Thanks again, you save my life!!
