### ISSUE TITLE
DanserGo: need help with acquiring Shared Object files

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [ptitSeb/box64#1651]
I am getting lots of errors and end up using the .so files i got from Debian Bookworm x64(Qemu + Proot in termux), i think getting danser to work can be possible but you will need ALOT of external .so files that i cant find, here is the log:

~/danserosu $ box64 danser
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A55 with 8 Cores
Hardware counter to slow (0 kHz), not using it
Will use Software counter measured at 1.0 GHz emulating 2.0 GHz
Params database has 69 entries
Box64 with Dynarec v0.2.8  built on Jun  8 2024 16:34:26
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 37 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/data/data/com.termux/files/usr/glibc/bin/:/data/data/com.termux/files/usr/bin/
Looking for danser
Rename process to "danser"
Using emulated libdanser-core.so
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) libresolv.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Error initializing native libGL.so.1 (last dlerror is libGL.so.1: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libGL.so.1
Error initializing native libX11.so.6 (last dlerror is libX11.so.6: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libX11.so.6
Using emulated libbass.so
Using emulated libbass_fx.so
Using emulated libbassmix.so
Error initializing native libgtk-3.so.0 (last dlerror is libgtk-3.so.0: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libgtk-3.so.0
Error initializing native libglib-2.0.so.0 (last dlerror is libglib-2.0.so.0: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libglib-2.0.so.0
Using native(wrapped) libm.so.6
Using emulated libyuv.so
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libpcre2-8.so.0
Error initializing native libgdk-3.so.0 (last dlerror is libgdk-3.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libgdk-3.so.0
Error initializing native libgmodule-2.0.so.0 (last dlerror is libgmodule-2.0.so.0: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
Error initializing native libgobject-2.0.so.0 (last dlerror is libgobject-2.0.so.0: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libgobject-2.0.so.0
Error initializing native libgio-2.0.so.0 (last dlerror is libgio-2.0.so.0: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libgio-2.0.so.0
Error initializing native libpangocairo-1.0.so.0 (last dlerror is libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libpangocairo-1.0.so.0
Error initializing native libpango-1.0.so.0 (last dlerror is libpango-1.0.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libpango-1.0.so.0
Error initializing native libharfbuzz.so.0 (last dlerror is libharfbuzz.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libharfbuzz.so.0
Error initializing native libcairo.so.2 (last dlerror is libcairo.so.2: cannot open shared object file: No such file or directory)
Error loading needed lib libcairo.so.2
Error initializing native libpangoft2-1.0.so.0 (last dlerror is libpangoft2-1.0.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libpangoft2-1.0.so.0
Error initializing native libfontconfig.so.1 (last dlerror is libfontconfig.so.1: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libfontconfig.so.1
Error loading needed lib libfribidi.so.0
Error initializing native libcairo-gobject.so.2 (last dlerror is libcairo-gobject.so.2: cannot open shared object file: No such file or directory)
Error loading needed lib libcairo-gobject.so.2
Error initializing native libgdk_pixbuf-2.0.so.0 (last dlerror is libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libgdk_pixbuf-2.0.so.0
Error initializing native libatk-1.0.so.0 (last dlerror is libatk-1.0.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libatk-1.0.so.0
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libepoxy.so.0
Error initializing native libXi.so.6 (last dlerror is libXi.so.6: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libXi.so.6
Error initializing native libatk-bridge-2.0.so.0 (last dlerror is libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory)
Error loading needed lib libatk-bridge-2.0.so.0
Error initializing native libXfixes.so.3 (last dlerror is libXfixes.so.3: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libXfixes.so.3
Error loading one of needed lib
Error initializing needed lib libm.so.6
Error initializing native libxcb.so.1 (last dlerror is libxcb.so.1: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libxcb.so.1
Error initializing native libXau.so.6 (last dlerror is libXau.so.6: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libXau.so.6
Error initializing native libXdmcp.so.6 (last dlerror is libXdmcp.so.6: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libXdmcp.so.6
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libGLdispatch.so.0
Error initializing native libGLX.so.0 (last dlerror is libGLX.so.0: cannot open shared object file: No such file or directory)
Using emulated /data/data/com.termux/files/usr/glibc/lib/x86_64-linux-gnu/libGLX.so.0
Error loading one of needed lib
Error initializing needed lib libc.so.6
Error loading one of needed lib
Error: Loading needed libs in elf /data/data/com.termux/files/home/danserosu/danser
~/danserosu $

The unknown libraries are mostly in the start of the log file.

**Comment by ptitSeb** [comment]
You need to install the ARM64 version of those libs, box64 will use them.

**Comment by GuythatUhmCreatesRandomStuff** [comment]
> You need to install the ARM64 version of those libs, box64 will use them.

I tried compiling it with Go but i am missing GLX and proot is slow for me, it seems i cant find the arm64 versions of the libs on termux and have to use the proot, i installed an ubuntu arm64 proot to compile it there instead with the required libs to see if it even works to begin with, maybe after compiling i can copy the lib folder to the termux danser folder if it exists.

**Comment by ptitSeb** [comment]
> > You need to install the ARM64 version of those libs, box64 will use them.
> 
> I tried compiling it with Go but i am missing GLX and proot is slow for me, it seems i cant find the arm64 versions of the libs on termux and have to use the proot, i installed an ubuntu arm64 proot to compile it there instead with the required libs to see if it even works to begin with, maybe after compiling i can copy the lib folder to the termux danser folder if it exists.

You just need to install those library in your ubuntu proot. libxcb, libGLX... Those are standard opngl and X11 library, nothing special here.

Closing the ticket. Fell free to open a new ticket it if you still have issue with box64.
