### ISSUE TITLE
Error while trying to install dotnet 8

### ISSUE THREAD

**Issue by hongtm77** [ptitSeb/box64#1669]
Hi, i was trying to install a basic program that requires dotnet 8, and got the following error message:-

![image](https://github.com/ptitSeb/box64/assets/67082163/0a3b901d-0db3-4cac-ad0f-9edce6248111)

What is status 17 means ya? 

My current setup is installed wine and box64 from pi-apps onto my switch ubuntu.

Appreciate for the help

**Comment by hongtm77** [comment]
Hi, how do i install .net 8 on the system ya? I tried to install a program, and it requires .net 8.0.7 and i downloaded it. After that i tried to install using Wine Program Manager and nothing happened. I tried several times and after more than 5 mins no pop up said already installed or something. Then i tried installing the previous program, it says required .net 8.0.7. Is there another way to install the .net 8.0.7?

**Comment by ptitSeb** [comment]
duplicate of #1660
