### ISSUE TITLE
Kerbal Space Program hangs on 'Calling __dup2 (/usr/lib/libc.so.6)(0x7, 0x1, 0x0, ...) =>'

### ISSUE THREAD

**Issue by Itai-Nelken** [ptitSeb/box64#167]
Here is the `LOG2` output (it's 25mb, so I had to compress it):
[log2.zip](https://github.com/ptitSeb/box64/files/7570197/log2.zip)
There are no errors with `LOG1`.

**Comment by ptitSeb** [comment]
It's not hangig at "__dup2", it's just that this function redirect stdout, so you don't see anything anymore on the console.
Use `BOX64_TRACE_FILE=trace.txt` to have box64 log in a file directly.

**Comment by Itai-Nelken** [comment]
I updated box64 and it's working now. Anyway the tracw dile would be over 5gb.

**Comment by ptitSeb** [comment]
Ah it's working now? Nice!!!
Maybe it's the new STRONGMEM emulation? Does this one use `libmonobdwgc-2.0.so`?

**Comment by bbbruni** [comment]
@Itai-Nelken 
I'm trying to re-phrase ptitSeb
1) Could you please say if rinning `$ BOX86_DYNAREC_STRONGMEM=0 ./ksp.x64` crashes (or whatever KSP executable is called)?
2) Could you please say if running  `$ grep libmonobdwgc trace.txt` gives an output?

**Comment by ptitSeb** [comment]
easier: do `find . -name libmonobdwgc-2.0.so` from the root of the installed folder ;)

**Comment by Itai-Nelken** [comment]
> easier: do `find . -name libmonobdwgc-2.0.so` from the root of the installed folder ;)

It isn't found.
