### ISSUE TITLE
error: only one operation may be used at a time

### ISSUE THREAD

**Issue by ZeeVanjul** [ptitSeb/box64#1714]
![Screenshot_20240807-150325_Termux_X11](https://github.com/user-attachments/assets/22b98a82-f938-4132-87f1-e772898a8327)

any help? im using arch64 chroot

**Comment by ptitSeb** [comment]
Why are you using `pacman` to run `cmake`? also, cmake doesn't need sudo.

**Comment by ZeeVanjul** [comment]
> Why are you using `pacman` to run `cmake`? also, cmake doesn't need sudo.

im sorry i wass beginner about that,, the problem already solved, 

![Screenshot_20240807-235853_Termux_X11](https://github.com/user-attachments/assets/59bf14a1-407b-41d8-a0f1-905219d82c91)

**Comment by ptitSeb** [comment]
So you got it working? ticket can be closed?
