### ISSUE TITLE
Steam - Unimplemented Opcode (02) DD 28 46 FF F7 15 FE D5

### ISSUE THREAD

**Issue by KweezyPlay** [ptitSeb/box64#172]
[box64_log2.log](https://github.com/ptitSeb/box64/files/7579692/box64_log2.log)

**Comment by ptitSeb** [comment]
Update your box86 version, it's too old.
Also, this is a box86 dump, not a box64 one.

**Comment by KweezyPlay** [comment]
> Update your box86 version, it's too old. Also, this is a box86 dump, not a box64 one.

anyway, just updated box86, still same problem

**Comment by ptitSeb** [comment]
Strange, steam worked for me last time I checked.  Maybe you are missing a native lib? what OS are you using?

**Comment by KweezyPlay** [comment]
> Strange, steam worked for me last time I checked. Maybe you are missing a native lib? what OS are you using?

Ubuntu Desktop 21.04 ARM64 (Raspberry Pi 4 4Gb)
