### ISSUE TITLE
Unsupported Syscall 0x3Fh (63)

### ISSUE THREAD

**Issue by jpalus** [ptitSeb/box64#174]
Continuation of #170 but for another hardkernel uboot binary: [aml_encrypt_g12b](https://github.com/hardkernel/u-boot/raw/odroidn2-v2015.01/fip/g12b/aml_encrypt_g12b)
```
$ touch zero
$ box64 ./aml_encrypt_g12b --bl30sig --level v3 --input zero --outpput zero.enc
Box64 v0.1.6 27e5ae1 built on Nov 22 2021 11:14:39
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 60 Env var
Looking for ./aml_encrypt_g12b
argv[1]="--bl30sig"
argv[2]="--level"
argv[3]="v3"
argv[4]="--input"
argv[5]="zero"
argv[6]="--outpput"
argv[7]="zero.enc"
Error: Unsupported Syscall 0x3Fh (63)
```
Appears to be syscall for uname.

**Comment by ptitSeb** [comment]
Yes indeed.
I'll wrap it later, it will need some special care to return an "x86_64" system I guess, and not an atm64 one...

**Comment by jpalus** [comment]
With uname syscall in place it now complains about missing support for `arch_prctl(ARCH_SET_FS)`. @ptitSeb any chance on implementing it? If needed I can create new ticket.

**Comment by ptitSeb** [comment]
Mmmm, this sound like it's a statically linked binary. So linked with static libc, mibm and pthread, wich box doesn support. Can you `readelf -aW /PATH/TO/PROGRAM | grep NEEDED` to check what it is linked with?

**Comment by jpalus** [comment]
Yes indeed that is a statically linked binary, what a shame. Will try my luck with qemu. I suppose this ticket can be closed now.

**Comment by ptitSeb** [comment]
well, I have in mind some workaround, but it will not be 100% effictive on all binary (and I don't know when I'll tacle this one also).. And emulating libc is not how box has been designed, sorry.

**Comment by rajdakin** [comment]
Is this fixed now?
