### ISSUE TITLE
Unimplemented Opcode (0F 38 F6 E8) 67 F3 4D 0F 38 F6 F7 C4 62 FB F6 7E 38 48 89

### ISSUE THREAD

**Issue by shenmo7192** [ptitSeb/box64#1775]
137104|0x6ffff9a893b3: Unimplemented Opcode (0F 38 F6 E8) 67 F3 4D 0F 38 F6 F7 C4 62 FB F6 7E 38 48 89
Sigfault/Segbus while quitting, exiting silently

```
Dynarec will not try to make big block
Dynarec will try to normalize generated NAN
Dynarec will try to generate x86 precise IEEE->int rounding
Dynarec will play it safe with x64 flags
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Kunpeng-920 with 8 Cores
Will use Hardware counter measured at 100 MHz emulating 3.2 GHz
Params database has 87 entries
Box64 with Dynarec v0.3.1 9beb7457 built on Aug 26 2024 16:17:03

```

**Comment by ksco** [comment]
`67 F3 4D 0F 38 F6 F7` is `adox r14, r15`, it's indeed unimplemented, may I ask what program is this?

**Comment by shenmo7192** [comment]
> `67 F3 4D 0F 38 F6 F7` is `adox r14, r15`, it's indeed unimplemented, may I ask what program is this?

spark-wine9-wow when trying to launch wechat


Here is the package

https://mirrors.sdu.edu.cn/spark-store/aarch64-store/depends/spark-wine/wine9/spark-wine9-wow_9.11-staging_arm64.deb

**Comment by shenmo7192** [comment]
Let me test it

**Comment by shenmo7192** [comment]
Test PASS. Thank you very much, I will upgrade my box64 package to fix this
