### ISSUE TITLE
Unturned - Random exception

### ISSUE THREAD

**Issue by KweezyCode** [ptitSeb/box64#178]
Pathfinding exception on startup, after server loading NPCs are not moving
LOG:
[log.txt](https://github.com/ptitSeb/box64/files/7596277/log.txt)

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
This appears to be working now: https://github.com/ptitSeb/box86-compatibility-list/issues/163

Closing as resolved.
