### ISSUE TITLE
Is it posibble to compile box64 on RPi 3B+

### ISSUE THREAD

**Issue by michasus** [ptitSeb/box64#179]
Hi, i'm trying to compile and run box64 on my Raspberry Pi 3B+, but i'm encountering a compilation error.

uname -a: "Linux michasus-rpi 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux"
Cmake cmd: "cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo" (using DRPI4ARM64, because i could not find other rpi ARM64 flag)

[...]
[ 27%] Building C object CMakeFiles/arm64_pass2.dir/src/dynarec/dynarec_arm64_f0.c.o
[ 27%] Building C object CMakeFiles/arm64_pass2.dir/src/dynarec/dynarec_arm64_660f.c.o
[ 28%] Building C object CMakeFiles/arm64_pass2.dir/src/dynarec/dynarec_arm64_6664.c.o
[ 28%] Building C object CMakeFiles/arm64_pass2.dir/src/dynarec/dynarec_arm64_f20f.c.o
[ 28%] Building C object CMakeFiles/arm64_pass2.dir/src/dynarec/dynarec_arm64_f30f.c.o
[ 28%] Building C object CMakeFiles/arm64_pass3.dir/src/dynarec/dynarec_arm64_64.c.o
[ 28%] Built target arm64_pass2
[ 29%] Building C object CMakeFiles/arm64_pass3.dir/src/dynarec/dynarec_arm64_66.c.o
{standard input}: Assembler messages:
{standard input}: Warning: end of file not at end of a line; newline inserted
{standard input}:625: Error: unknown pseudo-op: `.'
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[2]: *** [CMakeFiles/arm64_pass3.dir/build.make:160: CMakeFiles/arm64_pass3.dir/src/dynarec/dynarec_arm64_00.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:272: CMakeFiles/arm64_pass3.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

Sorry for english mistakes!

**Comment by ptitSeb** [comment]
you run out of memory.
Use a simple "make" to build, not any "-j" parameter. Or add a swap if you are already using a simple "make".

**Comment by michasus** [comment]
Thank you!
Added 1GB swap and now it works even with "make -j 4"
