### ISSUE TITLE
Dynarec stopped because of x64 Opcode 67 66 48 0F 7E DA F3 4C 0F 38 F6 D8 66 4D 0F

### ISSUE THREAD

**Issue by Geahuam94** [ptitSeb/box64#1794]
got this error while trying to get a valheim dedicated server to run on an oracle arm instance

**Comment by ptitSeb** [comment]
I just added this opcode yesterday (last commit)! SO just update box64 and try again, this message should be gone.

**Comment by Geahuam94** [comment]
Thanks, updated box64 like you recommended and it resolved the message
