### ISSUE TITLE
Step by step instruction how to use box64 with some example game/app

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [ptitSeb/box64#189]
Would be nice to have some step by step instruction about how to use box64 with some particular example app or game. Now I'm not exactly sure how to proceed with it.

And a side question: is it possible to create native android apps with box64???
Would be happy if would be able to run these:
https://solvespace.com/index.pl
https://www.thunderbird.net/en-US/
in Android

**Comment by ptitSeb** [comment]
I guess a new .md file in docs could do the trick.

As for Android, for now, box64 cannot be built as a native android app (there are some technicial difference between the linux running on andoid and actual desktop linux that make the build not straightforward).

**Comment by Hacker1245** [comment]
What exactly do you want to run?

**Comment by ptitSeb** [comment]
Closing the ticket. There are solution and countless youtube video on how to install box64droid, winlator, or the other script that integrated termux, termux-x11, box86+box64, wine and inputbridge on Android.
