### ISSUE TITLE
Zoom: Error when trying to use system libturbojpeg.so

### ISSUE THREAD

**Issue by stormchaser3000** [ptitSeb/box64#190]
```
Error loading needed lib libturbojpeg.so.0
Warning: Cannot dlopen("libturbojpeg.so.0"/0x64cbdd18, 2)
Using emulated /home/iansutter/Misc/zoom/libturbojpeg.so
Warning: Weak Symbol __gmon_start__ not found, cannot apply R_X86_64_JUMP_SLOT @0xfffee8484e68 (0x2956)
```

This happens when box64 tried to load the system libturbojpeg and seems to impact performance on zoom to some extent. It may also have caused a freeze up, however, I don't have the evidence to support that at the moment.

**Comment by ptitSeb** [comment]
Yes, libturbojpeg is not wrapped on box64 yet (but it still tries to load it because it's some code copied from box86). I'll add it later.

**Comment by stormchaser3000** [comment]
ah ok, nice to know what's in the pipeline then :)
