### ISSUE TITLE
[Question] Is musl supported, or no?

### ISSUE THREAD

**Issue by ethical-haquer** [ptitSeb/box64#1900]
Is musl supported by Box64, or no?
Can it be compiled and used on postmarketOS (Alpine Linux based)?
TIA.

**Comment by ptitSeb** [comment]
Probably not.
But the amount of changes needed is probably pretty low, espcially if it's for running x86_64 musl binary only. 

It might be (much) more complex to implement glibc emulation...

**Comment by ethical-haquer** [comment]
@ptitSeb 
Yeah, I was hoping to run an x64 glibc binary on arm64 musl, I can see that's a bit of a stretch. Thanks for the reply, I think this can be closed then.
