### ISSUE TITLE
Custom gamepad not working.

### ISSUE THREAD

**Issue by AndrewCromar** [ptitSeb/box64#1908]
I am working on a project which will be running my Unity games on the Raspberry Pi 5 using box64, I got the games running and I have a controller working with it. I am working on making a custom controller using a Raspberry Pi Pico as the brain. When I try to use this controller in game it does not work while my actual controller does work.

I realize this sounds like an issue with my code but when I test the rp controller on [harwaretester.com](https://hardwaretester.com/gamepad)(on the same device), it works fine. I think my controller is not getting into box64 somehow. The code for my controller is [here](https://github.com/AndrewCromar/Andrew-Arcade/tree/main/gamepad/code/firmware) but I really don't think anything is wrong with the controller because it does work.

Is there any configuration that I have to do to get it to work?

**Comment by AndrewCromar** [comment]
I fixed it, turns out Linux was doing some goofy stuff, not sure what exactly but after a bunch of testing and fixing I got it working.

**Comment by ptitSeb** [comment]
Glad you have it working :)

How is the overall project? going smoothly?

**Comment by AndrewCromar** [comment]
Everything is going smooth and working as expected! Now that I have the controller working I can finally start working on the software and building the controller case.
