### ISSUE TITLE
Wine internal error

### ISSUE THREAD

**Issue by Ilya114** [ptitSeb/box64#191]
Hello! I installed box64 and wine version 6(other version not work) on my phone (redmi note 8, droidian) and when I run any program, it gives an internal error. Maybe you didn't install it?

**Comment by ptitSeb** [comment]
I use wine 6.0.1 from Build service of PlayOnLinux without issue. I know later version of wine (like 6.10+) don't work for now.
I will need more detail on your version and error message.

**Comment by wormstest** [comment]
I use version 6.2. So the problem is?

**Comment by ptitSeb** [comment]
use version 6.0.1 or 6.0.2 for now.

**Comment by wormstest** [comment]
box64 wine64 wineboot
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.7 40c5824 built on Dec  9 2021 20:09:37
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 34 Env var
BOX64 try to Preload libtls-padding.so
Looking for wine64
argv[1]="wineboot"
Error loading needed lib libtls-padding.so
Warning, cannot pre-load a lib
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated /home/droidian/wine64/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.7 40c5824 built on Dec  9 2021 20:09:37
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 35 Env var
BOX64 try to Preload libtls-padding.so
Looking for /home/droidian/wine64/bin/wine64
argv[1]="wineboot"
Error loading needed lib libtls-padding.so
Warning, cannot pre-load a lib
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated /home/droidian/wine64/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.7 40c5824 built on Dec  9 2021 20:09:37
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 35 Env var
BOX64 try to Preload libtls-padding.so
Looking for /home/droidian/wine64/bin/wineserver
Error loading needed lib libtls-padding.so
Warning, cannot pre-load a lib
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/droidian/wine64/lib64/wine/../libwine.so.1
Error loading needed lib /home/droidian/wine64/lib64/wine/kernel32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/kernel32.so"/0x7d8e6da0, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/kernelbase.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/kernelbase.so"/0x7d8f3950, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/wineboot.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/wineboot.so"/0x7d8ff690, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/advapi32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/advapi32.so"/0x7d90b980, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/sechost.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/sechost.so"/0x7d90bd40, 2)
Using emulated /home/droidian/wine64/lib64/wine/ucrtbase.so
Using emulated /home/droidian/wine64/lib64/wine/ws2_32.dll.so
Error loading needed lib /home/droidian/wine64/lib64/wine/ws2_32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/ws2_32.so"/0x7d91b660, 2)
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.7 40c5824 built on Dec  9 2021 20:09:37
BOX64: Wine64 detected, WINEPRELOADRESERVE="000400000-000488000"
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 37 Env var
BOX64 try to Preload libtls-padding.so
Looking for /home/droidian/wine64/bin/wine64
argv[1]="C:\windows\system32\conhost.exe"
argv[2]="--unix"
argv[3]="--width"
argv[4]="120"
argv[5]="--height"
argv[6]="30"
argv[7]="--server"
argv[8]="0x10"
Error loading needed lib libtls-padding.so
Warning, cannot pre-load a lib
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated /home/droidian/wine64/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /home/droidian/wine64/lib64/wine/../libwine.so.1
Error loading needed lib /home/droidian/wine64/lib64/wine/kernel32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/kernel32.so"/0x95b3ba20, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/kernelbase.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/kernelbase.so"/0x95b4ac80, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/conhost.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/conhost.so"/0x95b56b60, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/advapi32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/advapi32.so"/0x95b66f50, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/sechost.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/sechost.so"/0x95b671e0, 2)
Using emulated /home/droidian/wine64/lib64/wine/ucrtbase.so
Using emulated /home/droidian/wine64/lib64/wine/gdi32.so
Using emulated /home/droidian/wine64/lib64/wine/user32.so
Error loading needed lib /home/droidian/wine64/lib64/wine/setupapi.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/setupapi.so"/0x95b8e7b0, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/rpcrt4.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/rpcrt4.so"/0x95b8ef70, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/version.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/version.so"/0x95b8f0f0, 2)
Using emulated /home/droidian/wine64/lib64/wine/shell32.dll.so
Error loading needed lib /home/droidian/wine64/lib64/wine/shell32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/shell32.so"/0x7da8add0, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/shlwapi.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/shlwapi.so"/0x7dbfb070, 2)
Using emulated /home/droidian/wine64/lib64/wine/gdi32.so
Warning, mmap on 32bits didn't worked, ask 0x40000, got 0x79a04fd000  tried again with 0x64d62000, got 0x64d62000
Error loading needed lib /home/droidian/wine64/lib64/wine/shcore.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/shcore.so"/0x7dc0ca90, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/ole32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/ole32.so"/0x7dc0d890, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/combase.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/combase.so"/0x7dc0dcd0, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/rpcrt4.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/rpcrt4.so"/0x7dc0dcd0, 2)
Using emulated /home/droidian/wine64/lib64/wine/user32.so
Error loading needed lib /home/droidian/wine64/lib64/wine/setupapi.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/setupapi.so"/0x7dc16890, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/version.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/version.so"/0x7dc16a00, 2)
Warning, mmap on 32bits didn't worked, ask 0x40000, got 0x794c931000  tried again with 0x64d62000, got 0x64d62000
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Error loading needed lib /home/droidian/wine64/lib64/wine/imm32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/imm32.so"/0x7dd45ea0, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/imm32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/imm32.so"/0x95cd2b20, 2)
droidian@droidian:~/wine64/bin$

**Comment by ptitSeb** [comment]
I don't see any error there.

**Comment by wormstest** [comment]
wine 6.0.1=internal error

**Comment by wormstest** [comment]
```
Using emulated /home/droidian/wine64/lib64/wine/../libwine.so.1
Error loading needed lib /home/droidian/wine64/lib64/wine/kernel32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/kernel32.so"/0x7c255530, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/kernelbase.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/kernelbase.so"/0x7c26c820, 2)
0024:err:process:exec_process L"Z:\\home\\droidian\\Downloads\\wglgears.exe" not supported on this system
```

**Comment by wormstest** [comment]
```
0050:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
Error loading needed lib /home/droidian/wine64/lib64/wine/kernel32.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/kernel32.so"/0x87d71600, 2)
Error loading needed lib /home/droidian/wine64/lib64/wine/kernelbase.so
Warning: Cannot dlopen("/home/droidian/wine64/lib64/wine/kernelbase.so"/0x87d83030, 2)
0024:err:process:exec_process L"Z:\\home\\droidian\\Downloads\\qemu-w64-setup-20210706.exe" not supported on this system
```

**Comment by ptitSeb** [comment]
box64 cannot run any 32bits program. I'm assuming `wglgears.exe` here is 32bits. You need box86 for 32bits, but for this you need armhf multiarch of chroot or something similar.

**Comment by wormstest** [comment]
qemu 64 bit is not work,too,internal error

**Comment by wormstest** [comment]
64 bit program is too not work

**Comment by ptitSeb** [comment]
qemu might be a 694bits program, but the setup `qemu-w64-setup-20210706.exe` probably not. What `file qemu-w64-setup-20210706.exe` gives you?

**Comment by wormstest** [comment]
It was a test installer. How to make on box64 viber? wine internal error.

**Comment by ptitSeb** [comment]
Does the included `wincfg` or `winemine` program works?

**Comment by wormstest** [comment]
> Does the included `wincfg` or `winemine` program works?

yes

**Comment by wormstest** [comment]
![Снимок экрана от 2021-12-11 18-02-06](https://user-images.githubusercontent.com/93242944/145683246-62405b93-ed3f-445c-a38b-deba8ec7bef7.png)

**Comment by ptitSeb** [comment]
So wine is working with 64bits programs.

Try to find other 64bits programs. Check there are 64bits with `file`.

**Comment by wormstest** [comment]
> So wine is working with 64bits programs.
> 
> Try to find other 64bits programs. Check there are 64bits with `file`.

vnc viewer is works

**Comment by wormstest** [comment]
Viber is not work...

**Comment by wormstest** [comment]
How to install winetricks?

**Comment by ptitSeb** [comment]
Use the regular way (with `update_winetricks` in `/usr/bin`) and create a shell script in `/usr/local/bin` names `winetricks` with this content:
```
#!/bin/bash

BOX86_LOG=0 BOX86_NOBANNER=1 BOX64_LOG=0 BOX64_NOBANNER=1 /usr/bin/winetricks "$@"
```
