### ISSUE TITLE
Unimplemented 32bits Opcode with Theme Hospital (gog)

### ISSUE THREAD

**Issue by tartanpion** [ptitSeb/box64#1911]
wine64 '/home/bloodmoon/.wine/drive_c/GOG Games/Theme Hospital/Launch Theme Hospital.lnk' 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 91 entries
Box64 with Dynarec v0.3.1 cb5dafe8 built on Oct  7 2024 11:24:10
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
BOX64: Detected 48bits at least of address space
WINE prereserve of 0x10000:0x8000 done
WINE prereserve of 0x110000:0x30000000 done
WINE prereserve of 0x7f000000:0x3000000 done
Counted 59 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/var/lib/snapd/snap/bin/:/usr/local/sbin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
Looking for /usr/local/bin/wine64
Apply RC params for wine64
Applying BOX64_MAXCPU=64
argv[1]="/home/bloodmoon/.wine/drive_c/GOG Games/Theme Hospital/Launch Theme Hospital.lnk"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
WINE wine_main_preload_info found and updated 0x100202030 -> 0x35d81e30
Using emulated /home/bloodmoon/wine/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 91 entries
Box64 with Dynarec v0.3.1 cb5dafe8 built on Oct  7 2024 11:24:10
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
BOX64: Detected 48bits at least of address space
WINE prereserve of 0x10000:0x8000 done
WINE prereserve of 0x110000:0x30000000 done
WINE prereserve of 0x7f000000:0x3000000 done
Counted 61 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/var/lib/snapd/snap/bin/:/usr/local/sbin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
Looking for /home/bloodmoon/wine/bin/wine64
Apply RC params for wine64
Applying BOX64_MAXCPU=64
argv[1]="/home/bloodmoon/.wine/drive_c/GOG Games/Theme Hospital/Launch Theme Hospital.lnk"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
WINE wine_main_preload_info found and updated 0x100202030 -> 0x35d81e30
Using emulated /home/bloodmoon/wine/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
posix_spawn(0xffff926ff0bc, "/home/bloodmoon/wine/bin/wineserver", (nil), (nil), 0xffff926ff0c0["/home/bloodmoon/wine/bin/wineserver", "", ...], 0xffff926ff480), IsX64=1, IsX86=0 IsScript=0 envp is context->envv
 => posix_spawn(0xffff926ff0bc, "/usr/bin/box64", (nil), (nil), 0xffffd5bcb5b0 ["/usr/bin/box64", "/home/bloodmoon/wine/bin/wineserver", ""...:1], 0xffffd5bcbe28)
posix_spawn returned 0
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 91 entries
Box64 with Dynarec v0.3.1 cb5dafe8 built on Oct  7 2024 11:24:10
BOX64: Detected 48bits at least of address space
Counted 61 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/var/lib/snapd/snap/bin/:/usr/local/sbin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
Looking for /home/bloodmoon/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) libbsd.so.0
002c:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
002c:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
002c:fixme:winediag:loader_init wine-staging 9.19 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
0034:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
0034:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
0040:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
0040:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
0068:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
0068:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
0098:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
0098:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
00b8:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
00b8:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
00d8:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
00d8:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
00f0:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
00f0:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
0024:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
0024:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
0118:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
0118:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
Using emulated /home/bloodmoon/wine/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libexpat.so.1
Using emulated /home/bloodmoon/wine/lib/wine/x86_64-unix/winex11.so
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXfixes.so.3
0024:fixme:exec:SHELL_execute flags ignored: 0x00004000
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 91 entries
Box64 with Dynarec v0.3.1 cb5dafe8 built on Oct  7 2024 11:24:10
BOX64: Wine64 detected, WINEPRELOADRESERVE="000400000-00247b000"
BOX64: Detected 48bits at least of address space
WINE prereserve of 0x10000:0x8000 done
WINE prereserve of 0x110000:0x30000000 done
WINE prereserve of 0x7f000000:0x3000000 done
BOX64: Detected running wine with "dosbox.exe"
Counted 63 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/var/lib/snapd/snap/bin/:/usr/local/sbin/:/usr/lib/jvm/default/bin/:/usr/bin/site_perl/:/usr/bin/vendor_perl/:/usr/bin/core_perl/
Looking for /home/bloodmoon/wine/bin/wine
Apply RC params for wine
Applying BOX64_MAXCPU=64
argv[1]="C:\GOG Games\Theme Hospital\DOSBOX\dosbox.exe"
argv[2]="-conf"
argv[3]="..\dosboxTH.conf"
argv[4]="-conf"
argv[5]="..\dosboxTH_single.conf"
argv[6]="-noconsole"
argv[7]="-c"
argv[8]="exit"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
WINE wine_main_preload_info found and updated 0x100202030 -> 0x35d81e30
Using emulated /home/bloodmoon/wine/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
0120:err:environ:init_peb starting L"C:\\GOG Games\\Theme Hospital\\DOSBOX\\DOSBox.exe" in experimental wow64 mode
0120:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x7fff000413b0, syscall 0x30140320, not installing seccomp.
0120:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
Using emulated /home/bloodmoon/wine/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so.6
   bloodmoon@bloodmoon-pc  /.wine/drive_c/GOG Games/Theme Hospital  Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libexpat.so.1
Using emulated /home/bloodmoon/wine/lib/wine/x86_64-unix/dnsapi.so
Using native(wrapped) libresolv.so.2
Using emulated /home/bloodmoon/wine/lib/wine/x86_64-unix/ws2_32.so
Using emulated /home/bloodmoon/wine/lib/wine/x86_64-unix/opengl32.so
Using emulated /home/bloodmoon/wine/lib/wine/x86_64-unix/winex11.so
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXfixes.so.3
22369|0x6d6c03: Unimplemented 32bits Opcode (02 8B 55 10) 66 6A 00 52 50 53 E8 92 DE FF FF 8B 55 08 83
Sigfault/Segbus while quitting, exiting silently

**Comment by ptitSeb** [comment]
Ok, the opcode has been added. You can update and try again.

**Comment by tartanpion** [comment]
It needs wine's tweak like fullscreen=false but it's OK now for box64.
