### ISSUE TITLE
Dxvk vulkan performance is bad when running steam thru wine with wow64 on the M1

### ISSUE THREAD

**Issue by m1m1k4tz** [ptitSeb/box64#1921]
Also I’ve reproduced that you need a working wine prefix from an x86 desktop to login I installed core fonts with winetricks so the buttons work better too

**Comment by m1m1k4tz** [comment]
Vulkan was just released as well so no need for developer packages

**Comment by m1m1k4tz** [comment]
Oh also I noticed when I zipped the wine prefix up  and my compiled wine with wow64 build I had to unzip it with the terminal for it to work right

**Comment by m1m1k4tz** [comment]
Oh also I’m not sure if this is new to you but in the blog post they mention using TSO mode in fex not sure if that would help https://lwn.net/Articles/970907/

**Comment by m1m1k4tz** [comment]
Also I’m guessing this stuff is upstreamed enough so the containers are no longer necessary https://docs.fedoraproject.org/en-US/fedora-asahi-remix/x86-support/

**Comment by m1m1k4tz** [comment]
Actually a container is still necessary because I get an error without it and the guide is taken down so here’s what I would do
```
# specify 40 because of a bug thats fixed in 41
toolbox create -r 40
toolbox enter -r 40
sudo dnf copr enable @asahi/mesa
sudo dnf --best install alsa-lib alsa-plugins-pulseaudio alsa-utils dhcpcd eglinfo glmark2 glx-utils muvm mesa-demos mesa-dri-drivers passt pipewire-libs pulseaudio-libs pulseaudio-utils socat sommelier virglrenderer xorg-x11-server-Xwayland --exclude pipewire --exclude pipewire-pulseaudio --exclude pulseaudio
```
Then compile and install box64 and transfer over the working wineprefix

**Comment by m1m1k4tz** [comment]
Also I've updated the scripts I use to compile wine with wow64 on my fedora desktop inside a toolbox container
```
#!/bin/bash
sudo dnf group install -y 'C Development Tools and Libraries'
sudo dnf group install -y 'Development Tools'

sudo dnf install -y mingw64-gcc mingw32-gcc libX11-devel libXcursor-devel libXfixes-devel libXi-devel libXrandr-devel libXrender-devel wayland-devel.x86_64 rust-xkbcommon+wayland-devel.noarch freetype-devel.x86_64 alsa-lib-devel.x86_64 pulseaudio-libs-devel.x86_64 dbus-devel.x86_64 fontconfig-devel gnutls-devel mesa-libGL-devel libunwind-devel gstreamer1-devel.x86_64 gstreamer1-plugins-base-devel.x86_64 gstreamer1-plugins-good mesa-libOSMesa-devel.x86_64 vulkan-loader-devel.x86_64 SDL2-devel ocl-icd-devel.x86_64 krb5-devel chrpath cups-devel fontforge fonts-rpm-macros gettext-devel giflib-devel gsm-devel libXcomposite-devel libXinerama-devel libXmu-devel libXxf86dga-devel libXxf86vm-devel libgphoto2-devel libpcap-devel libv4l-devel mesa-libGLU-devel openldap-devel perl-generators sane-backends-devel unixODBC-devel
```

```
#!/bin/bash
if [ ! -d ~/wine-dirs ]; then
  mkdir ~/wine-dirs
fi

if [ -d ~/wine-dirs/wine-source ]; then
  cd ~/wine-dirs/wine-source
  rm configure~
  git pull
  git submodule update --init --recursive
  autoreconf -fi
fi
if [ ! -d ~/wine-dirs/wine-source ]; then
  git clone https://gitlab.winehq.org/wine/wine.git/ ~/wine-dirs/wine-source
  git submodule update --init --recursive
  autoreconf -fi
fi

if [ ! -d ~/wine-dirs/wine-build ]; then
mkdir ~/wine-dirs/wine-build
fi

cd ~/wine-dirs/wine-build
../wine-source/configure --disable-tests --with-mingw --with-wayland --enable-archs=i386,x86_64
make -j"$(nproc --ignore=2)"
```

**Comment by ptitSeb** [comment]
> Vulkan was just released as well so no need for developer packages

You might need to use `BOX64_MMAP32=1` to force external memory map to be created in 32bits space and avoid some buffer copy?

**Comment by ptitSeb** [comment]
> Oh also I’m not sure if this is new to you but in the blog post they mention using TSO mode in fex not sure if that would help https://lwn.net/Articles/970907/

Yeah, I have not implement M1 TSO mode in box64 yet. Current TSO in box64 is called strongmem, an dyou set it up with `BOX64_DYNAREC_STRONGMEM=1`. The plan, on M1, is to activate the hardware tso as soon as strongmem=1 is selected (and disable the emulated one).

**Comment by ptitSeb** [comment]
> Actually a container is still necessary because I get an error without it and the guide is taken down so here’s what I would do


What guide was taken down? installing box64 with krum?

**Comment by m1m1k4tz** [comment]
> > Actually a container is still necessary because I get an error without it and the guide is taken down so here’s what I would do
> 
> What guide was taken down? installing box64 with krum?

https://gist.github.com/teohhanhui/042a395010d9946ceee14768736e3780

**Comment by m1m1k4tz** [comment]
Strongmem didn't seem to solve the problem, but it might also be that the drivers aren't fully there yet. The game was Fallout New Vegas if you want to try and reproduce it

**Comment by ptitSeb** [comment]
> Strongmem didn't seem to solve the problem, but it might also be that the drivers aren't fully there yet. The game was Fallout New Vegas if you want to try and reproduce it

What issue you have: it's slow or it crashes?

If it's slow: stringmem will not help (it might make things worse).
If it crashes: yes, strongmem might help.

**Comment by m1m1k4tz** [comment]
My bad, I meant MMAP32 and yeah it was slow but it gets in game I haven’t tested 64 bit stuff with dxvk though yet

**Comment by m1m1k4tz** [comment]
Here's a log too 
[vulkan.txt](https://github.com/user-attachments/files/17352674/vulkan.txt)

**Comment by ptitSeb** [comment]
Are you sure it's a box64 issue?

**Comment by ptitSeb** [comment]
MMmmm, If I'm reading this log correctly, you are using LLVMpipe, so the LAVApipe vulkan software driver, not an hardware accelerated one. That's why it's slow.

**Comment by m1m1k4tz** [comment]
I’m not actually sure if it’s a driver issue or box64 wow64 issue because it’s the early days of the driver and I don’t have any other powerful arm hardware to test it on. If you run vkmark it performs well but says llvmpipe also

**Comment by ptitSeb** [comment]
can you try vkmark x86 and x64 version maybe?

**Comment by m1m1k4tz** [comment]
I tried vkmark but it freezes at [texture] anisotropy=16:
```
[alex@toolbox ~]$ vkmark
=======================================================
    vkmark 2017.08
=======================================================
    Vendor ID:      0x10005
    Device ID:      0x0
    Device Name:    llvmpipe (LLVM 18.1.6, 128 bits)
    Driver Version: 1
    Device UUID:    32342e312e3761616161616161616161
=======================================================
[vertex] device-local=true: FPS: 833 FrameTime: 1.200 ms
[vertex] device-local=false: FPS: 833 FrameTime: 1.200 ms
[texture] anisotropy=0: FPS: 995 FrameTime: 1.005 ms
[texture] anisotropy=16:
```

**Comment by m1m1k4tz** [comment]
I think this could be driver related but I saw they have windows games running on fex so I'm not sure

**Comment by ptitSeb** [comment]
Well, on the native build, are the frametime of the first 3 tests similar?

Anyway, i'm pretty sure you are ot using M1 Vulkan driver there. It would not say `llvmpipe` if it was the case, but `honeycomb` or something like that.

**Comment by m1m1k4tz** [comment]
@alyssarosenzweig what do you think?

**Comment by m1m1k4tz** [comment]
Okay, I’ve updated the drivers in toolbox and it correctly says Apple M1, but now it won’t get in game and says 
```
Failed to initialize renderer.
Unknown error creating the Gamebryo Renderer.
```

**Comment by m1m1k4tz** [comment]
Also, I’ve noticed windows with drop down menus work much better in the virtual desktop mode inside wine

**Comment by m1m1k4tz** [comment]
[vulkan.txt](https://github.com/user-attachments/files/17400864/vulkan.txt)

**Comment by m1m1k4tz** [comment]
```
=======================================================
    vkmark 2017.08
=======================================================
    Vendor ID:      0x10005
    Device ID:      0x0
    Device Name:    Apple M1 (G13G B1)
    Driver Version: 100675584
    Device UUID:    5ff7d04326f7ba4e18fcc45eac30dfcb
=======================================================
[vertex] device-local=true: FPS: 7194 FrameTime: 0.139 ms
[vertex] device-local=false: FPS: 7302 FrameTime: 0.137 ms
[texture] anisotropy=0: FPS: 7256 FrameTime: 0.138 ms
[texture] anisotropy=16: FPS: 7364 FrameTime: 0.136 ms
[shading] shading=gouraud: FPS: 7235 FrameTime: 0.138 ms
[shading] shading=blinn-phong-inf: FPS: 7286 FrameTime: 0.137 ms
[shading] shading=phong: FPS: 7240 FrameTime: 0.138 ms
[shading] shading=cel: FPS: 7285 FrameTime: 0.137 ms
[effect2d] kernel=edge: FPS: 7296 FrameTime: 0.137 ms
[effect2d] kernel=blur: FPS: 4403 FrameTime: 0.227 ms
[desktop] <default>: FPS: 7317 FrameTime: 0.137 ms
[cube] <default>: FPS: 7094 FrameTime: 0.141 ms
[clear] <default>: FPS: 6859 FrameTime: 0.146 ms
=======================================================
                                   vkmark Score: 7010
=======================================================
```

**Comment by m1m1k4tz** [comment]
Also, heres a log for Half-Life 2
[hl2vulkan.txt](https://github.com/user-attachments/files/17401364/hl2vulkan.txt)

**Comment by m1m1k4tz** [comment]
Errors like this one seem to come up in a lot of games `0314:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0xffff6c6d0000 does not fit 32-bit pointer`

**Comment by m1m1k4tz** [comment]
[Fallout4.txt](https://github.com/user-attachments/files/17406658/Fallout4.txt)

**Comment by m1m1k4tz** [comment]
It looks like with a muvm update you don’t need a container anymore

**Comment by ptitSeb** [comment]
> Errors like this one seem to come up in a lot of games `0314:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0xffff6c6d0000 does not fit 32-bit pointer`

Use `BOX64_MMAP32=1` for that.

**Comment by m1m1k4tz** [comment]
> > Errors like this one seem to come up in a lot of games `0314:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0xffff6c6d0000 does not fit 32-bit pointer`
> 
> Use `BOX64_MMAP32=1` for that.

I just tried but I still get the 32 bit pointer errors sadly

**Comment by ptitSeb** [comment]
> > > Errors like this one seem to come up in a lot of games `0314:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0xffff6c6d0000 does not fit 32-bit pointer`
> > 
> > 
> > Use `BOX64_MMAP32=1` for that.
> 
> I just tried but I still get the 32 bit pointer errors sadly

Mmm, that's strange, because this one was added to avoid this kind of error.

Btw, is vulkan still slow or can this specific ticket can be closed (and probably some other open) or at least renamed?

**Comment by m1m1k4tz** [comment]
Okay now it won’t get in game at all before with llvmpipe it could get in game but it was slow I’ll open a new ticket

**Comment by ptitSeb** [comment]
> With the new mmap updates I’m getting in game in more games, thanks!

Which mmap update fixed it?

**Comment by m1m1k4tz** [comment]
I think the recent work you did might have helped it feels like with Fallout 3 when I use that hack but it still crashes a lot

**Comment by m1m1k4tz** [comment]
I’ve only got Fallout 3 in game with 1200x800

**Comment by salvalie** [comment]
i also does have that warging with BOX64_MMAP32=1 on hangover, latest hangover does accept box64 env vars.

**Comment by ptitSeb** [comment]
I don't think `BOX64_MMAP32=1` will work on hangover. This setting is for box64 standalone only, as it use a globaly redirected `mmap(...)` and box64 memory tracking, that are not part of hangover.
