### ISSUE TITLE
Protontricks crashes bwrap launcher

### ISSUE THREAD

**Issue by FoxbitDreamtail** [ptitSeb/box64#1929]
I'm on a Raspberry Pi 5, and unfortunately Protontricks does not work, Protontricks is a useful tool for installing executables within certain runtime environments for Steam games or proton instances, It also helps in selling certain dependencies which do not exist in stock proton without needing to install a whole different version of proton.

Protontricks was installed using Python 3 and pipx.

The exact steps I followed are as follows.
1) Install Steam via PiApps(which also installs both Box86 and Box64)
2) Sign into Steam and install a proton-requiring game.
3) Install pipx with the following command: `sudo apt install pipx`
4) Install Protontricks via Python 3 using pipx: `python3 -m pipx install protontricks`
5) Upon a successful install, run `protontricks` and try to use it.

My Raspberry Pi 5, which I'm running this on, is running MX Linux 23.4, If there was a newer version, I would be running it. Any game in which either has a Linux native version or is a relatively janky engine like Plants vs. Zombies or Geometry Dash works fine. But the instant that I try doing any Windows only Unity or Unreal(Let's be honest, there is no way in hell any Unreal game was going to run on a pi) game, it gives me a DirectX 11 error, which is why I'm trying to install proton tricks and install the DirectX runtime, Also, I am mortified to compile the graphics driver from source because last time I did that using PiKISS, my entire system was stuck using LLVMPIPE For graphics rendering. And that is not ideal, especially if you want to play games.

**Comment by ivon852** [comment]
On my RPI5, the protontricks can be launched by running: `box86 protontricks --gui --no-bwrap`

For the DirectX issue, it seems that this is due to the lack of support of DXVK on Raspberry Pi (see [Box86's notes](https://github.com/ptitSeb/box86?tab=readme-ov-file#notes-about-vulkan)), therefore you have to set `PROTON_USEWINED3D=1  %command%` in the launch options of the game.Sometimes you also have to override mesa version by setting `MESA_GL_VERSION_OVERRIDE=3.2`.

**Comment by FoxbitDreamtail** [comment]
> On my RPI5, the protontricks can be launched by running: `protontricks --gui --no-bwrap`
Thanks, I will try this.

> For the DirectX error, it seems that this is due to the lack of support of DXVK on Raspberry Pi (see [Box86's notes](https://github.com/ptitSeb/box86?tab=readme-ov-file#notes-about-vulkan)), therefore you have to set `PROTON_USEWINED3D=1 %command%` in the launch options of the game, then the error should disappear.
I do do this but there are games that in spite of this still do not work or have major graphical errors due to this.

> Sometimes you also have to override mesa version by setting `MESA_GL_VERSION_OVERRIDE=3.2`.
I will also try this, thank you.
