### ISSUE TITLE
Might be possible to run IBKR TWS Trading Software ?

### ISSUE THREAD

**Issue by pm-alonso** [ptitSeb/box64#193]
Hi devs, when first saw your project I was static !
What a time to be alive ! haha

Programming for me is like magic, i do not understand how you do it.
I am just wanting to run this trading platform in my raspberry pi 4 since a long time ago. this is the last app that still ties me to x86/64.

Maybe you can extend your magic with box64 to make this work on Rpi4 ?
https://www.interactivebrokers.com/en/index.php?f=16040

I have tried latest and offline linux 64 versions downloads with same results, a hang after a good start...

my terminal output is as follows:

pi@mypi:~/Downloads/IBKR_TWS_Linux_64 $ ./tws-latest-standalone-linux-x64.sh 
Unpacking JRE ...
Starting Installer ...
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.7 5d1298e built on Dec 13 2021 17:16:27
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 30 Env var
Looking for /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/bin/java
argv[1]="-Dexe4j.moduleName=/home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh"
argv[2]="-Dexe4j.totalDataLength=163474083"
argv[3]="-Dinstall4j.cwd=/home/pi/Downloads/IBKR_TWS_Linux_64"
argv[4]="-Djava.ext.dirs=/home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/ext:/home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/jre/lib/ext"
argv[5]="-classpath"
argv[6]="i4jruntime.jar:launcher0.jar"
argv[7]="install4j.Installer3063371052"
Using native(wrapped) libpthread.so.0
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/bin/../lib/amd64/jli/libjli.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/server/libjvm.so
Using native(wrapped) libm.so.6
Error: Global Symbol collector_func_load not found, cannot apply R_X86_64_GLOB_DAT @0x7fa35040a8 ((nil)) in /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/server/libjvm.so
Warning: Weak Symbol collector_func_load not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa3504908 (0x22068e)
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libverify.so
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libjava.so
Java HotSpot(TM) 64-Bit Server VM warning: Can't detect initial thread stack location - find_vma failed
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libzip.so
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libnet.so
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libnio.so
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libmanagement.so
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libawt.so
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libawt_xawt.so
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXtst.so.6
Using native(wrapped) libXi.so.6
Using native(wrapped) libXinerama.so.1
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libfontmanager.so
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libfontconfig.so.1
Using emulated /home/pi/Downloads/IBKR_TWS_Linux_64/tws-latest-standalone-linux-x64.sh.1633.dir/jre/lib/amd64/libt2k.so

-------- and there it stays forever...

Maybe it is a java virtuam machine problem.... dont know.

I am using last debian buster arm64 bullseye image from raspberry pi official download site.

In any case thank you !

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
This should be fixed now. Closing as resolved.
