### ISSUE TITLE
Unimplemented Opcode (47 0B 00 00)

### ISSUE THREAD

**Issue by dcoredump** [ptitSeb/box64#1932]
Hi,

first of all: thanks for box64/86! It's a very powerful tool on an RPi!!!

I don't know if it's ok if I open an issue here for every unimplemented opcode, but I'll try. If not, that's ok and I'll sit quietly in the corner and cry to myself :)

This is what I am getting when trying to run `ArmaReforgerServer`:

```
14413|0x117c4c9: Unimplemented Opcode (47 0B 00 00) 64 F6 85 64 F6 FF FF 04 0F 85 6D 02 00 00 45
Sigfault/Segbus while quitting, exiting silently
```

Hope this can be easily fixed.

Thanks a lot!

Holger

**Comment by ptitSeb** [comment]
Ok, opcode added.

**Comment by dcoredump** [comment]
Thanks! I checked out the latest `main` and recompiled. Now I am getting:

```
6385|0x117c4c9: Unimplemented Opcode (47 0B 00 00) 64 F6 85 64 F6 FF FF 04 0F 85 6D 02 00 00 45
Sigfault/Segbus while quitting, exiting silently
```

Looks like the same opcode, or am I wrong?

**Comment by ptitSeb** [comment]
yeah, you are right, I implemented the wrong opcode, I added "64 85" instead og "64 F6 85" :(. I'll add the correct one soon.

**Comment by ptitSeb** [comment]
Ok, I added the correct opcode this time (only on interpreter, but that's enough to make things runs).

**Comment by dcoredump** [comment]
Ok - thanks! Error message is gone.
