### ISSUE TITLE
Fallout New Vegas Box64

### ISSUE THREAD

**Issue by dave9292** [ptitSeb/box64#1936]
Hi, I have a question and a request, the situation is as follows: FNV works without crashes only with STRONGMEM=1, with 0 it crashes after a couple of minutes, but the thing is that with 1 , fps drops a lot (from about 60 to 35-40, which is a lot), the only way out is to use Box64 from January 23 (wow64 support) and until about February 10 or so, on these versions when STRONGMEM= 1 fps drops only from 60 to 50 and the game does not crash, is it possible to make it so that it would be possible to play without STRONGMEM? Fallout 3 uses the same engine, and it runs without STRONGMEM without crashes.. please note, thanks in advance

I use arm64 android builds

**Comment by FoxbitDreamtail** [comment]
I think what would be better would be a launcher with Android/Desktop where the user can on a per-application basis pick which build of Box64/Box86 runs best for them, [Winlator](https://winlator.org/) does this already, also there is a mod version of [winlator with better compatibility](https://github.com/MrPhryaNikFrosty/Winlator-Frost).

**Comment by dave9292** [comment]
> I think what would be better would be a launcher with Android/Desktop where the user can on a per-application basis pick which build of Box64/Box86 runs best for them, [Winlator](https://winlator.org/) does this already, also there is a mod version of [winlator with better compatibility](https://github.com/MrPhryaNikFrosty/Winlator-Frost).
> 
> unrelated note: how in F*#k are you running this project without something like winlator?!

I use Mobox, although I prefer Winlator, but that’s not the point. The current state of Box64 is concerning, as there has been a regression in FNV since the beginning of February 2024.

**Comment by ptitSeb** [comment]
> > I think what would be better would be a launcher with Android/Desktop where the user can on a per-application basis pick which build of Box64/Box86 runs best for them, [Winlator](https://winlator.org/) does this already, also there is a mod version of [winlator with better compatibility](https://github.com/MrPhryaNikFrosty/Winlator-Frost).
> > unrelated note: how in F*#k are you running this project without something like winlator?!
> 
> I use Mobox, although I prefer Winlator, but that’s not the point. The current state of Box64 is concerning, as there has been a regression in FNV since the beginning of February 2024.

Can you pinpoint the exact commit that provoque the regression?

**Comment by dave9292** [comment]
> > > I think what would be better would be a launcher with Android/Desktop where the user can on a per-application basis pick which build of Box64/Box86 runs best for them, [Winlator](https://winlator.org/) does this already, also there is a mod version of [winlator with better compatibility](https://github.com/MrPhryaNikFrosty/Winlator-Frost).
> > > unrelated note: how in F*#k are you running this project without something like winlator?!
> > 
> > 
> > I use Mobox, although I prefer Winlator, but that’s not the point. The current state of Box64 is concerning, as there has been a regression in FNV since the beginning of February 2024.
> 
> Can you pinpoint the exact commit that provoque the regression?

Sure! Here’s the translation:

Good day! I'm very noob at these things, but as a regular user, I shared my observations. While testing a bit yesterday, I discovered that the regression (a significant drop in performance with strongmem=1) starts after February 5. So, in the period from January 23rd (I take the report from January 23 because it seems like the first build with Wow64 support) to February 5, something changed, but I don't know what exactly, because I'm a noob :(

**Comment by ptitSeb** [comment]
> Good day! I'm very noob at these things, but as a regular user, I shared my observations. While testing a bit yesterday, I discovered that the regression (a significant drop in performance with strongmem=1) starts after February 5. So, in the period from February 5 something changed, but I don't know what exactly, because I'm a noob :( Versions from January 23 to February 5 have the highest performance with Strongmem 1 enabled; I have not tried versions before January 23, since I use Wine with wow64 support.
> 

the dates you are mentionning are from box64 build?

On 3rd of february tehre is [ARM64_DYNAREC] Reworked STRONGMEM 2 & 3 "[ARM64_DYNAREC] Reworked STRONGMEM 2 & 3", but it's supposed to change strongmem 2&3, not 1.

**Comment by dave9292** [comment]
> > Good day! I'm very noob at these things, but as a regular user, I shared my observations. While testing a bit yesterday, I discovered that the regression (a significant drop in performance with strongmem=1) starts after February 5. So, in the period from February 5 something changed, but I don't know what exactly, because I'm a noob :( Versions from January 23 to February 5 have the highest performance with Strongmem 1 enabled; I have not tried versions before January 23, since I use Wine with wow64 support.
> 
> the dates you are mentionning are from box64 build?
> 
> On 3rd of february tehre is [ARM64_DYNAREC] Reworked STRONGMEM 2 & 3 "[ARM64_DYNAREC] Reworked STRONGMEM 2 & 3", but it's supposed to change strongmem 2&3, not 1.

Yes, I use Box64.
Honestly, I don't know what else to say about this, for me there is a simple fact that after February 5th and up to now, I can't play FNV with Strongmem 1, because it eats up 20 fps, and I don't have a very powerful android device (Snapdragon 778g), besides, I have to play only on Termux based glibc projects, because Box64 is not suitable for Winlator and you need to do manipulations with the source code to make them work (patching or something) Apparently, in my case i need a more powerful device, thanks for your time, have a nice day!

**Comment by ptitSeb** [comment]
> > > Good day! I'm very noob at these things, but as a regular user, I shared my observations. While testing a bit yesterday, I discovered that the regression (a significant drop in performance with strongmem=1) starts after February 5. So, in the period from February 5 something changed, but I don't know what exactly, because I'm a noob :( Versions from January 23 to February 5 have the highest performance with Strongmem 1 enabled; I have not tried versions before January 23, since I use Wine with wow64 support.
> > 
> > 
> > the dates you are mentionning are from box64 build?
> > On 3rd of february tehre is [ARM64_DYNAREC] Reworked STRONGMEM 2 & 3 "[ARM64_DYNAREC] Reworked STRONGMEM 2 & 3", but it's supposed to change strongmem 2&3, not 1.
> 
> Yes, I use Box64. Honestly, I don't know what else to say about this, for me there is a simple fact that after February 5th and up to now, I can't play FNV with Strongmem 1, because it eats up 20 fps, and I don't have a very powerful android device (Snapdragon 778g), besides, I have to play only on Termux based glibc projects, because Box64 is not suitable for Winlator and you need to do manipulations with the source code to make them work (patching or something) Apparently, in my case i need a more powerful device, thanks for your time, have a nice day!

You can try to without strongmem=1 but with `BOX64_X87DOUBLE=1`. It help for some people, maybe for you too.
