### ISSUE TITLE
(overclocking)(Pi5)Crash with higher CPU clock via memory errors.

### ISSUE THREAD

**Issue by FoxbitDreamtail** [ptitSeb/box64#1939]
I can't help but notice that games run through steam, of course. It's happened to crash due to memory errors at higher CPU clock speeds on the Raspberry Pi 5. I cannot say if this is the same for the Pi 4 as I have not tested it, I tried overclocking my Raspberry Pi to get better performance on it, and I did see some pretty decent results, however those results were short-lived, as box 64 then kicked up an error about memory address being wrong and then it crashed the whole game, Specifically, Terraria began to hold a substantially consistent 61 FPS and BatIM became playable... Does anyone else know why this is and why it's only affecting Box 64? As when I play Minecraft there is no effect and that steam has little to no effect either? It's only games running through a box64....

**Comment by m1m1k4tz** [comment]
Maybe your cooling isn't good enough or you overclocked it too much?

**Comment by FoxbitDreamtail** [comment]
> Maybe your cooling isn't good enough or you overclocked it too much?

I am considering a 5$ Raspberry Pi upgraded cooler... but I don't know if it really would be worth it. Also, it may have something to do with the Raspberry Pi's firmware, which I'm almost certain of, considering that the RAM errors happen even if I am not in the operating system. Say I overclock to say 3Ghz, which should be a stable overclock for the Pi 5. My Raspberry Pi simply doesn't. It kernel panics instead.

**Comment by LukeShortCloud** [comment]
This appears to be a hardware issue. Overclocking always has the risk of leading to stability issues. I have a cooler and fan upgrade on my Pi 5 and I highly recommend it if you're going to overclock. It does make a difference. I suspect that it is more common to see issues with Box64 because of more demanding games than Minecraft and emulation overhead.
