### ISSUE TITLE
(Steam)(Linux)Slime Rancher 

### ISSUE THREAD

**Issue by FoxbitDreamtail** [ptitSeb/box64#1944]
when I realized that SlimeRancher was linux native, I rushed to install/try it out, but when I launched it, many testures failed to load and were black, the slimes and UI rendered correctly however... but none of the environment or the player is rendered correctly. and then roughly 30 seconds after launch the game just crashes with no popup or anything.

**Comment by FoxbitDreamtail** [comment]
It seems that the game won't crash while you are playing it But the graphics are still f*cked and whenever you pick up a largo slime, it slows your game to a crawl, Otherwise, beyond the graphics issues, it is playable on Pi 5... But I cannot stress this enough. It is not a good experience.

**Comment by ptitSeb** [comment]
That looks like a GPU Driver issue there, and not a box64 issue. Use the Mesa Software renderer to see if it render correctly (at super slow speed). If it render wells, that menas it's a driver issue.

**Comment by FoxbitDreamtail** [comment]
> That looks like a GPU Driver issue there, and not a box64 issue. Use the Mesa Software renderer to see if it render correctly (at super slow speed). If it render wells, that **means** it's a driver issue.

how do I do that without breaking the driver entirely?

**Comment by Hacker1245** [comment]
> > That looks like a GPU Driver issue there, and not a box64 issue. Use the Mesa Software renderer to see if it render correctly (at super slow speed). If it render wells, that **means** it's a driver issue.
> 
> how do I do that without breaking the driver entirely?

it for sure is a driver issue because it ran fine on an Adreno GPU.

**Comment by FoxbitDreamtail** [comment]
> it for sure is a driver issue because it ran fine on an Adreno GPU.

ok, then better idea, would compiling and running the latest mesa fix the VC7,1 vulkan issues I have been having and potentially fix this set of graphical errors as well?

**Comment by FoxbitDreamtail** [comment]
> You could have search, it' easy to find.
> 
> use `LIBGL_ALWAYS_SOFTWARE=1`

well, after putting that as a launch option "LIBGL_ALWAYS_SOFTWARE=1 %command%" it runs with no graphical errors, however it is now a slideshow, completely unplayable.

**Comment by ptitSeb** [comment]
Of course it"s slow. It's software rendering, it will not be fast. But it's justy prove it's a graphic driver issue and not a box64 issuie.

I suggest this ticket to be closed.

**Comment by FoxbitDreamtail** [comment]
> Of course it"s slow. It's software rendering, it will not be fast. But it's justy prove it's a graphic driver issue and not a box64 issuie.
> 
> I suggest this ticket to be closed.

I agree but would compiling a more up-to-date driver fix the graphics issues?

**Comment by FoxbitDreamtail** [comment]
I found something interesting though. If you force your Mesa OpenGL version to 3.2 using `MESA_GL_VERSION_OVERRIDE=3.2` Then all graphics render normally with no slowdown. *This* is the solution I was looking for. I hope that this helps other people in need of this solution.

**Comment by FoxbitDreamtail** [comment]
Well, I found an issue for the graphics and fixed the issue with the graphics. I am now seeing the sigfault that everyone is saying Causing the game to crash.

**Comment by ptitSeb** [comment]
have you tried using `BOX64_DYNAREC_STRONGMEM=1`?

**Comment by FoxbitDreamtail** [comment]
> have you tried using `BOX64_DYNAREC_STRONGMEM=1`?

I haven't by will be trying that in conjunction with the other command that I have and see if that works better and doesn't crash. I will be testing it for roughly two and a half hours(my usual play session time) to see if it crashes or not.

**Comment by FoxbitDreamtail** [comment]
same error after roughly 30 minutes of play.... how should I apply this option? I tried it as a steam launch option before `%command%`, was that wrong?

**Comment by FoxbitDreamtail** [comment]
tried it with the other order and while it did start faster this time, it crashed faster too, ~1-3 minute(s) of playtime...

**Comment by ptitSeb** [comment]
> same error after roughly 30 minutes of play.... how should I apply this option? I tried it as a steam launch option placed before `%command%` but after `MESA_GL_VERSION_OVERRIDE=3.2`, was that wrong? I'll try switching the two and seeing if that fixes anything.

yes, like that it work. If it's better but still crahy, you need to set it to "2" then.

**Comment by FoxbitDreamtail** [comment]
> yes, like that it work. If it's better but still crahy, you need to set it to "2" then.

You said before that this was related to graphics drivers, right? Well, I decided to grab the Debian back course version of Mesa and see if it would help. I'm of course going to temporarily remove the two flags in which I set for slime rancher and see if it makes a difference. And if it doesn't, then I will add the flags back and we will continue with this.

**Comment by FoxbitDreamtail** [comment]
So the Mesa issue with OpenGL is still very much an issue with OpenGL for graphics rendering. But I now have Vulkan working, And I'm only saying this because Box64 used the native library and didn't even attempt to emulate it! I will be trying DXVK later.

**Comment by FoxbitDreamtail** [comment]
So bad news for this issue, Conventional wisdom saved the day as the game no longer crashes with the updated driver. I honestly really should have done this first. When in graphical doubt, update your drivers.
