### ISSUE TITLE
Fallout New Vegas won’t get past the launcher using vulkan on the M1

### ISSUE THREAD

**Issue by m1m1k4tz** [ptitSeb/box64#1946]
Removing DXVK makes it play fine

**Comment by m1m1k4tz** [comment]
[falloutnvmmap32.txt](https://github.com/user-attachments/files/17413670/falloutnvmmap32.txt)

**Comment by m1m1k4tz** [comment]
I did it by passing the env variable with `muvm -e`

**Comment by m1m1k4tz** [comment]
> I don't see it trying to go through box64 mmap64 handler here. Did you apply the `BOX64_MMAP32` on command line or suing `box64rc`?
> 
> side question: do you know if honeycomb use libc mmap or syscall mmap to do it's memory mapping?

I'm not a graphics developer unfortunately and the driver is still early so maybe @alyssarosenzweig might be willing to help sorry

**Comment by m1m1k4tz** [comment]
This might be driver issues also I just don’t have any other arm hardware powerful enough to test on have you tried dxvk on ampere with wine wow64?

**Comment by m1m1k4tz** [comment]
Also honeykrisp is based off the new nvidia NVK driver so you might be able to get a pretty close setup with an nvidia gpu

**Comment by m1m1k4tz** [comment]
Okay, I asked asahi Lina and she thinks it’s libc it’s shared code between the OpenGL and vk drivers as far as she knows

**Comment by m1m1k4tz** [comment]
Does this reproduce for you on ampere with wow64? Looking thru the wine wow64 merges memory mapping was a pain point for them https://gitlab.winehq.org/wine/wine/-/merge_requests?scope=all&state=merged&search=Vulkan+wow64

**Comment by m1m1k4tz** [comment]
Okay this issue is being tracked on hangover too as https://github.com/AndreRH/hangover/issues/168

**Comment by m1m1k4tz** [comment]
I’m thinking that this is just a missing extension in the driver it’s weird that the MMAP32 hack won’t work though

**Comment by ptitSeb** [comment]
> I’m thinking that this is just a missing extension in the driver it’s weird that the MMAP32 hack won’t work though

If the graphic driver use syscall instead of libc `mmap` to allocate it's memory, the MMAP32 hack will not work.

**Comment by m1m1k4tz** [comment]
Ah okay, that makes sense

**Comment by m1m1k4tz** [comment]
On OpenGL the battery life you can get from this game is really impressive so I can only imagine how it will be under box32 with dxvk it’s a shame that the driver doesn’t support VK_EXT_map_memory_placed though because hangover needs it to function correctly
