### ISSUE TITLE
Regression causes steam on the M1 to crash often

### ISSUE THREAD

**Issue by m1m1k4tz** [ptitSeb/box64#1947]
Reverting 65c2b103b16b321a81c8d26db7c228f0ab2d1201 seems to fix this. I've also tried strongmem but it didn't help

**Comment by ptitSeb** [comment]
Oh noooooo; not that one. I spent 2 days on this already :'(

**Comment by ptitSeb** [comment]
also, steam is super hard to debug, I would prefer something else to track that regression (and I didn't saw any regression on my side, but uisng the Linux version of Steaam, I'assuming you talk about the Windows version).

**Comment by m1m1k4tz** [comment]
> also, steam is super hard to debug, I would prefer something else to track that regression (and I didn't saw any regression on my side, but uisng the Linux version of Steaam, I'assuming you talk about the Windows version).

I’m using the windows version, yes. I think that could be a good idea though if box32 is going to run steam I could just revert it for now and keep testing the games on the M1

**Comment by ptitSeb** [comment]
I have found something, and pushed a fixed. Not sure it's the root cause of the issue you are experience, but it will certainly help. Can you update box64 and try again, to see if the unstability are gone now?

**Comment by m1m1k4tz** [comment]
I do think it helps but it still crashes pretty quickly when I interact with the client it seems like
[steam.txt](https://github.com/user-attachments/files/17437540/steam.txt)

**Comment by m1m1k4tz** [comment]
Wine was just updated to use the capstone library I'm not sure if that makes debugging wine stuff any easier for you too

**Comment by ptitSeb** [comment]
I have pushed a workaround for this issue. I disable the new Native Flags handling for "steamwebhelper.exe". It should be stable again.

**Comment by m1m1k4tz** [comment]
Thanks! It looks like this works
