### ISSUE TITLE
Install Bash by default

### ISSUE THREAD

**Issue by LukeShortCloud** [ptitSeb/box64#1948]
Would it be possible to install the install the Bash binary by default? Have `sudo make install` copy `tests/bash` to `/usr/local/bin/box64-bash` so that it's (1) installed and (2) has a slightly different name that does not conflict with the native `bash`.

**Comment by ptitSeb** [comment]
Sure, that would be easy.
But how would be the best way to setup `BOX64_BASH` environnement variable?

**Comment by ptitSeb** [comment]
Ok, done with cdf81eb1d7adb3faf8d0050798810742947e09af

**Comment by LukeShortCloud** [comment]
I can confirm that Bash now works out-of-the-box. Thanks, Seb!
