### ISSUE TITLE
Xbox Microsoft login is small and unusable trying to play MCC on the M1

### ISSUE THREAD

**Issue by m1m1k4tz** [ptitSeb/box64#1950]
fc7d204d4bca211f2462a0534e77f0929f121330 seemed to make the browser not crash anymore when the browser comes up to login but its unresponsive when you try to click get started  
![Screenshot from 2024-10-20 18-01-41](https://github.com/user-attachments/assets/4f1fbb9e-fc17-412e-a73e-c9df519078fa)

**Comment by ptitSeb** [comment]
I tried on my Ampere machine and it worked fine on my side. Is that a regression?

**Comment by m1m1k4tz** [comment]
Okay that kinda confirms my suspicions that it’s a driver or scaling issue somewhere I might try messing around with a virtual desktop and see if I can workaround this when I try clicking anywhere it’s unresponsive currently

**Comment by m1m1k4tz** [comment]
Since I’m pretty sure this is a scaling thing I’m pretty sure it has nothing to do with box64 so I’ll close this ticket
