### ISSUE TITLE
[questions] if Proton is supported does it mean I can launch games that are on SteamOS?

### ISSUE THREAD

**Issue by Behinder** [ptitSeb/box64#1951]
I don't know why I need it  but I was able to build it on ARM64 Ubuntu in virtual machine on M2Pro Probably because it will be necessary to run Steam, however box86 is not able to compile.
Is there any reason to build it natively on Apple Silicon while we have Rosetta?

**Comment by ptitSeb** [comment]
Box86 cannot be built on AppleSilicon, this chip do not support 32bits arm. Use box32 from box64 (but it's incomplete for now).

Steam is a mixed 32bits/64bits application, and needs box86+box64 to run (box32 is not yet compatible with Steam).
Proton can run with box32+box64, but box32 doesn't not have Vulkan support yet, so result are modests

Rosetta is for MacOS apps. If you want to use Rosetta and not Box, use an x86_64 version of Ubuntu and notan Arm64 version of it.

**Comment by m1m1k4tz** [comment]
Right now the only solution for steam using box is to run the steam exe with wine compiled with wow64.b(https://github.com/Kron4ek/Wine-Builds/releases) And a good prefix taken from an x86_64 machine ptitSeb is working on box32 to be able to get the native version of steam working though Otherwise, you should do dnf install steam to use FEX-Emu on Asahi Linux if you want video games currently. I think installing FEX takes about a gb to get working not sure though

**Comment by m1m1k4tz** [comment]
On a side note hangover just released support for x86_64 apps. (https://github.com/AndreRH/hangover/commits/master/) I haven't tried it as it doesn't use box64 for 64 bit apps because its not compatible with the new ARM64EC tool chain yet.

**Comment by Behinder** [comment]
Technically I am not building on Apple Silicon, but on Ubuntu that is run
inside virtual machine.

wt., 22 paź 2024 o 15:58 ptitSeb ***@***.***> napisał(a):

**Comment by m1m1k4tz** [comment]
Your best bet if you want to stick with macOS is to use Apple's Game Porting Toolkit (https://developer.apple.com/games/game-porting-toolkit/), CrossOver (https://www.codeweavers.com/crossover#mac) or Parallels Desktop (https://www.parallels.com/products/desktop/)

**Comment by Behinder** [comment]
Parallels Desktop uses Qemu under the hood it's a no-go. You cannot install
systems that has no version for ARM like Mojave. Windows 10 support is
non-existent, not sure about 11 now.
 Crossover is not worth money because it works as bad as wine and lot of
games are not supported just because.
If a user can port game himself then I would really like to know how :) and
Apple didn't want to add GPT to older systems than Sonoma so it's not
viable solution in long term.
Asahi Linux currently is not able to be run in virtual machine, and yes not
everyone wants to have 2 systems installed side by side.

So with that landscape I really not seeing where Box86 is usefull. Maybe
you should change naming convention to avoid confusion.



śr., 23 paź 2024 o 00:13 m1m1k4tz ***@***.***> napisał(a):

**Comment by m1m1k4tz** [comment]
This isn’t a box64 issue so I would suggest closing this.

**Comment by Behinder** [comment]
you started that "other solution" info :)

śr., 23 paź 2024 o 00:27 m1m1k4tz ***@***.***> napisał(a):

**Comment by LukeShortCloud** [comment]
Steam and Proton are both working with Box32 now. I recommend using Fedora Asahi Remix as it fully supports OpenGL and Vulkan (something Linux virtual machines lack when running on a macOS host).

One lingering issue is that Box64 only supports 64-bit Vulkan libraries (not 32-bit) but that'll be worked on soon.

Closing as resolved.
