### ISSUE TITLE
[BOX32] Add binfmt support for 32-bit applications

### ISSUE THREAD

**Issue by LukeShortCloud** [ptitSeb/box64#1973]
Currently, Box64 only works for x86_64 applications automatically via `binfmt`. It looks like that configuration file is dynamically generated by CMake.

https://github.com/ptitSeb/box64/blob/aebfd61539c595dddea2e3612c2ad4c358d2eae8/system/box64.conf.cmake

Perhaps there can be a new build option `-D BOX32_BINFMT=1` to additonally enable support for x86_32 applications. Leave it off by default since it can conflict with Box86. Box32 is also still in early stages of development.

**Comment by ptitSeb** [comment]
Done. For now, it's an option in the cmake project.

**Comment by LukeShortCloud** [comment]
It works great, thank you for the addition!
