### ISSUE TITLE
Cinebench R15

### ISSUE THREAD

**Issue by Heasterian** [ptitSeb/box64#20]
Cinebench R15 crashes at start of CPU benchmark with missing opcode.

```
7235|0x5b29894: Unimplemented Opcode (F9) 0F C3 45 00 E8 93 98 FF FF 48 83 C6 04 48 89
```

**Comment by theofficialgman** [comment]
unrelated to cinebenchr15 but also missing this opcode for geekbench5 to run
```14583|0x1c37966: Unimplemented Opcode (D2) 64 FF 50 10 89 C0 48 89 45 20 C7 45 0C 00 00```

**Comment by ptitSeb** [comment]
@theofficialgman please don't hijack a ticket for something not related. Opcodes are quite different, there is no reason to regroup missing opcode inside a single ticket...

**Comment by Heasterian** [comment]
As Cinebench R15 is working now, I'm closing issue.

**Comment by theofficialgman** [comment]
> @theofficialgman please don't hijack a ticket for something not related. Opcodes are quite different, there is no reason to regroup missing opcode inside a single ticket...

my apologies, I will test the latest version today to make sure 2010f8d fully solved geekbench5

Would you rather have a discussion tab/main issue documenting all the unsupported opcodes or is this not necessary since you already know which ones aren't supported?

**Comment by ptitSeb** [comment]
I prefer issues grouped per apps / games.
