### ISSUE TITLE
Box64 problems with compiling

### ISSUE THREAD

**Issue by SC13NC3F1CT10N** [ptitSeb/box64#200]
I attempted to compile Box64 on my Raspberry Pi 4 running Ubuntu Mate 21.10. The error occurs when running  `make -j4`
This is a copy of the entire process:

Scanning dependencies of target WRAPPERS
Scanning dependencies of target dynarec_arm
[  0%] Generating ../src/wrapped/generated/functions_list.txt
[  0%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o
[  1%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm64_functions.c.o
cc1: error: ‘-mfloat-abi=hard’: selected architecture lacks an FPU
[  1%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm64.c.o
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:82: CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: error: ‘-mfloat-abi=hard’: selected architecture lacks an FPU
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:108: CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm64_functions.c.o] Error 1
cc1: error: ‘-mfloat-abi=hard’: selected architecture lacks an FPU
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:95: CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm64.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:248: CMakeFiles/dynarec_arm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Detected same build as last run, skipping
[  1%] Built target WRAPPERS
make: *** [Makefile:182: all] Error 2

If anyone could help with this issue it would be appreciated.

**Comment by ptitSeb** [comment]
Did you followed the instructions from `docs/COMPILE.md`?

**Comment by SC13NC3F1CT10N** [comment]
Yes, I did.

**Comment by ptitSeb** [comment]
How did you configured the cmake project? Also, are you using latest sources from github?
Also also, if you mis-configured the project first, don't forget to purge the `build` folder so cmake pick new correct default.

**Comment by SC13NC3F1CT10N** [comment]
Sorry for the time of this reply, I had left the issue for a while but the solution is to just use Raspberry Pi OS 64-bit instead of Ubuntu.
