### ISSUE TITLE
Performance regression in many games

### ISSUE THREAD

**Issue by skydark719** [ptitSeb/box64#2009]
I recently noticed that since commit [3448e94] (Improve handling of memory protection and execution bit), there’s been a noticeable performance regression across many of the games I've tried. In some games, the issue is more noticeable, while in others it’s less so.

For example, in Fable: The Lost Chapters, the frame rate dropped from around ~55FPS to ~35FPS, or in Sonic Lost World, it went from ~45FPS to ~40FPS.

I'm using an Nvidia Tegra X1+ device, and this issue started occurring after compiling that particular commit.

**Comment by ptitSeb** [comment]
Thanks for the repport. I didn't notice any speed regression on my side with the things I tested, but I will investigate. Do you have some other games that exhibit the speed regression?

**Comment by skydark719** [comment]
It also happens to me with other games using Wine and DXVK, like Devil May Cry IV, Just Cause 2, and Castlevania Lords of Shadow, Yume Nikki 3D and Dead Space.

But I tested a demo of a Linux game in OpenGL (Ultrakill), and the speed is the same, also not changes with Max Payne 2 on Wine and DXVK. Not all games are affected.

If you want to test, Yume Nikki 3D is a free and lightweight indie game, using wine and wow64 (without DXVK because it uses DirectDraw7). In this case you'll probably notice performance drop.

**Comment by ptitSeb** [comment]
Ok, I reproduce the issue with that game. I'll analyse to understand what is going on.

**Comment by ptitSeb** [comment]
Ok, I fixed the issue, I think. At least Yum 3D is back to it's original speed for me. If you can test that new version.
