### ISSUE TITLE
FNV strongmem issue one more time...

### ISSUE THREAD

**Issue by dave9292** [ptitSeb/box64#2015]
Hi Ptitseb and good day. I already wrote here earlier about the problem with Fallout New Vegas and Strongmem with huge fps drops at 1 value. It looks like I found a commit https://github.com/ptitSeb/box64/commit/8d0cc15eb0d078e5ae457bca8b11a31c28a96e27
 after which (as I see it) strongmem=1 became strongmem=2, before this commit, playing with strongmem 1 fps loss was only 5-6, but after it became 15.. I'm playing on the build dated January 29th and this is quite good if you don't take into account all the subsequent months of optimizations due to which FPS can be even higher.
and again, without strongmem 1 the game just dies randomly without errors within 1-15 minutes of playing.

I just want to play my favorite game on my old device, and I don’t have the money to buy a flagship yet to say “ha! who cares? I have a powerful enough processor to play even with Strongmem 3!”

**Comment by ptitSeb** [comment]
This commit you linked is not supposed to havec changed strongmem=1 behaviour. Only strongmem=2,3 and introduced 4. strone that you see a performance drop on strongmem=1 there.
I'll try to recheck everything, to be sure...

**Comment by dave9292** [comment]
> This commit you linked is not supposed to havec changed strongmem=1 behaviour. Only strongmem=2,3 and introduced 4. strone that you see a performance drop on strongmem=1 there. I'll try to recheck everything, to be sure...

To be honest, I'm quite far from programming languages ​​and in general, so forgive me for this, I tried to identify the commit but I don't understand it at all (or almost)
I conducted tests a month ago and found that the performance drop was after the first days of February (until about February 5-6), that is, the period from January 29 to February 5-6) something changed in the behavior of Strongmem=1.
In modern builds with Strongmem=1, fps drops by almost 20 in FNV.
I really appreciate your project and how you devote time to ordinary people with these problems, considering that development is ongoing, thank you!

**Comment by dave9292** [comment]
Looks like the commit https://github.com/ptitSeb/box64/commit/81e4e26dc51b85720fbc3ba2ffe68030e5d227fa did the job, huge thanks to @ksco for Weakbarrier and Strongmem rework, that's just AWESOME! and of course thanks to @ptitSeb for the project, that's one of the coolest things I've ever seen!
