### ISSUE TITLE
Segmentation Fault trying to run Telegram Messenger

### ISSUE THREAD

**Issue by Gato303** [ptitSeb/box64#202]
Hello, this is my very first post.  I tried to run Telegram for Linux for AMD64, cause the Flatpak version crashes when viewing certain media content (like animated stickers) and the Snapcraft version runs very slow after some update.

I read about getting the required AMD64 libraries for the program to work and placed them in the directory where the executable Telegram file was, I downloaded `libdrm.so.2 libEGL.so.1 libGLdispatch.so.0`

I run on the command line where the Telegram AMD64 binary is and I get this output with error and the program never start

`carlos@carlos-pi:~/Telegram$ box64 Telegram 
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.6 nogit built on Dec 20 2021 20:41:16
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 60 Env var
Looking for Telegram
Using native(wrapped) libX11.so.6
Using emulated libdrm.so.2
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using emulated libEGL.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libxcb.so.1
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated libGLdispatch.so.0
Error: PltResolver: Symbol g_variant_type_copy(ver 0: g_variant_type_copy) not found, cannot apply R_X86_64_JUMP_SLOT 0x62dff48 (0xd43e96) in /home/carlos/Telegram/Telegram
3625|SIGSEGV @0x6496bcec (???(box64/0x6496bcec)) (x64pc=0x22093/???:"???", rsp=0x4a, stack=0xffff96aed000:0xffff972ed000 own=(nil) fp=0x42), for accessing 0x42 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
Segmentation fault (core dumped)
carlos@carlos-pi:~/Telegram$ `

I don't know what to do next and can't find help to solve this error,  I will thank any help.

**Comment by rajdakin** [comment]
Is this fixed now?
