### ISSUE TITLE
error: unknown type name '__uint128_t'

### ISSUE THREAD

**Issue by kirby3021** [ptitSeb/box64#203]
When trying to compile using the make -j$(nproc) command, I keep encountering the following error:

error: unknown type name '__uint128_t'

I have followed all of the steps listed on [pymylifeup](https://pimylifeup.com/raspberry-pi-x64/) to the letter and am curious what may be causing this problem. I am currently running Raspbian GNU/Linux 11 (bullseye). 

Please let me know if you need any additional information. I have attached a text version of the compiler output to this issue if that helps.
[error message.txt](https://github.com/ptitSeb/box64/files/7805909/error.message.txt)

**Comment by ptitSeb** [comment]
Box64 cannot be built on 32bits system. You NEED a 64bits OS for it, as detailled in the README

**Comment by kirby3021** [comment]
Thanks for the quick response, this is my first attempt at using the Pi and I thought I had downloaded the correct OS. Looks like I have some more work to do.

**Comment by ptitSeb** [comment]
Yes, the 64bits OS for Pi4 is still tagged beta and not straightforward to find and download.
