### ISSUE TITLE
[DYNAREC] BOX64_DYNAREC_STRONGMEM tuning for libjvm

### ISSUE THREAD

**Issue by xiangzhai** [ptitSeb/box64#2041]
Hi,

The weak memory model architectures[1] reproduced less memory barrier related issue after tuning `BOX64_DYNAREC_STRONGMEM` to bigger one:

| BOX64_DYNAREC_STRONGMEM | SPECjvm2008[2] derby Reproduced SIGSEGV (run 10 times) smaller is better |
| ------------------------------------------------ | ------------------------------------------------------------------------------------------------------- |
| 1 | 80% |
| 3 | 20% |

So is it OK tuning `BOX64_DYNAREC_STRONGMEM` to bigger one for libjvm?

```
diff --git a/src/librarian/library.c b/src/librarian/library.c
index bf922d60..c206d365 100644
--- a/src/librarian/library.c
+++ b/src/librarian/library.c
@@ -371,7 +371,7 @@ static int loadEmulatedLib(const char* libname, library_t *lib, box64context_t*
             #ifdef DYNAREC
             printf_dump(LOG_INFO, "libjvm detected, disable Dynarec BigBlock and enable Dynarec StrongMem, hide SSE 4.2\n");
             box64_dynarec_bigblock = 0;
-            box64_dynarec_strongmem = 1;
+            box64_dynarec_strongmem = 3;
             #else
             printf_dump(LOG_INFO, "libjvm detected, hide SSE 4.2\n");
             #endif
```

[1] Synchronization Overview and Case Study on Arm Architecture  https://community.arm.com/arm-community-blogs/b/infrastructure-solutions-blog/posts/synchronization-overview-and-case-study-on-arm-architecture-563085493
[2] SPECjvm2008 https://www.spec.org/jvm2008/

Thanks,
Leslie Zhai

**Comment by ksco** [comment]
Hmmm, this seems not correct, the bigger the number, the more barriers should be inserted. Anyway, the strong memory model is in refactoring right now, starting from arm64, it will be fixed soon on LA64 too.

**Comment by xiangzhai** [comment]
> Hmmm, this seems not correct, the bigger the number, the more barriers should be inserted.

Yup, and the performance regression is obvious (~18.29%) for heavier barrier:

| BOX64_DYNAREC_STRONGMEM | SPECjvm2008[2] derby Score bigger is better |
| ------------------------------------------------ | ------------------------------------------------------------ |
| 1 | 57.985 |
| 3 | 47.378 |

Thanks,
Leslie Zhai

**Comment by ksco** [comment]
This is not an issue, it's just a fact that `STRONGMEM=3` will be slower than `=1`. I think this can be closed.
