### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by qwertypower** [ptitSeb/box64#2047]
Hi @ptitSeb. Look at videos. The new version of box64 lagging with any wine and settings(strongmem, forward, etc)
Old box64 0.3.1 
https://github.com/user-attachments/assets/7e88ceb1-3c07-47d9-9bff-cc24660154d1

Latest box64 0.3.1
https://github.com/user-attachments/assets/6b8bfc01-be36-484d-9529-6ee98c45a5da

Alice madness returns, Unreal Engine 3.

**Comment by ptitSeb** [comment]
Did you build from source? If yes check that the ccmake settings haven't reset themself for some reason and you run without dynarec enabled now.

**Comment by qwertypower** [comment]
> Did you build from source? If yes check that the ccmake settings haven't reset themself for some reason and you run without dynarec enabled now.

No, builded by https://github.com/sandstranger/WinlatorBox64Builds/releases/tag/box64_5629887
By the way, this issue exists from 0.3.1.4e10cd6

**Comment by ptitSeb** [comment]
> > Did you build from source? If yes check that the ccmake settings haven't reset themself for some reason and you run without dynarec enabled now.
> 
> No, builded by https://github.com/sandstranger/WinlatorBox64Builds/releases/tag/box64_5629887 By the way, this issue exists from 0.3.1.4e10cd6
> 
> P.S. Dynarec works. I will try to output the logs.

Mmm, unfortunatly, that's not a real bisection on box64 sources, so that doesn't really help me.

**Comment by qwertypower** [comment]
> > > Did you build from source? If yes check that the ccmake settings haven't reset themself for some reason and you run without dynarec enabled now.
> > 
> > 
> > No, builded by https://github.com/sandstranger/WinlatorBox64Builds/releases/tag/box64_5629887 By the way, this issue exists from 0.3.1.4e10cd6
> > P.S. Dynarec works. I will try to output the logs.
> 
> Mmm, unfortunatly, that's not a real bisection on box64 sources, so that doesn't really help me.

Okay, thank you, i will try to compile latest box64 myself and report results.

**Comment by ksco** [comment]
what are your settings in specific? especially strongmem, is it strongmem=2?

**Comment by qwertypower** [comment]
Still same problem with https://github.com/ptitSeb/box64/actions/runs/11921132727
