### ISSUE TITLE
SIGSEGV when running KSP

### ISSUE THREAD

**Issue by Pythonic456** [ptitSeb/box64#206]
On running this command:
`$ box64 KSP.x86_64`
I get this output:
[output.txt](https://github.com/ptitSeb/box64/files/7833273/output.txt)
In the GUI, KSP says it is loading "Asset Bundle Definitions", I left it for over and hour with no progress.
The CPU stays maxed the whole time.
As soon as it tries to load the "Asset Bundle Definitions", the SIGSEGV happens.

OS: Raspberry Pi OS 64-bit Buster 10
Box64: Latest

**Comment by ptitSeb** [comment]
Is this
```
libGL error: failed to create dri screen
libGL error: failed to load driver: vc4
libGL error: failed to open /dev/dri/card1: No such file or directory
libGL error: failed to load driver: vc4
```
Normal? (it's not box64 fault). You seems to be running software llvmpipe...
Also, there are a lot of ALSA error, that also don't look normal.

Error is when calling `Lingoona.NativeMethods.setLanguage(...)` that is probably calling some wrapped function, either with a mystake in the wrapping, or completly missing. I'll check if I can reproduce on my side. Just to be sure, you are using latest version?

**Comment by Pythonic456** [comment]
Latest version of box64, KSP 1.12.1 it seems.

**Comment by Itai-Nelken** [comment]
Latest version of KSP has never worked as far as I know.

**Comment by Pythonic456** [comment]
I did get it running once or twice a while back, same version of KSP as I'm trying now, you could start a new world in KSP and build a rocket, however (as far as I remember) launching a rocket had issues.

**Comment by Pythonic456** [comment]
[This version](https://github.com/ptitSeb/box86/issues/273#issuecomment-798660651) (1.2.2) worked with box86 because it was 32-bit, but the newer versions are 64-bit only, requiring box64 to run. I am 100% positive that I have got 1.12.1 running on box64 before.

**Comment by ptitSeb** [comment]
I got the latest KSP running on box64 now. But it will not work on RPI4 because of some unsupported texture format (BC7 iirc). It does boot, but don't complete the loading.
I haven't tested older version, but I suppose it should work now.

**Comment by Pythonic456** [comment]
Alright, I will close this issue, and will also test some older versions later.
