### ISSUE TITLE
Snapdragon 8s gen 3 низкий FPS

### ISSUE THREAD

**Issue by King6696** [ptitSeb/box64#2064]
На Snapdragon 8s gen 3 в играх низкий FPS при этом GPU практически не нагружен, когда ета проблема будет исправлена?

**Comment by ptitSeb** [comment]
Please ask your questions in English.

As for you question: I don't know, I don't have performances issues on my side. Be more specific.

**Comment by weed89** [comment]
After commit 0912e8f huge performance regression on Poco F3. Tested in Dying Light.

**Comment by ptitSeb** [comment]
> After commit [0912e8f](https://github.com/ptitSeb/box64/commit/0912e8f16d8c937d9f115d22539d2ac5255925ab) on winlator 7.1.3 glibc huge performance regression on Poco F3. Tested in Dying Light.

This commit exactly? or somewhere after this commit (including it)?

**Comment by weed89** [comment]
I just nested next one that is b0c10c9 works good as well, so right after that one regression appears.

**Comment by ptitSeb** [comment]
> I just tested next one that is [b0c10c9](https://github.com/ptitSeb/box64/commit/b0c10c9ae5938302b2bb9c941ba2a15e15d61be0) works good as well, so right after that one regression appears.

Ok, I don't understand.

0912e8f : speed regression, but b0c10c9 has good speed?

**Comment by weed89** [comment]
0912e8f no performance regression, works well.

**Comment by ptitSeb** [comment]
So, there is no performance regression on current version of box64?

**Comment by weed89** [comment]
Current is the 93fa532 I tested, that one is causing performance regression and fps drop for like 10 fps roughly.

**Comment by ptitSeb** [comment]
Ah, ok, I understand now.

**Comment by weed89** [comment]
Also commit 93fa532 causes Fallout 4 to crash.
Warcraft III The Frozen Throne works as usual (no performance impact on it).

**Comment by ptitSeb** [comment]
Ok, I pushed a fix, can you try again?

**Comment by weed89** [comment]
Commit 73b17d4 fixed issues with Fallout4, but still keeps poor performance in Dying Light.

**Comment by ksco** [comment]
@weed89 the above PR should fix your issue, and a slightly higher fps in the menu too. :)

**Comment by weed89** [comment]
@ksco idk what you did there but all the games now work optimally now as they were on commit 0912e8f.
-Fallout 4 no longer crash, performance is good.
-Dying Light performance is good.
-Left 4 Dead 2 performance is good.
-Sun Haven (unity game, strongmem 1) performance is good
-Warcraft III Frozen Throne performance is good.
You fixed the performance issue. Thanks!

**Comment by ksco** [comment]
Thank you for the testing!

**Comment by rajdakin** [comment]
@weed89 Nice! If possible, could you please add Fallout 4 and Sun Haven to the [ptitSeb/box86-compatibility-list](https://github.com/ptitSeb/box86-compatibility-list/issues) repo? (Just add new issues for each individual games with screenshots, that way the status can be tracked on [the compatibility list](box86.org/app). I've just checked, the other apps are already present there.)

**Comment by weed89** [comment]
But this is box64. It goes into box86 compatability list?

**Comment by rajdakin** [comment]
No, the box86 compatibility list is a repo dedicated to maintaining a list of app status for box86, box64 and box32, ie "working" or "not working". The actual issues must be reported in the correct repo (either the box86 repo for issues with box86, or this box64 repo for issues with box64 and/or box32).
The name "box86-compatibility-list" only mentions box86 for historical reasons (box86 was developed first). The issues in the compatibility list repo are explored by [the compatibility list on box86.org](box86.org/app) to build the array.
