### ISSUE TITLE
Performance regression (weakbarrier)

### ISSUE THREAD

**Issue by dave9292** [ptitSeb/box64#2068]
Hi, I noticed quite a serious regression after this build, on all builds settings: strongmem=1, weakbarrier=1
https://github.com/ptitSeb/box64/actions/runs/11921132727/job/33224607941
I'm attaching screenshots with comparison, thanks in advance :)

1) screenshot from this build https://github.com/ptitSeb/box64/actions/runs/11998786363) same result on all builds after build in 2)
![Screenshot_20241124-235253](https://github.com/user-attachments/assets/9b054c69-43c7-478a-9353-7491b3e9d07d)
2) screenshot from this build (last fastest)
https://github.com/ptitSeb/box64/actions/runs/11921132727/job/33224607941
![Screenshot_20241125-002910](https://github.com/user-attachments/assets/bd80d8a5-e0e3-4d8b-851d-140a5088a5b8)
3) screenshot with Strongmem=1 without Weakbarrier=1
![Screenshot_20241124-235838](https://github.com/user-attachments/assets/35858955-6b02-4cf8-8d68-ebfcd0076f02)

**Comment by dave9292** [comment]
> What's the game and your hardware?

Fallout New Vegas, Snap 778g. A14.

**Comment by ksco** [comment]
Can you try this one to see if it's slow or fast? https://github.com/ptitSeb/box64/actions/runs/11995282400

(BTW, this issue has nothing to do with weakbarrier)

**Comment by ksco** [comment]
> By the way, is there any explanation why Fallout New Vegas crashes so often without Strongmem=1? Fallout 3 is built on the same engine and was released 2 years earlier, but it doesn't crash.

Because it depends not only on the game engine, but also on the game itself.

**Comment by dave9292** [comment]
> > By the way, is there any explanation why Fallout New Vegas crashes so often without Strongmem=1? Fallout 3 is built on the same engine and was released 2 years earlier, but it doesn't crash.
> 
> Because it depends not only on the game engine, but also on the game itself.

I see It's a bit disappointing that all the YT videos of this game on Box86/64 show gameplay for 5-10 minutes and then a crash. I don't know how the game performs on ExaGear; maybe I should give it a try, although I'm sure the FPS will be veeeery low. In any case, thanks for your answers, I will be waiting for any improvements regarding the FPS if it's possible, or stay with the build that has the highest FPS.

**Comment by ksco** [comment]
@dave9292 If I'm not asking too much, can you test FNV using https://github.com/ptitSeb/box64/actions/runs/12006722468 one more time?

There is a new and unofficial option called `BOX64_DYNAREC_PAUSE` in this build. You can set it to 0, 1, 2, or 3. The default value is 0, which should be the same as the "last fastest" you mentioned.

**Comment by dave9292** [comment]
@ksco
I would be happy to report that it helped, but unfortunately, it didn't, I tried 0 and even 3 (just to be sure!) absolutely no difference...

I probably ask too much, and it is not necessary to do this right now, I waited almost a year and you saved me with Weakbarrier, yes, it is long, but I am patient and can wait a longer, after all, I am still unemployed, but I am already (almost...) getting a job and planning to take something on Gen3 in near future :)

**Comment by ksco** [comment]
`BOX64_DYNAREC_PAUSE=0` would at least give you the same fps as the "last fastest", no?

**Comment by dave9292** [comment]
@ksco no, still same fps

**Comment by dave9292** [comment]
@ksco
These two screenshots are not 100% identical in the "scene", there is a shift in one of them, which VERY much affects the fps, sometimes a shift of a couple of pixels is enough for the fps to differ, for an accurate test the scene should be exactly the same, which is what I did. I did as you asked and did not intend to tell a lie, explain to me what is the point of this? thanks anyway.

**Comment by dave9292** [comment]
@ksco BOX64_DYNAREX_X87DOUBLE must be on or off?
