### ISSUE TITLE
[X64] termux proot(debian), can not start totalcmd after install

### ISSUE THREAD

**Issue by wangbin19860909** [ptitSeb/box64#2093]
totalcmd version: 11.50
wine version: wine-9.7
box64 version: latest source build, build opts: 
-D ARM64=1 -DCMAKE_C_COMPILER=gcc -DBAD_SIGNAL=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo 

BOX64_DYNAREC=0 worked but too slow

[box64-log.tar.gz](https://github.com/user-attachments/files/17964397/box64-log.tar.gz)

**Comment by ptitSeb** [comment]
I tried on my side. Grabbed the current TotalCMD 32bits, installed it and I can run it just fine on my machine. Is it the 32bits version that you used or something else? (I assumed 32bits becasue you mentionned WOW64 in the title)

**Comment by wangbin19860909** [comment]
Sorry, I confuse wow64 with x64

**Comment by ptitSeb** [comment]
Ah ok, well, I'll retest later.

**Comment by wangbin19860909** [comment]
@ptitSeb I tried 32bits TotalCMD with box86 and wine32, it works fine.

**Comment by ptitSeb** [comment]
Ok, found the issue in the 64bits version. It should work now with latest box64.
