### ISSUE TITLE
How to install winbind for WINE in Box64?

### ISSUE THREAD

**Issue by zcheese1** [ptitSeb/box64#2094]
Hello,
I am currently running WINE in Box64 on an aarch64 host. Some Windows programs require **winbind** (like **ntlm_auth**) to run properly. WINE can't use aarch64 packages so, is there any way? Thanks

**Comment by ptitSeb** [comment]
Install the aarch64 version of winbind, box64+wine will be able to use it with no issue.

**Comment by zcheese1** [comment]
> Install the aarch64 version of winbind, box64+wine will be able to use it with no issue.

Thanks! I forgot that box64 can wrap native libs
