### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by josch** [ptitSeb/box64#2098]
Hi,

you have made 851 commits since version 0.3.0. For distributions it is much easier to package something that has a git tag or a github release.

Please consider adding a new tag and/or release once you feel that it's ready.

Thanks!

cheers, josch

**Comment by ptitSeb** [comment]
Yeah, I'm aware it's been a long time already. I wanted to have box32 in a better shape before releasing. But I may have to act before it seems, box32 will take long to get stable.

**Comment by josch** [comment]
Thank you for your work! There is no rush, I did not mean to put pressure on you. Release when you feel it's "ready". :)

**Comment by josch** [comment]
@ptitSeb do you think i should keep box32 disabled as is the default for the Debian packaging of box64? Or should I build box32 for Debian next to box64?

**Comment by ptitSeb** [comment]
> @ptitSeb do you think i should keep box32 disabled as is the default for the Debian packaging of box64? Or should I build box32 for Debian next to box64?

good question. I think a strategy would be to enable box32 in box64 build, but have the binfmt integration as a separate package "box32".

**Comment by josch** [comment]
If you say that having a separate box32 package makes sense, then I would also put the binary into that one. Would you have objections to such a strategy? Thank you!

**Comment by ptitSeb** [comment]
> If you say that having a separate box32 package makes sense, then I would also put the binary into that one. Would you have objections to such a strategy? Thank you!

`box32` is not a separate bianry. At least not for now. It's integral part of box64.

**Comment by josch** [comment]
Oh, sorry I just read your blog post without having a look at the code. From the blog post and its mentioning of "it's a subproject" I got the completely wrong impression. XD

Yes, I think it makes sense to add a box32 binary package which depends on box64 and just contains the binfmt integration. Lets do it like that. :)
