### ISSUE TITLE
[BOX64] Error loading needed lib stdc++.so.6

### ISSUE THREAD

**Issue by Henry-Hiles** [ptitSeb/box64#2114]
Hello! I'm trying to run an amd64 game with box64 on postmarketos on an (arm64) oneplus 6t.

I'm recieving this error (I'll give the whole log if someone can tell me how to redirect the output, I can't seem to do it even with `&>`): 
![Screenshot from 2024-12-05 17-37-11](https://github.com/user-attachments/assets/e8d0204a-f7fe-498b-ba0f-5a87b15582a0)

A simple amd64 hello world binary does work fine.

Any troubleshooting help would be great, thanks!

**Comment by ptitSeb** [comment]
this lib "libstdc++.so.6" is needed by the program. The x86_64 version of it. It's usualy instealled with box64, but if you only have the box64 binary, you can copy the library directly in the same folder as the executable. You can find this lib in the `x64libs` folder of box64 repo, or use a version from you prefered linux distribution. You will probably need `libgcc_s.so.2` also.

**Comment by Henry-Hiles** [comment]
thank you!

**Comment by Henry-Hiles** [comment]
> this lib "libstdc++.so.6" is needed by the program. The x86_64 version of it. It's usualy instealled with box64, but if you only have the box64 binary, you can copy the library directly in the same folder as the executable. You can find this lib in the `x64libs` folder of box64 repo, or use a version from you prefered linux distribution. You will probably need `libgcc_s.so.2` also.

That worked, thank you! Now I'm getting these errs, despite these libs being in /usr/lib.

**Comment by jserv** [comment]
> That worked, thank you! Now I'm getting these errs, despite these libs being in /usr/lib: 

As @ptitSeb suggested, ensure the presence of x86-64 shared libraries in search paths, such as `/usr/lib/x86_64-linux-gnu/`. Moreover, instead of using screenshots for text-only messages, you can employ GitHub-flavored markdown syntax to represent command-line messages, for better rendering and searching.

**Comment by Henry-Hiles** [comment]
> > That worked, thank you! Now I'm getting these errs, despite these libs being in /usr/lib:
> 
> As @ptitSeb suggested, ensure the presence of x86-64 shared libraries in search paths, such as `/usr/lib/x86_64-linux-gnu/`. Moreover, instead of using screenshots for text-only messages, you can employ GitHub-flavored markdown syntax to represent command-line messages, for better rendering and searching.

Thank you, I'll try that shared library thing. As for the screenshots, as I'm on Linux mobile, I can't copy/paste from the console, and I can't seem to redirect the output of box64. If you could tell me how to redirect output to a file and still get all info that'd be great, thanks!

**Comment by rajdakin** [comment]
You can add the `BOX64_TRACE_FILE=/path/to/output/file` env. variable to redirect only the output from `box64` to the specified output file (see [the relevant paragraph in the `USAGE.md`](https://github.com/ptitSeb/box64/blob/main/docs/USAGE.md#box64_trace_file-)).

**Comment by Henry-Hiles** [comment]
Oh, thank you! So do i just copy all the amd64 binaries manually or is there a way to install them?

**Comment by jserv** [comment]
> Oh, thank you! So do i just copy all the amd64 binaries manually or is there a way to install them?

You can use `ldd` to figure out the shared libraries you need to satisfy the dependency.

**Comment by ptitSeb** [comment]
The lib you need are in the box64 repo, in the `x64libs` folder

**Comment by Henry-Hiles** [comment]
> The lib you need are in the box64 repo, in the `x64libs` folder

I don't think so? The libs from the errors aren't in that folder as far as I can see.

**Comment by ptitSeb** [comment]
> > The lib you need are in the box64 repo, in the `x64libs` folder
> 
> I don't think so? The libs from the errors aren't in that folder as far as I can see.

The libs from the screenshot are "wrapped". That means box64 can use the arm64 version of the lib. Just install the lib from your  OS distribution and box64 will pick it up and use it for the x86_64 program.
