### ISSUE TITLE
[Winlator] Massive Regression x100

### ISSUE THREAD

**Issue by gurachan** [ptitSeb/box64#2120]
![Screenshot_2024-12-06-22-05-17-773_com winlator](https://github.com/user-attachments/assets/0910ec97-c78a-4863-ba58-dfecb2cd78d1)

## Last Action Builds..
Y = 2 digit fps.
 - e305e5f: Y
 - 18ce48e: Y
 - 869ddcf: Y
 - 65e5e86: Y
 - 122b5e6: N
 - c2d7dc5: N

Expected fps: 1.5k+ now only get 80+ fps 2 digit :'(.

![Screenshot_2024-12-03-04-11-06-125_com winlator](https://github.com/user-attachments/assets/07800461-7f93-4448-b7da-318bf53c1051)

**Comment by ksco** [comment]
Thank you for the report! Pushed a fix above, please wait for the CI to finish and try again.

**Comment by gurachan** [comment]
b250056 fixed it thanks.
