### ISSUE TITLE
box64 winetricks "bug: w_metadata art2kmin corrupt, might need forward slashes"

### ISSUE THREAD

**Issue by wangbin19860909** [ptitSeb/box64#2123]
I setup winetricks with box64, when I run it, it end with "warning: bug: w_metadata art2kmin corrupt, might need forward slashes".
After add some log to winetricks, I found the root cause is the log "Warning, prereserve of xxxx is not free" box64 print.
winetricks will parse the message of command output, but that log broken the format of message.

I export BOX64_NOBANNER=1 but log still there, after I comment the line in wine_tools.c, winetricks works.
I wonder there is a way to remove all the log of box64? And what LOG_NONE means? it seems print always.

**Comment by ptitSeb** [comment]
> I setup winetricks with box64, when I run it, it end with "warning: bug: w_metadata art2kmin corrupt, might need forward slashes". After add some log to winetricks, I found the root cause is the log "Warning, prereserve of xxxx is not free" box64 print. winetricks will parse the message of command output, but that log broken the format of message.
> 
> I export BOX64_NOBANNER=1 but log still there, after I comment the line in wine_tools.c, winetricks works. I wonder there is a way to remove all the log of box64? And what LOG_NONE means? it seems print always.

Yeah LOG_NONE weans always print. I need to chenge this log to LOG_INFO level, so it will be silenced  for wintetricks use for example.

**Comment by ptitSeb** [comment]
Ok, I have changed the log level of those message. it should works fine now with latest box64.
