### ISSUE TITLE
Raspberry Pi4 4GB no longer booting after install

### ISSUE THREAD

**Issue by herkulessi** [ptitSeb/box64#213]
I have build/installed box64 multiple times according to the instrucions and EVERY time, my Raspberry Pi OS Lite (64 bit) refuses to boot after.

Booting ends in a Black screen via HDMI-Out and Internet wont work for ssh.
 Last thing to appear on Screen seems to be 
<code>[  OK  ] Started Kernel Device Manager</code>

I boot from a USB-Stick (seems more reliable than SD-Cards), but other than that, its just a RaspiOS Lite (most recent image) with the latest Updates and nothing else.

**Comment by ptitSeb** [comment]
Don't do the `sudo make install` and reboot your PI. Is it still booting in that case? Is that just the `sudo make install` that is breaking your OS?
You are using RPiOS 64bits?

**Comment by herkulessi** [comment]
Yes, I used the 64 bit RPiOS.
I just did what you suggested, and with the newer Image I used (just the most recent, that was not available last time) it just worked... I even tried a Programm that I am sure is 64 bits and it works. Im closing this for that reason.

No Idea what caused the problem in the first place, but either one of the last commits, or the newer OS Image fixed things.
