### ISSUE TITLE
[box64] Error loading needed lib

### ISSUE THREAD

**Issue by Cat7373** [ptitSeb/box64#2143]
Hi, I am trying to run an x86 based software on Raspberry Pi OS (essentially Debian) and it gives the following error:

```
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 cores
Will use hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 97 entries
Box64 with Dynarec v0.3.3 857c4600 built on Dec 12 2024 04:34:57
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 13 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
Looking for grass
Rename process to "grass"
Using native(wrapped) libssl.so.3
Using native(wrapped) libcrypto.so.3
Using native(wrapped) libpthread.so.0
Error loading needed lib libwebkit2gtk-4.1.so.0
Using native(wrapped) libgtk-3.so.0
Using native(wrapped) libgdk-3.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libcairo.so.2
Using native(wrapped) libcairo-gobject.so.2
Error loading needed lib libsoup-3.0.so.0
Error loading needed lib libjavascriptcoregtk-4.1.so.0
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) libresolv.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Error loading one of needed lib
Error: Loading needed libs in elf /home/cat73/grass/./grass
```

When I checked with `apt list | grep xxxlib`, I found that the libraries that were missing were all installed.

I don't know what to do next, hope to get help, thank you.

**Comment by ptitSeb** [comment]
box64 is tailored to run games. And while it can also run apps, some dependencies might be missing there. Typically, this apps use webkitgtk, but those libs are not wrapped. That means you need to find the x86_64 version of those libs to run that app: `libwebkit2gtk-4.1.so.0`, ` libsoup-3.0.so.0` and `libjavascriptcoregtk-4.1.so.0`

**Comment by Cat7373** [comment]
Thank you. What should I do after I find the corresponding library file under the x86 operating system?

**Comment by ptitSeb** [comment]
> Thank you. What should I do after I find the corresponding library file under the x86 operating system?

Copy the files in a folder were box32 will find them. In the binary folder or any standard folder or a custom folder and you use `LD_LIBRARY_PATH` or `BOX64_LD_LIBRARY_PATH` to point to that folder.
