### ISSUE TITLE
Very notable performance due to Build and Release Box64 #4772: Commit 5bde45c  (Winlator)

### ISSUE THREAD

**Issue by titooo7** [ptitSeb/box64#2152]
When 0.3.2 was released I tried it and I noticed an big performance regression on winlator (android).

I tried diffefent 'box64-latest.wcp' builds from the actions tab to identify which build was the one that introduced the regression till I found it:

From [this build](https://github.com/ptitSeb/box64/actions/runs/12137674194) (related to commit https://github.com/ptitSeb/box64/commit/5bde45cc8695e85de56dc11ecc391bfb2b74bb38) the performance regression in some games is massive. As it can be seen in the video the FPS drop like crazy going down to even 13fps only: https://streamable.com/h9qfy7

With the build 4771 from the same actions tab (and previous builds) it's quitte stable and the FPS can vary from 27 to 32 in the same area but it's not as bad as it's on #4772 and next ones.

I'm hoping the performance regression can be reversed so we, winlator users, can enjoy the other improvements and fixed that I suppose were added to 0.3.2

**Comment by ksco** [comment]
Can you try BOX64_DYNAREC_PAUSE=0 in those games to see if the performance come back to normal?

**Comment by titooo7** [comment]
> Can you try BOX64_DYNAREC_PAUSE=0 in those games to see if the performance come back to normal?

Yes! I just tried that! After using the env variable BOX64_DYNAREC_PAUSE=0 the performance went back to normal!

**Comment by titooo7** [comment]
> > > Can you try BOX64_DYNAREC_PAUSE=0 in those games to see if the performance come back to normal?
> > 
> > 
> > Yes! I just tried that! After using the env variable BOX64_DYNAREC_PAUSE=0 the performance went back to normal!
> 
> can you try BOX64_DYNAREC_PAUSE=1 too?

I just tried it. It's also good when using it with BOX64_DYNAREC_PAUSE=1

**Comment by ksco** [comment]
Thanks for the feedback, we made `BOX64_DYNAREC_PAUSE=3` the default because it shows improvements in some games' loading speed, but if it has some negative impact in some cases, I think the default should go back to 0.

**Comment by titooo7** [comment]
Issue can be closed. Commit[ #2152 ](https://github.com/ptitSeb/box64/issues/2152) fixed it

Thank you!
