### ISSUE TITLE
How to use GTK based gui program

### ISSUE THREAD

**Issue by nicksolark** [ptitSeb/box64#219]
I wanted to use the UniFlash (linux version) program from Ti on my Rasp Pi. However, it seems to use GTK which is not supported (directly, yet) by box64. There is a brief comment about placing GTK libraries to place known by box64. Could this be elaborated upon? Or would it be more possible to use wine and use the windows version?

I can add the error messages if needed. (They are on the pi and I was not singed into GitHub over there)

**Comment by ptitSeb** [comment]
gtk 2 is partly supported on box64, but gtk3 is not. Yes, the error message could help.

**Comment by nicksolark** [comment]
here is the error message in pastebin https://pastebin.com/G5FzZ6cG
I downloaded uniflash (its an installer, from what i can tell) andd placed it into Downloads/uniflash and ran the command 
"./filename.run"

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
GTK 3 is supported in Box64 now. Closing as resolved.
