### ISSUE TITLE
Trying new Mikrotik WinBox Linux on ARM64 issue

### ISSUE THREAD

**Issue by gartfr** [ptitSeb/box64#2217]
Hello, 
I'm trying to execute the new Mikrotik WinBox Tool that now has a native Linux version and works great on x64, but on my arm64 orangepi5 box64 just cannot make it  :

<code>gart@orangepi5:~/Apps/WinBox_Linux$ box64 WinBox 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A55 Cortex-A76 with 8 cores
Will use hardware counter measured at 24.0 MHz emulating 3.0 GHz
Params database has 98 entries
Box64 with Dynarec v0.3.3 14568978 built on Dec 26 2024 07:14:02
BOX64: Detected 48bits at least of address space
Counted 57 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/
Looking for WinBox
Rename process to "WinBox"
Using native(wrapped) libxcb-glx.so.0
Using native(wrapped) libEGL.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libz.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libexpat.so.1
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libxkbcommon.so.0
Using native(wrapped) libxkbcommon-x11.so.0
Using native(wrapped) libxcb-icccm.so.4
Using native(wrapped) libxcb-image.so.0
Using native(wrapped) libxcb-keysyms.so.1
Using native(wrapped) libxcb-randr.so.0
Using native(wrapped) libxcb-render-util.so.0
Using native(wrapped) libxcb-shm.so.0
Using native(wrapped) libxcb-sync.so.1
Using native(wrapped) libxcb-xfixes.so.0
Using native(wrapped) libxcb-render.so.0
Using native(wrapped) libxcb-shape.so.0
Using native(wrapped) libxcb-xkb.so.1
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libm.so.6
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) libbsd.so.0
Error: Symbol FT_Set_Named_Instance not found, cannot apply R_X86_64_JUMP_SLOT @0x10366b6b0 (0x3f1586) in /home/gart/Apps/WinBox_Linux/WinBox
Error: Symbol xcb_render_create_anim_cursor not found, cannot apply R_X86_64_JUMP_SLOT @0x10366c160 (0x3f2ae6) in /home/gart/Apps/WinBox_Linux/WinBox
Error: Symbol FT_Get_Var_Design_Coordinates not found, cannot apply R_X86_64_JUMP_SLOT @0x10366c168 (0x3f2af6) in /home/gart/Apps/WinBox_Linux/WinBox
APP,INFO: version: "4.0beta14"
PERS,WARN: read ERROR OPENING "No such file or directory" "/home/gart/.local/share/MikroTik/WinBox/settings.cfg.viw2"
APP,INFO: loading addrs db from: "/home/gart/.local/share/MikroTik/WinBox/Addresses.cdb"
PERS,WARN: read ERROR OPENING "No such file or directory" "/home/gart/.local/share/MikroTik/WinBox/Addresses.cdb"
APP,INFO: loading failed "" </code>

The most important is to look for the 3 errors at R_X86_64_JUMP_SLOT, in my opinion.
To me the necessary libs are installed.

Can you help, where do I have to look for ?

Thanks

**Comment by ptitSeb** [comment]
This 3 functions needs to be wrapped yes. I'll do that a bit later.

**Comment by ptitSeb** [comment]
Ok, I added those function. I hope it will be enough.

**Comment by gartfr** [comment]
Thanks, I will try tomorrow when the box64 deb package will be updated.
I will let you know.

**Comment by gartfr** [comment]
Hi,
The error messages disappeared, it seems the application is now running without errors, but the GUI is still not launching. 
For now, I don't think the problem is linked to box64, so we can close the ticket.
But still not working. I will have a look with the application dev.
Thanks for you support.
