### ISSUE TITLE
Crysis

### ISSUE THREAD

**Issue by Heasterian** [ptitSeb/box64#23]
Crysis crashes when running with Wine with dynarec and interpreter. 

[CrysisDynarec.txt](https://github.com/ptitSeb/box64/files/6760216/CrysisDynarec.txt)
[CrysisInterpreter.txt](https://github.com/ptitSeb/box64/files/6760217/CrysisInterpreter.txt) 
Here is addr2line.

```
Dynarec:
0x00000000648ce7b0

/home/heasterian/box64/src/emu/x64run.c:128
0x00000000648ce794
/home/heasterian/box64/src/emu/x64run.c:128
```

```
Interpreter:
0x00000000648fdd3c
/home/heasterian/box64/src/tools/box64stack.c:66
0x00000000648cedc0
/home/heasterian/box64/src/emu/x64run.c:478
```

**Comment by Heasterian** [comment]
So Crysis is crashing now just after black bars disappear after jumping out of the plane when using dx9.

I checked if they are any missing dynarec opcodes and looks like many are missing. I'm just putting output form console below.

[CrysisDyn.txt](https://github.com/ptitSeb/box64/files/6946652/CrysisDyn.txt)

**Comment by Heasterian** [comment]
Looks like Crysis still crashes in same place without any certain output in console indicating crash on Wine or box64 side.

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
Community reports show that Crysis is working now. If there are any new issues, please open a new GitHub Issue. Closing as resolved.
