### ISSUE TITLE
Can't compile - Rock64 Armbian Buster

### ISSUE THREAD

**Issue by v9999** [ptitSeb/box64#231]
I'm running a fresh install of Armbian Debian Buster server on my Rock64 (RK3288): 

`Linux rock64 5.10.60-rockchip64 #21.08.1 SMP PREEMPT Wed Aug 25 18:56:55 UTC 2021 aarch64 GNU/Linux`

I updated and upgraded the server as usual.

I followed the compiling steps but couldn't compile box64, here's a log:

`[ 29%] Building C object CMakeFiles/arm64_pass3.dir/src/dynarec/dynarec_arm64_db.c.o
during GIMPLE pass: dom
In file included from /home/rock/box64/src/dynarec/dynarec_arm64_db.c:23:
/home/rock/box64/src/dynarec/dynarec_arm64_db.c: In function ‘dynarec64_DB3’:
/home/rock/box64/src/dynarec/dynarec_arm64_helper.h:684:37: internal compiler error: in wide_int_to_tree_1, at tree.c:1549
 #define dynarec64_DB       STEPNAME(dynarec64_DB)
                                     ^~~~~~~~~~~~
/home/rock/box64/src/dynarec/dynarec_arm64_helper.h:668:24: note: in definition of macro ‘STEPNAME3’
 #define STEPNAME3(N,M) N##M
                        ^
/home/rock/box64/src/dynarec/dynarec_arm64_helper.h:670:21: note: in expansion of macro ‘STEPNAME2’
 #define STEPNAME(N) STEPNAME2(N, STEP)
                     ^~~~~~~~~
/home/rock/box64/src/dynarec/dynarec_arm64_helper.h:684:28: note: in expansion of macro ‘STEPNAME’
 #define dynarec64_DB       STEPNAME(dynarec64_DB)
                            ^~~~~~~~
/home/rock/box64/src/dynarec/dynarec_arm64_db.c:27:11: note: in expansion of macro ‘dynarec64_DB’
 uintptr_t dynarec64_DB(dynarec_arm_t* dyn, uintptr_t addr, uintptr_t ip, int ninst, rex_t rex, int rep, int* ok, int* need_epilog)
           ^~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/arm64_pass3.dir/build.make:232: CMakeFiles/arm64_pass3.dir/src/dynarec/dynarec_arm64_db.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....`

**Comment by ptitSeb** [comment]
It's an internal compiler error. Not box64 fault. Check your compiler version. Is it a stable or a dev. version?

**Comment by v9999** [comment]
> It's an internal compiler error. Not box64 fault. Check your compiler version. Is it a stable or a dev. version?

Hello, I'm noticing that my SBC is probably faulty anyways, I won't be able to dwelve further into the issue. Thanks.
