### ISSUE TITLE
Make command error.

### ISSUE THREAD

**Issue by JosephZaza** [ptitSeb/box64#234]
I get the following error message when trying to compile with make. I already have box86 installed and python 3.8.0. Not sure what is generating the issues. I'm on a Raspberry Pi 4 Model B Rev 1.2.

Scanning dependencies of target dynarec_arm
Scanning dependencies of target WRAPPERS
[  0%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm64_functions.c.o
[  0%] Generating ../src/wrapped/generated/functions_list.txt
[  1%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm64.c.o
[  1%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o
In file included from /box64/src/emu/x64emu_private.h:4,
                 from /box64/src/dynarec/dynarec_arm64.c:11:
/box64/src/include/regs.h:250:2: error: unknown type name ‘__uint128_t’
  __uint128_t u128;
  ^~~~~~~~~~~
In file included from /box64/src/dynarec/dynarec_arm64.c:17:
/box64/src/emu/x64run_private.h: In function ‘Fetch8’:
/box64/src/emu/x64run_private.h:20:54: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 static inline uint8_t Fetch8(x64emu_t *emu) {return *(uint8_t*)(R_RIP++);}
                                                      ^
/box64/src/emu/x64run_private.h: In function ‘Fetch8s’:
/box64/src/emu/x64run_private.h:21:54: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 static inline int8_t Fetch8s(x64emu_t *emu) {return *(int8_t*)(R_RIP++);}
                                                      ^
/box64/src/emu/x64run_private.h: In function ‘Fetch16’:
/box64/src/emu/x64run_private.h:24:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint16_t val = *(uint16_t*)R_RIP;
                     ^
/box64/src/emu/x64run_private.h: In function ‘Fetch16s’:
/box64/src/emu/x64run_private.h:30:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     int16_t val = *(int16_t*)R_RIP;
                    ^
/box64/src/emu/x64run_private.h: In function ‘Fetch32’:
/box64/src/emu/x64run_private.h:36:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint32_t val = *(uint32_t*)R_RIP;
                     ^
/box64/src/emu/x64run_private.h: In function ‘Fetch32s’:
/box64/src/emu/x64run_private.h:42:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     int32_t val = *(int32_t*)R_RIP;
                    ^
/box64/src/emu/x64run_private.h: In function ‘Fetch64’:
/box64/src/emu/x64run_private.h:48:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint64_t val = *(uint64_t*)R_RIP;
                     ^
/box64/src/emu/x64run_private.h: In function ‘Fetch64s’:
/box64/src/emu/x64run_private.h:54:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     int64_t val = *(int64_t*)R_RIP;
                    ^
/box64/src/emu/x64run_private.h: In function ‘Peek’:
/box64/src/emu/x64run_private.h:58:63: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 static inline uint8_t Peek(x64emu_t *emu, int offset){return *(uint8_t*)(R_RIP + offset);}
                                                               ^
/box64/src/emu/x64run_private.h: In function ‘Pop’:
/box64/src/emu/x64run_private.h:62:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint64_t* st = ((uint64_t*)(R_RSP));
                     ^
/box64/src/emu/x64run_private.h: In function ‘Push’:
/box64/src/emu/x64run_private.h:70:7: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     *((uint64_t*)R_RSP) = v;
       ^
In file included from /box64/src/emu/x64emu_private.h:4,
                 from /box64/src/dynarec/dynablock.c:10:
/box64/src/include/regs.h:250:2: error: unknown type name ‘__uint128_t’
  __uint128_t u128;
  ^~~~~~~~~~~
In file included from /box64/src/dynarec/dynablock.c:16:
/box64/src/emu/x64run_private.h: In function ‘Fetch8’:
/box64/src/emu/x64run_private.h:20:54: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 static inline uint8_t Fetch8(x64emu_t *emu) {return *(uint8_t*)(R_RIP++);}
                                                      ^
/box64/src/emu/x64run_private.h: In function ‘Fetch8s’:
/box64/src/emu/x64run_private.h:21:54: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 static inline int8_t Fetch8s(x64emu_t *emu) {return *(int8_t*)(R_RIP++);}
                                                      ^
/box64/src/emu/x64run_private.h: In function ‘Fetch16’:
/box64/src/emu/x64run_private.h:24:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint16_t val = *(uint16_t*)R_RIP;
                     ^
/box64/src/emu/x64run_private.h: In function ‘Fetch16s’:
/box64/src/emu/x64run_private.h:30:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     int16_t val = *(int16_t*)R_RIP;
                    ^
/box64/src/emu/x64run_private.h: In function ‘Fetch32’:
/box64/src/emu/x64run_private.h:36:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint32_t val = *(uint32_t*)R_RIP;
                     ^
/box64/src/emu/x64run_private.h: In function ‘Fetch32s’:
/box64/src/emu/x64run_private.h:42:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     int32_t val = *(int32_t*)R_RIP;
                    ^
/box64/src/emu/x64run_private.h: In function ‘Fetch64’:
/box64/src/emu/x64run_private.h:48:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint64_t val = *(uint64_t*)R_RIP;
                     ^
/box64/src/emu/x64run_private.h: In function ‘Fetch64s’:
/box64/src/emu/x64run_private.h:54:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     int64_t val = *(int64_t*)R_RIP;
                    ^
/box64/src/emu/x64run_private.h: In function ‘Peek’:
/box64/src/emu/x64run_private.h:58:63: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 static inline uint8_t Peek(x64emu_t *emu, int offset){return *(uint8_t*)(R_RIP + offset);}
                                                               ^
/box64/src/emu/x64run_private.h: In function ‘Pop’:
/box64/src/emu/x64run_private.h:62:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint64_t* st = ((uint64_t*)(R_RSP));
                     ^
/box64/src/emu/x64run_private.h: In function ‘Push’:
/box64/src/emu/x64run_private.h:70:7: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     *((uint64_t*)R_RSP) = v;
       ^
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:76: CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm64.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:63: CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o] Error 1
In file included from /box64/src/emu/x64emu_private.h:4,
                 from /box64/src/dynarec/dynarec_arm64_functions.c:15:
/box64/src/include/regs.h:250:2: error: unknown type name ‘__uint128_t’
  __uint128_t u128;
  ^~~~~~~~~~~
In file included from /box64/src/dynarec/dynarec_arm64_functions.c:21:
/box64/src/emu/x64run_private.h: In function ‘Fetch8’:
/box64/src/emu/x64run_private.h:20:54: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 static inline uint8_t Fetch8(x64emu_t *emu) {return *(uint8_t*)(R_RIP++);}
                                                      ^
/box64/src/emu/x64run_private.h: In function ‘Fetch8s’:
/box64/src/emu/x64run_private.h:21:54: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 static inline int8_t Fetch8s(x64emu_t *emu) {return *(int8_t*)(R_RIP++);}
                                                      ^
/box64/src/emu/x64run_private.h: In function ‘Fetch16’:
/box64/src/emu/x64run_private.h:24:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint16_t val = *(uint16_t*)R_RIP;
                     ^
/box64/src/emu/x64run_private.h: In function ‘Fetch16s’:
/box64/src/emu/x64run_private.h:30:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     int16_t val = *(int16_t*)R_RIP;
                    ^
/box64/src/emu/x64run_private.h: In function ‘Fetch32’:
/box64/src/emu/x64run_private.h:36:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint32_t val = *(uint32_t*)R_RIP;
                     ^
/box64/src/emu/x64run_private.h: In function ‘Fetch32s’:
/box64/src/emu/x64run_private.h:42:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     int32_t val = *(int32_t*)R_RIP;
                    ^
/box64/src/emu/x64run_private.h: In function ‘Fetch64’:
/box64/src/emu/x64run_private.h:48:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint64_t val = *(uint64_t*)R_RIP;
                     ^
/box64/src/emu/x64run_private.h: In function ‘Fetch64s’:
/box64/src/emu/x64run_private.h:54:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     int64_t val = *(int64_t*)R_RIP;
                    ^
/box64/src/emu/x64run_private.h: In function ‘Peek’:
/box64/src/emu/x64run_private.h:58:63: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 static inline uint8_t Peek(x64emu_t *emu, int offset){return *(uint8_t*)(R_RIP + offset);}
                                                               ^
/box64/src/emu/x64run_private.h: In function ‘Pop’:
/box64/src/emu/x64run_private.h:62:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     uint64_t* st = ((uint64_t*)(R_RSP));
                     ^
/box64/src/emu/x64run_private.h: In function ‘Push’:
/box64/src/emu/x64run_private.h:70:7: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     *((uint64_t*)R_RSP) = v;
       ^
/box64/src/dynarec/dynarec_arm64_functions.c: In function ‘arm_ud’:
/box64/src/dynarec/dynarec_arm64_functions.c:157:30: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     emit_signal(emu, SIGILL, (void*)R_RIP, 0);
                              ^
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:89: CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm64_functions.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:198: CMakeFiles/dynarec_arm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Detected same build as last run, skipping
[  1%] Built target WRAPPERS
make: *** [Makefile:163: all] Error 2

**Comment by ptitSeb** [comment]
Box64 needs a 64bits system to be built. You are building on a 32bits system, that's why you get those errors.

**Comment by JosephZaza** [comment]
Which I understand. I thought having box86 installed would fix that issue. Does it not?
