### ISSUE TITLE
Linker error while attempting to build

### ISSUE THREAD

**Issue by EmreTech** [ptitSeb/box64#239]
Hello! So I tried to build Box64 and everything went well until it started to link the program. It gave this error:
```
CMakeFiles/box64.dir/src/tools/my_cpuid.c.o: In function `my_cpuid':
/home/charlie/box64/src/tools/my_cpuid.c:49: undefined reference to `getcpu'
```

Here's the log of the terminal just in case:
[install-fail-Box64.txt](https://github.com/ptitSeb/box64/files/8104916/install-fail-Box64.txt)

**Comment by ptitSeb** [comment]
On what system are you building?

**Comment by theofficialgman** [comment]
they are on nintendo switch, ubuntu bionic

**Comment by ptitSeb** [comment]
so there is no getcpu function? do you have a warning about this?

**Comment by theofficialgman** [comment]
you can see the warning in the log they attached (its an entire buildlog)
```
/home/charlie/box64/src/tools/my_cpuid.c: In function ‘my_cpuid’:
/home/charlie/box64/src/tools/my_cpuid.c:49:17: warning: implicit declaration of function ‘getcpu’; did you mean ‘getNCpu’? [-Wimplicit-function-declaration]
                 getcpu(&cpu, &node);
                 ^~~~~~
                 getNCpu
```

**Comment by theofficialgman** [comment]
not exactly sure why the error occurs unless you are calling the function wrong, because this does exist in `/usr/include/aarch64-linux-gnu/bits/sched.h`
```
/* Get index of currently used CPU.  */

extern int sched_getcpu (void) __THROW;

```

**Comment by theofficialgman** [comment]
oh I see... getcpu and sched_getcpu are different functions
getcpu wasn't added till glibc 2.29 (so ubuntu focal and newer)
```
getcpu() was added in kernel 2.6.19 for x86-64 and i386.  Library
       support was added in glibc 2.29 (Earlier glibc versions did not
       provide a wrapper for this system call, necessitating the use of
       [syscall(2)](https://man7.org/linux/man-pages/man2/syscall.2.html).)
```
while sched_getcpu is available as old as glibc 2.14

**Comment by EmreTech** [comment]
Ah. That might explain why Box64 worked on Ubuntu Focal.

**Comment by ptitSeb** [comment]
Ok, so I changed to use `sched_getcpu` instead of `getcpu`. Hopefully it will work everywhere now.

**Comment by EmreTech** [comment]
It works now. Thanks.
