### ISSUE TITLE
Error using Steam in home streaming

### ISSUE THREAD

**Issue by CalcProgrammer1** [ptitSeb/box64#247]
Error: PltResolver: Symbol SDL_GetPreferredLocales(ver 0: SDL_GetPreferredLocales) not found, cannot apply R_X86_64_JUMP_SLOT 0xffff989898d8 (0xffff97e693c6) in /home/user/.local/share/Steam/ubuntu12_32/../ubuntu12_64/streaming_client

PinePhone Pro with Debian chroot.  Trying to stream games from my Windows PC.

**Comment by CalcProgrammer1** [comment]
Got farther now, the streaming client window opens briefly before closing.  Now it's missing an opcode:

215751|SIGILL @0xffff98f3fa70 (???(0xffff98f3fa70)) (x64pc=0x3c013/???:"???", rsp=0xffff98b97a08, stack=0xffff983dd000:0xffff98bdd000 own=(nil) fp=0x78253640), for accessing 0xffff98f3fa70 (code=1/prot=85), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil) opcode=48 83 EC 08 E8 F7 2C DC (C3 00 00 00 00)
Illegal instruction (core dumped)

**Comment by ptitSeb** [comment]
It's not a missing opcode, it's a wrapped function with a callback that is not wrapped correctly here probably (and some x86 code is executing in ARM).

**Comment by CalcProgrammer1** [comment]
Fixed now!  Awesome work!
