### ISSUE TITLE
It looks like wine32 is missing (l4t ubuntu)

### ISSUE THREAD

**Issue by hongtm77** [ptitSeb/box64#248]
Hi, I have successfully installed box64 on my l4t ubuntu nintendo switch. Then I installed wine64. But whenever I run wine, I got the error 'it looks like wine32 is missing'

my hardware:-

Ubuntu 18.04 LTS
ARMv8 processor rev 1
OS type 64 bit

**Comment by ptitSeb** [comment]
For now, wine needs box86 to run, which can be complicated to have running on a switch. There is no easy solution for now (you can find some docker / container based solution on github that might work for you: like this https://github.com/MaWalla/box86-docker )

**Comment by ptitSeb** [comment]
Box86 is a program, like box64. It allow x86 linux apps to run on arm (32bits) linux.
box86-docker is a linux container that have a arm 32bits linux distrib and box86, to allow to run box86 on ARM64 only linux system.
To run box86 on ARM64 Linux without docker, you need some Multiarch or chroot...

**Comment by hongtm77** [comment]
> Box86 is a program, like box64. It allow x86 linux apps to run on arm (32bits) linux. box86-docker is a linux container that have a arm 32bits linux distrib and box86, to allow to run box86 on ARM64 only linux system. To run box86 on ARM64 Linux without docker, you need some Multiarch or chroot...

Thanks for the explanation. Will try to get box86-docker. Will update the status once done. Thanks

**Comment by cobalt2727** [comment]
For what it's worth, the Switchroot devs have some documentation for this:

https://wiki.switchroot.org/en/Linux/Emulation/Box86

**Comment by hongtm77** [comment]
> For what it's worth, the Switchroot devs have some documentation for this:
> 
> https://wiki.switchroot.org/en/Linux/Emulation/Box86

Thanks for the response. Will check it out later. Cheers

**Comment by Trass3r** [comment]
> For now, wine needs box86 to run

Even for pure Win64 executables?
And does/will their WOW64 support change the game so everything can be run via box64?

**Comment by ptitSeb** [comment]
It will yes (but I have also to work on box64 side, to add 32bits code interpretor/dynarec)

**Comment by rajdakin** [comment]
Is this fixed now? Note that WOW64-enabled Wine seems to work now.

**Comment by LukeShortCloud** [comment]
Documentation has been provided on how to install Box86 on the Nintendo Switch. Box64 can also be used with Wine WoW64 as @rajdakin pointed out. Closing as complete.

**Comment by cobalt2727** [comment]
Worth noting that on L4T Ubuntu specifically (not Fedora, currently) running on a Switch, box86 and box64 are both automatically installed if the user runs the Steam script in the [L4T Megascript](https://github.com/cobalt2727/L4T-Megascript) tool that comes preinstalled with Switchroot L4T images.
