### ISSUE TITLE
Error allocating memory for elf

### ISSUE THREAD

**Issue by xiil34f** [ptitSeb/box64#251]
> xiil34f@localhost:~$ box64 bitwig-studio
Box64 v0.1.7 90fe733 built on Mar  5 2022 09:37:09
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 15 Env var
Looking for bitwig-studio
Error, memory map (@0x200000 0x158000/0x1000) for elf "/opt/bitwig-studio/bitwig-studio" allocated @0x7c2db65000
Error: allocating memory for elf /opt/bitwig-studio/bitwig-studio

I keep running into this error, has this been seen this before? I had a hard time looking for a solution.

**Comment by ptitSeb** [comment]
It seems box64 cannot alocate the main memory of the binare at the address it must be loaded. Seems 0x200000 is taken by something. Not much box64 can do here, it the mmap command fails.

**Comment by xiil34f** [comment]
@ptitSeb ah, well it's still a big help to know the solution would be outside of box64 :)

**Comment by ptitSeb** [comment]
Check with `cat /proc/self/maps` what the alocated map looks like for cat... Maybe you'll see something.

**Comment by xiil34f** [comment]
@ptitSeb You're right, 0x200000 is taken. I'm using Termux, so it's being used by proot I believe.

> xiil34f@localhost:~$ cat /proc/self/maps
00200000-00201000 r--p 00000000 fd:0a 431237                             /data/data/com.termux/files/usr/libexec/proot/loader

**Comment by ptitSeb** [comment]
Yep, so nothing box64 can do.  And I don't know Termux or proot well enough to help, sorry.

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
This is an issue with Termux which is out of our control. Closing.
