### ISSUE TITLE
Problem in box64 build on OrangePi4

### ISSUE THREAD

**Issue by fld2865** [ptitSeb/box64#255]
Hi guys,
totally newbie here on GitHub!!
I'm trying to build box64 on OrangePi4 (RK3399). The build process went smooth up (nearly) to the very end, where it can't link the final executable, as if missing most required libraries:

[ 32%] Linking C executable box64
CMakeFiles/box64.dir/src/main.c.o: In function `main':
/root/Projects/box64/src/main.c:1265: undefined reference to `pthread_atfork'
CMakeFiles/box64.dir/src/box64context.c.o: In function `init_mutexes':
/root/Projects/box64/src/box64context.c:122: undefined reference to `pthread_mutexattr_init'
/root/Projects/box64/src/box64context.c:123: undefined reference to `pthread_mutexattr_settype'
/root/Projects/box64/src/box64context.c:136: undefined reference to `pthread_mutexattr_destroy'
CMakeFiles/box64.dir/src/box64context.c.o: In function `NewBox64Context':
/root/Projects/box64/src/box64context.c:177: undefined reference to `dlopen'
/root/Projects/box64/src/box64context.c:184: undefined reference to `pthread_atfork'
/root/Projects/box64/src/box64context.c:186: undefined reference to `pthread_key_create'
...
/root/Projects/box64/src/dynarec/arm64/dynarec_arm64_functions.c:103: undefined reference to `cos'
collect2: error: ld returned 1 exit status
CMakeFiles/box64.dir/build.make:5808: recipe for target 'box64' failed
make[2]: *** [box64] Error 1
CMakeFiles/Makefile2:326: recipe for target 'CMakeFiles/box64.dir/all' failed
make[1]: *** [CMakeFiles/box64.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

so, it looks like there's a linker issue, and I don't know how to address it.
Any hint is welcome!!

Thanks,

fld2865

**Comment by ptitSeb** [comment]
You used the RK3399 profile right? What OS are you using?

**Comment by fld2865** [comment]
Hi ptitSeb,
sorry, you're right, I should've stated. I'm running on Armbian 20.04 for the OrangePi.

Thanks!!

**Comment by fld2865** [comment]
I used your guidelines:

git clone https://github.com/ptitSeb/box64
cd box64
mkdir build; cd build; cmake .. -DRK3399=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j4
sudo make install

**Comment by ptitSeb** [comment]
also, what `cmake --version` gives you?

**Comment by fld2865** [comment]
If you want, I can send the whole linker output, but I don't think it helps...

**Comment by ptitSeb** [comment]
No, iI don't need it. I suspect CMake to be bit old.
 3.10 is meh, I would prefer a 3.13+

**Comment by fld2865** [comment]
OK, how can I update it?

**Comment by ptitSeb** [comment]
I don't know. There isn't anything newer on armbian?

**Comment by fld2865** [comment]
I just installed it on purpose, and no, there isn't anything newer. I can try to update to a newer Armbian altogether, though.

**Comment by fld2865** [comment]
There's an Armbian 22.02, I'll give it a try.

Thanks!!

**Comment by fld2865** [comment]
And with Armbian 22.0.2 (cmake: 3.16.3) it did indeed work!!

**Comment by ptitSeb** [comment]
Ah good! I think I'll up the minimum cmake version required to build, in the `CMakeList.txt`.
I guess the ticket can be closed?

**Comment by fld2865** [comment]
Yes, sure, thanks again!!Il 23 Mar 2022 18:34, ptitSeb ***@***.***> ha scritto:
Ah good! I think I'll up the minimum cmake version required to build, in the CMakeList.txt.
I guess the ticket can be closed?
