### ISSUE TITLE
CMakeList.txt issue with `--as-need` and `--no-as-need` 

### ISSUE THREAD

**Issue by shantigilbert** [ptitSeb/box64#256]
Not sure if this is an issue but in my case I was trying to compile and I got this error while linking: 

```
bin/ld.gold: --no-as-need: unknown option
bin/ld.gold: --as-need: unknown option
```

If I change line 538 from CMakeLists.txt to 
`set_target_properties(${BOX64} PROPERTIES LINK_FLAGS "-Wl,--no-as-needed -lc -lm -ldl -lrt -lpthread -lresolv -Wl,--as-needed -pthread")`

It finishing linking. But I am not sure if this is a typo or something on my end.

**Comment by ptitSeb** [comment]
Yes, it's an issue. I have fixed that one on box86 but seems like I forgot to fix it in box64. I'll do that soon.

**Comment by rajdakin** [comment]
This looks like it is fixed, closing. Please reopen it if it is not.
