### ISSUE TITLE
Artifacts when running Unity build [ Ubuntu 21.04, 64 bit , RPI 400 ] 

### ISSUE THREAD

**Issue by Toernblom** [ptitSeb/box64#258]
Hey, getting weird artifacts(missing parts of the mesh etc) on 3D meshes and sprites in Unity. Running ubuntu 21.04 64 bit on a RPI 400. If i try running the executable with sudo it crashes and says "segmentation fault", without sudo it works fine. Has anyone had similiar issues?

**Comment by ptitSeb** [comment]
Can you try running without dynarec, with `BOX64_DYNAREC=0` and see if you have the same behaviour (warning, it will be very slow).
You can also try to use Software rendering, in case it's an issue with mesa, using `LIBGL_ALWAYS_SOFTWARE=true`

**Comment by Toernblom** [comment]
I'm assuming i would just paste that in terminal, none of those commands helped. I'll attach a screenshot of the issue aswell. 

correct in editor ( windows ):
https://gyazo.com/0637351972ebbf8fec88b81bc0352d3f

RPI:
https://gyazo.com/9846f1926127b030143a1c87bbf83b18

I've switched between the vulkan api and opengl when exporting and messed with some settings, first the Unity logo at the beginning was faulty aswell but that has fixed itself. Not sure which option helped with that tho. Works fine in a VM running ubuntu 21.04 on my windows machine aswell.

**Comment by Toernblom** [comment]
Haha fixed itself by rebooting.. Something i should've tried first perhaps. Ohwell.
