### ISSUE TITLE
Running bedrock_server (Minecraft Private Server App) on Ubuntu Arm with Box64 - got some bugs inside server

### ISSUE THREAD

**Issue by davidorze** [ptitSeb/box64#259]
(for reference, I'm opening a replica here, because I've mistaken and created it on box86 repo, [original link](https://github.com/ptitSeb/box86/issues/595))

So, for the Op Code you said, it seems to be ok now! But the skin issue is the same, just to point it.
![imagem_2022-03-28_221838](https://user-images.githubusercontent.com/52167789/160513216-26e21f7d-9971-46a5-a3ca-b5060b0b725c.png)

**Comment by davidorze** [comment]
Something happened! I logged in today, and it seems that the skin error is gone! lol

![image](https://user-images.githubusercontent.com/52167789/160635473-3ec00659-7810-4f1d-a0ba-0cf91dc90729.png)

**Comment by drushbrook** [comment]
@davidorze - My daughter experiences the skin Issue also.  After changing to one of her other skins in the wardrobe the other skins worked.  She then tried to create another skin using the same skin file and it was also broken.  Wonder if you experience the same.   Her sister had no issues with her own skin and they could see each other. 

She also tried the steve classic skin and she couldn't see herself but her sister could see her.

Here is the log...  Fresh spun up Ubuntu 20.04.4 on Oracle Cloud Ampere using cmake .. -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo

Dynarec log level is 1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
Box64 with Dynarec v0.1.7 ead3217 built on Apr  2 2022 06:42:16
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 28 Env var
Looking for ./bedrock_server
Using native(wrapped) libpthread.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libnsl.so.1
Using native(wrapped) libssl.so.1
Using native(wrapped) libcrypto.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
NO LOG FILE! - setting up server logging...
[2022-04-02 08:33:35:554 INFO] Starting Server
[2022-04-02 08:33:35:555 INFO] Version 1.18.12.01
[2022-04-02 08:33:35:555 INFO] Session ID 511f5403-ad45-4401-a350-0361a4b77e08
[2022-04-02 08:33:35:563 INFO] Level Name: Bedrock level
[2022-04-02 08:33:35:571 INFO] Game mode: 0 Survival
[2022-04-02 08:33:35:571 INFO] Difficulty: 1 EASY
[2022-04-02 08:33:35:741 INFO] opening worlds/Bedrock level/db
Warning, call to __cxa_thread_atexit_impl(0x2dbde30, 0x8b956560, 0x58baf98) ignored
[2022-04-02 08:33:39:966 INFO] IPv4 supported, port: 19132
[2022-04-02 08:33:39:966 INFO] IPv6 supported, port: 19133
[2022-04-02 08:33:40:597 INFO] Server started.
[2022-04-02 08:33:40:672 INFO] IPv4 supported, port: 48378
[2022-04-02 08:33:40:672 INFO] IPv6 supported, port: 51166
[2022-04-02 08:49:59:986 INFO] Player connected: mik***, xuid: ------
Warning, call to __cxa_thread_atexit_impl(0x2dbde30, 0xffff6c4a5e70, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x3893880, 0xffff78000df8, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x38938c0, 0xffff78000e20, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x2d5a860, 0xffff78000d10, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x2d5b2b0, 0xffff78000d38, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x2d5c550, 0xffff78000d60, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x2e0a430, 0xffff78000dc0, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x2d5a860, 0xffff6c4a5df0, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x2d5b2b0, 0xffff6c4a5e18, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x2d5c550, 0xffff6c4a5e40, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x2e0a430, 0xffff6c4a5ea0, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x3893880, 0xffff6c4a5ed8, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x38938c0, 0xffff6c4a5f00, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x3893880, 0xffff8c000e58, 0x58baf98) ignored
Warning, call to __cxa_thread_atexit_impl(0x38938c0, 0xffff8c000e80, 0x58baf98) ignored
[2022-04-02 08:56:07:921 INFO] Player connected: Pan**, xuid: -----------
tp Pan** mik**
Teleported Pan** to mik**

**Comment by davidorze** [comment]
Hi @drushbrook! Thanks for the message!
Actually, neither my friends or I have the skin 'working', I can't see theirs, and they don't see mine. 

When using a custom skin, it becomes a 'box', and when using the official skin or the standard, it becomes invisible... I don't know why, but it seems different from your issue. Also, in my DYNAREC log, I have it failing ('Dynarec stopped because of Opcode...), and yours doesn't.

**Comment by drushbrook** [comment]
@davidorze - 
We have seen both the box issue and the invisible issue but it didn't happen on all her skins.  When we get back from holidays I will attach the skin that works for her to see if that works for you.

I wonder if you still get the Dynarec stopped because of opcode on the latest build..  You can find the if you are using the latest commit in the log file - I have made it bold below. 

$ BOX64_DYNAREC_LOG=1 ./bedrock_server
Dynarec log level is 1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
**Box64 with Dynarec v0.1.7 a4772ff built on Apr  9 2022 04:46:38**
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 31 Env var
Looking for ./bedrock_server
Using native(wrapped) libpthread.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libnsl.so.1
Using native(wrapped) libssl.so.1
Using native(wrapped) libcrypto.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
NO LOG FILE! - setting up server logging...
[2022-04-09 04:56:39:262 INFO] Starting Server
[2022-04-09 04:56:39:263 INFO] Version 1.18.12.01

**Comment by drushbrook** [comment]
Some more information on what I have found with the skin issue:
1. Steve and Alex default skins show up invisible
2. Skin Pack skins (from the in game store) seem to work for me
3. Custom Skins show up as a box

Latest Log...  A number of __cxa_thread_atexit_impl warnings occured as the skins were being changed etc.
Time to set the Dynarec log level to DEBUG

Dynarec log level is 1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
Box64 with Dynarec v0.1.9 2a4c1d0 built on Apr 19 2022 20:40:21
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 31 Env var
Looking for ./bedrock_server
Using native(wrapped) libz.so.1
Using native(wrapped) libnsl.so.1
Using native(wrapped) libssl.so.1
Using native(wrapped) libcrypto.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
Using native(wrapped) libpthread.so.0
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
NO LOG FILE! - setting up server logging...
[2022-04-24 06:53:29:312 INFO] Starting Server
[2022-04-24 06:53:29:313 INFO] Version **1.18.30.04**
[2022-04-24 06:53:29:313 INFO] Session ID de1fbd5e-c280-4436-a86e-c0f337664514
[2022-04-24 06:53:29:323 INFO] Level Name: Bedrock level
[2022-04-24 06:53:29:332 INFO] Game mode: 0 Survival
[2022-04-24 06:53:29:333 INFO] Difficulty: 1 EASY
[2022-04-24 06:53:30:537 INFO] opening worlds/Bedrock level/db
Warning, call to __cxa_thread_atexit_impl(0x3199710, 0x69dcd2b8, 0x62d6358) ignored
[2022-04-24 06:53:36:621 INFO] IPv4 supported, port: 19132
[2022-04-24 06:53:36:621 INFO] IPv6 supported, port: 19133
[2022-04-24 06:53:36:376 INFO] Server started.
[2022-04-24 06:53:36:446 INFO] IPv4 supported, port: 46627
[2022-04-24 06:53:36:446 INFO] IPv6 supported, port: 60275
[2022-04-26 10:09:08:670 INFO] Player connected: mik***, xuid: —
Warning, call to __cxa_thread_atexit_impl(0x3199710, 0xffff6c4c9ff8, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x38cef10, 0xffff78000dc8, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x38cef50, 0xffff78000df0, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x2b56460, 0xffff78000d08, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x2b57130, 0xffff78000d30, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x2b583d0, 0xffff78000d58, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x3970b70, 0xffff78000e20, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x38cef10, 0xffff6c4ca028, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x38cef50, 0xffff6c4ca050, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x2b56460, 0xffff6c4c9f68, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x2b57130, 0xffff6c4c9f90, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x2b583d0, 0xffff6c4c9fb8, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x3970b70, 0xffff6c4ca080, 0x62d6358) ignored
[2022-04-26 10:20:41:533 INFO] Player disconnected: mik***, xuid: —
Warning, call to __cxa_thread_atexit_impl(0x38cef10, 0xffff8c000e28, 0x62d6358) ignored
Warning, call to __cxa_thread_atexit_impl(0x38cef50, 0xffff8c000e50, 0x62d6358) ignored

**Comment by voltagex** [comment]
No visible errors for me with Bedrock Server 1.19.50 and Box64 v0.2.1 9f3ea84b built on Dec  2 2022 10:16:32, but the same warnings as above.

Additionally, my Windows client will take ~30 seconds to connect to the server but be quite usable once connected.

**Comment by ptitSeb** [comment]
Try to update box64 and try again, mabye commit d0d18441cfdedac53b0ed8a772a88a1c26be7984 have helped.

**Comment by voltagex** [comment]
No noticeable improvement with Box64 v0.2.1 75083907 unfortunately.

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by voltagex** [comment]
@rajdakin try it and see?

**Comment by ptitSeb** [comment]
That' not how ticket work. Closing the ticket if the OP has lost interest.
