### ISSUE TITLE
Issue with x86-64 application launch

### ISSUE THREAD

**Issue by Regina-operation** [ptitSeb/box64#260]
Hello,
when launching x86-64 apllication I've got  strange message and application failed
3313|0x40d8f0: Unimplemented Opcode (C3) 66 0F 38 30 D0 66 0F 73 D8 08 66 0F 38 30 C0

Is there something not implemented on box64
The application used is sbf2rin (application for gnss purpose)

The version of box64 used is the following :
box64 -v
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.7 23bbab1 built on Mar  2 2022 10:58:22

Thanks for your help

**Comment by ptitSeb** [comment]
Yes, this opcode need to be implemented on box64 (66 0F 38 30: pmovzxbw), it's a SSE4 opcode, I'll add it soon.

**Comment by Regina-operation** [comment]
Very good news. Thank you very much

**Comment by ptitSeb** [comment]
Ok, it's done (it was simple because similar opcodes were already implemented). You can update box64 and try again.

**Comment by Regina-operation** [comment]
It Works !
Thank you very much
