### ISSUE TITLE
Segmentation fault in my_XVaCreateNestedList

### ISSUE THREAD

**Issue by mhavu** [ptitSeb/box64#265]
I have a (perhaps rather ambitious) goal of running Intel Quartus Prime on Apple M1 Pro using Box64. I started by adding the necessary native function wrappings in libc, libfontconfig, and libX11 for running the Quartus programmer installation wizard. The wizard starts, but after a couple of steps it segfaults in `my_XVaCreateNestedList`:
> 4597|SIGSEGV @0x64a5d7c0 (my_XVaCreateNestedList (/usr/local/bin/box64)) (x64pc=0xd0f33/???:"???", rsp=0xffffa028a698, stack=0xffff9fa97000:0xffffa0297000 own=(nil) fp=(nil)), for accessing (nil) (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
Segmentation fault (core dumped)

The wrapped functions I added to libX11 are not called before the segmentation fault, so they can't be the problem. Any pointers on how to start debugging this? 

I am running Ubuntu 21.10 on VMware Fusion for Apple Silicon, and I compiled Box64 using `-DARM_DYNAREC=ON`:
> Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
> Box64 with Dynarec v0.1.7 ead3217 built on Apr  4 2022 19:33:09

Should I try using `-DM1=1` instead?

**Comment by ptitSeb** [comment]
Those wrapped function are a bit tricky, there must still be a bug somewhere. I haven't spoted anything on a quick look, I'll try to check more thouroghly  later.

**Comment by mhavu** [comment]
The segmentation fault happens in the `SUPER()` macro on the first `for` loop iteration.

**Comment by ptitSeb** [comment]
Do you know what value is `i` and `n`?

**Comment by mhavu** [comment]
```
n = 6
i = 0
```

**Comment by ptitSeb** [comment]
I found some typo, and made some improvement.  Can you try again?

**Comment by mhavu** [comment]
Fixed the segfault. 👍 Thanks!

**Comment by ptitSeb** [comment]
\o/
