### ISSUE TITLE
Function parameters of type XID in libX11

### ISSUE THREAD

**Issue by mhavu** [ptitSeb/box64#266]
I noticed that most functions in libX11 with a parameter of type `XID` list it as `p` in their signature, but `XSaveContext` lists it as `u`. `XID` is defined as `unsigned long` in *wrapped/wrappedlibx11.c*. Should the `XID` type be `L`, or is `p` correct? I assume `u`is wrong in any case.

**Comment by ptitSeb** [comment]
`l` and `p` are correct, they will be both 8-bytes on 64bits (and 4-bytes on 32bits). `u` is incorrect on 64bits, but all `u` (and `i`) are upgrade to 8-bytes anyway on box64, so it's worong but it's automatically corrected.
