### ISSUE TITLE
Failure to create a lib for libprotobuf

### ISSUE THREAD

**Issue by mhavu** [ptitSeb/box64#269]
When loading a program, I came across the following error:
> Trying to add "libprotobuf.so.14" to maplib
> Trying to load "libprotobuf.so.14"
> Simplified name is "libprotobuf.so.14"
> Faillure to create lib => fail
> Error loading needed lib libprotobuf.so.14
> Error loading one of needed lib

What are the possible reasons for Box64 failing to use an emulated library?

**Comment by ptitSeb** [comment]
Use `BOX64_LOG=2` to have more details on what's happening.

**Comment by mhavu** [comment]
The trace above is all the detail I got about the issue with `BOX64_LOG=2`.

**Comment by mhavu** [comment]
Ah. This was an installation issue, a broken symlink. The library is supposed to be in there with the executable, along with some 20 other emulated libraries that do work, but this one is broken.
