### ISSUE TITLE
cant launch processing 3.5.2

### ISSUE THREAD

**Issue by JerboaWings** [ptitSeb/box64#272]
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.7 a4772ff built on Apr  7 2022 00:04:18
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 48 Env var
Looking for /home/pi/processing-3.5.2/java/bin/java
argv[1]="-splash:lib/about-1x.png"
argv[2]="-Djna.nosys=true"
argv[3]="-Djava.ext.dirs=/home/pi/processing-3.5.2/java/lib/ext"
argv[4]="-Xmx256m"
argv[5]="processing.app.Base"
argv[6]=""
Using native(wrapped) libpthread.so.0
Using emulated /home/pi/processing-3.5.2/java/bin/../lib/amd64/jli/libjli.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated /home/pi/processing-3.5.2/java/lib/amd64/server/libjvm.so
Using native(wrapped) libm.so.6
Warning: Global Symbol collector_func_load not found, cannot apply R_X86_64_GLOB_DAT @0x7f901afff0 ((nil)) in /home/pi/processing-3.5.2/java/lib/amd64/server/libjvm.so
Using emulated /home/pi/processing-3.5.2/java/lib/amd64/libsplashscreen.so
Using native(wrapped) libX11.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Error: PltResolver: Symbol XDefaultVisualOfScreen(ver 0: XDefaultVisualOfScreen) not found, cannot apply R_X86_64_JUMP_SLOT 0x7f8d7ba2d8 (0x7f8d55d8f6) in /home/pi/processing-3.5.2/java/lib/amd64/libsplashscreen.so
PLEASE HELP!!!!

**Comment by rajdakin** [comment]
Is this fixed now?
