### ISSUE TITLE
Compiler errors on AArch64 GCC7

### ISSUE THREAD

**Issue by theofficialgman** [ptitSeb/box64#278]
Starting yesterday, we started getting multiple Box64 compilation errors.
I've verified and can reproduce on ubuntu bionic 18.04 aarch64 with default gcc7

I am not sure which change caused this, but I know I was able to build successfully 14 days ago on commit:07a65d4

[install-fail-Box64 (1).txt](https://github.com/ptitSeb/box64/files/8468241/install-fail-Box64.1.txt)

**Comment by theofficialgman** [comment]
my guess is it has to do with this commit, since the compiler errors on `dynarec_arm64_00.c` and the date lines up to when we started experiencing errors

https://github.com/ptitSeb/box64/commit/f779d4fadb524857a8c6d74c62013ea2f381bc14

**Comment by theofficialgman** [comment]
I was able to have a user compile with 1 thread on gcc7 successfully, but since this is slow and this appears to be a compiler error I will just switch to gcc-11.

Feel free to close this unless you feel like this is a box64 issue.

**Comment by ptitSeb** [comment]
yeah, Internal Compiler Error, I think I'll just close it, especialy if you have switched compiler.
