### ISSUE TITLE
[Discussion]Can i run QEMU-system on it?

### ISSUE THREAD

**Issue by dontknowhy** [ptitSeb/box64#286]
well,i know this is a Strange idea .
But i still want to have a try.
i downloaded the qemu-system and it's dependency packages…
unpack it using MT Manager
copy them to the Termux
run it
and nothing
no nothing
it told me a .so file can't be found(or can't be load?),but i already unpack it and BOX64_LIBRARY_PATH is correct 
how can i fix it?

**Comment by ptitSeb** [comment]
I don't think Box64 will have the necessary "system oriented" opcode to run qemu-system.

The missing .so file is probably an unwrapped lib, so you need the x86_64 version of it probably, not the aarch64 one.

**Comment by dontknowhy** [comment]
> > I don't think Box64 will have the necessary "system oriented" opcode to run qemu-system.
> > 
> > The missing .so file is probably an unwrapped lib, so you need the x86_64 version of it probably, not the aarch64 one.
> 
> i seted the pixman so file to emulator mode but nothing work

this thing is just for fun
i already have a set of qemu-system
;)

**Comment by LukeShortCloud** [comment]
Using `qemu-system` with Box64 is not supported. Closing.
