### ISSUE TITLE
Error loading needed lib libjansson.so.4

### ISSUE THREAD

**Issue by cryptomic** [ptitSeb/box64#292]
```
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULLDynarec for ARM64, with extension: ASIMD ATOMICS AES CRC32 PMULL ATOMICS PageSize:4096
PageSize:4096
Box64 with Dynarec v0.1.9 5e69a69 built on Apr 24 2022 17:19:57
Box64 with Dynarec v0.1.9 5e69a69 built on Apr 24 2022 17:19:57
Using default BOX64_LD_LIBRARY_PATH: Using default BOX64_LD_LIBRARY_PATH: ./:./:lib/:lib/:lib64/:lib64/:x86_64/:x86_64/:bin64/:bin64/:libs64/
libs64/
Using default BOX64_PATH: Using default BOX64_PATH: ./:./:bin/
bin/
Counted 26 Env var
Counted 26 Env var
Looking for [redacted]
Looking for [redacted]
argv[1]="-c"
argv[2]="/cfg.json"
argv[1]="--printtoconsole"
Using native(wrapped) libcurl.so.4
Error loading needed lib libjansson.so.4
Error loading one of needed lib
Error: loading needed libs in elf [redacted]
shutting down
```

Any suggestions? I followed the instructions (https://pimylifeup.com/raspberry-pi-x64/) carefully.

Thanks!

**Comment by ptitSeb** [comment]
`libjansson.so.4` is not a wrapped library: you need to put the x86_64 version of it in the program folder so box64 can use it.

**Comment by cryptomic** [comment]
Thanks for the reply – are you able to guide me how to do that? New to Linux. Appreciated

**Comment by cryptomic** [comment]
I attempted to get the x86_64 version, but I'm out of my depth here:

`
wget http://mirrors.kernel.org/ubuntu/pool/main/j/jansson/libjansson4_2.11-1_amd64.deb
apt install ./libjansson4_2.11-1_amd64.deb 
`

`The following packages have unmet dependencies:
libjansson4:amd64 : Depends: libc6:amd64 (>= 2.14) but it is not installable`
