### ISSUE TITLE
`execv error: Input/output error`

### ISSUE THREAD

**Issue by C29H25N3O5** [ptitSeb/box64#300]
- Using the latest build of box64
- Ubuntu ARM on Apple M1 using Parallels (virtual machine)
- trying to run LÖVE 2D (x86_64)

When I execute the following command:
```
$ box64 ~/Desktop/l.AppImage
```

I get this message:
```   
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
Box64 with Dynarec v0.1.9 098317e built on May  2 2022 17:47:02
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 53 Env var
Looking for /home/chno/Desktop/l.AppImage
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libfuse.so.2
execv error: Input/output error
```

**Comment by C29H25N3O5** [comment]
To be clear, `l.AppImage` is short for `love-11.4-x86_64.AppImage`, but this issue happens on other x86_64 AppImage files as well.

**Comment by ptitSeb** [comment]
AppImage is not yet working with box64.
I have added some libfuse support a few days ago, but something is still not working and I also get that i/o error on execve. I haven't debugged it yet...

**Comment by natsbar** [comment]
I used to have the same error trying to us an appimage for Cubbit, but it looks like this error is fixed now.
Now, there is another error. Hope this is useful information and not just me making a user error.

natsbar@odroidhc4:~/Appimages$ box64 Cubbit-9.3.1.AppImage
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
Box64 with Dynarec v0.1.9 6392550 built on Jun 11 2022 19:30:12
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 28 Env var
Looking for Cubbit-9.3.1.AppImage
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libfuse.so.2
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
Box64 with Dynarec v0.1.9 6392550 built on Jun 11 2022 19:30:12
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 34 Env var
Looking for /tmp/.mount_Cubbitk0P7e0/@cubbitdesktop
Using emulated /tmp/.mount_Cubbitk0P7e0/libffmpeg.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libnss3.so
Using native(wrapped) libnssutil3.so
Using native(wrapped) libsmime3.so
Using native(wrapped) libnspr4.so
Using native(wrapped) libatk-1.0.so.0
Using native(wrapped) libatk-bridge-2.0.so.0
Using native(wrapped) libSM.so.6
Using native(wrapped) libICE.so.6
Using native(wrapped) libXau.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libcups.so.2
Using native(wrapped) libdbus-1.so.3
Using native(wrapped) libdrm.so.2
Error loading needed lib libgtk-3.so.0
Error loading one of needed lib
Error: loading needed libs in elf /tmp/.mount_Cubbitk0P7e0/@cubbitdesktop

**Comment by ptitSeb** [comment]
I have fixed libfuse / AppImage isue yesterday!

For now, box64 doesn't support gtk3, only gtk2. box86 support gtk3, so support for it will probably comes, but not sure when.

**Comment by natsbar** [comment]
Thank you for fixing the libfuse! I am happy to hear that I was not making a mistake.

**Comment by ptitSeb** [comment]
Can the ticket be closed now?

**Comment by natsbar** [comment]
My bad, I assumed it was closed. Yes, it can be closed. Thanks again for the fix.
