### ISSUE TITLE
undefined reference to `dynarec64_003' while linking executable

### ISSUE THREAD

**Issue by petersm8** [ptitSeb/box64#304]
I'm on the Pi 3b+, I have added a swap file of 2GB and ran make -j1
It completed with the following error:

> [ 98%] Building C object CMakeFiles/box64.dir/src/wrapped/wrappedxml2.c.o
> [ 98%] Building C object CMakeFiles/box64.dir/src/wrapped/wrappedxslt.c.o
> [ 99%] Building C object CMakeFiles/box64.dir/src/wrapped/wrappedldapr.c.o
> [ 99%] Building C object CMakeFiles/box64.dir/src/wrapped/wrappedlber.c.o
> [ 99%] Building C object CMakeFiles/box64.dir/src/wrapped/wrappedvulkan.c.o
> [100%] Linking C executable box64
> /usr/bin/ld: libdynarec.a(dynarec_native_pass.c.o): in function `native_pass3':
> /home/pi/box64/src/dynarec/dynarec_native_pass.c:156: undefined reference to `dynarec64_003'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/box64.dir/build.make:3634: box64] Error 1
> make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/box64.dir/all] Error 2
> make: *** [Makefile:182: all] Error 2

I thought that maybe I could still try and install it but this happened:

> sudo make install
> [  0%] Built target WRAPPERS
> [  8%] Built target native_pass3
> [ 10%] Built target dynarec_native
> [ 18%] Built target native_pass0
> [ 25%] Built target native_pass1
> [ 32%] Built target native_pass2
> [ 32%] Built target dynarec
> [ 33%] Linking C executable box64
> /usr/bin/ld: libdynarec.a(dynarec_native_pass.c.o): in function `native_pass3':
> /home/pi/box64/src/dynarec/dynarec_native_pass.c:156: undefined reference to `dynarec64_003'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/box64.dir/build.make:3634: box64] Error 1
> make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/box64.dir/all] Error 2
> make: *** [Makefile:182: all] Error 2

**Comment by ptitSeb** [comment]
One of the object file probably got corrupted somehow in a previous attempt (like if you first tried without the swap) and is still used...
From build folder, you can try `rm CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_00.c.o` to delete the object file that should contains that symbol and make again.

**Comment by petersm8** [comment]
Got it, thank you, unfortunately I was still having problems wit the make for that one file, but I was able to copy it from a different machine that was able to do it and it worked.
