### ISSUE TITLE
SEG FAULT when starting a server

### ISSUE THREAD

**Issue by petersm8** [ptitSeb/box64#305]
Got the following in terminal when I ran a script to start a server:

Started server process with pid 24815
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.9 59e367a built on May  8 2022 23:57:21
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 49 Env var
Looking for ./CoreKeeperServer
argv[1]="-batchmode"
argv[2]="-logfile"
argv[3]="CoreKeeperServerLog.txt"
Using emulated UnityPlayer.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXss.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libudev.so.1
/home/pi/corekeeperserver/Server/_launch.sh: line 39: 24815 Segmentation fault      DISPLAY=:99 ./CoreKeeperServer -batchmode -logfile CoreKeeperServerLog.txt "$@"

I have uploaded the Log.txt file
[CoreKeeperServerLog.txt](https://github.com/ptitSeb/box64/files/8653751/corekeeperlog.txt)
Any help or insight would be appreciated

**Comment by ptitSeb** [comment]
Can you update box64 and try again, I have improve stability and compatibility with Unity3d games, so it might be better now.

**Comment by ptitSeb** [comment]
@petersm8 can you try again? or should I close the ticket?

**Comment by LukeShortCloud** [comment]
This should work now. If not, please open a new GitHub Issue. Closing as resolved.
