### ISSUE TITLE
Regression on arm64

### ISSUE THREAD

**Issue by KiralyCraft** [ptitSeb/box64#31]
First and foremost let me thank you for this amazing piece of work. I've been playing Hollow Knight on my L4T Nintendo Switch, and I updated recently to the latest commit at the time of writing this (7948a2594555e6393d59be4c89f3804c93ac8723). To my surprise, the game now hangs with 0% CPU usage for the `box64` process. 

I started testing commits one by one. The first one I ever tried was this one: 67c80f683e335413efcb3ee4590f671ccdf5aae8 which added Tegra X1/T1 targets. I can confirm that still works.

Then I basically took them one by one and noticed when it got broken. Commit 27b3a3f33c90fc0daaf0ca8708c806b2a71b1625 causes box64 to segfault with "Aborted (Core Dumped)" It is the first occurence of the segfault since the addition of the Tegra targets. Commit fff2effd5bf28281cd560439106fc9189e43b03f still works. The one between I can't remember if I tested, but most likely I did and it works. 

Commit 3bab7d6c5365c6c46c97be27b807d077aba276ce is also segfaulting with that same message, and commit 85a460afb7002509c189bceec0c6746602441fa9 hangs with 0% usage. Please note that after 27b3a3f33c90fc0daaf0ca8708c806b2a71b1625 I did not test them anymore one by one, but in jumps (these ones mentioned here).

My cmake flags are `-DTEGRAX1=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DARM_DYNAREC=ON`

Please let me know of any other useful information you may need!

**Comment by ptitSeb** [comment]
Thanks for the testing.

So my "improvment to TLS" broken some things :'(
damn, I'll look at that!

**Comment by Heasterian** [comment]
Funny is that Hollow Knight works fine for me so it's probably some minor issue triggered by certain configuration/set up.

**Comment by ptitSeb** [comment]
It seems to be random. I got a crash 1 time over 4.
Still, I think I have fixed it, can you try again?

**Comment by KiralyCraft** [comment]
Yeeep! That did it, I tried over and over to break it but it just keeps on working. Many thanks for taking a look at it, seems to work wonderfully now!
