### ISSUE TITLE
Cannot clone box64

### ISSUE THREAD

**Issue by Skeeya** [ptitSeb/box64#312]
I want to install box64 on my raspberry pi 4b but i always get this "not found" message although this repo is available. Anyone knows why? (OS: 64 Bit Raspberry Lite)

pi@raspberry:~ $ git clone https://github.com/ptitSeb/box64.git
Cloning into 'box64'...
/usr/lib/git-core/git-remote-https: 1: 2526fc26bdbcb46c18435ed08: not found
/usr/lib/git-core/git-remote-https: 2: Description-en:: not found
/usr/lib/git-core/git-remote-https: 3: library: not found
/usr/lib/git-core/git-remote-https: 4: be: not found
/usr/lib/git-core/git-remote-https: 6: Package:: not found
/usr/lib/git-core/git-remote-https: 7: Description-md5:: not found
/usr/lib/git-core/git-remote-https: 8: Description-en:: not found
/usr/lib/git-core/git-remote-https: 9: library: not found
/usr/lib/git-core/git-remote-https: 10: be: not found
/usr/lib/git-core/git-remote-https: 12: Package:: not found
/usr/lib/git-core/git-remote-https: 13: Description-md5:: not found
/usr/lib/git-core/git-remote-https: 14: Description-en:: not found
/usr/lib/git-core/git-remote-https: 15: FFmpeg: not found
/usr/lib/git-core/git-remote-https: 16: mux,: not found
/usr/lib/git-core/git-remote-https: 17: machines: not found
/usr/lib/git-core/git-remote-https: 18: cutting: not found
/usr/lib/git-core/git-remote-https: 20: This: not found
/usr/lib/git-core/git-remote-https: 21: contains: not found
/usr/lib/git-core/git-remote-https: 22: and: not found
/usr/lib/git-core/git-remote-https: 24: The: not found
/usr/lib/git-core/git-remote-https: 25: to: not found
/usr/lib/git-core/git-remote-https: 26: codecs: not found
/usr/lib/git-core/git-remote-https: 28: This: not found
/usr/lib/git-core/git-remote-https: 30: Package:: not found
/usr/lib/git-core/git-remote-https: 31: Description-md5:: not found
/usr/lib/git-core/git-remote-https: 32: Syntax error: "(" unexpected

**Comment by fish4terrisa-MSDSM** [comment]
Hmm ..... your git seem broken.you might send your /usr/lib/git-core/git-remote-https file ,that should be a binary ,but the output shows that its a shell script(l'm not sure;-)

**Comment by fish4terrisa-MSDSM** [comment]
if that file is not broken ,you may backup the file and replace it with a Bash Script:
`#!/bin/bash`
`echo $* >> out.put`
then run `chmod 777 /usr/lib/git-core/git-remote-https`as root
and upload the file out.put and I will see what happened

**Comment by fish4terrisa-MSDSM** [comment]
sorry ,i didn't mention that you should clone box64 again and then the out.put would generate.the clone would fail ,but that's ok
