### ISSUE TITLE
Unityplayer doesn't start [ RPI 4, 64 bit RasPiOS ]

### ISSUE THREAD

**Issue by Toernblom** [ptitSeb/box64#313]
Hi, I've built and exported an executable to my rpi. Running 
`sudo BOX64 ./program`   fails at the line

`Using native(wrapped) libXxf86vm.so.1`

By running with dump as the log these are the last messages
`
Run X86 (0x9d37e5d0), RIP=0xa0b40, Stack=0x7f89b7b018
1186|0x7f88821000: Calling dup (/lib/aarch64-linux-gnu/libc.so.6)(0x1, 0x7F87474789, 0x1, ...) => return 0x4
1186|0x7f88821015: Calling fileno_unlocked (/lib/aarch64-linux-gnu/libc.so.6)(0x7F8A8604A0, 0x7F87474789, 0x1, ...) => return 0x2
1186|0x7f8882101c: Calling dup (/lib/aarch64-linux-gnu/libc.so.6)(0x2, 0x7F87474789, 0x1, ...) => return 0x5
1186|0x7f8882102a: Calling fileno_unlocked (/lib/aarch64-linux-gnu/libc.so.6)(0xA8C5FAA0, 0x7F87474789, 0x1, ...) => return 0x3
1186|0x7f88821034: Calling fileno_unlocked (/lib/aarch64-linux-gnu/libc.so.6)(0x7F8A860580, 0x7F87474789, 0x1, ...) => return 0x1
 ...  =>PltResolver: Addr=0x9d36a990, Slot=153 Return=0x7f8882103d: elf is UnityPlayer.so (VerSym=0x3a58)
            Apply Global R_X86_64_JUMP_SLOT 0x7f891738b0 with sym=dup2(ver 2: dup2@GLIBC_2.2.5) (0x7f890aa2f6 -> 0xa04a0 / (noelf))
 return 0x1
Run X86 (0x9d37e5d0), RIP=0xa04a0, Stack=0x7f89b7b018
1186|0x7f8882103d: Calling __dup2 (/lib/aarch64-linux-gnu/libc.so.6)(0x3, 0x1, 0x1, ...) =>
`

Running latest bullseye 64 bit full desktop. Is this a known issue?

**Comment by ptitSeb** [comment]
The log you copy/paste is truncated, because the call to "dup2" basicaly redirect stdout to internal Unity log...

Anyway, my guess is thta it just fail because it expect an opengl driver capable of creating at least 3.2+ context, wich default RPi4 driver doesn't support.
Use `MESA_GL_VERSION_OVERRIDE=3.2` env. var. and it should goes farther.

**Comment by Toernblom** [comment]
Gotcha!

Tried running that and sadly no, it did not. Still stuck at libXxf86vm.so.1.. 

I managed to get Unity to run like 1-2 months ago on the rpi and I haven't changed my process when making a fresh install, not sure what the difference is. Still using the same Unity build aswell.

**Comment by ptitSeb** [comment]
look in `l ~/.config/unity3d/` for the UnityPlayer log, to have more detail on the issue maybe?

**Comment by Toernblom** [comment]
Some issues with mscorlib.dll from mono it seems like. The file is there, not sure why it can't be loaded.
According to the logs its searching for mscorlib.dll.so however, and the file extension that is there is only .dll , not dll.so. Not sure if that makes any difference tho.

https://pastebin.com/HsQYxQPP

**Comment by ptitSeb** [comment]
the `mscorlib.dll` error is normal, don't worry.

That log is way to short, and end with Desktop 0x0@0 wich is obviously not correct.

Try to launch with `BOX64_TRACE_FILE=trace.txt BOX64_LOG=1 BOX64_SHOWSEGV=1` and check the `trace.txt` that will be generated.
Also and don't forget to launch with `MESA_GL_VERSION_OVERRIDE=3.2` all the time, I'm sure this one is mendatory.

**Comment by Toernblom** [comment]
Hmm. I get further if I use IL2CPP rather than Mono atleast. Now something with "libwayland"..

Ran using both Mono ( old build ) and IL2CPP

IL2CPP Trace and Terminal log
https://pastebin.com/V2DidCUQ


MONO Trace and Terminal log
https://pastebin.com/cyPDAkxH

**Comment by Toernblom** [comment]
Something that might be related is that i had to uncomment `dtoverlay=vc4-kms-v3d` in `/boot/config.txt`
to be able to get the official 7" screen to not be blank.

**Comment by ptitSeb** [comment]
mmm, so you don't have any 3d accelaration availble?

what `glxinfo -B` gives you? does `glxgears` works?

**Comment by Toernblom** [comment]
Nevermind that, managed to fix that with [this](https://github.com/raspberrypi/linux/issues/4020#issuecomment-991228842)

**Comment by ptitSeb** [comment]
so, now, UnityPlayer works? The ticket can be closed?

**Comment by Toernblom** [comment]
Sorry no, i only managed to fix so that 3d acceleration is available. Nothing changed with the logs as far as i can see

**Comment by Toernblom** [comment]
I've tried reflashing 64 bit version with both latest Ubuntu and RaspiOS from the raspberry pi imager and still getting stuck at the same place from the logs i posted previously ..

**Comment by ptitSeb** [comment]
does unity log still show a "Desktop 0x@0"?

**Comment by Toernblom** [comment]
Hmm, theres no unity3d folder now under ~/.config . What i did different this time was using the prebuilt binaries when installing box64 rather than building it. Is it perhaps located somewhere else now?

**Comment by ptitSeb** [comment]
Unity folder is dependant of the system, not box64 (unless it just doesn't start at all)

**Comment by Toernblom** [comment]
If i ran without any env variables from box64 a Unity log was output. New log [here](https://pastebin.com/ykjUci5s)

**Comment by ptitSeb** [comment]
Box64 is not compatible with Wayland for now. It tries to load wayland stuff, but not of the libs are wrapped, and even putting x86_64 will not work, as libEGL is not wrapped yet (and is a critical componant for Wayland)

**Comment by Toernblom** [comment]
Hmm, haven't included anything to do with Wayland from my side. Perhaps something in a new Unity version?

**Comment by ptitSeb** [comment]
I have no idea, but the library it's looking for are wayland stuffs. After the failed loading, nothing happens, so I guess it wants wayland.

**Comment by Toernblom** [comment]
Alright weird. I used the same build from Unity as i used when i successfully launched 1-2 months ago with nothing changed except new raspberry pi version and latest box64. Sad stuff , but thanks alot for the support. I greatly appreciate it!

**Comment by ptitSeb** [comment]
I have added support for wrapped libEGL, and also improve compatibility with unity3d game in current main.

Can you update your box64 and try again?

**Comment by ptitSeb** [comment]
Can this ticket be closed now?

**Comment by Toernblom** [comment]
Hi, been on vacation and just came back. The problem still persists after re-imaging the rpi and getting the latest update. It's still trying to search for Wayland using Unity 2021.3.2f1.

**Comment by ptitSeb** [comment]
I really don't think it's a box issue, but a system / configuration issue.

**Comment by Toernblom** [comment]
Alright i managed to get it to start now. I switched to ubuntu on rpi 22.04 but got the same problem at first, then it worked if i plugged my mouse and keyboard directly to the pi and ran in terminal rather than to ssh through. Have you seen this before?

**Comment by ptitSeb** [comment]
I haven't switched to Wayland yet, so I don't have much experience.
