### ISSUE TITLE
Compile fails on Fedora 35 aarch running inside proot-distro for termux

### ISSUE THREAD

**Issue by Root-voidX** [ptitSeb/box64#314]
Hello,
 
I'm trying to compile box64 on Fedora 35 aarch64 running inside proot distro for termux.

I used this line for config:

`cmake .. -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo`

Configuration showed no errors, however when I go to make, it stops at this error:

`make[2]: *** No rule to make target '/home/ai-fe/.compile-disk/box64/src/wrapped/wrappedalure_private.h', needed by '../src/wrapped/generated/functions_list.txt'. Stop.`

The header file does exist in src, so I dont know what i could be missing.

**Comment by ptitSeb** [comment]
I don't know what could happens, but maybe try to clone box64 in a regular folder, and not a hidden one like `.compile-disk`. Also, avoid space in the the folder name.

**Comment by Root-voidX** [comment]
> I don't know what could happens, but maybe try to clone box64 in a regular folder, and not a hidden one like `.compile-disk`. Also, avoid space in the the folder name.

That worked !

I actually have a usage question. Do I need to run box64 then the application name in terminal to use emulation? Also do you know how to use this with udocker?

**Comment by ptitSeb** [comment]
after `sudo make install` (and maybe a restart of systemd binfmt service), box64 should be used automatically. Just launch x86_64 apps normaly `./my_app` and box64 should be used automatically. You can still use `box64 ./my_app` of course.

I don't think box64 can be used to run x86_64 docker image for now (but I haven't tried).

**Comment by Root-voidX** [comment]
> after `sudo make install` (and maybe a restart of systemd binfmt service), box64 should be used automatically. Just launch x86_64 apps normaly `./my_app` and box64 should be used automatically. You can still use `box64 ./my_app` of course.
> 
> I don't think box64 can be used to run x86_64 docker image for now (but I haven't tried).

So, I tried box64 with x86_64 version of Paraviee but run into this issue, here is the terminal output in a text file!
[paraview-box64.txt](https://github.com/ptitSeb/box64/files/8793858/paraview-box64.txt)

**Comment by ptitSeb** [comment]
Well
First, that's a totatly different issue.
Second, `libgomp.so.1` is not wrapped in box64, so you need to find an x86_64 version of it and put it in the binary folder for box64 to find an duse it (it may not be the only missing lib).

**Comment by Root-voidX** [comment]
> Well First, that's a totatly different issue. Second, `libgomp.so.1` is not wrapped in box64, so you need to find an x86_64 version of it and put it in the binary folder for box64 to find an duse it (it may not be the only missing lib).

Ah so I need to put the x86_64 libs in the box86 lib folder ? One thing I notice is with fedora that dnf doesn't let me install both aarch64 packages and x86_64 packages, so i might need to find another way !
