### ISSUE TITLE
C++ iostreams cause a segmentation fault

### ISSUE THREAD

**Issue by Hypnotron** [ptitSeb/box64#315]
Inserting into std::cout or std::cerr causes a segmentation fault. The following program segfaults when compiled for x86_64 using either gcc 12.1.0 or clang 13.0.1 and run under box64 on both AArch64 and x86_64:
```
#include <iostream>

int main(int argc, char* argv[]) {
    std::cout << "broken\n";
    return 0;
}
```
```
6407|SIGSEGV @0x64941284 (???(box64+0x64941284)) (x64pc=0x7feadb4a05fe/libstdc++.so.6:"libstdc++.so.6/_ZNSo6sentryC2ERSo + 30", rsp=0x7feadad7c450), for accessing 0xffffffffffffffe8 (code=1)
```
Comparing the trace with native execution, it appears that at the time of the segfault, RSI contains the address of std::cout, but there are two addresses at std::cout when executed natively and a bunch of zeroes at std::cout under box64, so RAX gets loaded with a null pointer.

printf does not suffer from this issue.

**Comment by ptitSeb** [comment]
I'll try to reproduce this on my side.

**Comment by ptitSeb** [comment]
I tried to reproduce, building with clang++-13, but it did work on my side.
built with
````
clang++-13 -mtune=core2 -O2 -g cout_cpp.cpp -o cout_cpp
```
it works fine with box64, showing:
```
seb@D2000:~/git/box64/build$ ./cout_cpp
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with trace with Dynarec v0.1.9 c312ca4 built on May 30 2022 10:29:00
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 24 Env var
Looking for ./cout_cpp
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
broken
````
Can you share your binary and the full log also?

**Comment by ptitSeb** [comment]
I reproduce with your build.

It seems the issue is ` mov     rdi, cs:_ZSt4cout_ptr` at the very beggining, with the symbols apparently uninitialized for some reason.

The version I have that work use ` mov     edi, offset _ZSt4cout@GLIBCXX_3_4` so same symbol but versionned. I have to check if that can be the source of the issue.

**Comment by ptitSeb** [comment]
Acutaly, no, rdi is fine. The issue is with RSI, as you mentionned.
The code is `lea     rsi, aBroken    ; "broken\n"` wich seems to be wrong, so an issue with elfloader I guess.
