### ISSUE TITLE
[Regression] Can't connect to TS3-Server on RaspberryPI 3B anymore with box64 v0.1.8

### ISSUE THREAD

**Issue by XXXBold** [ptitSeb/box64#318]
## Description ##
With v0.1.8 there seems to be a regression with box64, which doesn't allow me to connect to my TS3-Server anymore. The Server starts as it should (doesn't crash) but it's not possible to connect to it.

I've opened a detailed post on the raspberrypi-forums first (https://forums.raspberrypi.com/viewtopic.php?t=334324), that suggested I should try with v0.1.6 of box64, which fixed the problem.

If you need further information, let me know. Hopefully this can be fixed in later revisions :)

## System Details ##
Hardware: Raspberry PI 3B
OS: RaspberryPI OS Lite (64-bit), installed using RPI Imager Tool
TS3-Server: Latest from website (v3.13.6, Linux x64), https://teamspeak.com/en/downloads/#server

**Comment by ptitSeb** [comment]
Oh, a regresion :(

I would need you to make a bisect between v0.1.6 and v0.1.8 to find the commit that introduced it. Are you familliar with `git bisec` and building box64 from sources?

**Comment by XXXBold** [comment]
I'm familiar with building from source, using these instructions: https://github.com/ptitSeb/box64/blob/main/docs/COMPILE.md#for-pi4
But not with `git bisec` unfortunately. However, if you're willing to give me some guidance, I'm ready to learn :)

Another thing I noticed: Building 0.1.8 takes remarkably longer than 0.1.6 and eats up a lot of RAM sometimes (Almost 4GB swap used).

**Comment by ptitSeb** [comment]
if you have current source in `~/box64` than to bisect you'll do this (also, I assume you tested with current version and it's still broken).
Prepare the bisec:
```
cd ~/box64/build
git checkout v0.1.8
cd .. ; git bisect bad ; cd build
```
Answer 'y' to  the question of git about initializing a bisec
then set the last known working version with:
```
git checkout v0.1.6
cd .. ; git bisect good ; cd build
```
After that, git will move between v0.1.6 and v0.1.8. At each step, build and test:
```
make -j6 && sudo make install
````
test. then if the result if good do `cd .. ; git bisect good ; cd build` or else `cd .. ; git bisect bad ; cd build` to go to next step.
After a few step, it should give the commit that broken it
You can then reset the bisect and go back to current main with
```
cd .. ; git bisect reset ; cd build
git checkout main
```

**Comment by XXXBold** [comment]
Thanks for the detailed instruction! I was able to follow them, here's the result:
```
f779d4fadb524857a8c6d74c62013ea2f381bc14 is the first bad commit
commit f779d4fadb524857a8c6d74c62013ea2f381bc14
Author: ptitSeb <sebastien.chev@gmail.com>
Date:   Sat Apr 9 18:48:12 2022 +0200

    [DYNAREC] Refactored dynarec, using box86 refactor

 src/dynarec/arm64/dynarec_arm64_00.c        | 114 ++--
 src/dynarec/arm64/dynarec_arm64_0f.c        | 209 ++++---
 src/dynarec/arm64/dynarec_arm64_64.c        |  33 +-
 src/dynarec/arm64/dynarec_arm64_66.c        |   4 +-
 src/dynarec/arm64/dynarec_arm64_660f.c      | 500 ++++++++-------
 src/dynarec/arm64/dynarec_arm64_6664.c      |   2 +-
 src/dynarec/arm64/dynarec_arm64_67.c        |  47 +-
 src/dynarec/arm64/dynarec_arm64_d8.c        | 164 +++--
 src/dynarec/arm64/dynarec_arm64_d9.c        | 173 ++++--
 src/dynarec/arm64/dynarec_arm64_db.c        |  76 ++-
 src/dynarec/arm64/dynarec_arm64_dc.c        | 100 +--
 src/dynarec/arm64/dynarec_arm64_dd.c        |  76 ++-
 src/dynarec/arm64/dynarec_arm64_df.c        |  86 ++-
 src/dynarec/arm64/dynarec_arm64_f0.c        |   4 +-
 src/dynarec/arm64/dynarec_arm64_f20f.c      |  82 ++-
 src/dynarec/arm64/dynarec_arm64_f30f.c      |  97 ++-
 src/dynarec/arm64/dynarec_arm64_functions.c | 422 ++++++++++++-
 src/dynarec/arm64/dynarec_arm64_functions.h |  33 +-
 src/dynarec/arm64/dynarec_arm64_helper.c    | 915 +++++++++++++++++++---------
 src/dynarec/arm64/dynarec_arm64_helper.h    | 110 +++-
 src/dynarec/arm64/dynarec_arm64_pass0.h     |  35 +-
 src/dynarec/arm64/dynarec_arm64_pass1.h     |  12 +-
 src/dynarec/arm64/dynarec_arm64_pass2.h     |  10 +-
 src/dynarec/arm64/dynarec_arm64_pass3.h     |  55 +-
 src/dynarec/arm64/dynarec_arm64_private.h   |  78 ++-
 src/dynarec/dynarec_native.c                | 231 +++++--
 src/dynarec/dynarec_native_pass.c           | 160 ++++-
 src/dynarec/dynarec_private.h               |  35 +-
 src/main.c                                  |   7 +-
 29 files changed, 2638 insertions(+), 1232 deletions(-)
```

**Comment by ptitSeb** [comment]
Thanks!
Ah damn, of course it's a big refactor :(
I'll need to check on my side and reproduce the issue, with ddebugger and all, to fix that one.

**Comment by ptitSeb** [comment]
Ok, I think I have found the issue. Please test latest sources.

I have tested on my side, running the server and the 32bits windows client on the same machine for testing :)
![debugging_teamspeak3_server](https://user-images.githubusercontent.com/3250792/172043109-b1142e89-c6cb-49af-a665-826cf790fbbe.png)

**Comment by XXXBold** [comment]
Also tested from my side, and can confirm it works again! Thanks for the fix! Will close this now.

**Comment by Maltz42** [comment]
This bit me on Saturday, and after some troubleshooting and head-scratching and deciding it might be box64, I came here to find that it was fixed by Sunday.  lol  Thanks to you both!
