### ISSUE TITLE
Zoom: more unimplemented Opcodes

### ISSUE THREAD

**Issue by stormchaser3000** [ptitSeb/box64#32]
```
61619|0xffff83f7ca05: Unimplemented Opcode (10) 66 0F 38 09 C1 66 0F 38 09 D3 66 0F 7F 07 66
```

this is after pulling in and compiling 81b1f61aec5b53716bff493b6dc21c6b7ec86df9

EDIT: Thank you for all your work on this project. Keep up the good work, but don't overwork yourself :)

**Comment by stormchaser3000** [comment]
That seems to have solved that error, but now getting this one:
```
67413|0xffff8e4939be: Unimplemented Opcode (01) 66 44 0F 38 09 C2 66 44 0F 38 09 D2 66 45 0F
```
with the same window freezing problem

**Comment by ptitSeb** [comment]
Strange, that's the same opcode I just added.

**Comment by ptitSeb** [comment]
it's the same opcode.
It's "66 0F 38 09"
the 4x between 66 and 0F is the "REX", used to change a few parameters in the opcode, but it's still the same.

**Comment by stormchaser3000** [comment]
oh... odd

**Comment by stormchaser3000** [comment]
ok, an update fixed that one. but now there is this one (which I am actually pretty sure is different).

```
12825|0xffffac07e16c: Unimplemented Opcode (D3) 0F D7 CA 48 83 E1 0F 83 F1 0F 44 0F BD C1 BA
```

**Comment by ptitSeb** [comment]
Yup, this one is different:
`0F D7 CA: pmovmskb ecx, mm2`

I'll add it soon.

**Comment by stormchaser3000** [comment]
I can now report that zoom appears to be working like a charm on box64. Both audio and video work and the microphone works as well.

I will not close this issue just yet as I will do some stress testing in a large meeting tonight at some time around 9:30 PM CDT. If I don't encounter any missing opcodes during that meeting I will probably close this issue.

**Comment by ptitSeb** [comment]
That's very good news! Especialy sound working, as that's still an issue on box86 with the 32bits version!

**Comment by Itai-Nelken** [comment]
I just tested on commit a5490dc6f209ff28c4ff86853755a5fa8feecf2f (latest as of writing) on manjaro arm kde plasma running on aa pinebook pro and everything is working other than screen sharing (I'll open a new issue for that).
thanks a lot @ptitSeb!

**Comment by stormchaser3000** [comment]
it is working quite well for me as well. I went to that meeting and besides the expected high CPU usage, it worked like charm. Thank you @ptitSeb
