### ISSUE TITLE
Winetricks Can't find Wine

### ISSUE THREAD

**Issue by Bhood23** [ptitSeb/box64#322]
Winetricks can't find Wine `root@localhost:~# BOX64_NOBANNER=1 winetricks -q corefonts vcrun2010 dotnet20sp1
------------------------------------------------------
warning: Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
------------------------------------------------------
------------------------------------------------------
warning: Your version of wine  is no longer supported upstream. You should upgrade to 6.x
------------------------------------------------------
Executing mkdir -p /root
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 0
drwxr-xr-x  7 root root 4096 Jun 11 02:18 .
drwxr-xr-x  4 root root 4096 Jun 11 03:02 ..
drwxr-xr-x  6 root root 4096 Jun  8 05:52 Program Files
drwxr-xr-x  6 root root 4096 Jun  8 05:57 Program Files (x86)
drwxr-xr-x  4 root root 4096 Jun 11 02:13 ProgramData
drwxr-xr-x  4 root root 4096 Jun  8 05:52 users
drwxr-xr-x 17 root root 4096 Jun 10 12:31 windows

Registry info:
/root/.wine/system.reg:#arch=win64
/root/.wine/user.reg:#arch=win64
/root/.wine/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "setarch: failed to execute /home/v8/wine/bin/wine: No such file or directory"
------------------------------------------------------`

Please help with this issue System info: root@localhost:/home/v8/wine/bin# neofetch
            .-/+oossssoo+/-.               root@localhost
        `:+ssssssssssssssssss+:`           --------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04 LTS
    .ossssssssssssssssssdMMMNysssso.       Host: samsung SM-N95
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-faked
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 days, 7 ho
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1324 (dpkg
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16   +sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: proot      ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: (8) @ 1.690GHz
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Memory: 3016MiB / 5.3GB
 

Thanks in advance

**Comment by ptitSeb** [comment]
This is really not readable. I guess you are running Ubuntu 64bits on Termux.

What is your issue and what have you installed?

**Comment by Bhood23** [comment]
> This is really not readable. I guess you are running Ubuntu 64bits on Termux.
> 
> What is your issue and what have you installed?

Thanks for replying 
I recently installed Winetricks and have tried running winetricks  with the BOX86_NOBANNER=1 winetricks command it keeps on not using Box86 to find wine I have checked /usr/local/bin/wine but it still won't work in trying to get fallout 3 on my Termux X11 proot but it still won't work

**Comment by ptitSeb** [comment]
Does box86 correctly trigger for 32bits apps? Can you run 32bits linux apps just by running thm (you can use the `test` folder of box86 repo, all test are 32bits binary linux executables).
What version of wine this is? where does it comes from?

**Comment by Bhood23** [comment]
> Does box86 correctly trigger for 32bits apps? Can you run 32bits linux apps just by running thm (you can use the `test` folder of box86 repo, all test are 32bits binary linux executables). What version of wine this is? where does it comes from?

The tests launched properly 


This is the Output

v8@localhost:~/x86/box86/tests$ ./test11
-bash: ./test11: No such file or directory
v8@localhost:~/x86/box86/tests$ box86 test11
ERROR: ld.so: object '/usr/lib/aarch64-linux-gnu/libgcc_s.so.1' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Box86 with Dynarec v0.2.7 2ed43c3c built on Jun  8 2022 03:19:35
Create/start 2 threads
Thread 1: Entered (10/20)
Thread 1: foo(), TLS data=0 2 "-1-"
Thread 2: Entered (10/20)
Thread 2: foo(), TLS data=1 4 "-2-"
Thread 2: bar(), TLS data=1 4 "-2-"
Thread 1: bar(), TLS data=0 2 "-1-"
Main completed
v8@localhost:~/x86/box86/tests$ box86 benchfloat
ERROR: ld.so: object '/usr/lib/aarch64-linux-gnu/libgcc_s.so.1' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Box86 with Dynarec v0.2.7 2ed43c3c built on Jun  8 2022 03:19:35
Memory required:  315K.


LINPACK benchmark, Double precision.
Machine precision:  15 digits.
Array size 200 X 200.
Average rolled and unrolled performance:

    Reps Time(s) DGEFA   DGESL  OVERHEAD    KFLOPS
----------------------------------------------------
     128   0.65  84.06%   3.80%  12.15%  308338.157
     256   1.20  83.30%   3.78%  12.92%  337471.091
     512   2.58  82.95%   4.04%  13.01%  313282.393
    1024   4.90  83.42%   3.83%  12.74%  328673.500




I have Wine-5.0 from PlayOnLinux Binaries

(:

**Comment by ptitSeb** [comment]
No it doesn't. It should run with just `./test11` for winetricks to run. You cannot use winetricks if box86 need to be use explicitly.
To my knowledge, there is an issue with Termux and binfmt, but I don't really know termux.

Anyway, it's not an issue with box86, so I'm closing the ticket.
