### ISSUE TITLE
Unable to run minecraft

### ISSUE THREAD

**Issue by tobelogin** [ptitSeb/box64#330]
As soon as Minecraft Dedicated Server updated,I can't run it any more.
Console was as follows.

pi@raspberrypi:~/test/minecraft $ ./bedrock_server
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.9 4b10506 built on Jun 25 2022 23:00:52
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 25 Env var
Looking for ./bedrock_server
Rename process to "bedrock_server"
Using native(wrapped) libnsl.so.1
Using native(wrapped) libssl.so.1
Using native(wrapped) libcrypto.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
Using native(wrapped) libpthread.so.0
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Error: PltResolver: Symbol OPENSSL_init_ssl(ver 34: OPENSSL_init_ssl@OPENSSL_1_1_0) not found, cannot apply R_X86_64_JUMP_SLOT 0x62a4fe0 (0x629a756) in /home/pi/test/minecraft/bedrock_server
Error: PltResolver: Symbol CONF_modules_unload(ver 23: CONF_modules_unload@OPENSSL_1_1_0) not found, cannot apply R_X86_64_JUMP_SLOT 0x62a4930 (0x62999f6) in /home/pi/test/minecraft/bedrock_server

**Comment by ptitSeb** [comment]
I have added the 2 functions, but was that the end of the log?

**Comment by tobelogin** [comment]
This is the whole log.

**Comment by ptitSeb** [comment]
Ok.
And is it working again now with the latest box64 sources?

**Comment by tobelogin** [comment]
It works,Thank you a lot
