### ISSUE TITLE
Error with openssl1.1.1 on Bedrock server (Error: PltResolver: Symbol TLS_method...)

### ISSUE THREAD

**Issue by ZekaNasu** [ptitSeb/box64#331]
I am a beginner. I'm translating from Japanese to English, so sorry for any weirdness.

I was trying to set up a Minecraft BedrockServer on ubuntu22.04 LTS/ArmCPU/OracleCloud, but on the way I got an error saying that I need libssl.so.1. [※Image 1](https://cdn.discordapp.com/attachments/986243502339944488/986243506425200640/unknown.png)

I think I was able to install it after a kind person showed me a website on how to install it.
Once I restarted my PC, the file path? The error message is as shown in the [※image 2](https://cdn.discordapp.com/attachments/976834960382124082/990688939742486548/unknown.png)
https://www.openssl.org/source/ , https://linuxpip.org/install-openssl-linux/

How can I solve the error? Thank you in advance for your answer.

**Comment by ptitSeb** [comment]
You need to update box64, I have already fixed this issue the week end (look #330 )

**Comment by ZekaNasu** [comment]
How do I perform a box64 update?
Delete the box64 folder and then the following command again?
I can't find the command for Ampere Altra so I'm running Ri4's

Or wait until the next version update of v0.1.9?

```
git clone https://github.com/ptitSeb/box64
cd box64
mkdir build; cd build; cmake ... -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j4
sudo make install
sudo systemctl restart systemd-binfmt
```

**Comment by ptitSeb** [comment]
do
```BASH
cd ~/box64/build
git pull
make -j3 && sudo make install
```
And it will be updated.

**Comment by ZekaNasu** [comment]
I found the cause.
Adding 'emit-server-telemetry=true' to server.properties to turn off the Server Telemetry notice gives an error.
When turned off, the TLS_method error is gone.

![ぴくつれ](https://user-images.githubusercontent.com/105807324/176233601-5793f00c-3eb0-4dab-be96-a446bdaaea35.png)


Can this cause? error? be corrected?
Or should I just contact Minecraft?
I wish we could be patient, but it bothers me every time.

**Comment by ptitSeb** [comment]
Did you update box64? I have fixed those errors already as I mentionned.

(And yes, a "Plt Resolver" error is a garantied crash)

**Comment by ptitSeb** [comment]
Oh, `TLS_mthod` is missing. I didn't noticed. I'll check that.

**Comment by ZekaNasu** [comment]
I updated, but the following error  （;_;）

![image](https://user-images.githubusercontent.com/105807324/176242839-be8c5a40-eb86-41e6-b255-3217fb117a93.png)

**Comment by ptitSeb** [comment]
New missing function. There maybe a lot of them, and unfortunatlmy, they will popup one by one...

**Comment by ptitSeb** [comment]
Yep...

**Comment by ZekaNasu** [comment]
New error

`Error: PltResolver: Symbol SSL_CTX_get_default_passwd_cb_userdata(ver 34: SSL_CTX_get_default_passwd_cb_userdata@OPENSSL_1_1_0) not found, cannot apply R_X86_64_JUMP_SLOT 0x62a5308 (0x629ada6) in /home/ubuntu/`

**Comment by ZekaNasu** [comment]
Next

`Error: PltResolver: Symbol SSL_CTX_get_ex_data(ver 34: SSL_CTX_get_ex_data@OPENSSL_1_1_0) not found, cannot apply R_X86_64_JUMP_SLOT 0x62a5318 (0x629adc6) in /home/ubuntu/`

**Comment by ZekaNasu** [comment]
`Error: PltResolver: Symbol SSL_get_verify_callback(ver 34: SSL_get_verify_callback@OPENSSL_1_1_0) not found, cannot apply R_X86_64_JUMP_SLOT 0x62a5378 (0x629ae86) in /home/ubuntu/`

**Comment by ZekaNasu** [comment]
`Error: PltResolver: Symbol SSL_get_verify_mode(ver 34: SSL_get_verify_mode@OPENSSL_1_1_0) not found, cannot apply R_X86_64_JUMP_SLOT 0x62a5388 (0x629aea6) in /home/ubuntu/`

**Comment by ZekaNasu** [comment]
Also, is this "std::system_error" error for box64?

```
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
Segmentation fault (core dumped)
```

![image](https://user-images.githubusercontent.com/105807324/176645495-b9633862-511e-4985-b40a-8d131289b998.png)

**Comment by ZekaNasu** [comment]
Yes You can download and run it from this URL
https://www.minecraft.net/en-us/download/server/bedrock/

In addition, I will tell you the OracleCloud (Alwayz Free) I am using.
Spec:Am 4core 24GB (VM.Standard.A1.Flex)

**Comment by code-monet** [comment]
I was trying this out today, and the server launched successfully. I have been able to connect and it seems okay for the first minute. Will use it for a bit and see if I run into issues.
Curious, how would you debug the ignored calls?

**Comment by ZekaNasu** [comment]
Sorry, I'm sorry, I'm not sure what happened to my OracleCloud account. My OracleCloud account was banned yesterday and I won't be able to touch it for a few days. (Looks like others have been banned without email too.)

Call to error~...... comes up when a world is created or when a player leaves the server.

Systemd_error (Core dump) occurred when I joined a world, AFK for about 5 minutes and tried to break inventory or blocks again.

Code-momet, if you are not running the server in OracleCloud (Arm), it could be on the Oracle side.

(Translated from Japanese to English)
DeepLで翻訳しました https://www.deepl.com/app/?utm_medium=android-share

**Comment by code-monet** [comment]
I'm running it on Oracle Cloud! The first warning I see is:

```
Error loading needed lib libproviders.so
Warning: Cannot dlopen("libproviders.so"/0x9bf73830, 2)
```
(I thought I fixed that on my server yesterday, will take a look again).

After that, when loading the world, I see:
```
Warning, call to __cxa_thread_atexit_impl(0x446d180, 0x9b9f2f60, 0x629c008) ignored
```

When player connects, I see:
```
Warning, call to __cxa_thread_atexit_impl(0x446d180, 0xffff58501bc0, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x51dab30, 0xffff68001b80, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x51dab70, 0xffff68001ba8, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4025a80, 0xffff58501b30, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4026910, 0xffff58501b58, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4027bb0, 0xffff58501b80, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x51dab30, 0xffff78001b80, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x51dab70, 0xffff78001ba8, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x51dab30, 0xffff70001b80, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x51dab70, 0xffff70001ba8, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4025a80, 0xffff68001ac0, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4026910, 0xffff68001ae8, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4027bb0, 0xffff68001b10, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x5276910, 0xffff68001bd8, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4025a80, 0xffff70001ac0, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4026910, 0xffff70001ae8, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4027bb0, 0xffff70001b10, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x5276910, 0xffff70001bd8, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4025a80, 0xffff78001ac0, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4026910, 0xffff78001ae8, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x4027bb0, 0xffff78001b10, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x5276910, 0xffff78001bd8, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x51dab30, 0xffff58501bf0, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x51dab70, 0xffff58501c18, 0x629c008) ignored
```

When player disconnects, I see:
```
Warning, call to __cxa_thread_atexit_impl(0x51dab30, 0xffff74001b80, 0x629c008) ignored
Warning, call to __cxa_thread_atexit_impl(0x51dab70, 0xffff74001ba8, 0x629c008) ignored
```

I played a little bit and it seems to work fine. Other players' skins are invisible, I just see their shadow, so I'm guessing the errors above have to do with the skin up/download service.

**Comment by code-monet** [comment]
Looked around a bit, the libproviders.so error has been seen by other people recently and appears to be because of an openssl-configuration file mismatch. The configuration file on the ARM machine is 3.0.2, but the amd64 library I got is 1.1.1n. I'll see if I can find a newer amd64 binary. I can get rid of the error by commenting out the `providers = provider_sect` section in the `/etc/ssl/openssl.cnf`, described [here](https://help.zoho.com/portal/en/community/topic/cant-install-zoho-workdrive-app-in-ubuntu-22-04), . This did not address the skin issue but probably I should try finding a compatible amd64 library instead.

**Comment by code-monet** [comment]
Tried that, looks like box64 doesn't have support for libssl3.

**Comment by LukeShortCloud** [comment]
Various SSL related libraries and functions including `SSL_get_ex_data_X509_STORE_CTX_idx` have been wrapped now. Closing as resolved.
