### ISSUE TITLE
Steam web views not working

### ISSUE THREAD

**Issue by Pythonic456** [ptitSeb/box64#337]
System info:
OS: Ubuntu 22.04 64-bit
Board: Raspberry Pi 4 4GB

I have both Box86 and Box64 installed through Pi-Apps, and installed Steam myself
from Steams official download page. Everything else seems to work, except for any kind of web view.
![Screenshot from 2022-07-01 11-21-01](https://user-images.githubusercontent.com/56113118/176877506-edf9f5e3-5f80-452a-b43a-4833e0fda0c2.jpg)
And in Small mode, I can see the list of games, install them, uninstall them, the works, but if I click "Properties" then nothing
happens, probably because it is also a web view.

**Comment by ptitSeb** [comment]
This is clearly mentionned in box86 README.

And yes, Properties is also a web view and will not work (uninstall also). You can use BigPicture to get to game properties as a workaround.
One day, webview will work, but for now, this is a know issue, so I close this ticket.
