### ISSUE TITLE
unable to build since https://github.com/ptitSeb/box64/commit/48b881f4912bc795e0467e334e359e9876f73c4f

### ISSUE THREAD

**Issue by theofficialgman** [ptitSeb/box64#342]
during building:
```
/home/gman/box64/src/libtools/threads.c: In function ‘my_pthread_cond_clockwait’:
/home/gman/box64/src/libtools/threads.c:678:16: warning: implicit declaration of function ‘pthread_cond_clockwait’; did you mean ‘my_pthread_cond_clockwait’? [-Wimplicit-function-declaration]
  678 |         return pthread_cond_clockwait(cond, getAlignedMutex((pthread_mutex_t*)mutex), __clock_id, __abstime);
      |                ^~~~~~~~~~~~~~~~~~~~~~
      |                my_pthread_cond_clockwait
```

and failure during linking
```
CMakeFiles/box64.dir/src/libtools/threads.c.o: In function `my_pthread_cond_clockwait':
/home/gman/box64/src/libtools/threads.c:678: undefined reference to `pthread_cond_clockwait'
collect2: error: ld returned 1 exit status
```

**Comment by ptitSeb** [comment]
On what are you building?

**Comment by theofficialgman** [comment]
switch (arm64 ubuntu bionic) with gcc 11

**Comment by theofficialgman** [comment]
[install-fail-Box64.log](https://github.com/ptitSeb/box64/files/9035325/install-fail-Box64.log)

thats my full log if you find it helpful

**Comment by ptitSeb** [comment]
I guess this phtread function is to recent for your system
I'll make the call optionnal, and return -1 if the function is not there.

**Comment by theofficialgman** [comment]
that is correct. it was added in glibc 2.30 https://abi-laboratory.pro/index.php?view=changelog&l=glibc&v=2.30

**Comment by theofficialgman** [comment]
it might be worthwhile to add CI for building on ubuntu bionic, or debian buster (or both) since these are the most used platforms for box64 instead of using 20.04 for everything

**Comment by PeterStrick** [comment]
> it might be worthwhile to add CI for building on ubuntu bionic, or debian buster (or both) since these are the most used platforms for box64 instead of using 20.04 for everything
> 
> ubuntu-18.04 is available through github actions which you can use to do this

Github Actions are actually used to build box64 on every commit
Just that the GitHub Action uses ubuntu-latest

**Comment by theofficialgman** [comment]
I am aware. which is why I am suggesting to use ubuntu-18.04 (instead of ubuntu-latest which currently is focal and will eventually be jammy)

**Comment by ptitSeb** [comment]
Yeah, I'll try to setup one of the build on an older OS version.

**Comment by ptitSeb** [comment]
If you have suggestion on how to modify the current github workflow to add some ubuntu 18 testing (for TegraX1 for example). I would like to avoid doing the tests twice, but just selecting to OS depending on the config

**Comment by theofficialgman** [comment]
closing as the commits related prior solve compilation
