### ISSUE TITLE
Suggestion: Allow for passing custom environment variables to only programs launched with BOX86/64

### ISSUE THREAD

**Issue by theofficialgman** [ptitSeb/box64#347]
I have a usecase where I would like to launch a program (steam) with different environment variables for the x86 bins from the x86_64 bins. There is no builtin functionality to the steam launch script to support this (and it is difficult to modify without triggering an automatic reinstall).

What I would like is a way set environment variables for the boxes to pick up on and pass to any boxed binary.
something like
```
BOX86_ENV='DISPLAY=:2' BOX64_ENV='DISPLAY=:0' steam
```

of course other normal environment variables should continue to be passed as before to all binaries (like setting STEAMOS=1 and STEAM_RUNTIME=1)

**Comment by ptitSeb** [comment]
Why do you need special env. var.. Why not simply suing `DISPLAY=:2`?

**Comment by theofficialgman** [comment]
because in my case, DISPLAY=:2 is going to an xephyr server for mesa software rendering (of x86 -> armhf) and DISPLAY=:0 is the host display used for x86_64 -> arm64 with full gpu acceleration. this is necessary on nvidia jetson as there are no armhf gpu drivers and the regular xserver can not display anything software mesa

**Comment by ptitSeb** [comment]
Ok, I'll think about some solution. There must be something simple.

Does this BOX86_ENV can only contains 1 env. var.?

**Comment by theofficialgman** [comment]
I only need one, though I guess it would be nice if multiple could be given

**Comment by ptitSeb** [comment]
Ok, I can probably just check at the start of box86/box64 if that env. var. exist, and then simply use `setenv` to define the env. var. So the current program will have the overriden env. But also all child process will have it too. This should not be too difficult to do with only 1 env. var.
I don't see any simple indea to allow multiple env. var. to be defined with 1 env, but I can check BOX86_ENV1, BOX86_ENV2... and incremement that number until no env var is found for the others...

**Comment by theofficialgman** [comment]
closing since this has been implemented and works as expected. thank you!

**Comment by theofficialgman** [comment]
@ptitSeb reopening because I think the `BOX64_ENV1` `BOX64_ENV2`, etc do not work
only the `BOX64_ENV` works for me

**Comment by ptitSeb** [comment]
Ah yes, I started with `BOX64_ENV0` by mistake. It's fixed now.
