### ISSUE TITLE
7 Days To Die dedicated server gets corrupted after few minutes of playing. [Not enough Hotpage...]

### ISSUE THREAD

**Issue by NikkeDoy** [ptitSeb/box64#353]
Hey! Amateur here trying to get 7 Days To Die dedicated server work on the Oracle Cloud Free Tier, but after a while it becomes unresponsive.
I've compiled box64 inside custom docker image so I can run the server on pterodactyl. Works great, but then server hangs like crazy and game becomes unplayable.  

Here is the trace log [https://pastebin.com/MPc7m73J](https://pastebin.com/MPc7m73J) hopefully someone finds it useful. 😋

_Great software BTW! Loving it so far._

**Comment by QuintenQVD0** [comment]
works fine for me on my pi 4 with 2 gb and 6 ports even running in docker (pterodactyl) https://pastebin.com/8JMJFa44

**Comment by NikkeDoy** [comment]
_It's been a year holy moly..._
Anyway, 7 Days to Die server is working almost flawlessly. Worlds generated with the random world generation have huge ravines when trying to generate roads, but that will be another issue.

I'll close this issue.
