### ISSUE TITLE
Non Vanilla M1 (m1max) Getting the Pagefile size error

### ISSUE THREAD

**Issue by sheppanator** [ptitSeb/box64#358]
Hi thanks for you work on box64.

Was trying to follow along on your instructions for running box64 (world of goo) on an asahi setup on my m1-max cpu.

When running anything I get the following error:
`Error: PageSize configuation is wrong: configured with 4096, but got 16384`

**Comment by ptitSeb** [comment]
You need to configure the cmake project with `-DM1=ON`

You can use `ccmake .. ` to alter the configuration. Make sure M1 is ON (and PAGE16K should also be ON)
Rebuild after you reconfigure and it should work.

**Comment by sheppanator** [comment]
Ah – thanks its my mistake. Working now!
