### ISSUE TITLE
Trying to build Box64 inside an arm64 container

### ISSUE THREAD

**Issue by Root-voidX** [ptitSeb/box64#370]
Hello, 

So for testing purposes I am trying to build box64 inside a CentOS-7 arm64 container running on my pc.

By default CentOS-7 has cmake-2.18, but i did install cmake-3.14, when I try to compile, it goes until the last step of linking and errors out with undefined references:

![image](https://user-images.githubusercontent.com/24353606/182117008-a53fb944-18e8-4877-b25d-ec7f80da95ac.png)

I have glibc-devel and glibc-static installed and I can find libpthreads and pthreads.h in PATH as well. Any ideas?

**Comment by ptitSeb** [comment]
I guess the OS is old and doesn't have those 2 "non portable" thread functions. I'm try to do some workaround later, but there are  not emulable and missing them will probably make many things not work properly.

**Comment by Root-voidX** [comment]
Ah i see, I can definitly move to a newer OS then. I wanted to try it on CentOS7 because the application I want to try works best with centos libraries. I did create a CentOS7 x86 chroot with the packages too, can I pass that to box64 so when it looks for libraries it will look in the chroot?

**Comment by ptitSeb** [comment]
yes, just use `BOX64_LD_LIBRARY_PATH`pointing the chroot.

Also, note that box64 is only for x86_64 programs. x86 (32bits) needs box86.

**Comment by Root-voidX** [comment]
> yes, just use `BOX64_LD_LIBRARY_PATH`pointing the chroot.
> 
> Also, note that box64 is only for x86_64 programs. x86 (32bits) needs box86.

Sounds good, I am trying to run Fluent and/or StarCCM+ using box64, they are x86_64 software. Can I use box64 to chroot into my x64 chroot by any chance? I just need the software to know these x64 libraries exist and they can access them, and that box64 can translate them for arm64 cpu?
