### ISSUE TITLE
SSE4.2 support

### ISSUE THREAD

**Issue by milosivanovic** [ptitSeb/box64#371]
Thanks for the great work with box64! Is there any estimated timeline on when we might see support for SSE4.2?

I see you responded here https://boilingsteam.com/box64-witness-the-birth-of-the-arm-gaming-scene/ about a year ago:
> The emulated x86_64 CPU has all the minimum expected extensions: FPU/MMX/SSE/SSE2. Also SSSE3. I started a few SSE4.x opcodes, but it is not fully supported yet.

Is that still in progress?

**Comment by ptitSeb** [comment]
there is partial SSE4.2 support, but it's not complete, and not in my immediate todo. Some 4.2 opcodes are really complex, What do you need SSE4.2 support for?

**Comment by ptitSeb** [comment]
With https://github.com/ptitSeb/box64/commit/5c13f8f10ac82ca642a6c930585989cc0d75a664 I have added SSE 4.2 support

**Comment by jserv** [comment]
Is it time to close this issue?

**Comment by LukeShortCloud** [comment]
SSE 4.2 support has been added. Closing as complete.
