### ISSUE TITLE
Trying to run SAM (from NREL.gov) on a Raspberry Pi 4/8GB

### ISSUE THREAD

**Issue by teamit-denver** [ptitSeb/box64#373]
Using the SAM grid for Linux from https://sam.nrel.gov/download.html on a RPi4/8GB: Here's the run:

~/SAM/2021.12.02 $ ./SAM
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096
Box64 with Dynarec v0.1.9 1ff0a7c built on Jul 25 2022 01:31:55
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 50 Env var
Looking for /home/nick/SAM/2021.12.02/linux_64/sam.bin
Rename process to "sam.bin"
Using emulated /home/nick/SAM/2021.12.02/linux_64/ssc.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libsecret-1.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libcurl.so.4
Using native(wrapped) libm.so.6
Using native(wrapped) libgtk-x11-2.0.so.0
Using native(wrapped) libgdk-x11-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libatk-1.0.so.0
Using native(wrapped) libcairo.so.2
Using native(wrapped) libgthread-2.0.so.0
Using native(wrapped) libX11.so.6
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libSM.so.6
Using native(wrapped) libXtst.so.6
Using native(wrapped) libpangoft2-1.0.so.0
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Error: Global Symbol gtk_major_version not found, cannot apply R_X86_64_GLOB_DAT @0x1b1cd98 ((nil)) in /home/nick/SAM/2021.12.02/linux_64/sam.bin
Error: Global Symbol gtk_minor_version not found, cannot apply R_X86_64_GLOB_DAT @0x1b1ce50 ((nil)) in /home/nick/SAM/2021.12.02/linux_64/sam.bin
Error: Global Symbol gtk_micro_version not found, cannot apply R_X86_64_GLOB_DAT @0x1b1cf68 ((nil)) in /home/nick/SAM/2021.12.02/linux_64/sam.bin
22038|0x7f9cca9284: Unimplemented Opcode (FF 03 02 D1) 82 17 00 B0 E5 53 01 91 E4 43 01 91 E3 33 01

**Comment by LukeShortCloud** [comment]
These symbols have been wrapped:

https://github.com/search?q=repo%3AptitSeb%2Fbox64%20gtk_major_version&type=code

Closing as resolved.
