### ISSUE TITLE
box64 wine64 Cannot dlopen("/usr/lib64/wine/x86_64-unix/kernel32.so"/0x97ae57b5, 2)

### ISSUE THREAD

**Issue by fengxue-jrql** [ptitSeb/box64#377]
Using emulated /usr/lib64/wine/x86_64-unix/libwine.so.1
Error loading needed lib /usr/lib64/wine/x86_64-unix/wineboot.so
Warning: Cannot dlopen("/usr/lib64/wine/x86_64-unix/wineboot.so"/0x7d28db7b35, 2)
Warning: Unsupported libc Syscall 0xFFFF (65535)
Warning: Unsupported libc Syscall 0x13D (317)
0100:err:unwind:install_bpf prctl(PR_SET_SECCOMP, ...): ?????.
Error loading needed lib /usr/lib64/wine/x86_64-unix/kernel32.so
Warning: Cannot dlopen("/usr/lib64/wine/x86_64-unix/kernel32.so"/0x97ae57b5, 2)
Error loading needed lib /usr/lib64/wine/x86_64-unix/kernelbase.so
Warning: Cannot dlopen("/usr/lib64/wine/x86_64-unix/kernelbase.so"/0x97bf1b75, 2)
Error loading needed lib /usr/lib64/wine/x86_64-unix/advapi32.so
Warning: Cannot dlopen("/usr/lib64/wine/x86_64-unix/advapi32.so"/0x97c3ba85, 2)

**Comment by LukeShortCloud** [comment]
This should be fixed in the latest versions of Box64 and Wine. Either use Box86 along with Box64, Box64 with Box32 support enabled, or Box64 with Wine WoW64 for Wine to work properly. Closing as resolved.
