### ISSUE TITLE
Spiritfarer (Unity3D): Unimplemented Opcode (E2) FE 97 E1....

### ISSUE THREAD

**Issue by artdeell** [ptitSeb/box64#38]
Details:
 - Raspberry Pi 4B (8GB)
 - Ubuntu 64-bit
 - Box64 with Dynarec v0.1.3 5b5b974 built on Jul  7 2021 11:24:22
Spiritfarer (Unity3D game) crashes on startup after initial resource load.
Last lines of Player.log are:
```

TYPE: 31
* Assertion at mini-amd64.c:209, condition `amd64_is_imm32 (disp)' not met

85706|0x648fadc2: Unimplemented Opcode (E2) FE 97 E1 FF FF 17 15 2F 00 D0 A0 02 38 91 00
```

**Comment by artdeell** [comment]
[Player.log](https://github.com/ptitSeb/box64/files/6776217/Player.log)

**Comment by mogery** [comment]
Hey! This should now be fixed if you rebuild from a fresh pull. Could you try it out?

**Comment by ptitSeb** [comment]
Closing the ticket, no news for more than 6 months is good news (I suppose).
