### ISSUE TITLE
Can't build box64 at all on Termux

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [ptitSeb/box64#385]
Heya, I'm trying to build box64 on Termux but I'm getting this issue: https://haste.powercord.dev/onekanefav

Any information you need I'll be happy to acquire!

**Comment by ptitSeb** [comment]
What is the system you install on term? Debian family works. The one based on musl will not work.

**Comment by dirt2022** [comment]
Please check this error ;
hardware: Arrch64 android
compiler: clang14
about termux....emm you can try this:
https://f-droid.org/repo/com.termux_118.apk  (it is latest)
(It's a terminal emulator , with a minimize linux and a lot of packages: cmake,python,clang,proot ... (only can run bionic , glibc is disabled 😅 ))
error info **tentative definition has type 'struct __jmp_buf_tag' that is never completed**,I'm try to fix it,it still not work...

**Comment by dirt2022** [comment]
It may be useful
edit setjmp.h
add these things:

struct __jmp_buf_tag
  {
    /* NOTE: The machine-dependent definitions of `__sigsetjmp'
       assume that a `jmp_buf' begins with a `__jmp_buf' and that
       `__mask_was_saved' follows it.  Do not move these members
       or add others before it.  */
    jmp_buf __jmpbuf;		/* Calling environment.  */
    int __mask_was_saved;	/* Saved the signal mask?  */
    sigset_t __saved_mask;	/* Saved signal mask.  */
  };

**Comment by dirt2022** [comment]
> Heya, I'm trying to build box64 on Termux but I'm getting this issue: https://haste.powercord.dev/onekanefav
> 
> Any information you need I'll be happy to acquire!

Look at this😅

**Comment by ptitSeb** [comment]
the setjmp structures have different implementation on Android than on Linux basicaly. For now, build on Linux a system. Building on something else is not supported.
