### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dirt2022** [ptitSeb/box64#388]
Hardware Snapdragon 8xx
clang 14.
/home/box64/src/elfs/elfloader.c:992:38: error: use of undeclared identifier 'STB_GNU_UNIQUE'                                               if(!to_add || (bind==STB_GNU_UNIQUE && FindGlobalSymbol(maplib, symname, -1, NULL)))                                                             ^                        /home/box64/src/elfs/elfloader.c:1029:34: error: use of undeclared identifier 'STB_GNU_UNIQUE'                                          if(!to_add || (bind==STB_GNU_UNIQUE && 
FindGlobalSymbol(maplib, symname, version, vername)))        
                                             ^
FindGlobalSymbol(maplib, symname, version, vername))) Also not work

SOFTWARE:ANDROID NDK r25

**Comment by ptitSeb** [comment]
You are using ANDROID profile?

**Comment by dirt2022** [comment]
> You are using ANDROID profile?

Yeah!

**Comment by ptitSeb** [comment]
Mmmm, ok, I add a test for that `STB_GNU_UNIQUE` define and define it if not found.

**Comment by dirt2022** [comment]
Stop

**Comment by ptitSeb** [comment]
?

**Comment by dirt2022** [comment]
> ?

I reopened another , names "Termux On Android,"after now,Box64 On Android branch is established.Another questions about this can commit here.

**Comment by ptitSeb** [comment]
box64 now have an ` ANDROID`  build profile. It should build without error, but I haven't tested it, so I don't know if it works.

Note that this build of box64 (build with ` ANDROID` ) should be use to run x86_64 android program, not x86_64 linux program.

**Comment by LukeShortCloud** [comment]
Many community reports show that Box64 builds on Android these days. Closing as complete.
