### ISSUE TITLE
Factorio Server Failing to Start

### ISSUE THREAD

**Issue by dofrancis** [ptitSeb/box64#392]
I'm using an Oracle Cloud server with ARM64, and I compiled box64 with
$ cmake .. -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPAGE64K=1
When I try to start the server, it just stalls after here.
```
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:65536
Box64 with Dynarec v0.1.9 ca8ff5f built on Aug 15 2022 21:09:42
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 43 Env var
Looking for ./factorio
Rename process to "factorio"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
```
A simple hello world program works, so I could be missing something.
Here is a log from BOX64_LOG=2. https://hastebin.com/ugucaqopas.yaml
I'm not exactly sure what I'm doing wrong, but hopefully the log helps.

**Comment by ptitSeb** [comment]
I don't see anything special in the logs, just some SIGINT being done, not sure how, and the program quits peacefully after a few SIGINT it seems.

**Comment by dofrancis** [comment]
> I don't see anything special in the logs, just some SIGINT being done, not sure how, and the program quits peacefully after a few SIGINT it seems.

The SIGINT is manual. If I don't SIGINT the program will stay stuck.

**Comment by ptitSeb** [comment]
How do you know it's stuck and not loading something silently?

**Comment by dofrancis** [comment]
I left it for a long time (~1 hr) and it stayed the same. Also, if I run the program natively, there is output in the terminal. When I search factorio in this repository, other people have something after `Using native(wrapped) libm.so.6`.

**Comment by jackson-57** [comment]
I'm able to reproduce this. I built box64 today with the same cmake args and tried to run the ARK dedicated server. It hangs with dynarec enabled. If I use `BOX64_DYNAREC=0`, it doesn't hang. Same thing applies with the Factorio dedicated server. The system is an Oracle Cloud Ampere VM running Oracle Linux.

**Comment by jackson-57** [comment]
Potential duplicate #261?

I'm starting to wonder if this is an Oracle Linux specific issue. Everyone else seems to be running Box64 on Ubuntu with more success.

**Comment by ptitSeb** [comment]
Maybe it's a side effect of the 64K page size? The Dynarec will be impacted by the page size.

**Comment by docgalaxyblock** [comment]
@dofrancis Did you ever tried this again?

I am using a server managment software called AMP by CubeCoders
It has box64 implemented for its Factorio template

You need to use Ubuntu 20.04 or better Debian cause on Ubuntu 22.04 the factorio server crashes with a segmentation fault... (even in x64)

I guess this issue can be closed

**Comment by jackson-57** [comment]
If there's still issues with one distro, I think it should be documented somewhere, although it doesn't have to be this issue specifically.

**Comment by ptitSeb** [comment]
but does the original issue is still there?

**Comment by jackson-57** [comment]
I ended up switching over to Ubuntu as well, so I can't check, at least easily. I might be able to check on someone else's instance, if need be.

**Comment by ptitSeb** [comment]
I think I'll just close the ticket.

**Comment by dofrancis** [comment]
> @dofrancis Did you ever tried this again?
> 
> I am using a server managment software called AMP by CubeCoders It has box64 implemented for its Factorio template
> 
> You need to use Ubuntu 20.04 or better Debian cause on Ubuntu 22.04 the factorio server crashes with a segmentation fault... (even in x64)
> 
> I guess this issue can be closed

I have not tried it on Oracle Linux in a while because it worked when I tried on Ubuntu.
