### ISSUE TITLE
Raspberry Pi OS (64 bit) error on make -j$(nproc)

### ISSUE THREAD

**Issue by jbs30000** [ptitSeb/box64#393]
It gets to 31% then errors out.

[ 31%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/dynarec_native_pass.c.o
{standard input}: Assembler messages:
{standard input}: Warning: end of file not at end of a line; newline inserted
{standard input}:628: Error: unknown pseudo-op: `.lc2'
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[2]: *** [CMakeFiles/native_pass3.dir/build.make:147: CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_00.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:276: CMakeFiles/native_pass3.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

**Comment by ptitSeb** [comment]
It's an out-of-melory error. Relaunch (and maybe use a lower -j, like -J3 or -j2) and it will work.

**Comment by jbs30000** [comment]
I'll do that.  Thank you.

**Comment by pitkhalet** [comment]
I did this on rpi4 2GB and it did not work, is 2GB RAM not enough?

**Comment by ptitSeb** [comment]
did what? Don't use any `-j` to be sure. Just `make`...

**Comment by pitkhalet** [comment]
thanks for the reply! I used -j1 and it did not work. I found a comment on a youtube video who increased the swap file to 2GB. I did this and it looks like its completing right now

**Comment by StoneAgeSkillz** [comment]
Hi,
similar issue:

```
sudo apt install git build-essential cmake -y
sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install gcc-arm-linux-gnueabihf libc6:armhf libncurses5:armhf libstdc++6:armhf -y
git clone https://github.com/ptitSeb/box64.git
cd box64
mkdir build
cd build
sudo cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

Output for `make -j$(nproc)`:

[ 26%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_67.c.o
{standard input}: Assembler messages:
{standard input}: Warning: end of file not at end of a line; newline inserted
{standard input}:628: Error: unknown pseudo-op: `.lc20'
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[2]: *** [CMakeFiles/native_pass3.dir/build.make:147: CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_00.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
^Cmake[2]: *** Deleting file 'CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_66.c.o'
make[2]: *** [CMakeFiles/native_pass3.dir/build.make:199: CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_67.c.o] Interrupt
make[2]: *** [CMakeFiles/native_pass3.dir/build.make:186: CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_66.c.o] Interrupt
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [CMakeFiles/Makefile2:276: CMakeFiles/native_pass3.dir/all] Error 2

Failed to compile.

Output for `make -j3`:

[ 25%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_67.c.o
[ 25%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_d8.c.o
[ 25%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_d9.c.o
[ 25%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_db.c.o
[ 26%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_dc.c.o
[ 26%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_dd.c.o
[ 26%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_de.c.o
[ 27%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_df.c.o
[ 27%] Building C object CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_f0.c.o
{standard input}: Assembler messages:
{standard input}: Warning: end of file in string; '"' inserted
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[2]: *** [CMakeFiles/native_pass3.dir/build.make:160: CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_0f.c.o] Error 1
make[2]: *** Deleting file 'CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_0f.c.o'
make[2]: *** Waiting for unfinished jobs....
{standard input}: Assembler messages:
{standard input}: Warning: end of file not at end of a line; newline inserted
{standard input}:628: Error: unknown pseudo-op: `.lc20'
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[2]: *** [CMakeFiles/native_pass3.dir/build.make:147: CMakeFiles/native_pass3.dir/src/dynarec/arm64/dynarec_arm64_00.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:276: CMakeFiles/native_pass3.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

Made it pass 25% (dynarec_arm64_67.c.o), failed a bit later, at 27% dynarec_arm64_f0.c.o .

make -j2 failed at 24%

It is a fresh install of RaspiOs Bullseye 64bit on 240GB USB3 SSD, RPi4 4GB running @2.1GHz,
I run at 74°C on a x346 cooler and 12V fan running silently of the 5V GPIO pins. (with propper cooling at 28°C)

But it does not matter. It fails even without oveclock. And I want to use all cores. 
USB3 cant be too slow, the drive is an overkill, its somewhat cooled, but it runs stable at 2.1GHz, now with force_turbo=1 @74°C max (63°C idle) with no throttling. 
So where is the error? 
Even 4GB is not enough? 
If its RAM, then how do i use some of the overkill USB SSD as a RAM*?

Thanks for your input and ideas.

* replace RAM with correct terminology

**Comment by ptitSeb** [comment]
No, 4GB is not enough for a fresh build on 4 cores. You need more like 8GB.

**Comment by StoneAgeSkillz** [comment]
That was a fast reply, thank you for that. And it was what i needed. So i increased the swap file an it compiled.

`sudo dphys-swapfile swapoff
sudo nano /etc/dphys-swapfile`

change `CONF_SWAPSIZE=100 to` needed size (MB)
I also changed max size.

`sudo dphys-swapfile setup
sudo dphys-swapfile swapon
sudo reboot`

**Comment by Pumpkin040109** [comment]
cheah7749@raspberrypi:~/opencv/build $ make -j$(nproc)
[  0%] Built target opencv_highgui_plugins
[  0%] Built target opencv_dnn_plugins
[  1%] Built target libopenjp2
[  4%] Built target carotene_objs
[  4%] Built target opencv_videoio_plugins
[  5%] Built target ittnotify
[  5%] Built target quirc
[  8%] Built target libprotobuf
[  9%] Built target ade
[  9%] Built target gen_opencv_python_source
[ 10%] Built target tegra_hal
[ 16%] Built target opencv_core
[ 17%] Built target opencv_flann
[ 19%] Built target opencv_ml
[ 19%] Built target opencv_hdf
[ 19%] Built target opencv_version
[ 24%] Built target opencv_imgproc
[ 25%] Built target opencv_surface_matching
[ 25%] Built target opencv_intensity_transform
[ 25%] Built target opencv_phase_unwrapping
[ 26%] Built target opencv_photo
[ 27%] Built target opencv_imgcodecs
[ 27%] Built target opencv_quality
[ 27%] Built target opencv_plot
[ 28%] Built target opencv_reg
[ 28%] Built target opencv_xphoto
[ 29%] Built target opencv_features2d
[ 29%] Built target opencv_freetype
[ 29%] Built target opencv_fuzzy
[ 29%] Built target opencv_hfs
[ 30%] Built target opencv_line_descriptor
[ 31%] Built target opencv_img_hash
[ 32%] Built target opencv_saliency
[ 42%] Built target opencv_dnn
[ 43%] Built target opencv_videoio
[ 43%] Linking CXX shared library ../../lib/libopencv_calib3d.so
[ 43%] Built target opencv_dnn_superres
[ 43%] Built target opencv_text
[ 43%] Built target opencv_model_diagnostics
[ 44%] Built target opencv_highgui
[ 45%] Built target opencv_datasets
[ 45%] Built target opencv_ts
[ 45%] Built target opencv_dnn_objdetect
[ 46%] Built target opencv_visualisation
[ 46%] Built target opencv_annotation
[ 46%] Built target opencv_bioinspired
[ 46%] Built target opencv_perf_photo
[ 48%] Built target opencv_perf_imgproc
[ 50%] Built target opencv_perf_core
[ 50%] Built target opencv_perf_reg
[ 50%] Built target opencv_perf_xphoto
[ 51%] Built target opencv_perf_dnn
[ 51%] Built target opencv_perf_dnn_superres
[ 51%] Built target opencv_perf_features2d
[ 52%] Built target opencv_perf_imgcodecs
[ 53%] Built target opencv_perf_videoio
[ 54%] Built target opencv_perf_line_descriptor
[ 54%] Built target opencv_perf_bioinspired
/usr/bin/ld: CMakeFiles/opencv_calib3d.dir/src/usac/ransac_solvers.cpp.o: in function `cv::usac::Ransac::run(cv::Ptr<cv::usac::RansacOutput>&)::{lambda(cv::Range const&)#3}::operator()(cv::Range const&) const::{lambda(cv::usac::Score const&, cv::Mat const&, bool)#1}::operator()(cv::usac::Score const, cv::Mat const, bool) const':
ransac_solvers.cpp:(.text._ZZZN2cv4usac6Ransac3runERNS_3PtrINS0_12RansacOutputEEEENKUlRKNS_5RangeEE1_clES8_ENKUlRKNS0_5ScoreERKNS_3MatEbE_clESC_SF_b[_ZZZN2cv4usac6Ransac3runERNS_3PtrINS0_12RansacOutputEEEENKUlRKNS_5RangeEE1_clES8_ENKUlRKNS0_5ScoreERKNS_3MatEbE_clESC_SF_b]+0x44): undefined reference to `__atomic_load_8'
/usr/bin/ld: ransac_solvers.cpp:(.text._ZZZN2cv4usac6Ransac3runERNS_3PtrINS0_12RansacOutputEEEENKUlRKNS_5RangeEE1_clES8_ENKUlRKNS0_5ScoreERKNS_3MatEbE_clESC_SF_b[_ZZZN2cv4usac6Ransac3runERNS_3PtrINS0_12RansacOutputEEEENKUlRKNS_5RangeEE1_clES8_ENKUlRKNS0_5ScoreERKNS_3MatEbE_clESC_SF_b]+0x74): undefined reference to `__atomic_load_8'
/usr/bin/ld: ransac_solvers.cpp:(.text._ZZZN2cv4usac6Ransac3runERNS_3PtrINS0_12RansacOutputEEEENKUlRKNS_5RangeEE1_clES8_ENKUlRKNS0_5ScoreERKNS_3MatEbE_clESC_SF_b[_ZZZN2cv4usac6Ransac3runERNS_3PtrINS0_12RansacOutputEEEENKUlRKNS_5RangeEE1_clES8_ENKUlRKNS0_5ScoreERKNS_3MatEbE_clESC_SF_b]+0x400): undefined reference to `__atomic_store_8'
/usr/bin/ld: ransac_solvers.cpp:(.text._ZZZN2cv4usac6Ransac3runERNS_3PtrINS0_12RansacOutputEEEENKUlRKNS_5RangeEE1_clES8_ENKUlRKNS0_5ScoreERKNS_3MatEbE_clESC_SF_b[_ZZZN2cv4usac6Ransac3runERNS_3PtrINS0_12RansacOutputEEEENKUlRKNS_5RangeEE1_clES8_ENKUlRKNS0_5ScoreERKNS_3MatEbE_clESC_SF_b]+0x420): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/opencv_calib3d.dir/src/usac/ransac_solvers.cpp.o: in function `cv::usac::Ransac::run(cv::Ptr<cv::usac::RansacOutput>&)::{lambda(cv::Range const&)#3}::operator()(cv::Range const&) const [clone .isra.0]':
ransac_solvers.cpp:(.text._ZZN2cv4usac6Ransac3runERNS_3PtrINS0_12RansacOutputEEEENKUlRKNS_5RangeEE1_clES8_.isra.0[_ZNSt17_Function_handlerIFvRKN2cv5RangeEEZNS0_4usac6Ransac3runERNS0_3PtrINS5_12RansacOutputEEEEUlS3_E1_E9_M_invokeERKSt9_Any_dataS3_]+0xfac): undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [modules/calib3d/CMakeFiles/opencv_calib3d.dir/build.make:791: lib/libopencv_calib3d.so.4.8.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:5211: modules/calib3d/CMakeFiles/opencv_calib3d.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

would like to ask what wrong above?

**Comment by ptitSeb** [comment]
> 
> would like to ask what wrong above?

This is a question for the opencv project, this is box64 here (your libatomic seems oudated or something like that, but again, I'm not a maintainer of opencv, there might be other reason).

**Comment by Pumpkin040109** [comment]
> > would like to ask what wrong above?
> 
> This is a question for the opencv project, this is box64 here (your libatomic seems oudated or something like that, but again, I'm not a maintainer of opencv, there might be other reason).

can i get the solution from you?

**Comment by ptitSeb** [comment]
> > > would like to ask what wrong above?
> > 
> > 
> > This is a question for the opencv project, this is box64 here (your libatomic seems oudated or something like that, but again, I'm not a maintainer of opencv, there might be other reason).
> 
> can i get the solution from you?

Probably not. I never built opencv, so I cannot really help you. It seems no not find a symbol that should come with `libatomic` maybe you didn't install `libatomic-dev`? That's all I can tell you.

**Comment by Pumpkin040109** [comment]
> > > > would like to ask what wrong above?
> > > 
> > > 
> > > This is a question for the opencv project, this is box64 here (your libatomic seems oudated or something like that, but again, I'm not a maintainer of opencv, there might be other reason).
> > 
> > 
> > can i get the solution from you?
> 
> Probably not. I never built opencv, so I cannot really help you. It seems no not find a symbol that should come with `libatomic` maybe you didn't install `libatomic-dev`? That's all I can tell you.

it's okay, i try to find the solution
