### ISSUE TITLE
Zoom SDK App Segementation fault wiht Box64

### ISSUE THREAD

**Issue by linanw** [ptitSeb/box64#397]
Running into a issue with my app build with zoom sdk. The app is build with amd64, works fine on a PC, but having issue on ARM64 device with Box64. My setup is able to run zoom linux client properly. 

```
Begin to join session...
Using native(wrapped) libasound.so.2
ALSA lib control.c:1471:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:1471:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib control.c:1471:(snd_ctl_open_noupdate) Invalid CTL 
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM 
8209|SIGSEGV @0x64a5398c (???(zoom_v-sdk_linux_bot+0x64a5398c)) (x64pc=0x402d3/???:"???", rsp=0x7fb799fd18, stack=0x7fb71a1000:0x7fb79a1000 own=(nil) fp=0x7fb79a0170), for accessing 0x8 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x2dc1fddb6ca32000 RSP-0x18:0x0000000082b6c2a0 RSP-0x10:0x000000007ee75cf0 RSP-0x08:0x000000000000006c
RSP+0x00:0x0000007fb7b35a2e RSP+0x08:0x0000007fb79a01a8 RSP+0x10:0x00000002828ed918 RSP+0x18:0x00000042828edb38
Segmentation fault
``` 
I did gdb with the core dump, and found below. It seems a issue from Box64, but I'm not sure. Need advices here. Thanks in advice.

![image](https://user-images.githubusercontent.com/4076165/186556575-d79a80e2-885a-4b74-96e4-bdadf90ea0e2.png)

![image](https://user-images.githubusercontent.com/4076165/186563899-65ac7def-fb36-4445-bf35-dc366170ff4a.png)

**Comment by ptitSeb** [comment]
Can you update box64 and try again? It should work now and this ticket can be closed.

**Comment by LukeShortCloud** [comment]
Closing as resolved.
