### ISSUE TITLE
Error during make -j4 

### ISSUE THREAD

**Issue by Spitgrooves** [ptitSeb/box64#400]
Hi,
During the make -j4 command I got this issue :
[  1%] Building C object CMakeFiles/dynarec_native.dir/src/dynarec/arm64/dynarec_arm64_functions.c.o
[  1%] Built target WRAPPERS
In file included from /home/math/box64/src/emu/x64emu_private.h:4,
                 from /home/math/box64/src/dynarec/dynablock.c:10:
/home/math/box64/src/include/regs.h:250:2: error: unknown type name ‘__uint128_t’
  250 |  __uint128_t u128;
      |  ^~~~~~~~~~~
In file included from /home/math/box64/src/dynarec/dynablock.c:16:
....
....
make[2]: *** [CMakeFiles/native_pass1.dir/build.make:95: CMakeFiles/native_pass1.dir/src/dynarec/arm64/dynarec_arm64_emit_tests.c.o] Error 1
make[2]: *** [CMakeFiles/native_pass1.dir/build.make:108: CMakeFiles/native_pass1.dir/src/dynarec/arm64/dynarec_arm64_emit_math.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:163: CMakeFiles/native_pass1.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

I ran the command on a raspberry pi4 with Raspbian GNU/Linux 11 (bullseye)
Do you know where that come from ?

**Comment by ptitSeb** [comment]
you are building box64 on a 32bits OS. Read the README.md and COMPILE.md, you need a 64bits OS.

**Comment by Sangeeth-S-Santhosh** [comment]
Hello,
Sorry for bothering again on this topic..
I have a 64-bit OS (uname -m >> aarch64) and still get this exact error and now I'am stuck at nowhere..not sure if I am doing it wrong or just stupid..
Sorry again if it is an unnecessary discussion topic...

**Comment by ptitSeb** [comment]
you have the error with `unknown type name ‘__uint128_t’` on a 64bits OS?
What OS is this and what compiler are you using?

**Comment by Sangeeth-S-Santhosh** [comment]
Oops ,I'am very sorry for bothering you... 
just learned a new fact that "Uname -m"  indicates your CPU architecture and not actual OS bit version. 
I have bullseye which is indeed 32-bit binary and I was confused with "uname -m >> aarch64" command...yes I was being stupid , but at least learned a new fact..
Again sorry for bothering

**Comment by ptitSeb** [comment]
no problem. learning new thing is makes all this interresting!
