### ISSUE TITLE
I can not run minecraft bedrock dedicated server on android

### ISSUE THREAD

**Issue by ramidep** [ptitSeb/box64#403]
I installed ubuntu on my android device with proot-distro on termux, then i compiled box64 and installed with make install, but when i start the server, it give me an error saying "Error: allocating memory for elf /root/server/bedrock_server"

**Comment by ptitSeb** [comment]
Termux proot is not designed to run emulation stuff. Check Termux issue, it's been mentionned a couple of time I think.
It's not a box64 issue.
