### ISSUE TITLE
Symbol not found (__vfwprintf_chk@GLIBC_2.4)

### ISSUE THREAD

**Issue by AMDBartek** [ptitSeb/box64#404]
When trying to run unrar using box64 I got the following error:
```
root@localhost:~/unrar# ./unrar-nonfree
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
Box64 with Dynarec v0.1.9 b25aa07 built on Sep 12 2022 11:49:59
BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/
BOX64_PATH: ./:bin/                                        
Counted 31 Env var                                         
Looking for ./unrar-nonfree                                
Rename process to "unrar-nonfree"                         
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Error: PltResolver: Symbol __vfwprintf_chk(ver 3: __vfwprintf_chk@GLIBC_2.4) not found, cannot apply R_X86_64_JUMP_SLOT 0x645050 (0x4024d6) in /root/unrar/unrar-nonfree
```
It happens with and without the dynarec enabled.

I know that there is a free and open source RAR package but it doesn't seem to be able to extract my archive (free RAR only supports old RAR archive versions).

**Comment by ptitSeb** [comment]
Symbol not found for ticket 404, seems about right ;)

**Comment by AMDBartek** [comment]
Haha yeah, what a coincidence. It seems to be working but produces weird behaviour. I can't copy it because of the weird characters so I have to screenshot it.

![Screenshot_20220912-142044](https://user-images.githubusercontent.com/46637209/189665357-061a414f-f438-4b3b-839a-254676c7f263.png)

**Comment by ptitSeb** [comment]
Mmmm, bad wrapping I guess. I'll grab a copy of that unrar and reproduce on my side to fix it.

**Comment by AMDBartek** [comment]
OK, thank you though it extracted my file fine.

I got the binary from this deb from the rar website: https://www.rarlab.com/rar/unrar_5.2.5-0.1_amd64.deb

**Comment by ptitSeb** [comment]
The print is fixed now, but, you need to launch with `BOX64_NOBANNER=1 BOX64_LOG=0` or it will print nothing on the screen (it's a libc limitation, cannot switch between non-wide and wide stdout...)

**Comment by AMDBartek** [comment]
OK, it is working fine now, thank you a lot
