### ISSUE TITLE
Duplicate default in USAGE.md

### ISSUE THREAD

**Issue by kujeger** [ptitSeb/box64#405]
https://github.com/ptitSeb/box64/blob/342241a24d4edf5a288d50c5b2bd04fef57a29d9/docs/USAGE.md#box64_dynarec_fastnan

```
#### BOX64_DYNAREC_FASTNAN
Enable/Disable generation of -NAN
* 0 : Generate -NAN like on x86 (Default.)
* 1 : Don't do anything special with NAN, to go as fast as possible (default)
```

Both of these claiming to be the default seems wrong; introduced in https://github.com/ptitSeb/box64/commit/b25aa07e11029a036e0d5fc43183b41d61bf4e13

**Comment by ptitSeb** [comment]
Thanks, it's fixed now, can the ticket be closed?
