### ISSUE TITLE
Crusader Kings II 3.3.3 crashes with invalid opcode

### ISSUE THREAD

**Issue by thaihugo** [ptitSeb/box64#406]
Hi,

trying to run Crusader Kings II 3.3.3 from steam version fail with the following unimplemented Opcode on Raspberry Pi 4. The error happens at soon as a single player game is launched with or without DLC.

Previous 32 versions (3.1.1) do work fully with box86. The current version is 64 bits only and launches with box64.

The same problem happens with Europa Universalis IV 1.32, roughly 3 minutes after launching a game. As Crusader Kings II is free on steam, I thought it would be a better case.

I understand this is something added lately from the developers. I just wanted to document the case, as the emulation is working on previous versions.

would you need a full debug log for his issue?

thanks a lot for all you work.

`2813882|0x7fa4de73aa: Unimplemented Opcode (C9 48 89 02) F0 86 4B 28 48 0F BE E9 40 0F B6 ED 85 ED 74
2814001|SIGSEGV @0x64b59c30 (???(ck2+0x64b59c30)) (x64pc=0x7fa2468bb3/libpops_api.so:"???", rsp=0x7f8425fe48, stack=0x7f84060000:0x7f84260000 own=0x7f84060000 fp=(nil)), for accessing 0x80000 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=0x14f6253
RSP-0x20:0x00000000756b1010 RSP-0x18:0x0000007f8425ff38 RSP-0x10:0x0000007fa27b3a36 RSP-0x08:0x0000000000000000
RSP+0x00:0x0000007fa245996b RSP+0x08:0x0000000000000000 RSP+0x10:0x0000007f8425fef8 RSP+0x18:0x00000000756b1148
Error: PltResolver: Symbol backtrace(ver 3: backtrace@GLIBC_2.2.5) not found, cannot apply R_X86_64_JUMP_SLOT 0x20517a8 (0x8e0876) in /mnt/0DF9-72DB/sources/CrusaderKingsII/game/ck2
2814001|Double SIGSEGV (code=1, pc=0x64b59c30, addr=0x80000)!
`

**Comment by thaihugo** [comment]
I can confirm  the newest build solves the problem. Crusader Kings II vanilla works, some DLC still hang the game but without a message.

Europa Universalis IV latest version needed the same opcode. It is now working fully with DLC too.

For me this issue can be closed.

Thanks a lot for the quick add.

**Comment by ptitSeb** [comment]
Ok, thanks for testing. I close the ticket then.
