### ISSUE TITLE
Open Zoom on box64 from zoom link.

### ISSUE THREAD

**Issue by aneeshlingala** [ptitSeb/box64#407]
I am using a Mediatek MT8183, with Debian 11, and KDE desktop, with a Custom kernel, version 5.19.1-stb-mt8+, when I try to open Zoom in box64 from zoom link, zoom tries to open but gives me this error: Unable to create io-slave. klauncher said: Unknown protocol 'zoommtg'.

**Comment by paulwratt** [comment]
are you sure thats _not_ an XDG configuration issue (like opening `ftp:// ..` in new-ish Chromium)

**Comment by aneeshlingala** [comment]
How do I update it then?

**Comment by ptitSeb** [comment]
I don't think the issue is relevent to box64 here.

Anyway, you should update box64 to latest version , as it support latest zoom release.

**Comment by LukeShortCloud** [comment]
Closing as resolved.
