### ISSUE TITLE
random "Error: PltResolver: Symbol _dl_find_object(ver 18: _dl_find_object@GLIBC_2.35) not found" during minecraft bedrock server execution

### ISSUE THREAD

**Issue by bennasar99** [ptitSeb/box64#410]
I'm trying to run Minecraft bedrock dedicated server on android chroot arm64 and I get the following error, from time to time:

`Error: PltResolver: Symbol _dl_find_object(ver 18: _dl_find_object@GLIBC_2.35) not found, cannot apply R_X86_64_JUMP_SLOT 0x7e319c0120 (0x7e319a4240) in libgcc_s.so.1
`
When it happens, the server freezes.

Is this something I can fix with libraries configuration or is it box64's fault?

Thanks in advance.

**Comment by ptitSeb** [comment]
This is a very recent function (`_dl_find_object` from glibc 2.35 it seems) that is not wrapped in box64 yet. The function is quite complex,, so I can add a dummy quickly but a real wrapped function is way more complicated.

In the mean time, maybe you can try to put an older version of libstdc++ / libgcc_s than the one supplied with the server (like the one supplied with box64). It might work better.

**Comment by bennasar99** [comment]
Well, it seems to work now (with an older version of libgcc), so thanks!

Missatge de ptitSeb ***@***.***> del dia dc., 21 de set. 2022
a les 8:52:

**Comment by m1m1k4tz** [comment]
hello i get a similar issue when trying to run wine on wayland with wow64
`Error: Symbol _dl_find_object not found, cannot apply R_X86_64_JUMP_SLOT @0x10008f398 (0xa736) in /home/alex/wine-dirs/wine64-build/dlls/ntdll/ntdll.so
Error: relocating Plt symbols in elf ntdll.so
Error initializing needed lib ntdll.so
wine: could not load ntdll.so: Cannot dlopen("/home/alex/wine-dirs/wine64-build/dlls/ntdll/ntdll.so"/0x5bdd04b0, 2)
` if i dont run it from box64 ../test/bash it gives me `Looking for /home/alex/wine-dirs/wine64-build/wine64
Not an ELF file (sign=#!/b)
Error: reading elf header of /home/alex/wine-dirs/wine-source/tools/winewrapper, try to launch natively instead
/home/alex/wine-dirs/wine64-build/wine64: line 107: /home/alex/wine-dirs/wine64-build/loader/wine64: cannot execute binary file: Exec format error
/home/alex/wine-dirs/wine64-build/wine64: line 107: /home/alex/wine-dirs/wine64-build/loader/wine64: Success
`

**Comment by LukeShortCloud** [comment]
Closing as resolved.
