### ISSUE TITLE
Artifacting in Karlson Demo

### ISSUE THREAD

**Issue by D2Lx0wse** [ptitSeb/box64#414]
![Istantanea_2022-09-23_20-45-12](https://user-images.githubusercontent.com/92229936/192037848-42c841a0-233b-41d8-98c7-4f254e525d02.png)

Anyone knows a fix?(all settings are at the lowest beside slow mo, motion blur, and another one I can't remember)

**Comment by D2Lx0wse** [comment]
![image](https://user-images.githubusercontent.com/92229936/192039293-183c88c2-0829-41cc-9edb-333e0abebfe8.png)
For context, it should look like this

**Comment by D2Lx0wse** [comment]
![Istantanea_2022-09-23_21-22-51](https://user-images.githubusercontent.com/92229936/192042357-559ab76e-6c13-478a-aac7-09c41223b0be.png)
On the samepi slide in the woods(unity) doesn't artifact at all

**Comment by D2Lx0wse** [comment]
I have a pi 400 and the game runs fine in a vnc in a termux proot environment so it could be a driver issue

**Comment by ptitSeb** [comment]
vnc+termux will run on LLVMpipe I suppose?

**Comment by LukeShortCloud** [comment]
This is an issue with the graphics driver being used by VNC and not Box64 itself. Closing.
