### ISSUE TITLE
Start application with service in Raspberry Pi

### ISSUE THREAD

**Issue by Toernblom** [ptitSeb/box64#416]
Hey, not a bug rather a question. I've tried making a service to launch the application and i can't seem to make it work. Just calling the bash script to launch the app itself is fine but not when making it a service. Is there a recommended way to just boot directly into the application and not see the desktop at all, ever? 

This is my service file, placed in /etc/systemd/system, done daemon-reload and tried starting with systemctl start, aswell as enable and rebooted.
```

[Unit]
Description=Start Unity App

[Service]
ExecStart=/home/pi/Services/run.sh
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=piservice
User=pi
Group=pi
WorkingDirectory=/home/pi/Services

[Install]
WantedBy=basic.targetp

```

**Comment by ptitSeb** [comment]
Not sure the binfmt integration will kick in as a service. Maybe try to explicitly use box86 to launch stuffs?

**Comment by Toernblom** [comment]
Hmm, can't seem to start the application with that service no matter what. 

The shell script is just this for now
`box64 /home/pi/Downloads/New/hmi.x86_64`

Running the script from a terminal is fine and boots.

Doing `sudo systemctl start UnityService.service `  runs successfully but doesn't boot the application

**Comment by ptitSeb** [comment]
I'm not sure I can help here. This doesn't seems to be an issue with box64, unless some function needs wrapping?
I'm not familiar with services, I have no experience in setting up one or anything...

**Comment by thaihugo** [comment]
> Hmm, can't seem to start the application with that service no matter what.
> 
> The shell script is just this for now `box64 /home/pi/Downloads/New/hmi.x86_64`
> 
> Running the script from a terminal is fine and boots.
> 
> Doing `sudo systemctl start UnityService.service ` runs successfully but doesn't boot the application

A service does not run in the same context as your terminal. 
- First, you launch as a system (sudo) user. It is possible the binfmt association is not done in this context.
- Second, most path are defined by your own users variable setting (.profile, .bash). The service context has different path settings. Try to use full path (for example /usr/bin/box64 /home/user/bintorun) before each executable.

There are similar problems running a user program as a service not related to box64. You can try to see if you can read more about it in the docs or on internet.

**Comment by Toernblom** [comment]
Okey thanks for the info! Got it to work by using autostart. However, can't seem to use `MESA_GL_VERSION_OVERRIDE` when using the absolute path to box64. Do i need to specify that in some other way than i normally do by just using
`MESA_GL_VERSION_OVERRIDE=3.2 ./hmi.x86_64` ?

**Comment by Toernblom** [comment]
Fixed by editing `/etc/environment` and making the `MESA_GL_VERSION_OVERRIDE` as a global variable plus calling a bash script with a delay.
