### ISSUE TITLE
Cannot load libraries for the Linux version of Dying Light.

### ISSUE THREAD

**Issue by Hacker1245** [ptitSeb/box64#428]
Trying to run Dying Light (Steam version) with box64 under Mobian results in it failing to load libimagelib, libgamelib and libengine.
![index](https://user-images.githubusercontent.com/29224894/196907480-49638dd2-2ecc-47b6-9f48-469726355b67.png)

**Comment by ptitSeb** [comment]
libjpeg is not wrapped, so you need the x86_64 version of the lib. Use `LD_LIBRARY_PATH` pointing at steam-runtime folders, the x86_64 version should be there somewhere (along libGLEW also)

**Comment by Hacker1245** [comment]
now I have a different issue
![index](https://user-images.githubusercontent.com/29224894/197045152-6ccb6838-73c1-45fc-833b-0a2fe33a0297.png)

**Comment by Hacker1245** [comment]
Here's the rest of the missing wrappers: https://bpa.st/RHMQ

**Comment by ptitSeb** [comment]
Can you update and try again, to see if this ticket can be closed? Check the COMPILE.md also, about Termux.

**Comment by Hacker1245** [comment]
The ticket can be closed.
![Screenshot from 2023-03-09 19-35-51](https://user-images.githubusercontent.com/29224894/224136807-5c677c84-c177-4ff6-9f62-6f0380e14948.png)

Btw, Termux is irrelevant for me as I am running this on a mainline kernel without any Android interference.

**Comment by ptitSeb** [comment]
That's not a very clean picture! But I guess that's a mesa driver issue...

Closing the ticket :)
