### ISSUE TITLE
[emteria installer] xkb_compose_table_new_from_locale 

### ISSUE THREAD

**Issue by sll00** [ptitSeb/box64#431]
Hello, is it possible to get xkb_compose_table_new_from_locale wrapped in xkbcommon? 
I'm unable to pass input to [emteria installer](https://emteria.com/api/installer/Linux/1.1-43) 

`Error: PltResolver: Symbol xkb_compose_table_new_from_locale(ver 10: xkb_compose_table_new_from_locale@V_0.5.0) not found, cannot apply R_X86_64_JUMP_SLOT 0xffff6b1450f8 (0xffff6af42496) in /tmp/.mount_EmteriG6JcPT/usr/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so`

**Comment by ptitSeb** [comment]
The function has been added, you can update and try again

**Comment by sll00** [comment]
Thanks for the swift commit! Unfortunately, seems there's at least one more needed. 

Symbol xkb_compose_state_new

I took a look around for the source to see if we're missing anything else - but unfortunately couldn't find it.

**Comment by ptitSeb** [comment]
Ok, I've added some more function. The app start now.  I didn't try to login, so not sure how it runs after that point.

**Comment by sll00** [comment]
`Symbol xkb_compose_state_feed`

This is new culprit which is blocking keyboard input.

**Comment by sll00** [comment]
` xkb_compose_state_get_status`

**Comment by sll00** [comment]
Though, now I can use mouse input - so this is a great improvement!

**Comment by sll00** [comment]
Keyboard input and login now confirmed working. 

`xkb_compose_state_reset`

This should allow the drop down menus to function.

**Comment by ptitSeb** [comment]
So, all good now? this ticket can be closed?
