### ISSUE TITLE
Failure compiling box64 on Pi 4 x64

### ISSUE THREAD

**Issue by Knightmare-Frame** [ptitSeb/box64#441]
Hello,

So I am following these steps here in order to compile the box64:

https://pimylifeup.com/raspberry-pi-x64/

When I attempt to run the "make" command, it just fails with the following regarding INT128 (warning its quite a large output, ill submit the whole thing via txt file):

[box64 compiler error.txt](https://github.com/ptitSeb/box64/files/9941893/box64.compiler.error.txt)

In file included from /home/pi/box64/src/dynarec/arm64/dynarec_arm64_helper.h:19,
                 from /home/pi/box64/src/dynarec/arm64/dynarec_arm64_emit_tests.c:24:
/home/pi/box64/src/include/../emu/x64primop.h: In function ‘imul64_direct’:
/home/pi/box64/src/include/../emu/x64primop.h:567:2: error: expected expression before ‘__int128’
  __int128 res = (__int128)(int64_t)d * (int64_t)s;
  ^~~~~~~~
/home/pi/box64/src/include/../emu/x64primop.h:569:22: error: ‘res’ undeclared (first use in this function); did you mean ‘rex_s’?
  *res_lo = (uint64_t)res;
                      ^~~
                      rex_s
/home/pi/box64/src/include/../emu/x64primop.h:569:22: note: each undeclared identifier is reported only once for each function it appears in
/home/pi/box64/src/include/../emu/x64primop.h: In function ‘mul64_rax’:
/home/pi/box64/src/include/../emu/x64primop.h:613:11: error: ‘__int128’ is not supported on this target
  unsigned __int128 res = (unsigned __int128)R_RAX * s;
           ^~~~~~~~
/home/pi/box64/src/include/../emu/x64primop.h:613:36: error: ‘__int128’ is not supported on this target
  unsigned __int128 res = (unsigned __int128)R_RAX * s;
                                    ^~~~~~~~
/home/pi/box64/src/include/../emu/x64primop.h:615:40: warning: right shift count >= width of type [-Wshift-count-overflow]
  emu->op1.u64 = R_RDX = (uint64_t)(res >> 64);
                                        ^~
make[2]: *** [CMakeFiles/native_pass0.dir/build.make:76: CMakeFiles/native_pass0.dir/src/dynarec/arm64/dynarec_arm64_emit_tests.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/native_pass0.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

I confirmed that the OS is 100% 64-bit aarch64.

root@dev-rpi02:/home/pi/box64/build# uname -a
Linux dev-rpi02.knightmare.me 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux
root@dev-rpi02:/home/pi/box64/build# lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
Flags:               fp asimd evtstrm crc32 cpuid

Any ideas on how I can get this to compile? It might be worth noting that I just did the x86 using that sites other guide, but then it told me to move to x64 and install it as well, x86 compiling went fine so I am at a loss here.

Thank you!

**Comment by ptitSeb** [comment]
Well, you still seems to be using a 32bits compiler, even if your OS is 64bits. What gcc version are you using?

**Comment by Knightmare-Frame** [comment]
Sorry, not super familiar with Linux compilers, but here is the output for gcc -v

root@dev-rpi01:/home/pi# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran                                                                                                                ,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr                                                                                                                /lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time                                                                                                                =yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --wit                                                                                                                h-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=                                                                                                                release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)
root@dev-rpi01:/home/pi#

**Comment by ptitSeb** [comment]
Yes, it's the 32bits compiler. I don't understand your system, but if `gcc` is 32bits, I think your OS is also 32bits, so box64 will not work there.

**Comment by Knightmare-Frame** [comment]
So I just reimaged the pi, im gonna do the installation and setup of x64 first, then try x86 and see if that works. So far x64 looks to be going now. Its odd, the OS was 100% 64-bit but I guess the installation steps of the x86 version of box caused it to default to 32-bit compiler I guess? I will let you know if that does the trick.

**Comment by Knightmare-Frame** [comment]
That did the trick, the x86 commands had me add archhf which is 32 bit and so after reinstallation of the OS I was able to start with the 64 bit steps first, then x86 with no problem. Thank you!

**Comment by a-oliveira7** [comment]
I was having the same issue, chatgpt has helped me figure out how to fix this. 
When I ran these two, I saw I was on a 64 bit os but using 32 bit gcc. the commands to fix this are:

```sudo apt update```
```sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu```

Next, create a new build directory and run CMake, specifying the 64-bit compiler:

```
cd ~
git clone https://github.com/ptitSeb/box64
cd box64
mkdir build
cd build
export CC=aarch64-linux-gnu-gcc
export CXX=aarch64-linux-gnu-g++
cmake ..
```

After CMake has finished generating the build files, you can compile the project:

```make -j4```

If the build is successful, you should now have a 64-bit version of the box64 binary.

**Comment by inkui** [comment]
Hello.

I still have the same issue. Did exactly what you said, worked perfectly before
make - j4
"Mfloat abi hard selected architecture lacks an FPU"
I feel to stupid for this 😢

**Comment by inkui** [comment]
![17112258848117787867674598828675](https://github.com/ptitSeb/box64/assets/11257132/d3d6f898-51dc-4dda-88c5-f161c8f472d1)

**Comment by d00ugs** [comment]
cmake .. -DRPI5ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo worked for me
