### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by TukangM** [ptitSeb/box64#444]
![image](https://user-images.githubusercontent.com/91467886/200116598-5a09e529-a017-487a-b95b-19e541e9f5d4.png)

idk how uninstall box64
make uninstal?
apt remove box64?
:D

**Comment by ptitSeb** [comment]
remove the binary: `sudo rm /usr/local/bin/box64`

**Comment by TukangM** [comment]
ahh yes. thankyou
