### ISSUE TITLE
Implement xmlSetStructuredErrorFunc

### ISSUE THREAD

**Issue by sean-heller** [ptitSeb/box64#445]
Hi, I'm trying to run an old XML utility, and running into the follow error:

`Using native(wrapped) libxml2.so.2
Using emulated /tmp/PrevueCLI-2.0-Linux/libCYaml.so
Error: PltResolver: Symbol xmlSetStructuredErrorFunc(ver 7: xmlSetStructuredErrorFunc@LIBXML2_2.6.0) not found, cannot apply R_X86_64_JUMP_SLOT 0x7f8d5dc8f0 (0x7f8d5b2506) in /tmp/PrevueCLI-2.0-Linux/libFoundationXML.so
`

I believe this could be fixed if we implemented the function here:
https://github.com/ptitSeb/box64/blob/34355d6b0c537ccdfcfcdb30e8c3e6672a8ee72b/src/wrapped/wrappedxml2_private.h#L996

Any guidance on how to get started doing this?

Thanks!

**Comment by LukeShortCloud** [comment]
The `xmlSetStructuredErrorFunc` function has been wrapped. Closing as resolved.
