### ISSUE TITLE
Python 3.10 missing functions.

### ISSUE THREAD

**Issue by Raezroth** [ptitSeb/box64#446]
I miraculious got gmod running. main menu doesn't work so game has to be loaded through console. I tried the GmodCEFCoded fix which is a ridiculously long ways  away from work. got a python error.
``
raezroth@danctnix:~$ ./GModCEFCodecFix-Linux 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 3be1e33 built on Nov  9 2022 07:03:32
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 26 Env var
Looking for ./GModCEFCodecFix-Linux
Rename process to "GModCEFCodecFix-Linux"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libz.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.9 3be1e33 built on Nov  9 2022 07:03:32
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 29 Env var
Looking for /home/raezroth/GModCEFCodecFix-Linux
Rename process to "GModCEFCodecFix-Linux"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libz.so.1
Using emulated /tmp/_MEIhwiu6q/libpython3.10.so.1.0
Using native(wrapped) libutil.so.1
Using native(wrapped) libm.so.6
Error: Symbol posix_spawn_file_actions_addopen not found, cannot apply R_X86_64_JUMP_SLOT @0xffffbbd07158 (0x5e2b0) in /tmp/_MEIhwiu6q/libpython3.10.so.1.0
Error: Symbol posix_spawnattr_setschedparam not found, cannot apply R_X86_64_JUMP_SLOT @0xffffbbd074a0 (0x5e940) in /tmp/_MEIhwiu6q/libpython3.10.so.1.0
Error: Symbol sched_setparam not found, cannot apply R_X86_64_JUMP_SLOT @0xffffbbd07d88 (0x5fb10) in /tmp/_MEIhwiu6q/libpython3.10.so.1.0
Error: Symbol pthread_getcpuclockid not found, cannot apply R_X86_64_JUMP_SLOT @0xffffbbd07ef0 (0x5fde0) in /tmp/_MEIhwiu6q/libpython3.10.so.1.0
Error: Symbol sem_clockwait not found, cannot apply R_X86_64_JUMP_SLOT @0xffffbbd08358 (0x606b0) in /tmp/_MEIhwiu6q/libpython3.10.so.1.0
Error: Symbol posix_spawnattr_setschedpolicy not found, cannot apply R_X86_64_JUMP_SLOT @0xffffbbd08660 (0x60cc0) in /tmp/_MEIhwiu6q/libpython3.10.so.1.0
Error: Symbol posix_spawnattr_setpgroup not found, cannot apply R_X86_64_JUMP_SLOT @0xffffbbd088a8 (0x61150) in /tmp/_MEIhwiu6q/libpython3.10.so.1.0
Error: relocating Plt symbols in elf libpython3.10.so.1
Error initializing needed lib libpython3.10.so.1
[323682] Error loading Python lib '/tmp/_MEIhwiu6q/libpython3.10.so.1.0': dlopen: Cannot dlopen("/tmp/_MEIhwiu6q/libpython3.10.so.1.0"/0xffffbb875930, 102)``

**Comment by LukeShortCloud** [comment]
I checked all of the missing symbols and confirmed they are now wrapped in Box64. Closing as resolved.
