### ISSUE TITLE
WS4000 on RPi4 Ubuntu MATE

### ISSUE THREAD

**Issue by parandandrd** [ptitSeb/box64#448]
Attempting to run WS4000V4 on an 8GB RPi4 under Ubuntu MATE 22.10. Receive the following error both installing from deb and building from source:

> Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Cores:4
Box64 with Dynarec v0.1.9 d3152469 built on Nov 13 2022 18:00:55
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 55 Env var
Looking for WS4000v4
Rename process to "WS4000v4"
Using emulated libfmod.so.9
Using native(wrapped) libcurl.so.4
Using native(wrapped) librt.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libX11.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libasound.so.2
Error loading needed lib libX11-xcb.so
Warning: Cannot dlopen("libX11-xcb.so"/0x8a1502, 101)
Using native(wrapped) libGL.so.1
Using native(wrapped) libEGL.so.1
Using native(wrapped) libvulkan.so.1
memset
glfwdestroywindow
glfwdestroycursor
glfwplatformsetgammaramp
glfwTerminateVulkan
glfwFreeMonitors
glfwPlatformTerminate
XFreeCursor
free(_glfw.x11.clipboardString)
XCloseIM(_glfw.x11.im)
_glfwTerminateEGL()
XCloseDisplay(_glfw.x11.display)
_glfwTerminateGLX()
_glfwTerminateJoysticksLinux()
_glfwTerminateThreadLocalStoragePOSIX()
memset

**Comment by ptitSeb** [comment]
install libX11-xcb, it's missing from your system (this is a wrapped lib, so the one from your system will be used)

**Comment by LukeShortCloud** [comment]
Installing `libX11-xcb` should fix this issue. Closing as resolved.
