### ISSUE TITLE
On archlinuxarm binfmt is messed up

### ISSUE THREAD

**Issue by Rippanda12** [ptitSeb/box64#450]
``` cat /proc/sys/fs/binfmt_misc/x86_64 
enabled
interpreter /usr/local/bin/box64
flags: 
offset 0
magic 7f454c4602010100000000000000000002003e00
mask ffffffffffffff00000000fffffffffffeffffff
```
yet /usr/local/bin/box64 doesn't exist

**Comment by ptitSeb** [comment]
Why `/usr/local/bin/box64` doesn't exist? you didn't installed it there?

**Comment by Rippanda12** [comment]
i used the pkgbuild

**Comment by Jai-JAP** [comment]
The issue is that on arch box is installed at /use/bin/box** but binfmt still is redirecting to /usr/local/bin/box**

I will fix the issue soon.
