### ISSUE TITLE
recent zoom client not working

### ISSUE THREAD

**Issue by gadido30** [ptitSeb/box64#451]
Hi All

I have downloaded latest zoom client, 
When I tired to run zoom client , it show an error: "libffmpeg.so" is missing, any idea?

The old zoom client work perfect

**Comment by theofficialgman** [comment]
don't cross list on box64 (from pi-apps). this isn't a box64 issue and is an issue caused by upstream zoom that needs pi-apps packaging changes

**Comment by ptitSeb** [comment]
Please update to latest box64 version and try again, it should work now, and this ticket can be closed.

**Comment by LukeShortCloud** [comment]
Closing as resolved.
