### ISSUE TITLE
Compile Issues on Slarm64-15.0

### ISSUE THREAD

**Issue by BusinessKid** [ptitSeb/box64#456]
I tried this on  a RazPI 4B running slarm64 using kernel 5.16.7 and the headers are a disaster. I quickly fell into a pattern of
1. make -j4 > ../../box64.err 2>&1
2. less ../../box64.err & note missing header.
3. locate <missing header>
4. sudo ln -s misplaced/missing header --> desired location
5. make -j4 > ../../box64.err 2>&1, etc...

I very quickly linked /usr/include/asm --> /usr/include/asm-generic. After about 30 iterations of these steps above, I got fed up, and used lndir to link /usr/include/asm & /usr/include/linux to the kernel source equivalents, but that's caused problems.  So I'll backtrack and remove my symlinks. Have you a precompiled version about? 

You can get slarm64 (an unofficial slackware64 distribution on Aarch64) from slarm64.org or slackware.uk/slarm64. There are binary images and good support on linuxquestions.org, where it has a forum (under distributions.

**Comment by BusinessKid** [comment]
EDIT:  I removed all symlinks in /usr/include/linux, and continued. After putting 6 or so back, I came ground to a halt on /usr/include/linux/init.h which throws errors. I'm no programmer, so it's over to you.

**Comment by ptitSeb** [comment]
Box64 use standard linux path and should compile on any linux system. If it doesn't, check your distrib maintener, it's not box64 fault.
There are binary generated for each commit: select the check mark of the last commit, choose "Detail" of one of the entry, then on the new screen, use "Summary" on the up left. Now, scrool down, you'll see box64 binary for each configuration built.

**Comment by BusinessKid** [comment]
You were right on the icludes. A lot of the headers from /usr/src/linux/arch/arm64/include were AWOL, so I sent the maintainer an exact list of how I corrected the situation. He is expert at porting x86_64 packages to Aarch64, but this was the fiorst serious Arm64 package that had been tried, I get the impression.

 

I played with it for a while last night. It ran without crashing for 10 minutes last night, drew the border of the zoom opening dialogue, but never progressed and remained maxed out on cpu. Ideas welcome. I have box64 and ZoomLauncher each with separate logfiles. My idea is to install native copies of everything that the system is emulating. Linux-x86_64 is what I'll install. If I need windows ones, please shout!  

 
 

Sent: Sunday, November 27, 2022 at 9:12 AM
