### ISSUE TITLE
Zoom - reduce  memory overhead?

### ISSUE THREAD

**Issue by BusinessKid** [ptitSeb/box64#461]
I now have the Linux-x86_64 Zoom working on a Slarm64 (=Slackware64 Aarch port) on a RazPi 4 w/4G. I had to load a swap file, as the memory exceeded 4G during startup. Sound is yet to test

If it's emulating a library, that uses more ram. How can I find what libraries box64 is emulating? Also, is this line ok?
/path/to/box64 /path/to/ZoomLauncher >~/ZoomLauncher.err 2>&1

I suddenly stopped getting output.

**Comment by ptitSeb** [comment]
Yes, your command line is fine. But sometimes, program just play with the stdout/stderr, so you don't have logs directly.
If you just want box logs, you can use `BOX64_TRACE_FILE=trace.txt`

To see if a lib is native or emulated, just look at box64 log. Not that is you redirect stdout, box64 will be silent. But you can force it to have log with `BOX64_LOG=1`

Be sure to use latest box64, it should have less memory footprint. But still, it use more memory than usinng native libs yes.

**Comment by BusinessKid** [comment]
Thanks.I'll use $BOX64_TRACE_FILE. My Zoom works but the audio is terrible. The video is top class (on hdmi). I'll minimise emulation. I'm an invalid, and it's a slow process for me, but I'll get there. Box64 is a lot less paranoid & hysterical than wine!
