### ISSUE TITLE
Performance profiling?

### ISSUE THREAD

**Issue by voltagex** [ptitSeb/box64#462]
Is it possible to run some kind of profiling to see where box64 is slowing down? Running bedrock_server is extremely slow on initial connection from a client.

**Comment by ptitSeb** [comment]
Not for now.
But you can use `BOX64_DYNAREC_LOG=1` and see if you see that Dynarec stopped because of a missing opcode.

**Comment by LukeShortCloud** [comment]
If you need any more help with profiling, please let us know. Closing as resolved.
