### ISSUE TITLE
No logs, No/low sound under Aarch64

### ISSUE THREAD

**Issue by BusinessKid** [ptitSeb/box64#463]
Because I wanted to make room on / for a swapfile, I removed the something of value and ended restoring a backup. Logs vanished after the first time I set BOX64_LOG=2 and never returned. I'm pretty sure that's coincidence. 

On my backup, there never was any trace log kept. Can you spot errors in this script?
`#!/bin/bash

BOX64_LOG=1
BOX64_LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:/usr/lib/x86_64
BOX64_PATH=/opt/zoom/:$PATH
BOX64_DYNAREC_LOG=2
BOX64_TTRACE_FILE=/home/dec/box64.err
#export $BOX64_LOG $BOX64_LD_LIBRARY_PATH $BOX64_PATH $BOX64_DYNAREC_LOG

cd /opt/zoom 
/usr/local/bin/box64 /opt/zoom/ZoomLauncher 
`
If I uncomment the 'export' line, the script spits syntax errors at me. The memory stays pretty full (≅3.3G vs ≤1.5G normally). My only approach was to run down some of those libraries that were being emulated. From the few logs I got, I spotted some libraries were native, others (a lot) were emulated. What does this mean exactly? You've no VM there.
Anyhow, I got busy with text mangling tools, and this is the list box64 says it's emulating. There is repetition. I'll finish with that list, but any ideas to improve the sound are welcome. I'll try it on a regular meeting tmw as I'm doing upstairs/downstairs test meetings and that sucks when you're an invalid. 
[https://pastebin.com/P31e2dea](url)

**Comment by ptitSeb** [comment]
I don't think you want `BOX64_DYNAREC_LOG=2` but `BOX64_LOG=2` instead right?

Also, it's `BOX64_TRACE_FILE` not `BOX64_TTRACE_FILE` (notice the double T)

**Comment by BusinessKid** [comment]
Well, there's a broad smile on my face here as I write this. I tried the RazPi on a regular meeting. Sound was lower than normal, video was good, and it was an enjoyable experience. This is a big deal for me as I'm getting our religious meetings over Zoom at the moment. I can sit and watch them on the main tv in the front room with my wife. These days, I can't even carry a laptop about. If everything stays as is, I can use this.

**Comment by BusinessKid** [comment]
Just FYI, I solved the memory problem. Versions-5.10.x and above are about twice the size of version 5.9.x. Zoom's share price is dropping as the pandemic situation normalises, so they are adding features in an attempt to boost sales. With zoom 5.9.x and earlier (I presume) memory foorprint is only about 2 Gigs.

 

It gives an insight into windoze programming techniques - the best part of 2 Gigs sitting in ram doing nothing! If you overdrive sound to about 120% in pavucontrol's playback & output devices tabs, sound comes through without distortion.

 

ls -lh /mnt/hd/LinuxArchives/zoom*
-rw-r--r-- 1 dec users 125M Jun 12 12:31 /mnt/hd/LinuxArchives/zoom-5.10.7-x86_64.tar
-rw-r--r-- 1 dec users 137M Nov 28 10:11 /mnt/hd/LinuxArchives/zoom-5.12.6.173-x86_64.tar.xz
-rw-r--r-- 1 dec users 126M Jul 27 11:37 /mnt/hd/LinuxArchives/zoom_x86_64-5.11.3-3882.tar
-rw-r--r-- 1 dec users  55M Feb  4  2022 /mnt/hd/LinuxArchives/zoom_x86_64-5.9.3-1911.tar
 

--

Regards

 

The Business Kid.

 
 

Sent: Saturday, December 03, 2022 at 7:40 PM
