### ISSUE TITLE
Steam bad GLX context after recent libxcb_render update

### ISSUE THREAD

**Issue by Raezroth** [ptitSeb/box64#469]
After updating to the latest commit, Steam now refuses to connect to x11. 

Steam Log :: 
[steam.log](https://github.com/ptitSeb/box64/files/10170110/steam.log)

I will see if I can force it with some environment variables.

**Comment by ptitSeb** [comment]
steam is 32bits process, and so run with box86. Chnages to box64 will not affect it (only the "steamwebhelper is a 64bits porcess, but it doesn't run for now anyway and is disabled with box64).

You issue is not related to box64 latest changes.

**Comment by ptitSeb** [comment]
please update both box86 and box64 to latest version (and read box86-s README.md about Steam).
If you are on Termux, check BAD_SIGNAL on COMPILE.md

Steam should work now.

**Comment by Raezroth** [comment]
After updating bookworm it fixed itself
