### ISSUE TITLE
Evoland: Legendary Edition

### ISSUE THREAD

**Issue by Firlaev-Hans** [ptitSeb/box64#47]
It's a Steam game with Steamworks DRM, so I had to use the Goldberg Emu. Don't tell anyone ;-)
The game always segfaults on launch, though the output seems to be a little different every time, so I have two logs right here:

[Evoland_box64.log](https://github.com/ptitSeb/box64/files/6795953/Evoland_box64.log)
[Evoland_box64_2.log](https://github.com/ptitSeb/box64/files/6795955/Evoland_box64_2.log)

From second log:
```
9994|SIGSEGV @0x990438a0 (???(0x990438a0)) (x64pc=0x7f87366cb7/???:"???", rsp=0x7f8cb5af20, stack=0x7f8c35d000:0x7f8cb5d000 own=(nil) fp=0x7), for accessing 0xffffffff96370a98 (code=1/prot=0), db=0x994e8960(0x99043880:0x990438e4/0x7f87366ca4:0x7f87366cc5/???:clean, hash:1d809688/1d809688) handler=0x7f8ccfdc90
SIGNAL 11
fun$13881(h2d/Sprite.hx:0)
9994|SIGSEGV @0x7f8d186138 (gsignal (/lib/aarch64-linux-gnu/libc.so.6)) (x64pc=0x9410bf73/???:"???", rsp=0x7f8cb5ae80, stack=0x7f8c35d000:0x7f8cb5d000 own=(nil) fp=0x7), for accessing 0x3e80000270a (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
```

**Comment by rajdakin** [comment]
Does it work now?

**Comment by Firlaev-Hans** [comment]
> Does it work now?

No, still fails to launch.

**Comment by Firlaev-Hans** [comment]
Just in case it is helpful here's another log with BOX64_DLSYM_ERROR=1:
[dlsym_log.txt](https://github.com/ptitSeb/box64/files/7109682/dlsym_log.txt)

**Comment by ptitSeb** [comment]
strange crash. I don't think I've seen something built with haxel run with box64 yet. I think I have this one on my collection, I'll try to install it to test on my side.

**Comment by Firlaev-Hans** [comment]
I gave this one another try today on my Jetson Nano. It launches now, although it takes rather long to do so.
_Evoland: Legendary Edition_ bundles Evoland 1 & 2 in one executable.
Evoland 1 appears to be fully playable, but Evoland 2 just... hangs? It's not like the game fully freezes, but... you can't do anything except open and the menu, you can't move.

As a side note, for anyone looking to play this on ARM: if you own the original releases of Evoland 1 & 2, which were made with Adobe AIR, you can:
1. Simply run those with box86+wine, if running 32 bit apps is an option for you.
2. Find a 64 bit AIR runtime by HARMAN and run it with box64+wine, if you can't run 32 bit apps.
3. Use [Lightspark](https://github.com/lightspark/lightspark), an open source reimplementation of Adobe Flash/AIR which you can compile natively for arm64. Evoland 1 should be fully playable with only a few glitches this way, but Evoland 2 still has significant issues that prevent it from being playable in Lightspark.

**Comment by Firlaev-Hans** [comment]
The game seems to work fine now. I tried in on an Acer Aspire 1 (Snapdragon 7c / Adreno 618). It launches quickly, performs well and doesn't hang.
