### ISSUE TITLE
job for systemd-binfmt.service failed because the control process existed with err or code.

### ISSUE THREAD

**Issue by gonovar** [ptitSeb/box64#470]
thats what i got when trying to download box64. ive been working on this chromebook to do something for almost a month now. if i can just get it to play the might and magic games id be happy.

**Comment by ptitSeb** [comment]
bifmt integration will probably not work there. But you can run stuff without it. Just use `box64` in front of everything you want to run and it should work
For shell script, you also need to define `BOX64_BASH=~/box64/tests/bash` env. var. (if you build box64 from source using the COMPILE.md doc, else you'll have to adapt the path)

**Comment by p0358** [comment]
So for this to work, you need `binfmt_misc` module in the kernel. It's likely that Chromebooks don't have it in their kernel. If you're using a custom kernel/build, same thing applies. For example I use this one and I see there's an issue there for this module missing there too: https://github.com/hexdump0815/imagebuilder/issues/24

You can check with `lsmod | grep binfmt` if you have it, if nothing gets printed then it's missing

**Comment by LukeShortCloud** [comment]
This is an issue with ChromeOS and not Box64. Closing.
