### ISSUE TITLE
Wine64 install guide?

### ISSUE THREAD

**Issue by GreatHaop** [ptitSeb/box64#471]
in README.md

> I tested Wine 7.5 64bits and it worked, but more recent version will probably just not work yet.

Is there an installation guide for it?

**Comment by ptitSeb** [comment]
Extract to `~wine` then create those symlink;
```
sudo ln -s ~/wine/bin/wine /usr/local/bin/wine
sudo ln -s ~/wine/bin/wineserver /usr/local/bin/wineserver
sudo ln -s ~/wine/bine/wineboot /usr/local/bin/wineboot
sudo ln -s ~/wine/bin/wine64 /usr/local/bin/wine64
sudo ln -s ~/wine/bin/winecfg /usr/local/bin/winecfg
```

**Comment by GreatHaop** [comment]
> Extract to ~wine then create those symlink;

extract wine-i386:i386 and wine:amd64?

**Comment by GreatHaop** [comment]
I can't find wine64 in wine-staging_7.5:amd64 for some reason

**Comment by mio-19** [comment]
> Extract to `~wine` then create those symlink;
> 
> ```
> sudo ln -s ~/wine/bin/wine /usr/local/bin/wine
> sudo ln -s ~/wine/bin/wineserver /usr/local/bin/wineserver
> sudo ln -s ~/wine/bine/wineboot /usr/local/bin/wineboot
> sudo ln -s ~/wine/bin/wine64 /usr/local/bin/wine64
> sudo ln -s ~/wine/bin/winecfg /usr/local/bin/winecfg
> ```

What deb packages should be used?

**Comment by ksco** [comment]
> What deb packages should be used?

You can use the ones built by PlayOnLinux: https://www.playonlinux.com/wine/

**Comment by LukeShortCloud** [comment]
The latest recommended is to use Wine builds from here:

https://github.com/Kron4ek/Wine-Builds/releases

Extract the archive, `cd` into it, and then use `box64 ./bin/wine64 notepad.exe` as a test.

Closing as resolved.
