### ISSUE TITLE
Debian package?

### ISSUE THREAD

**Issue by BusinessKid** [ptitSeb/box64#481]
This thing is based on Debian, right? Have you a Debian package anywhere? One that automagically pre-installs dependencies?
It should be better on zoom.

**Comment by ptitSeb** [comment]
Look at the first chapter of the [docs/COMPILE.md](docs/COMPILE.md) there is a deb build by someone else.

**Comment by BusinessKid** [comment]
Thanks. I just zapped an sdcard for Debian for the graphics. I want to get zoom sucking diesel by tonight, but  the RazPi OS (/etc/debian-version = 11.5) is all jammy side down still. I have that on my RazPi 4, but no sshd set up yet :-(.
