### ISSUE TITLE
Not issue! Just Request!

### ISSUE THREAD

**Issue by Saikatsaha1996** [ptitSeb/box64#489]
Dear developer!

Happy New year 🎉

I have a request for Android community!

Can you add support for Android aarch64 application with `box64` & `box86` ?

If yes it will very helpful for `Android` users..
Like Android has old `exagear emulator` but it only supported `x86` platform and only can run `32bit` exc..

If you add Android application with box64 & box86
So we can develop a good Android emulator community with x64 & x86 `Boxemulator` Android..

I hope you can understand..
Source code exagear

https://github.com/akbarri/ExaGear-SU
Just for example & development purpose only..

Thank you
Regards
Saikat Saha

**Comment by ThieuMinh26** [comment]
Sound nice but impractical as wine on android is still a mess . Better use proot + wine  , also you can use fex-emu in proot too . tldr ; you just need modded termux that contain only proot , pulse audio , vnc , zink to so that termux is not in background so it cant be killed by phantom process killer

**Comment by ThieuMinh26** [comment]
The rest will be the same as using linux . We just need a proot distro with built-in vnc display

**Comment by Saikatsaha1996** [comment]
> The rest will be the same as using linux . We just need a proot distro with built-in vnc display

Yes already tried but not useful with vnc + proot-distro..

Android screen is small when you trying something you should have hardware mouse & keyboard..

That's why if you have apk like exagear it will very much useful.. no need to vnc or SDL x11 extra application..

And also it will help to install 64 bit & 32 bit windows application..

Just need to create exagear types apk with box86 & box64 ..

I don't have skills for Android development..
But i understand it is tough but we should work together.. need contirbuter..
Mey be i can arrange some contributor from exagear community..

**Comment by ThieuMinh26** [comment]
Also we dont have box32 yet . Android and arm is ditching 32bit support  , making box86 useless

**Comment by Saikatsaha1996** [comment]
> Also we dont have box32 yet . Android and arm is ditching 32bit support , making box86 useless
https://github.com/ptitSeb/box86
