### ISSUE TITLE
Help wanted with application

### ISSUE THREAD

**Issue by Saikatsaha1996** [ptitSeb/box64#492]
I am trying to run Android ndk with box64 it's working only targeted version when `x86_64-unknown-linux-gnu`

But not working with `aarch64-linux-android`

Any solution please?

![Screenshot_2023-01-04-07-56-03-199_tech ula](https://user-images.githubusercontent.com/72664192/210473420-96f06eae-95cb-474f-8a8b-433f55bd29d7.jpg)

**Comment by fish4terrisa-MSDSM** [comment]
Dont use box64 to run ndk , [Lzhiyong/termux-ndk](https://github.com/Lzhiyong/termux-ndk) is what you are looking for.
