### ISSUE TITLE
Error loading needed lib libjack.so.0

### ISSUE THREAD

**Issue by michele-perrone** [ptitSeb/box64#495]
Hi all, first of all I want to make my compliments to the developers of box64. It's amazing to have it.

To my issue: I'm trying to install [`wineasio`](https://github.com/wineasio/wineasio), and I need to register the `wineasio.dll` library with this command:
```
wine64 regsvr32 /home/michele/wine-staging-7.22-1-x86_64/usr/lib/wine/x86_64-windows/wineasio.dll
```

However, the command fails with the following output:
```
Using emulated /home/michele/wine-staging-7.22-1-x86_64/usr/lib/wine/x86_64-unix/wineasio.dll.so
Error loading needed lib libjack.so.0
Error loading one of needed lib
Error initializing needed lib wineasio.dll.so
0118:err:module:open_builtin_so_file failed to load .so lib "/home/michele/wine-staging-7.22-1-x86_64/usr/lib/wine/x86_64-unix/wineasio.dll.so"
regsvr32: Failed to load DLL '/home/michele/wine-staging-7.22-1-x86_64/usr/lib/wine/x86_64-windows/wineasio.dll'
```

My specs:
* Raspberry Pi 4B, 2GB RAM
* Manjaro ARM
* Wine Staging 7.22
* box64 0.2.0

I have `/usr/lib/libjack.so.0` installed. Why can't `box64` find it?

**Comment by louisnw01** [comment]
@michele-perrone I'm also having the same issue; did you find a fix?
