### ISSUE TITLE
MC bedrock spam curl_easy_setopt 

### ISSUE THREAD

**Issue by QuintenQVD0** [ptitSeb/box64#497]
I am trying to run a bedrock server but I get this:

![afbeelding](https://user-images.githubusercontent.com/67589015/212474303-1a25c953-cac2-4281-ae24-045ed7fb4e0a.png)

the `Warning, call to __cxa_thread_atexit_impl(0x5a09560, 0xffff5401b668, 0x6d16008) ignored` are fine but the console gets spamed with 

I have this on ubuntu 20.04 and debian 11

`Error: unimplemented option 20094 in curl_easy_setopt`

**Comment by ptitSeb** [comment]
Yeah, I ned to add support for this value.

**Comment by tristanmorgan** [comment]
I find if I disable the `emit-server-telemetry` it stops the error message. (and then complains about telemetry being disabled).

**Comment by ptitSeb** [comment]
ah, just when I added the missing function...

**Comment by tristanmorgan** [comment]
I'll still test this out when [ryanfortner](https://github.com/ryanfortner)'s pipeline builds new debs.

**Comment by QuintenQVD0** [comment]
Thank you!

I can confirm that the console spam is now gone:
![afbeelding](https://user-images.githubusercontent.com/67589015/213907952-eb96332a-7f05-403e-a2ec-162f4f032882.png)
