### ISSUE TITLE
does box64 run native on android environtment?

### ISSUE THREAD

**Issue by TukangM** [ptitSeb/box64#498]
im wanted to compile box64 both box86 for rooted android phone (as magisk module). if possible just place box86 64 binary to /usr/bin (i forgot the path)?

 why me ask this. me using proot (busybox - linux deploy ubuntu 22.04), kalilinux nethunter root(proot - magisk module) and termux-proot(many limitation) have common issue when run bds server and wine slow when run with box64 (kali linux nethuner have wine 5.0 much stable on arm64)

**Comment by fish4terrisa-MSDSM** [comment]
box64 runs in proot environment,but it is impossible to complie for android natively now (due to some differents between   Gnu libc and Bionic libc)

**Comment by TukangM** [comment]
oh yeah thanks for the help

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/235980923-c5222cd5-b0a5-4f58-a8f5-ebf1b2d49af3.png)
oh yeah. it does
