### ISSUE TITLE
Illegal instruction 

### ISSUE THREAD

**Issue by davidzengxhsh** [ptitSeb/box64#504]
Hi, Folks

I am running a test using box64. The binary is built on x86. Most of the tests are working well and the performance looks good. But there is one test failed with "Illegal instruction".
Here is the full output:

Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:80
Params database has 14 entries
Box64 with Dynarec v0.2.1 d1f63fe2 built on Jan 30 2023 01:32:10
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 39 Env var
Looking for ./gcc-x64
argv[1]="test.c"
argv[2]="-o"
argv[3]="test.s"
Rename process to "gcc-x64"
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
449170|SIGILL @0xc1e230 (???(0xc1e230)) (x64pc=0x50113/???:"???", rsp=0xffffbe8beeb8, stack=0xffffbe0c2000:0xffffbe8c2000 own=(nil) fp=0x751e9038), for accessing 0xc1e230 (code=1/prot=87), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x00000000751e9038 RSP-0x18:0x0000000075224940 RSP-0x10:0x0000000075158ab0 RSP-0x08:0x0000000000000006
RSP+0x00:0x0000000000437237 RSP+0x08:0x0000ffffbe8bef30 RSP+0x10:0x0000000000484c3e RSP+0x18:0x0000ffffbe8bf0c8 opcode=48 85 FF B8 01 00 00 00 (C3 00 00 00 00)
Illegal instruction (core dumped)

If my understanding is correct, the illegal instruction is reported against opcode C3. 
But i checked the code, C3 is already implemented in Dynarec:
https://github.com/ptitSeb/box64/blob/dd111f55f6e846be683b248cd8d76cdc1c621f12/src/dynarec/arm64/dynarec_arm64_00.c#L1592

Is there anything wrong here?

**Comment by ptitSeb** [comment]
The SIGILL is probably a consequence of something else going wrong here. Can you run with `BOX64_ROLLING_LOG=1` to see what are the latest wrapped function call, as it maybe an issue with one.

**Comment by davidzengxhsh** [comment]
This is the log with BOX64_ROLLING_LOG=1:
`Rolling log, showing last 16 function call on signals
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:80
Params database has 14 entries
Box64 with Dynarec v0.2.1 d1f63fe2 built on Jan 30 2023 01:32:10
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 39 Env var
Looking for ./gcc-x64
argv[1]="test.c"
argv[2]="-O3"
argv[3]="-finline-limit=0"
argv[4]="-fif-conversion"
argv[5]="-fif-conversion2"
argv[6]="-o"
argv[7]="test.s"
Rename process to "gcc-x64"
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Last calls
466304|0xcf79ce: Calling calloc (./gcc-x64)(0x1, 0x40, 0x41, ...) => return 0x61FC7C80
466304|0xbcc3e6: Calling ???(/lib64/libc.so.6+0xffff89868480)(0x61FBC000, 0x0, 0x820, ...) => return 0x61FBC000
466304|0xbcb708: Calling ???(/lib64/libc.so.6+0xffff89868480)(0x61FB8320, 0x0, 0x28, ...) => return 0x61FB8320
466304|0xbcb708: Calling ???(/lib64/libc.so.6+0xffff89868480)(0x61FB3900, 0x0, 0x30, ...) => return 0x61FB3900
466304|0xbd3819: Calling strlen (/lib64/libc.so.6)("cleanup") => return 0x7
466304|0x530a8a: Calling memcmp (/lib64/libc.so.6)(0x61F7CB60, 0xFFFF86C4C3B8, 0xD, ...) => return 0x0
466304|0x530d2a: Calling memcmp (/lib64/libc.so.6)(0x61F2B678, 0xFFFF86C4C3C6, 0x5, ...) => return 0x0
466304|0xbcb708: Calling ???(/lib64/libc.so.6+0xffff89868480)(0x61F16200, 0x0, 0x40, ...) => return 0x61F16200
466304|0x530a8a: Calling memcmp (/lib64/libc.so.6)(0x61F37618, 0xFFFF86C4C3D0, 0x13, ...) => return 0x0
466304|0x530d2a: Calling memcmp (/lib64/libc.so.6)(0x61DD2218, 0xFFFF86C4C3E7, 0x6, ...) => return 0x0
466304|0xca408c: Calling ???(/lib64/libc.so.6+0xffff89867950)(0x61E0A86A, 0xFFFF86C4C3F0, 0x2, ...) => return 0x61E0A86A
466304|0x530d2a: Calling memcmp (/lib64/libc.so.6)(0x61DD21B8, 0xFFFF86C4C3F6, 0x6, ...) => return 0x0
466304|0x530a8a: Calling memcmp (/lib64/libc.so.6)(0x61F37618, 0xFFFF86C4C3FE, 0x13, ...) => return 0x0
PltResolver  => return 0x61E29B00
466304|0x437237: Calling my__obstack_newchunk (./gcc-x64)(0xF7A540, 0x38, 0x38, ...) => return
466304|0x65435e: Calling free (./gcc-x64)(0x61FC7C80, 0xC, 0x41, ...) => return 0xF743E8
466304|SIGILL @0xc1e230 (???(0xc1e230)) (x64pc=0x50113/???:"???", rsp=0xffff88c93e58, stack=0xffff88497000:0xffff88c97000 own=(nil) fp=0x61dcb038), for accessing 0xc1e230 (code=1/prot=87), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000000061dcb038 RSP-0x18:0x0000000061e06460 RSP-0x10:0x0000000061d3a670 RSP-0x08:0x0000000000000006
RSP+0x00:0x0000000000437237 RSP+0x08:0x0000ffff88c93ed0 RSP+0x10:0x0000000000484c3e RSP+0x18:0x0000ffff88c94068 opcode=48 85 FF B8 01 00 00 00 (C3 00 00 00 00)
Illegal instruction (core dumped)
`

**Comment by ptitSeb** [comment]
Yeah, so issue will be the wrapped `_obstack_newchunk(...)`. I need to analyse what that function is supposed to do and check with what the wrapper is actually doing.

**Comment by ptitSeb** [comment]
I tried some fix, can you update box64 and try again?

**Comment by davidzengxhsh** [comment]
Tried with the latest code, issue fixed. 
Thanks!
