### ISSUE TITLE
bizhawk cant load roms

### ISSUE THREAD

**Issue by InfamousKnight** [ptitSeb/box64#506]
Using snapdragon 845 build because I'm using android with Ubuntu on vnc.

i tried running bizhawk on box64 and got this far:

ubuntu@localhost:~$ box64 '/home/ubuntu/Downloads/BizHawk_devbuild_b1e8d93f/EmuHawkMono.sh' 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:8
Params database has 15 entries
Box64 with Dynarec v0.2.1 87b66b8d built on Feb  2 2023 14:42:47
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 44 Env var
Looking for /home/ubuntu/Downloads/BizHawk_devbuild_b1e8d93f/EmuHawkMono.sh
Not an ELF file (sign=#!/b)
Error: reading elf header of /home/ubuntu/Downloads/BizHawk_devbuild_b1e8d93f/EmuHawkMono.sh, try to launch natively instead

depencies needed to run bizhawk: libc6-dev libopenal1 mono-complete

program opens up fine, its just when you load a rom, the program opens an error message saying core accepted the rom but threw an exception.

i think it might be because box64 doesnt load .so files?

**Comment by fish4terrisa-MSDSM** [comment]
Please dont use box64 to run shell script.Edit the shell script and use box64 to load the binary.

**Comment by InfamousKnight** [comment]
ok, i ran emuhawk.exe without box64 and the program opens but i still cant open roms

so when i ran it through box64, it crashed with this:


ubuntu@localhost:~$ box64 '/home/ubuntu/Downloads/BizHawk_devbuild_b1e8d93f/EmuHawk.exe' 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:8
Params database has 15 entries
Box64 with Dynarec v0.2.1 87b66b8d built on Feb  2 2023 14:42:47
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 46 Env var
Looking for /home/ubuntu/Downloads/BizHawk_devbuild_b1e8d93f/EmuHawk.exe
Not an ELF file (sign=MZ�)
Error: reading elf header of /home/ubuntu/Downloads/BizHawk_devbuild_b1e8d93f/EmuHawk.exe, try to launch natively instead
/home/ubuntu/Downloads/BizHawk_devbuild_b1e8d93f/EmuHawk.exe: 1: MZ����@���: not found
/home/ubuntu/Downloads/BizHawk_devbuild_b1e8d93f/EmuHawk.exe: 2: Syntax error: word unexpected (expecting ")")
ubuntu@localhost:~$

**Comment by fish4terrisa-MSDSM** [comment]
EmuHawk.exe is an windows exe binary,box64 cant run it.

**Comment by ptitSeb** [comment]
If you want to run shell script with box64, you need to setup `BOX64_BASH` env. var.

To run exe file, you probably need Wine.

The error on load rom: does it write anything on the console?

**Comment by InfamousKnight** [comment]
No, nothing is written on console

**Comment by ptitSeb** [comment]
Well, console are maybe redirected?
Youc an use `BOX64_TRACE_FIILE=log.txt` to redirect all box64 log to 1 file (I assume only 1 process is launched with box64 here).

**Comment by InfamousKnight** [comment]
How would i do that?

**Comment by InfamousKnight** [comment]
ok, i tried that, and nothing is written to the log file..

im guessing it might be because i didnt run sudo systemctl restart systemd-binfmt after installing box64

**Comment by ptitSeb** [comment]
I don't think binfmt integration doesn't work on proot, so it will probably change nothing.

**Comment by ptitSeb** [comment]
Maybe add `BOX64_LOG=1 BOX64_DLSYM_ERROR=1 BOX64_SHOWSEGV=1` in front of the command line

**Comment by InfamousKnight** [comment]
I redid my entire setup with this https://github.com/TecnicalBot/modded-distro and now it's even less functional.. it says no sound device and literally nothing shows on the screen. No OSD like fps. It uses a null hawk for no core loaded.. and I don't know what to do..

**Comment by ptitSeb** [comment]
I cannot help you with Termux stuff, I'm not a user myself.

**Comment by InfamousKnight** [comment]
Actually,  I somehow got it fixed. I'll test more later. By fixed, I mean the sound and display issue. 

I'll test more once I get off work

**Comment by InfamousKnight** [comment]
![Screenshot_20230203_155438_VNC Viewer](https://user-images.githubusercontent.com/2607985/216784289-1ffdd58b-7117-49eb-b5aa-c2439ea7938e.jpg)

**Comment by ptitSeb** [comment]
did you try to launch with `BOX64_LOG=1 BOX64_DLSYM_ERROR=1 BOX64_SHOWSEGV=1` as mentionned earlier, because it looks like a missing wrapped function, but I have no idea which one.

**Comment by InfamousKnight** [comment]
I have, and still nothing in the log file.

On the other hand, i spoke with the developers at bizhawk and they
mentioned blip_buf for audio resampling.

I asked what hasher they use and still waiting for their response

**Comment by YoshiRulz** [comment]
Bespoke wrapper for HW-accel'd SHA1. It's in the first line of the stacktrace. https://github.com/TASEmulators/BizHawk/issues/2731#issuecomment-1417262885

When using the shell script, pass `--mono-no-redirect` as the first argument or it will redirect stdout to a file. You should probably just use `mono EmuHawk.exe` though.

**Comment by ptitSeb** [comment]
So, BizHawk to actually works with box64, you need `mono`  build for x86_64. Chances are you are using the `mono` from you system, so built for Aarch64 (and so box64 is never involved).
There is no easy way to get a pre-built binary of `mono` for x86_64. It is suggested to build it from sources, which is not an easy way. I haven't found any tarball of binary of mono, just packages to be installed on Debian/Ubuntu/Fedora/etc... which need x86_64 multiarch and so are not an easy way to install too.
If you find an x86_64 version of `mono`, it might work, but for now, with Aarch64 version of `mono`, it will not work.

**Comment by ptitSeb** [comment]
Yes, that might work.

**Comment by InfamousKnight** [comment]
Yeah, I don't know how use that tool. I think all the .so files have to be in some long command string.

The other option is to use steam and proton. Using the windows version of bizhawk.

Is there any guide on how to get steam running on arm devices? I looked on YouTube and I can't find any guide.

**Comment by InfamousKnight** [comment]
Got it to work with wine! But limited to non-waterbox cores. It runs surprisingly fast. Might just be my phone that's relatively powerful

**Comment by ptitSeb** [comment]
Closing the ticket, don't think it's worth keeping this one open.

**Comment by InfamousKnight** [comment]
![Image](https://github.com/user-attachments/assets/8a0cc8a7-96bd-41e1-8c4f-879aff4bed2f)

Recently with micewine, I found this error when trying to open bizhawk.  The issue isn't fulled fixed because bizhawk dev builds don't work at all. And from my understanding, android has limitations compared to real linux.

I already told the micewine developer about this. But I don't know if that project is to blame

**Comment by ptitSeb** [comment]
I don't see anything wrong on the screenshot. Just some wine warning, nothing box64 specific.
