### ISSUE TITLE
Feature Requests to cope with Zoom

### ISSUE THREAD

**Issue by BusinessKid** [ptitSeb/box64#510]

**Comment by ptitSeb** [comment]
You will need to be more specific here.

**Comment by BusinessKid** [comment]
Sorry about the mess - one handed typing.

I have box64 for Zoom-x86_64 on my 4GB raspberry pi. I installed Zoom-5.9x, but the meeting wouldn't admit me because that was ≥5.10.3 Zoom have been adding useless features that nobody wants. Startup time for 5.9.x was ~60S and it used ~2 GB of ram. My next oldest archive was 5.10.7. Stats for that are ~120S startup time and 4.5 GB of ram. Further htop shows only 1 - 1¼ cores used. 5.11.x & 5.12.x each have more junk added, to judge by archive size.

May I request:
1. As Dynarec is apparently processing the extra libs, why not parallel that, as Arm cpus typically have more cores than speed?
2. Why not stick up some "Getting out of bed - please wait" type notice before guys conclude it's crashed & reboot?
3. The biggest Zoom archive is only 130MB. Dynarec must be memory hungry. Maybe some memory/ram notice?

**Comment by theironrobin** [comment]
I can't load zoom at all. 15 minutes later it just looks like its hanging. 5.13.x

**Comment by BusinessKid** [comment]
The highest Zoom I ran top date has been 5.12.x. You need about 6G ram in total to  start zoom. I have 4G of ram, and 2G of swap. Try running 'htop' in a terminal and it will keep you informed of cpu & memory usage. Have you no erarlier archive of zoom?

**Comment by ptitSeb** [comment]
Zoom should be working with latest box64 version. Can you update and try again, so this ticket can be closed?

**Comment by theironrobin** [comment]
Zoom works with latest box64

**Comment by LukeShortCloud** [comment]
Zoom is now working. Unfortunately, there will always be memory overhead with emulation. Especially on the Raspberry Pi where RAM is limited, we recommend swap for a stable experience not just with Box64 but with all programs. Glad to hear SAV_MEM is working nicely for you! Closing as resolved.
