### ISSUE TITLE
Full support for register_printf_specifier

### ISSUE THREAD

**Issue by davidzengxhsh** [ptitSeb/box64#516]
In commit 973864e partial support for register_printf_specifier was added, but I still got symbol error like this:
Error: PltResolver: Symbol register_printf_type(ver 7: register_printf_type@GLIBC_2.10) not found, cannot apply R_X86_64_JUMP_SLOT 0xffffb765bdc8 (0xffffb7618130) in /lib/x86_64-linux-gnu/libquadmath.so.0
Error: PltResolver: Symbol register_printf_specifier(ver 7: register_printf_specifier@GLIBC_2.10) not found, cannot apply R_X86_64_JUMP_SLOT 0xffffa840fda8 (0xffffa83cc0f0) in /lib/x86_64-linux-gnu/libquadmath.so.0

Also, there are some other symbols not found as below:
Error: PltResolver: Symbol _ZGVbN4vv_powf(ver 5: _ZGVbN4vv_powf@GLIBC_2.22) not found, cannot apply R_X86_64_JUMP_SLOT 0x18a4040 (0x403086)
Symbol _ZGVbN2vv_pow(ver 13: _ZGVbN2vv_pow@GLIBC_2.22) not found
Symbol _ZGVbN2v_cos(ver 5: _ZGVbN2v_cos@GLIBC_2.22) not found
Symbol cexp(ver 3: cexp@GLIBC_2.2.5) not found
Symbol _ZGVbN2v_sin(ver 4: _ZGVbN2v_sin@GLIBC_2.22) not found

Are all these related to the wrapper implementation?

**Comment by ptitSeb** [comment]
I don't really understand what is going on. The "partial" support should have remove the PltResolver error. And those other symbols are really strange.
Can you post the full log?

**Comment by davidzengxhsh** [comment]
Thanks for your reply! Actually this is a serial of tests. Below the log from a WRF model test. 
./wrf_test
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:80
Params database has 15 entries
Box64 with Dynarec v0.2.1 87b66b8d built on Feb 13 2023 10:24:19
BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 39 Env var
Looking for ./wrf_test
Rename process to "wrf_test"
Using emulated lib/libjemalloc.so.2
Using emulated /lib/x86_64-linux-gnu/libgfortran.so.5
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libmvec.so.1
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /lib/x86_64-linux-gnu/libquadmath.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Redirecting overriden malloc function for lib/libjemalloc.so.2
Error: PltResolver: Symbol **register_printf_type**(ver 7: register_printf_type@GLIBC_2.10) not found, cannot apply R_X86_64_JUMP_SLOT 0xffff8b018dc8 (0xffff8afd5130) in /lib/x86_64-linux-gnu/libquadmath.so.0

WRF V3.6.1 MODEL
Timing for processing wrfinput file:    0.31000 elapsed seconds

Error: PltResolver: Symbol **_ZGVbN4vv_powf**(ver 5: _ZGVbN4vv_powf@GLIBC_2.22) not found, cannot apply R_X86_64_JUMP_SLOT 0x18a4040 (0x403086) in /home/david/box64_test/wrf_x86/wrf_test
Error: PltResolver: Symbol **register_printf_specifier**(ver 7: register_printf_specifier@GLIBC_2.10) not found, cannot apply R_X86_64_JUMP_SLOT 0xffff8b018da8 (0xffff8afd50f0) in /lib/x86_64-linux-gnu/libquadmath.so.0

**Comment by ptitSeb** [comment]
Your Box64 is not recent enough. Commit #87b66b8 doesn't have the printf_register thingy.
Go in you box64 clone and do `git pull`, than build and test again. The other error will stay tho, I need to see what those `_ZGVbN4vv_powf` function are and were do they come from.

**Comment by davidzengxhsh** [comment]
yes, you're correct, the latest code has printf_register_*. 
My bad, I checked out an old version because I saw an error like this:
FillBlock at 0x56c950 triggered a segfault, cancelling

And it seems you have fixed it in the latest code.

**Comment by ptitSeb** [comment]
Yes indeed, I had some nasty typo and bugs in some latest refactor. It should be stable now.

**Comment by LukeShortCloud** [comment]
Closing as resolved.
