### ISSUE TITLE
JIT for RISC-V?

### ISSUE THREAD

**Issue by JeremyRand** [ptitSeb/box64#517]
It was mentioned in https://github.com/ptitSeb/box64/issues/242#issuecomment-1052656727 that a RISC-V JIT was under development, but I don't see an issue open for that. Thus I am opening one. Is there any status update since that comment circa a year ago?

**Comment by ptitSeb** [comment]
Still haven't started the JIT itself no. I wanted to have a stable enough version of box64 before starting it. I hope I will work on this soon.

**Comment by JeremyRand** [comment]
No worries, thanks for the update. Personally I'm much more interested in POWER9 JIT, but my understanding is that POWER9 is blocked by RISC-V, so if that's still the case, I suppose I'm transitively interested in seeing RISC-V happen. :)

**Comment by JeremyRand** [comment]
That's reasonable. More arch diversity is a good thing in my book, even if my preferred arch happens to come second, so no complaints here.

**Comment by fish4terrisa-MSDSM** [comment]
You can use my project [archriscv-term](https://github.com/fish4terrisa-MSDSM/archriscv-term) to test riscv64 software in android phone.

**Comment by ptitSeb** [comment]
So, RISCV JIT is started.
There are a few opcode implemented, and it's starting to work fine.

Here is video of a game running on a Vision Five 2 board, uisng Box64 (and gl4es): https://youtu.be/6G9zMIaAvjY

**Comment by LekKit** [comment]
> So, RISCV JIT is started. 

Keep up the great work and thanks for your efforts)
I will soon be testing this on [RVVM](https://github.com/LekKit/RVVM) and VF2, and perhaps would try to contribute something. For now sponsored this a tiny bit as I'm really interested in RISC-V support.

**Comment by ptitSeb** [comment]
> > So, RISCV JIT is started.
> 
> Keep up the great work and thanks for your efforts) I will soon be testing this on [RVVM](https://github.com/LekKit/RVVM) (Would help profile icache related stalls, etc) and VF2, and perhaps would try to contribute something. For now sponsored this a tiny bit as I'm really interested in RISC-V support.

Thanks! It would be interresting to see Box64 running in RVVM (impressive project you have there btw!). I like double emulation :D

**Comment by ksco** [comment]
Our CI is double emulating right now... ;)

**Comment by ptitSeb** [comment]
Ah yes, Box64 in QEMU!

**Comment by ksco** [comment]
Some notes on how to run Super Hexagon on a Vision Five 2 SBC, in case someone wants to try it. ;)

I'm assuming you're running the default Debian image provided by StarFive.

1. Clone https://github.com/ptitSeb/box64 and https://github.com/ptitSeb/gl4es, then build and install them.
2. Download the game from GOG.com, it's a shell script installer.
3. `chmod +x gog_super_hexagon_2.1.0.4.sh`
4. `./gog_super_hexagon_2.1.0.4.sh` to install the game.
5. `cd ~/GOG\ Games/Super\ Hexagon/game`
6. `LD_LIBRARY_PATH=/path/to/gl4es/lib/:$LD_LIBRARY_PATH BOX64_EMULATED_LIBS=libSDL2-2.0.so.0 box64 ./x86_64/superhexagon.x86_64`.
7. Enjoy!

Thank @ptitSeb for your help!

**Comment by LekKit** [comment]
Some news: Got Minecraft bedrock server running under box64 on both VF2 and RVVM (yay). It's starting up pretty slowly, and I might have some ideas why (and overall some *useless* recomendations):
- I see a lot of icache related stalls esp. under RVVM where basically 2 JITs work on top of one another
- This is evident in profiling, where I see it's hitting dirty code 90% of the time, and on physical hw zifence takes a serious penalty. It's suggested by RISC-V spec that you do bulk & lazy updates to self-modifying code and batch them in a single zifence as soon as that path becomes accessible
- I might be wrong (Collected some data from VM), but sometimes jump targets are not properly aligned which is a perf hit for SiFive SoCs predictor (In perfect case you'd align hot jump targets to 4 byte boundaries)

I'm yet to dig into box64 codebase but I will see if I can try and help with anything

**Comment by ptitSeb** [comment]
Good news indeed :)

Well, about the slowiness, the Dynarec is still far from complete. So as soon as an unimplemented opcode (byt the dynarec) is found, the block is stopped and the interpreter is used until next jmp/ret/call (basicaly). That's also why small block are created a lot, because they are interupted. The more opcode will be integrated in the Dynarec, the longer the block will be and less zifence and all will be called.
Unaligned jmp target should not happens. If one happens, there is an error somewhere.

**Comment by LekKit** [comment]
> That's also why small block are created a lot, because they are interupted

Ah yeah that makes total sense, it's kinda familiar even

> Unaligned jmp target should not happen

It's not unaligned per se RISC-V standard, but I see 2-byte aligns a lot when tracing in RVVM, and according to Bruce Hoult it incurs some penalty on the predictor on actual U74. My data however might come from some glue/generic code in box64 and not from JIT (I should rebuild with `-falign-jumps=4`), but it'd mean it spends a significant amount of time there

**Comment by LukeShortCloud** [comment]
JIT support has been added for RISC-V. Arm still has the best JIT support. It's all on-going work by our community members. Closing as resolved.
