### ISSUE TITLE
Run SlayTheSpire desktop version on Android 

### ISSUE THREAD

**Issue by seirios** [ptitSeb/box64#519]
I'm trying to run SlayTheSpire Linux desktop version on my Android ARM64 phone with a Debian installation.

So far, thanks to the BOX64_BASH feature I was able to install it. However, when I try launching it, I get an error related to Java runtime (the same as reported in #232  and #464 ).

I'm aware that Java support is not ready, so this is just an expression of interest in that feature. Thanks for the great work!

**Comment by ptitSeb** [comment]
The Error with the "collector_func_load" symbol is not really an error. I have hidden it now.
You should try again with latest version. I have more java stuffs running on my side. If you have instability, try to use `BOX64_DYNAREC_STRONGMEM=1` (or maybe 2), it might help with heavy multi-thread programs.

**Comment by seirios** [comment]
Thanks. I've retried with version from today, and it crashes with SIGSEGV from `CodeHeap::allocate`, as in #464 . Full log attached with `BOX64_DYNAREC_STRONGMEM=2`, but similar results with other values: [strongmem2.log](https://github.com/ptitSeb/box64/files/10787148/strongmem2.log).

**Comment by ptitSeb** [comment]
With latest box64, I got it run
![Screenshot from 2023-04-16 10-38-50](https://user-images.githubusercontent.com/3250792/232287790-58a750c5-efd0-4d65-8609-07601aa6a94b.png)

**Comment by ptitSeb** [comment]
Can this ticket be closed now?

**Comment by seirios** [comment]
Yes, thanks a lot!
