### ISSUE TITLE
Failing to pull (unrelated histories)

### ISSUE THREAD

**Issue by theofficialgman** [ptitSeb/box64#52]
I'm not sure if its just me but I've gotten a fatal error when pulling due to unrelated histories multiple times with this repo.

Has there been any reason on your end for this to happen?

**Comment by ptitSeb** [comment]
I never had that issue on my side. I'm not even sure what that error means.

**Comment by theofficialgman** [comment]
```remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 28 (delta 26), reused 18 (delta 16), pack-reused 0
Unpacking objects: 100% (28/28), done.
From https://github.com/ptitSeb/box64
 + 3d656b5...5287e42 main       -> origin/main  (forced update)
fatal: refusing to merge unrelated histories
```
every time...
pretty sure its what happens if you force push and delete a commit, etc
But I wouldn't think that would even matter since I'm doing a clone --depth=1 and pull --depth=1

**Comment by theofficialgman** [comment]
```git status
On branch main
Your branch and 'origin/main' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```
all I did was clone the project yesterday

**Comment by ptitSeb** [comment]
I don't force push anything. I know @rajdakin  had forced pushed something on this repo, but it's at least one month ago, so I don't think it's relevent with your recuring problem.

Are you sure it's not a media issue? Are you on a SDCard that is failing maybe?

**Comment by theofficialgman** [comment]
it could be a media issue... but I really really doubt it (this is running from an sd card)
I'll clone on my pc both ways and let you know after you next push

**Comment by theofficialgman** [comment]
hmm.. I pulled today without any issues
I'll leave this open for a week or two just to make sure everything stays fine (really not sure what the problem is/was)

**Comment by ptitSeb** [comment]
Can I close the ticket now?

**Comment by theofficialgman** [comment]
yes this can be closed... it was just me not understanding that you can't pull with git after having clones with  --depth=1
