### ISSUE TITLE
Gamepads work incorrectly in Unity games

### ISSUE THREAD

**Issue by Shatur** [ptitSeb/box64#527]
I tried to run Streets of Rogue and Tangledeep. Both games written in Unity and works fine, except gamepad buttons work incorrectly. I tried two gamepads: Xbox Wireless Controller (works properly using https://github.com/atar-axis/xpadneo dkms driver) and GameSir X2 Pro (configured it with xboxdrv). Both work fine in other native games and in Iconoclasts (not a Unity game). And Xbox Wireless Controller works fine on PC with the mentioned two games (and configured the same way via xpadneo). So I suspect that it could be an issue with box64. I use version 0.2.

**Comment by ptitSeb** [comment]
What is not working properly? the button mapping?

**Comment by Shatur** [comment]
> What is not working properly? the button mapping?

Yes, axes are inverted and some buttons not mapped. But presses are detected, in Streets of Rogue I can map all buttons in settings.

**Comment by ashutosh887** [comment]
@ptitSeb @Shatur I would like to contribute to the Org. Please assign me some issues

**Comment by ptitSeb** [comment]
@ashutosh887 ok, you want to analyse this ticket?

**Comment by ashutosh887** [comment]
Would love to resolve any beginner issues first to that I can get an idea of the ecosystem @ptitSeb 😊

**Comment by ptitSeb** [comment]
Ah well, I didn't put `the "good fist issue" tags on the issues, and this one doesn't seem completly easy. I tend to do the easy one when I see them. I'll try to save them a bit now.

You can help on this one. The point would be to reproduce the issue with something simple, and then to try again without dynarec active (so with `BOX64_DYNAREC=0`). and see if it (sloooowly) reproduce the issue or now. This is to understand if it's a Dynarec issue or something else.

**Comment by Shatur** [comment]
Sorry, looks like the issue is in game, I just reproduced the same behavior on my PC.
