### ISSUE TITLE
Steam login menu not working

### ISSUE THREAD

**Issue by asdfghjkl403622** [ptitSeb/box64#529]
Hey!

I used the linux arm gaming chroot guide to run steam, and when I did, I ended up with this:
![borked login screen](https://user-images.githubusercontent.com/44118606/221372940-8d34150c-8eca-413f-93fa-3a36a6ccfa36.png)
I tried looking at the console output, which just complained about cef which I talked about in this issue https://github.com/Raezroth/Linux-ARM-Gaming-Chroot/issues/16
I tried -nocefsandbox and -oldbigpicture as well and no dice
here's the command I use to launch steam:
MESA_GL_VERSION_OVERRIDE=3.2 PAN_MESA_DEBUG=gl3 steam +open steam://open/minigameslist -noreactlogin
any tips?

**Comment by ptitSeb** [comment]
You need to use `steam_chrome` branch of box64 for now to get steam working. Also, be aware that steam will barely fit in 4Gb or ram with box currently.

**Comment by asdfghjkl403622** [comment]
I thought that was only with the ful steam web client? why isn't that in the guide?

**Comment by asdfghjkl403622** [comment]
That branch of box64 is not compiling in the chroot

**Comment by asdfghjkl403622** [comment]
`/root/box64/src/include/../emu/x64primop.h: In function 'mul64_rax':
/root/box64/src/include/../emu/x64primop.h: In function 'mul64_rax':
/root/box64/src/include/../emu/x64primop.h:613:18: error: '__int128' is not supported on this target
  613 |         unsigned __int128 res = (unsigned __int128)R_RAX * s;
      |                  ^~~~~~~~
/root/box64/src/include/../emu/x64primop.h:613:18: error: '__int128' is not supported on this target
  613 |         unsigned __int128 res = (unsigned __int128)R_RAX * s;
      |                  ^~~~~~~~
/root/box64/src/include/../emu/x64primop.h:613:43: error: '__int128' is not supported on this target
  613 |         unsigned __int128 res = (unsigned __int128)R_RAX * s;
      |                                           ^~~~~~~~
/root/box64/src/include/../emu/x64primop.h:613:43: error: '__int128' is not supported on this target
  613 |         unsigned __int128 res = (unsigned __int128)R_RAX * s;
      |                                           ^~~~~~~~
/root/box64/src/include/../emu/x64primop.h:615:47: warning: right shift count >= width of type [-Wshift-count-overflow]
  615 |         emu->op1.u64 = R_RDX = (uint64_t)(res >> 64);
      |                                               ^~
/root/box64/src/include/../emu/x64primop.h:615:47: warning: right shift count >= width of type [-Wshift-count-overflow]
  615 |         emu->op1.u64 = R_RDX = (uint64_t)(res >> 64);
      |                                               ^~
make[2]: *** [CMakeFiles/native_pass2.dir/build.make:118: CMakeFiles/native_pass2.dir/src/dynarec/arm64/dynarec_arm64_emit_logic.c.o] Error 1
make[2]: *** [CMakeFiles/native_pass2.dir/build.make:104: CMakeFiles/native_pass2.dir/src/dynarec/arm64/dynarec_arm64_emit_math.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:201: CMakeFiles/native_pass2.dir/all] Error 2
make: *** [Makefile:166: all] Error 2`

**Comment by ptitSeb** [comment]
> I thought that was only with the ful steam web client? why isn't that in the guide?

Steam is always evolving. The steamwebhelper is now needed as soon as the login page, and the old login has been removed.

**Comment by ptitSeb** [comment]
> `/root/box64/src/include/../emu/x64primop.h: In function 'mul64_rax': /root/box64/src/include/../emu/x64primop.h: In function 'mul64_rax': /root/box64/src/include/../emu/x64primop.h:613:18: error: '__int128' is not supported on this target 613 | unsigned __int128 res = (unsigned __int128)R_RAX * s; | ^~~~~~~~ /root/box64/src/include/../emu/x64primop.h:613:18: error: '__int128' is not supported on this target 613 | unsigned __int128 res = (unsigned __int128)R_RAX * s; | ^~~~~~~~ /root/box64/src/include/../emu/x64primop.h:613:43: error: '__int128' is not supported on this target 613 | unsigned __int128 res = (unsigned __int128)R_RAX * s; | ^~~~~~~~ /root/box64/src/include/../emu/x64primop.h:613:43: error: '__int128' is not supported on this target 613 | unsigned __int128 res = (unsigned __int128)R_RAX * s; | ^~~~~~~~ /root/box64/src/include/../emu/x64primop.h:615:47: warning: right shift count >= width of type [-Wshift-count-overflow] 615 | emu->op1.u64 = R_RDX = (uint64_t)(res >> 64); | ^~ /root/box64/src/include/../emu/x64primop.h:615:47: warning: right shift count >= width of type [-Wshift-count-overflow] 615 | emu->op1.u64 = R_RDX = (uint64_t)(res >> 64); | ^~ make[2]: *** [CMakeFiles/native_pass2.dir/build.make:118: CMakeFiles/native_pass2.dir/src/dynarec/arm64/dynarec_arm64_emit_logic.c.o] Error 1 make[2]: *** [CMakeFiles/native_pass2.dir/build.make:104: CMakeFiles/native_pass2.dir/src/dynarec/arm64/dynarec_arm64_emit_math.c.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:201: CMakeFiles/native_pass2.dir/all] Error 2 make: *** [Makefile:166: all] Error 2`

You are compiling in a 32bits environement. You need a 64bits environnement to build box64.

**Comment by asdfghjkl403622** [comment]
perhaps this is a bit out of the scope of this issue to ask, but do you know how to make the chroot compile it in 64bits? if not I guess I have some reading to do

**Comment by ptitSeb** [comment]
no I don't, sorry. I don't use chroot.

**Comment by asdfghjkl403622** [comment]
that's alright. I think I can just specify using make in the host system to compile into the chroot directory

**Comment by asdfghjkl403622** [comment]
can confirm, is working now! thanks!
