### ISSUE TITLE
Runescape Launcher

### ISSUE THREAD

**Issue by theironrobin** [ptitSeb/box64#533]
`> $ runescape-launcher
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:8
Box64 with Dynarec v0.2.0 93fde45 built on Feb 27 2023 21:37:20
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 56 Env var
Looking for /usr/share/games/runescape-launcher/runescape
argv[1]="--configURI"
argv[2]="https://www.runescape.com/k=5/l=$(Language:0)/jav_config.ws"
Rename process to "runescape"
Using native(wrapped) libSM.so.6
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libX11.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libcairo.so.2
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libgdk-x11-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgtk-x11-2.0.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libm.so.6
Error loading needed lib libcap.so.2
Error loading one of needed lib
Error: loading needed libs in elf /usr/share/games/runescape-launcher/runescape

alex@naga /lib                                                [15:58:30]
> $ ls | grep cap
libcap-ng.so
libcap-ng.so.0
libcap-ng.so.0.0.0
libcap.so
libcap.so.2
libcap.so.2.67
libpcap.so
libpcap.so.1
libpcap.so.1.10.3
libsysprof-capture-4.a
libtss2-tcti-pcap.so
libtss2-tcti-pcap.so.0
libtss2-tcti-pcap.so.0.0.0`

Any idea what I am doing wrong?

**Comment by ptitSeb** [comment]
`libcap` is not wrapped, so you need the x86_64 version for box64 to load it.

**Comment by LukeShortCloud** [comment]
I recommend using this site to find x86_64 packages to download and extract: https://pkgs.org/ Then you can use `BOX64_LD_LIBRARY_PATH` to load them. Since there are no issues with Box64 itself, I'll go ahead and close this out. Let us know if you have any issues using the emulated `libcap` libraries.
