### ISSUE TITLE
juste une question

### ISSUE THREAD

**Issue by mu578** [ptitSeb/box64#540]
Bonjour,

pourquoi la limitation sur l'endian? pas une critique, juste une interrogation sur le choix imposé qui est surprenant.

**Comment by mu578** [comment]
boujour, oui je sais mais rien empeche un swap. c'est juste un re-ordering

**Comment by ptitSeb** [comment]
Mais dans ce cas, il faut connaitre chaque structure en détail, ce n'est plus un simple appel direct, c'est un appel + transformation.

C'est faisable bien sûr, mais pas la cible pour box64 actuellement (et cela represente beaucoup de travail aussi)

**Comment by mu578** [comment]
Merci, oui je sais que ce n'est pas aussi simple et naif, de toutes les façons bravo pour ce projet cela marche definitivement mieux que tout ce qui a été tenté avant.

**Comment by ptitSeb** [comment]
Merci :)
