### ISSUE TITLE
oray_sunloginclient

### ISSUE THREAD

**Issue by huangguiniab** [ptitSeb/box64#56]
I tried to install this software on my system, but it requires libgtk3, because of the dependencies of the package, I cannot install it. So I used packages.debian.org to manually search for the library files I needed. Its took me an afternoon. In the end, although I completed all the runtime libraries,but I still got an error. This is the output.
[a.txt](https://github.com/ptitSeb/box64/files/6815990/a.txt)

**Comment by huangguiniab** [comment]
Sorry, I didn’t see the notification, I’ll test it again today

**Comment by huangguiniab** [comment]
[outbox64.txt](https://github.com/ptitSeb/box64/files/7082277/outbox64.txt)
Not working..........
Do you need binary files?

**Comment by ptitSeb** [comment]
Missing symbols. I'll add them. For now, I don't need the binary.

**Comment by huangguiniab** [comment]
[outbox64.txt](https://github.com/ptitSeb/box64/files/7115382/outbox64.txt)

**Comment by ptitSeb** [comment]
I wrapped gtk2... But not yet gtk3. So maybe it has improve, but I don't think it's enough to make it runs.

**Comment by huangguiniab** [comment]
okay.......
I think this is enough,Maybe we should give it up temporarily......
