### ISSUE TITLE
[RV64] Implementing CALL/JMP

### ISSUE THREAD

**Issue by ksco** [ptitSeb/box64#562]
Seems that implementing CALL/JMP is quite challenging, as it involves dealing with cache and native call handling. @ptitSeb, would you be able to help us in implementing these instructions? For instance, if you could implement one of the CALL and JMP family instructions, then @xctan and I could proceed with implementing the rest.

**Comment by ptitSeb** [comment]
Yeah, I was planning to implement CALL/RET and JMP. I will probably do a first batch of Jxx conditionnal jump also.
After that, I'll work on x87/sse infrastructure.

**Comment by ksco** [comment]
Great, I will keep this ticket open to track the progress.
