### ISSUE TITLE
Zoom: Double SIGSEGV

### ISSUE THREAD

**Issue by AarizYT** [ptitSeb/box64#57]
I got this error when I tried to run Zoom on Termux PRoot Ubuntu 20.04 (ARM64). 

Error log:-
``Box64 with Dynarec v0.1.3 f73bbfc built on Jul 14 2021 11:35:34
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 30 Env var
Looking for /root/zoom/zoom
Zoom detected, trying to use system libturbojpeg if possible
Using native(wrapped) libdl.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) librt.so.1
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libxcb-xfixes.so.0
Using native(wrapped) libxcb-shape.so.0
Using native(wrapped) libxcb-shm.so.0
Using native(wrapped) libxcb-randr.so.0
Error initializing native libxcb-image.so.0 (last dlerror is libxcb-image.so.0: cannot open shared object file: No such file or directory)
Using emulated /lib/x86_64-linux-gnu/libxcb-image.so.0
Using native(wrapped) libxcb-keysyms.so.1
Using native(wrapped) libxcb-xtest.so.0
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXtst.so.6
Using emulated /lib/x86_64-linux-gnu/libglib-2.0.so.0
Using native(wrapped) libdbus-1.so.3
Using emulated /lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
Using emulated /lib/x86_64-linux-gnu/libQt5Quick.so.5
Using emulated /lib/x86_64-linux-gnu/libQt5Widgets.so.5
Using emulated /lib/x86_64-linux-gnu/libQt5X11Extras.so.5
Using emulated /lib/x86_64-linux-gnu/libQt5Gui.so.5
Using emulated /lib/x86_64-linux-gnu/libQt5Qml.so.5
Using emulated /lib/x86_64-linux-gnu/libQt5Network.so.5
Using emulated /lib/x86_64-linux-gnu/libQt5Script.so.5
Using emulated /lib/x86_64-linux-gnu/libQt5DBus.so.5
Using emulated /lib/x86_64-linux-gnu/libQt5Core.so.5
Using native(wrapped) libGL.so.1
Using native(wrapped) libpthread.so.0
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /lib/x86_64-linux-gnu/libxcb-util.so.1
Using native(wrapped) libpcre.so.3
Using native(wrapped) libz.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libicui18n.so.56
Using emulated /usr/lib/x86_64-linux-gnu/libicuuc.so.56
Using emulated /usr/lib/x86_64-linux-gnu/libicudata.so.56
Using emulated /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
No PulseAudio daemon running, or not running as session daemon.
cat: /proc/sys/kernel/pid_max: Permission denied
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
Using emulated /root/zoom/platforms/libqxcb.so
Using emulated /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libXrender.so.1
Error initializing native libxkbcommon-x11.so.0 (last dlerror is libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory)
Using emulated /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0
Using native(wrapped) libxkbcommon.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1
Using native(wrapped) libXcursor.so.1
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Using emulated /root/zoom/platforminputcontexts/libcomposeplatforminputcontextplugin.so
Using emulated /root/zoom/imageformats/libqsvg.so
Using emulated /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: BE:34:D1:4C:15:A0][client: Linux][OS:  Ubuntu 20.04.1 LTS x64][Hardware: CPU Core:6 Frenquency:1.352 G Memory size:2725MB CPU Brand:              Intel(R) Pentium(R) 4 CPU 1000MHz GPU Brand:][Req ID: ]
Linux Client Version is 5.7.1 (26030.0627)
QSG_RENDER_LOOP is
XDG_CURRENT_DESKTOP = ;   GDMSESSION = ;   XDG_SESSION_TYPE =
Graphics Card Info::
Zoom package arch is 64bit, runing OS arch is x86_64
AppIconMgr::systemDesktopName log Desktop Name:
28412|SIGSEGV @0x72fe1c769c (???(0x72fe1c769c)) (x64pc=0x7300482621//usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5:"/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5/_ZN19QXcbBasicConnection10internAtomEPKc", rsp=0x731b0d3600, stack=0x731a8d5000:0x731b0d5000 own=(nil) fp=0x73003cb250), for accessing 0x8 (code=1/prot=0), db=0x73003f80c0(0x72fe1c7548:0x72fe1c7770/0x73004825e0:0x7300482632//usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5/_ZN19QXcbBasicConnection10internAtomEPKc:clean, hash:71bec8df/71bec8df) handler=0x731dc186a0
Error: Unsupported Syscall 0x38h (56)
28412|Double SIGSEGV (code=1, pc=0x72fe1c769c, addr=0x8)!``

**Comment by ptitSeb** [comment]
you are missing 2 arm64 libs: libxcb-image.so.0 and libxkbcommon-x11.so.0
install them, it should improve things.

**Comment by AarizYT** [comment]
I installed the arm64 packages that contain those 2 libraries, here's the error log now:-
``Box64 with Dynarec v0.1.3 f73bbfc built on Jul 14 2021 11:35:34
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 30 Env var
Looking for zoom
Zoom detected, trying to use system libturbojpeg if possible
Using native(wrapped) libdl.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) librt.so.1
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libxcb-xfixes.so.0
Using native(wrapped) libxcb-shape.so.0
Using native(wrapped) libxcb-shm.so.0
Using native(wrapped) libxcb-randr.so.0
Using native(wrapped) libxcb-image.so.0
Using native(wrapped) libxcb-keysyms.so.1
Using native(wrapped) libxcb-xtest.so.0
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXtst.so.6
Using emulated /lib/x86_64-linux-gnu/libglib-2.0.so.0
Using native(wrapped) libdbus-1.so.3
Using emulated libQt5QuickWidgets.so.5
Using emulated libQt5Quick.so.5
Using emulated libQt5Widgets.so.5
Using emulated libQt5X11Extras.so.5
Using emulated libQt5Gui.so.5
Using emulated libQt5Qml.so.5
Using emulated libQt5Network.so.5
Using emulated libQt5Script.so.5
Using emulated libQt5DBus.so.5
Using emulated libQt5Core.so.5
Using native(wrapped) libGL.so.1
Using native(wrapped) libpthread.so.0
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpcre.so.3
Using native(wrapped) libz.so.1
Using emulated libicui18n.so.56
Using emulated libicuuc.so.56
Using emulated libicudata.so.56
Using emulated /lib/x86_64-linux-gnu/libgthread-2.0.so.0
No PulseAudio daemon running, or not running as session daemon.
cat: /proc/sys/kernel/pid_max: Permission denied
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
Using emulated /root/zoom/platforms/libqxcb.so
Using emulated libQt5XcbQpa.so.5
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libxkbcommon-x11.so.0
Using native(wrapped) libxkbcommon.so.0
Using native(wrapped) libXcursor.so.1
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Using emulated /root/zoom/platforminputcontexts/libcomposeplatforminputcontextplugin.so
Using emulated /root/zoom/imageformats/libqsvg.so
Using emulated libQt5Svg.so.5
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: BE:34:D1:4C:15:A0][client: Linux][OS:  Ubuntu 20.04.1 LTS x64][Hardware: CPU Core:6 Frenquency:1.352 G Memory size:2725MB CPU Brand:              Intel(R) Pentium(R) 4 CPU 1000MHz GPU Brand:][Req ID: ]
Linux Client Version is 5.7.1 (26030.0627)
QSG_RENDER_LOOP is
XDG_CURRENT_DESKTOP = ;   GDMSESSION = ;   XDG_SESSION_TYPE =
Graphics Card Info::
Zoom package arch is 64bit, runing OS arch is x86_64
AppIconMgr::systemDesktopName log Desktop Name:
Using emulated /root/zoom/QtQuick.2/libqtquick2plugin.so
Using emulated /root/zoom/QtQuick/Controls.2/libqtquickcontrols2plugin.so
Using emulated libQt5QuickTemplates2.so.5
Using emulated libQt5QuickControls2.so.5
Using emulated /root/zoom/QtQuick/Layouts/libqquicklayoutsplugin.so
Using emulated /root/zoom/QtQuick/Window.2/libwindowplugin.so
Using emulated /root/zoom/QtQuick/Templates.2/libqtquicktemplates2plugin.so
Using emulated /root/zoom/xcbglintegrations/libqxcb-glx-integration.so
Using native(wrapped) libxcb-glx.so.0
Using emulated /root/zoom/xcbglintegrations/libqxcb-egl-integration.so
Using emulated /lib/x86_64-linux-gnu/libEGL.so.1
Using emulated /lib/x86_64-linux-gnu/libGLdispatch.so.0
Using emulated /root/zoom/QtQuick/Controls/libqtquickcontrolsplugin.so
mprotect failed in ExecutableAllocator::makeExecutable: Permission denied
Warning, jumping to a no-block address 0x90000781a9bd7bfd from 0x733b3149e0 (db=0x733b35b310, x64addr=0x7439a15fb7)
19285|SIGSEGV @0x648d2e9c (???(box64/0x648d2e9c)) (x64pc=0x90000781a9bd7bfe/???:"???", rsp=0x743db01cc0, stack=0x743d305000:0x743db05000 own=(nil) fp=0x2c4), for accessing 0x781a9bd7bfd (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=0x74406486a0
Error: Unsupported Syscall 0x38h (56)
19285|Double SIGSEGV (code=1, pc=0x648d2e9c, addr=0x781a9bd7bfd)!``

**Comment by ptitSeb** [comment]
Your logs are missing all new lines, making it very difficult to read!

There seems to be issue I don't have on my side or regular linux: "mprotect failed in ExecutableAllocator::makeExecutable: Permission denied"

It seems to then jump to a NULL function pointer and segfault there.
I assume this is an issue with PRoot, as I don't reproduce the issue on plain linux.
Also, I don't use EGL on my side (I haven't put x86_64 version of libEGL. I use OpenGL (to use wrapped native OpenGL). Note that EGL is not wrapped on box64, so it will not be hardware accelerated anyway.

**Comment by AarizYT** [comment]
Sorry for that, here's the output in a txt file. I hope this helps. 
[output.txt](https://github.com/ptitSeb/box64/files/6820914/output.txt)

**Comment by ptitSeb** [comment]
those error: "5846|SIGSEGV @0x649064f0 (???(box64/0x649064f0)) (x64pc=0x64ef8033/???:"???", rsp=0x7158aeb718, stack=0x71588ec000:0x7158aec000 own=0x71588ec000 fp=0x70cc12b160), for accessing 0x71a0902fe0 (code=2/prot=3), db=(nil)((nil):(nil)/(nil)" are suspicious but I don't know what going on there.
Can you do `addr2line -e box64 -a 0x649064f0` (you may need to put the full path to box64).

**Comment by AarizYT** [comment]
Here is the output:- 
``0x00000000649064f0                                                     /root/box64/src/tools/bridge.c:107``

**Comment by AarizYT** [comment]
Still getting some errors after applying the patch. 
The full log is in the linked file. I did ``addr2line -e box64/build/box64 -a 0x648d2ecc``
and got the following output:-
``0x00000000648d2ecc
/root/box64/src/emu/x64run.c:66 (discriminator 3)``
[output2.txt](https://github.com/ptitSeb/box64/files/6822172/output2.txt)

**Comment by ptitSeb** [comment]
Can you try to delete this file `/lib/x86_64-linux-gnu/libEGL.so.1` to be sure it sure native OpenGL and not EGL

**Comment by AarizYT** [comment]
Here's the log after deleting the file:-
[output3.txt](https://github.com/ptitSeb/box64/files/6822211/output3.txt)

**Comment by ptitSeb** [comment]
use `BOX64_DLSYM_ERROR=1` env var to have more detail.
You do have some OpenGL in your proot right?

**Comment by AarizYT** [comment]
Zoom on Android doesn't pick the right audio output for my bluetooth headphones. The audio quality is bad and the selected output interferes with my internet. 

I have switched to another PRoot container. I am using Ubuntu 21.04 with GL4ES now. The other container didn't have OpenGL working. I still have errors with Zoom on this container. I am linking the output file with ``BOX64_DLSYM_ERROR=1`` variable enabled. 
[output4.txt](https://github.com/ptitSeb/box64/files/6823234/output4.txt)

**Comment by ptitSeb** [comment]
I don't think gl4es is working here. I see a "No EGL config found" that doesn't sound good.
You can try with `LIBGL_FB=3` to force slower PBuffer mode that may work, or try without OpenGL for now, by removing `xcbglintegrations/libqxcb-glx-integration.so`

**Comment by ptitSeb** [comment]
I think Zoom is working now with Box64. Can this ticket be closed?
