### ISSUE TITLE
have android arm64 build?

### ISSUE THREAD

**Issue by szllzs** [ptitSeb/box64#593]
i modify src to build on android arm64, build ok，but can not run

**Comment by ptitSeb** [comment]
Box64 needs a Linux system to run. Android is not Linux.
You should use Termux to create a Linux system, then you can use box64 there (build with the `BAD_SIGNAL`  and `ARM_DYNAREC` compile options for better compatibility)

**Comment by Ilya114** [comment]
> Android is not Linux.

Android like Debian, Ubuntu is based on the Linux kernel. Why not?

**Comment by ptitSeb** [comment]
> > Android is not Linux.
> 
> Android like Debian, Ubuntu is based on the Linux kernel. Why not?

Take a Debian program and try to run it under Android, you'll see why.

**Comment by Ilya114** [comment]
> Take a Debian program and try to run it under Android, you'll see why.

Well, it won't work. But if it doesn't run in Arch, then it's not Linux? For Android, there are applications in apk or aab format, as well as deb in Debian

**Comment by ptitSeb** [comment]
No, it's not apk vs deb issues. It's just that Android is not Linux. It use a modified Linux kernel, and the userspace is completly different.
Use TERMUX to run Linux program on Android (including box86/box64)

**Comment by Ilya114** [comment]
> It use a modified Linux kernel, and the userspace is completly different.

Well, then Android is base on Linux kernel but using bionic, not glibc that`s why can`t run programs from desktop Linux OSes. I think we can end here

**Comment by 500InternalError** [comment]
Can we statically link glibc to make box64 work on Android?

**Comment by fish4terrisa-MSDSM** [comment]
> Can we statically link glibc to make box64 work on Android?

That does not work, as static build is just not possible

**Comment by boatsky** [comment]
Can I build glibc on termux and run box86?

**Comment by boatsky** [comment]
like this
https://github.com/fhh200000/GlibC-AArch64-Android

**Comment by 500InternalError** [comment]
I managed to build box64 against glibc in native termux(https://github.com/termux-pacman/glibc-packages I installed glibc and other stuffs like gcc from here to compile box64), but found it kinda useless, since most programs require libraries that haven't been ported to termux, you need to either build them yourself or to manually download dependencies from a "normal" distribution like archlinuxarm and extract those things to a proper location, launch your program with LD_LIBRARY_PATH and hope everything works. Plus if you want to use wine you need to patch it to avoid it writing to /tmp. This really wastes tooooo much time.

**Comment by fish4terrisa-MSDSM** [comment]
> I managed to build box64 against glibc in native termux(https://github.com/termux-pacman/glibc-packages I installed glibc and other stuffs like gcc from here to compile box64), but found it kinda useless, since most programs require libraries that haven't been ported to termux, you need to either build them yourself or to manually download dependencies from a "normal" distribution like archlinuxarm and extract those things to a proper location, launch your program with LD_LIBRARY_PATH and hope everything works. Plus if you want to use wine you need to patch it to avoid it writing to /tmp. This really wastes tooooo much time.

Can you send me the binary you built? It sounds interesting,as then we can run static x64 binary directly in termux.

**Comment by fish4terrisa-MSDSM** [comment]
> I managed to build box64 against glibc in native termux(https://github.com/termux-pacman/glibc-packages I installed glibc and other stuffs like gcc from here to compile box64), but found it kinda useless, since most programs require libraries that haven't been ported to termux, you need to either build them yourself or to manually download dependencies from a "normal" distribution like archlinuxarm and extract those things to a proper location, launch your program with LD_LIBRARY_PATH and hope everything works. Plus if you want to use wine you need to patch it to avoid it writing to /tmp. This really wastes tooooo much time.

And ,can you tell me more details about how you built it?Much Thanks: )

**Comment by 500InternalError** [comment]
> > I managed to build box64 against glibc in native termux(https://github.com/termux-pacman/glibc-packages I installed glibc and other stuffs like gcc from here to compile box64), but found it kinda useless, since most programs require libraries that haven't been ported to termux, you need to either build them yourself or to manually download dependencies from a "normal" distribution like archlinuxarm and extract those things to a proper location, launch your program with LD_LIBRARY_PATH and hope everything works. Plus if you want to use wine you need to patch it to avoid it writing to /tmp. This really wastes tooooo much time.
> 
> Can you send me the binary you built? It sounds interesting,as then we can run static x64 binary directly in termux.

I've deleted it. But you can use my PKGBUILD if you want to build it(Notice that my PKGBUILD misplaces the `etc` folder, but it's not a big problem). You can follow these steps:

1. Switch your package manager to pacman, you can follow official [guide](https://wiki.termux.com/wiki/Switching_package_manager)
2. Edit `/data/data/com.termux/files/usr/etc/pacman.conf` and enable gpkg-dev repository.
3. Install base-devel, cmake and all packages in gpkg-dev repo(some packages are not needed, but for convenience I installed all of them). 
4. Clone the aur repo https://aur.archlinux.org/box64-git.git and replace the PKGBUILD it with my [PKGBUILD.txt](https://github.com/ptitSeb/box64/files/11924562/PKGBUILD.txt).
5. Run `grun --shell`, then run `makepkg -si` and you have box64 installed.
