### ISSUE TITLE
[RV64] JIT of vector instructions

### ISSUE THREAD

**Issue by xctan** [ptitSeb/box64#595]
RISC-V is still a young architecture that has more extensions to be added. Currently, the “V” vector extension is in a [frozen state](https://github.com/riscv/riscv-v-spec/tree/57998875a3aebfe53407e82f1ec9fda0fef746c7) and is expected to be ratified in the near future. T-Head has implemented a draft version (namely 0.7.1) of the V extension in their cores before, but apparently this is not widely adopted by most distros.

As a result, we still lack real-world support for the (stable) vector extension as of now. This poses a challenge if we want to directly translate ARM neon instructions to their RISC-V V counterparts. Should we leave these instructions to the emulation interpreter or use scalar instructions as a workaround?

**Comment by ptitSeb** [comment]
I have some idea to workaround the lack of vector instructions. I'll work on that later, when I start implementing x87 and SSE opcodes. I need to work on some infrastructure first, but it will come...

**Comment by ksco** [comment]
Is it ok to add floating point instructions now? Is the infrastructure ready? We're running out of integer scalar instructions.

**Comment by ptitSeb** [comment]
Yes, float infrasturture is ready. I have put some x87 and SSE2 "SS" and "SD" instructions already.
Convertion to int and comparison are not done yet and might be tricky to do, but the other can be added.

the other SSE/SSE2+ can be done also, but I think I'll create some helper macro to help the writting, so prefer x87/SS/SD opcode for now.

**Comment by ksco** [comment]
@xctan This can be closed I think, as we've implemented a whole bunch of SIMD opcode.
