### ISSUE TITLE
libatomic missing, Valheim dedicated server

### ISSUE THREAD

**Issue by sb1337** [ptitSeb/box64#609]
Hello,

when trying to run a valheim dedicated server on the Raspberry Pi the server is fully functional except crossplay with Xbox. For crossplay to work we need the "libparty.so" which cannot be loaded because of this error message:

Error: Symbol __atomic_load not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa9e24150 (0x971876) in /DATA/usb1/private/valheim/app/valheim_server_Data/Plugins/libparty.so
Error: Symbol __atomic_exchange not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa9e24158 (0x971886) in /DATA/usb1/private/valheim/app/valheim_server_Data/Plugins/libparty.so
Error: relocating Plt symbols in elf libparty.so
Unable to preload the following plugins:
	libparty.so

**Comment by sb1337** [comment]
This is no duplicate to https://github.com/ptitSeb/box64/issues/472
In 472 they try to run valheim server together with a modding framework.

**Comment by s91402001** [comment]
@sb1337 Could you share your configurations for building a pi 4 dedicated server? I would like your OS version, ram size, and other helpful information since I also want to deploy a dedicated server on my 4GB pi4. Thanks!

**Comment by LukeShortCloud** [comment]
All of the requested functions have been wrapped. Closing as resolved.
