### ISSUE TITLE
Nvidia G-Sync demo

### ISSUE THREAD

**Issue by Grima04** [ptitSeb/box64#61]
When trying to run the 64-Bit (Windows) version of the Nvidia G-Sync Demo from [here](https://www.nvidia.com/de-de/geforce/community/demos/) on box64 with Wine 6.0 upstream from PlayOnLinux, the demo crashes due to an unimplemented opcode:

`6014|0x10004f834: Unimplemented Opcode (00) 66 8C C8 66 89 43 38 66 8C D0 66 89 43 42 41`

**Comment by Grima04** [comment]
Thanks for the quick implementation. Now there is another unimplemented opcode:
`9281|0x140415fc3: Unimplemented Opcode (C0) C5 E1 73 D0 34 C4 E1 F9 7E C0 C5 E1 FB 1D BB`

**Comment by ptitSeb** [comment]
This is an AVX opcode. That's not in Box64 scope for now!

**Comment by theofficialgman** [comment]
If you were just looking for a gsync and gsync demo for Linux, you can use this
https://github.com/dahenry/gl-gsync-demo

**Comment by rajdakin** [comment]
AVX is now supported by box64. Can this issue be closed now?

**Comment by LukeShortCloud** [comment]
@Grima04 Let us know if you encounter any further issues. As @rajdakin mentioned, AVX is implemented now. Closing as resolved.
