### ISSUE TITLE
Error: PltResolver: Symbol expl(ver 4: expl@GLIBC_2.2.5) not found, cannot apply R_X86_64_JUMP_SLOT

### ISSUE THREAD

**Issue by IvanYu123** [ptitSeb/box64#616]
I'm running a X86_64 application in Ubuntu and got this error message:
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Error: PltResolver: Symbol expl(ver 4: expl@GLIBC_2.2.5) not found, cannot apply R_X86_64_JUMP_SLOT 0x2fe7040 (0x414e46)

**Comment by IvanYu123** [comment]
Thanks very much. 
This issue fixed. But I got another error message:

Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Error: Unsupported Syscall 0x66h (102)
Segmentation fault

Could you please help?

**Comment by IvanYu123** [comment]
Error: Unsupported Syscall 0x8Ch (140)
It seems still need more syscall.

**Comment by antisaint81** [comment]
Hi, I figured since my issue s alsow ith R_X86_64_JUMP_SLOT I would mention here instead of starting a new issue, also with X86_64 in Ubuntu. 

Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Error: PltResolver: Symbol gdk_screen_get_monitor_workarea(ver 0: gdk_screen_get_monitor_workarea) not found, cannot apply R_X86_64_JUMP_SLOT 0x1024f5178 (0x102249b96)

**Comment by xingyi-engine** [comment]
hi, I get the same question with aarch64 in ubuntu too.
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A55 with 4 Cores
Will use Hardware counter measured at 24.0 MHz emulating 3.0 GHz
Params database has 89 entries
Box64 with Dynarec v0.3.1  built on Sep  6 2024 06:22:00
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 37 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/
Looking for STM32_Programmer_CLI
Rename process to "STM32_Programmer_CLI"
Using emulated /home/firefly/stm32CubeProg/bin/../lib/libcrypto.so.1.1
Using native(wrapped) libusb-1.0.so.0
Using emulated /home/firefly/stm32CubeProg/bin/../lib/libSTLinkUSBDriver.so
Using emulated /home/firefly/stm32CubeProg/bin/../lib/libjlinkarm.so.7
Using emulated /home/firefly/stm32CubeProg/bin/../lib/libhsmp11.so
Using native(wrapped) libdl.so.2
Using emulated /home/firefly/stm32CubeProg/bin/../lib/libQt6SerialPort.so.6
Using emulated /home/firefly/stm32CubeProg/bin/../lib/libQt6Xml.so.6
Using emulated /home/firefly/stm32CubeProg/bin/../lib/libQt6Qml.so.6
Using emulated /home/firefly/stm32CubeProg/bin/../lib/libQt6Core.so.6
Using native(wrapped) libpthread.so.0
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using emulated /home/firefly/stm32CubeProg/lib/libicui18n.so.56
Using emulated /home/firefly/stm32CubeProg/lib/libicuuc.so.56
Using emulated /home/firefly/stm32CubeProg/lib/libicudata.so.56
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libgthread-2.0.so.0
Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
Look for arc4random in loaded elfs
Warning, function arc4random not found in lib libbsd.so.0
Look for arc4random in loaded elfs
Warning, function arc4random not found in lib libbsd.so.0
Look for statx in loaded elfs
Warning, function statx not found in lib libc.so.6
Look for statx in loaded elfs
Warning, function statx not found in lib libc.so.6
Look for renameat2 in loaded elfs
Warning, function renameat2 not found in lib libc.so.6
Using emulated /home/firefly/stm32CubeProg/lib/libQt6Network.so.6
Using native(wrapped) libgssapi_krb5.so.2
Using native(wrapped) libresolv.so.2
Look for statx in loaded elfs
Warning, function statx not found in lib libc.so.6
Look for statx in loaded elfs
Warning, function statx not found in lib libc.so.6
Error: PltResolver: Symbol  statx(optver 33: statx@GLIBC_2.28) not found, cannot apply R_X86_64_JUMP_SLOT 0x3f086b6340 (0x3f080b6686) in /home/firefly/stm32CubeProg/bin/../lib/libQt6Core.so.6 (local_maplib=(nil), global maplib=0x60511250, deepbind=0)

**Comment by ptitSeb** [comment]
This function has just been added to box64 with #1800 , please update box64 and try again.

**Comment by xingyi-engine** [comment]
Thank you so much, I have updated box64 and try again, but the result is same.

Using native(wrapped) libz.so.1
Using native(wrapped) libgthread-2.0.so.0
Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
Look for arc4random in loaded elfs
Warning, function arc4random not found in lib libbsd.so.0
Look for arc4random in loaded elfs
Warning, function arc4random not found in lib libbsd.so.0
Look for statx in loaded elfs
Warning, function statx not found in lib libc.so.6
Look for statx in loaded elfs
Warning, function statx not found in lib libc.so.6
Look for renameat2 in loaded elfs
Warning, function renameat2 not found in lib libc.so.6
Using emulated /home/firefly/stm32CubeProg/lib/libQt6Network.so.6
Using native(wrapped) libgssapi_krb5.so.2
Using native(wrapped) libresolv.so.2
Look for statx in loaded elfs
Warning, function statx not found in lib libc.so.6
Look for statx in loaded elfs
Warning, function statx not found in lib libc.so.6
Error: PltResolver: Symbol  statx(optver 33: statx@GLIBC_2.28) not found, cannot apply R_X86_64_JUMP_SLOT 0x3f086b6340 (0x3f080b6686) in /home/firefly/stm32CubeProg/bin/../lib/libQt6Core.so.6 (local_maplib=(nil), global maplib=0x6766a1d0, deepbind=0)

firefly@firefly:~/box64$ git log
commit a450b9d12f99df13adcae4a570aeb780964d43b2 (HEAD -> main, origin/main, origin/HEAD)
Author: ptitSeb <sebastien.chev@gmail.com>
Date:   Fri Sep 6 18:01:40 2024 +0200

    [ARM64_DYNAREC] Improved AVX.66.0F38 8C opcode

**Comment by ptitSeb** [comment]
Oh, there is `Warning, function statx not found in lib libc.so.6` so I need to add some workaround it seems.

**Comment by ptitSeb** [comment]
First, I wil this ticket, because it the initial issue 'adding wrapping for `expl` function, has been done, and more unrelated issues are added, wich is a garantied to have the issue never fixed...

Second, I checked on my system, and `statx` exist but seems fairly recent in glibc: 2.28. So, not sure how easy it is to have a workaround for this call. I'll see if there is an easy way, but I'm not sure for now.

If you want to have a workaround for this, please open a new ticket.

**Comment by xingyi-engine** [comment]
thank you very much, it works. 

commit a6d7d83fb383a5c8cf9cde68af4136f7e2345259 (HEAD -> main, origin/main, origin/HEAD)
Author: ptitSeb <sebastien.chev@gmail.com>
Date:   Sat Sep 7 09:20:45 2024 +0200

    Added a workaround with syscall if statx function is not defined in libc

commit a450b9d12f99df13adcae4a570aeb780964d43b2
