### ISSUE TITLE
Missing lib downloader support

### ISSUE THREAD

**Issue by hex007** [ptitSeb/box64#63]
I have written a small script that downloads and extracts the missing libs automatically on being provided the name logged by box64 as a missing lib. It is a hasel to keep downloading and running only to find another dependency missing.

Is there a recommendation or any roadmap about incorporating something similar into box64/86 ?

I can share the bash script if not so.

**Comment by Painadath** [comment]
@hex007 please post the link to the script here it will be a big help as there is a lot of missing libs wheni try to run and app

**Comment by khanhduytran0** [comment]
Why don't you just setup multiarch instead?

**Comment by khanhduytran0** [comment]
(that skip qemu then use apt to install amd64 libs)

**Comment by Painadath** [comment]
@hex007 how did u get library name from log or how do u download it?

**Comment by hex007** [comment]
I have to manually launch the tool I am calling libget. It downloads from one of the online rpm/deb sources. 

I haven't had time to refine the script so it currently has hardcoded session tokens and if I release that then the token will get invalidated soon and the script will fail.

I will post it as soon. As I have it cleaned up

**Comment by Painadath** [comment]
@hex007 can u contact me i want to work in the donwloader
my discord id: White Lizard#8408

**Comment by Painadath** [comment]
@hex007 from where do u download pkgs

**Comment by rajdakin** [comment]
There is no such planned feature and will likely never be, as the goal of box is to run on as many platforms as possible, as fast as possible, with as few dependencies as possible. Automatically installing missing libraries would require to add at least a networking dependency and a lot more difficulties (such as knowing which libraries to install and where to find the missing libraries), which are outside the scope of this project.
