### ISSUE TITLE
Running Stardew Valley on VisionFive 2

### ISSUE THREAD

**Issue by ksco** [ptitSeb/box64#635]
I'm trying to run Stardew Valley on the VisionFive 2 SBC, and encountered the following errors, what should I do to fix this?

```
Dynarec for RISC-V PageSize:4096 Running on unknown riscv64 cpu with 4 Cores
Params database has 22 entries
Box64 with Dynarec v0.2.3 5e680e0f built on Mar 25 2023 03:53:49
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
BOX64 will force the used of emulated libs for libSDL2-2.0.so.0
Using default BOX64_PATH: ./:bin/
Counted 27 Env var
Looking for Stardew Valley
Rename process to "Stardew Valley"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /root/Downloads/squashfs-root/usr/lib/StardewValley/libhostfxr.so
Using emulated /root/Downloads/squashfs-root/usr/lib/StardewValley/libhostpolicy.so
Using emulated /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so
Warning: Global Symbol _ZTH12t_ThreadType not found, cannot apply R_X86_64_GLOB_DAT @0x3f9c1b1110 ((nil)) in /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so
Warning: Global Symbol _ZTH27t_pStackWalkerWalkingThread not found, cannot apply R_X86_64_GLOB_DAT @0x3f9c1b1128 ((nil)) in /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so
Warning: Global Symbol _ZTHN9StressLog19t_pCurrentThreadLogE not found, cannot apply R_X86_64_GLOB_DAT @0x3f9c1b1148 ((nil)) in /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so
Warning: Global Symbol _ZTH15t_CantStopCount not found, cannot apply R_X86_64_GLOB_DAT @0x3f9c1b1160 ((nil)) in /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so
Warning: Global Symbol _ZTH16t_CantAllocCount not found, cannot apply R_X86_64_GLOB_DAT @0x3f9c1b1250 ((nil)) in /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so
Warning: Weak Symbol __gmon_start__ not found, cannot apply R_X86_64_JUMP_SLOT @0x3f9c1b1650 (0x71e86)
Warning: Weak Symbol _ZTH12t_ThreadType not found, cannot apply R_X86_64_JUMP_SLOT @0x3f9c1b16e8 (0x71fb6)
Warning: Weak Symbol _ZTH27t_pStackWalkerWalkingThread not found, cannot apply R_X86_64_JUMP_SLOT @0x3f9c1b16f0 (0x71fc6)
Warning: Weak Symbol _ZTHN9StressLog19t_pCurrentThreadLogE not found, cannot apply R_X86_64_JUMP_SLOT @0x3f9c1b1708 (0x71ff6)
Warning: Weak Symbol _ZTH15t_CantStopCount not found, cannot apply R_X86_64_JUMP_SLOT @0x3f9c1b1710 (0x72006)
Warning: Weak Symbol _ZTH16t_CantAllocCount not found, cannot apply R_X86_64_JUMP_SLOT @0x3f9c1b1778 (0x720d6)
Error: Symbol pthread_mutexattr_setrobust not found, cannot apply R_X86_64_JUMP_SLOT @0x3f9c1b1e40 (0x72e66) in /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so
Error: Symbol pthread_mutex_consistent not found, cannot apply R_X86_64_JUMP_SLOT @0x3f9c1b1e58 (0x72e96) in /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so
Error: relocating Plt symbols in elf libcoreclr.so
Error initializing needed lib /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so
Failed to load /root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so, error: Cannot dlopen("/root/Downloads/squashfs-root/usr/lib/StardewValley/libcoreclr.so"/0x369a3918, 1)

FillBlock at (nil) triggered a segfault, cancelling
FillBlock at (nil) triggered a segfault, cancelling
1983|Ask to run at NULL, quit silently
```

**Comment by ptitSeb** [comment]
2 missing symbol on pthread, I'll check that on my side and will add them

**Comment by ksco** [comment]
So symbols from a native .so need to be manually added in order to be resolved?

**Comment by ptitSeb** [comment]
I have added the symbol (it's pushed also). But it's crashing for me, I'm investigating...

**Comment by ksco** [comment]
Yeah, I applied the latest commits, now it ends with:
```
FillBlock at (nil) triggered a segfault, cancelling
FillBlock at (nil) triggered a segfault, cancelling
3468|Ask to run at NULL, quit silently
```

**Comment by ksco** [comment]
Seems something bad happened in DynaRec.

**Comment by ptitSeb** [comment]
Yeah, I'm debugging it. It's quite difficult, has part of the issue seems to be inside a block generated by mono JIT.
I have found 2 issues already, but it's still failling...
Once all dynarec issue are fixed, I'll hae to look at wrapping libicu...

**Comment by ksco** [comment]
Tried using v0.22 with this commit https://github.com/ptitSeb/box64/commit/56e980556236709f287b87ab41b643a5607d4982 applied at the top, it ended with `Sigfault/Segbus while quitting, exiting silently`. So something is broken outside Dynarec maybe.

**Comment by ptitSeb** [comment]
I have found the issue. I'll push the fix in a couple of hour I think...

**Comment by ksco** [comment]
Wow, Stardew Valley works?

**Comment by ptitSeb** [comment]
Need top finish the wrapping of libicu and we'll see.

**Comment by ptitSeb** [comment]
I got it to works on my VisionFive 2 with the default Derbian image.
I needed to install locale first, or it would crash:
```BASH
sudo apt install locales
sudo dpkg-reconfigure locales
```
I used `en-US-UTF8` but any will probably work.
The system SDL2 is not configured for OpenGL, only GLES, so I needed to use the emulated version and gl4es, so I launched with
```BASH
LD_LIBRARY_PATH=~/git/gl4es/lib box64 ./Stardew\ Valley
```
The emulated SDL2 is automaticaly picked up.

It takes ages to load (like 20min?) and is too slow for now. So more opcodes needs to be implemented for this one :)

![stardewvalley](https://user-images.githubusercontent.com/3250792/229086359-12d6e64a-0490-4f61-939d-1ca20e2c9814.png)

**Comment by ksco** [comment]
Still super cool! trying it out now.

**Comment by ksco** [comment]
Got it working too.

**Comment by ptitSeb** [comment]
Now it needs more opcodes...
You can run with `BOX64_DYNAREC_LOG=1 LD_LIBRARY_PATH=~/git/gl4es/lib box64 ./Stardew\ Valley | grep stopped` to see the missing opcode in the dynarec (and you can ctrl-c when you have enough).
As you can see, a lot are missing!

**Comment by ksco** [comment]
OK, I would consider implementing these opcodes first. ;)

**Comment by ksco** [comment]
https://ksco.cool/aCrw

OK, got a long-enough list, I'll try to implement these.

**Comment by ptitSeb** [comment]
There is a lot of duplicate (that's a good news), but there are someanying one, like the C1 "rol" or all the F0 locked ones...

**Comment by ptitSeb** [comment]
Made a reddit entry for this: https://www.reddit.com/r/RISCV/comments/127hiq8/still_a_bit_slow_as_dynarec_is_not_complete_but/

**Comment by ksco** [comment]
Stardew Valley runs OK on VisionFive 2, it's just a bit too slow. I'll recheck this game once I got a more powerful RISC-V device.

**Comment by ksco** [comment]
@xctan and I found that if we turned hotpage off with `BOX64_DYNAREC_HOTPAGE=0`, the game becomes super smooth...

**Comment by ksco** [comment]
The cutscenes can run at full speed, and the gameplay is around 15fps, but you can clearly feel the lack of some opcodes. So, it can be even better.

**Comment by ksco** [comment]
> I can add a specific entry in box64.box64rc file for this game in the mean time.

Yeah, please do that, at least for now..

**Comment by ksco** [comment]
Actually this game runs fully in Dynarec now, but it's playable anyway ;)

**Comment by josch** [comment]
@ptitSeb if Stardew Valley runs on the VF2, does that mean it should also run fine on arm64? I'm still getting these errors: https://github.com/ptitSeb/box64/issues/293#issuecomment-1501432748 Should I open a new issue about this? I'd really love to get Stardew Valley running (even if slow) on my Cortex A52. :)

**Comment by ksco** [comment]
@josch I'm assuming you're running a GOG version of Stardew Valley. Try to remove everything in your `x86_64-linux-gnu` folder and reinstall box64 again.

**Comment by ksco** [comment]
The lack of `libliblttng-ust` shouldn't cause any issue, but if you have an x86-64 lib that box64 can find and use, things will be different.

**Comment by ptitSeb** [comment]
I did a video of Stardew valley running on the VF2 and posted it on Reddit https://www.reddit.com/r/RISCV/comments/12yuze1/video_of_stardew_valley_running_on_a_riscv/

It's mostly loading time, but there is some game play...
