### ISSUE TITLE
packaging for Debian

### ISSUE THREAD

**Issue by josch** [ptitSeb/box64#639]
Hi,

I packaged box64 for Debian here: https://salsa.debian.org/debian/box64/

One of the problems I encountered was, that box64 tries to install files that are owned by the `libgcc-s1:amd64` and `libstdc++6:amd64` packages, namely `/lib/x86_64-linux-gnu/libgcc_s.so.1` and `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`, respectively. This is a bit of a bummer because this means that the arm64 box64 package will have to conflict with both amd64 libraries. This in turn will make it impossible for a user who wants to install box64 to install any amd64 packages making use of the amd64 gcc and C++ libraries.

Why is this important? Proprietary amd64 Debian packages that I'd like to try running with box64 will also depend on the gcc and C++ library packages. If the arm64 box64 package conflicts with the amd64 libraries, then I will be unable to install proprietary amd64 packages that I want to use with box64 to avoid having to use super slow QEMU user emulation.

I wonder: do you think there is a way for the arm64 box64 package to co-exist with the amd64 gcc and C++ libraries?

**Comment by ptitSeb** [comment]
I can move the libs to some other place, or not package the libs at all. The libs are just the amd64 one, that I have put here for conveniance. But there are optionnal (just very usefull for simple "make install").

**Comment by josch** [comment]
Thank you for your super quick reply!

If they are optional, could you add a CMake switch to allow not installing them? Currently I'm patching CMakeLists.txt to avoid their installation:

https://salsa.debian.org/debian/box64/-/blob/master/debian/patches/install.patch

**Comment by ptitSeb** [comment]
Ok, All add a switch to not package/install them. Any idea of the name of the switch?

**Comment by josch** [comment]
What are the consequences of not having those installed? Maybe that should be part of the name so that somebody using the switch knows what they are doing?

**Comment by ptitSeb** [comment]
If you don't have it installed, most x86 program will not run, as most program have some c++ dependancy nowadays. The message that libstdc++ or libgcc_s is missing should be quite clear.
But if the system have amd64 foreign architecture installed, box64 will find the libs there, so the one in the box64 repo are not needed in that case.
I would assume an install of box64 (or box86) without libs is for use allongside a `dpkg --add-architexture x86_64` or something like that.

**Comment by josch** [comment]
Thank you, that makes sense! Maybe `-DUSE_MULTIARCH_STDCPP` or `-DNO_INSTALL_AMD64_LIBCPP`?

Then I'd add a dependency on `libgcc-s1:amd64` and `libstdc++6:amd64` to the Debian box64 package so that the libraries will definitely be present when one installs box64:arm64 with that switch enabled.

**Comment by ptitSeb** [comment]
`NO_LIB_INSTALL` is probably more simple, and more generic. I'll do that for both box64 and box86.

**Comment by ptitSeb** [comment]
I've pushed 6ff68849f88cbec622fe7a485e301111319ab8d6
Is it what you needed?

**Comment by josch** [comment]
The commit contains some riscv64 related changes that are not relevant for this problem, right?

Other than those, the NO_LIB_INSTALL related changes look exactly like what I was looking for. Feel free to close this issue. Thank you!

**Comment by ptitSeb** [comment]
Yeah, sorry. I saw that I missed riscv64 stuff so I added it at the same time.

**Comment by josch** [comment]
No problem. I just remove those parts when applying your patch on top of my packaging until you make a new release including that commit.

I have a small follow up question now that I'm reading the riscv64 related code you added: I saw in the CMakeLists.txt that box64 can be run on arm64 (of course) but also on ppc64el, loongarch and riscv64. But if I'm reading it correctly, then you can also build and run it on x86_64 (amd64) and i686? How does it make sense to run box64 on the intel arches?

Feel free to close this issue any time. Thanks!

**Comment by ptitSeb** [comment]
I run box64 on x86_64 for debugging purpose only. It make no sense in a practical point of view.

**Comment by josch** [comment]
The latest box64 release (from March) is now part of Debian unstable. It would be nice to have another release tagged soon because the version from March is lacking behind in many ways compared to what is currently in git.

Thanks!

**Comment by ptitSeb** [comment]
> The latest box64 release (from March) is now part of Debian unstable. It would be nice to have another release tagged soon because the version from March is lacking behind in many ways compared to what is currently in git.
> 
> Thanks!

Yes, I'm working on getting box stable to release a new stable soon! Hopefully in less than 2 weeks it will be tagged :)

**Comment by LukeShortCloud** [comment]
Box64 is now packaged for Debian. Closing as resolved.
