### ISSUE TITLE
maybe its helpful

### ISSUE THREAD

**Issue by abasgames** [ptitSeb/box64#66]
https://github.com/luo9674/VGPU

**Comment by ptitSeb** [comment]
I have gl4es, that is more advance than this for now.

**Comment by abasgames** [comment]
what about now ? https://github.com/luo9674/VGPU/releases/tag/v1.2-beta

**Comment by ptitSeb** [comment]
no thanks.
I'll add GL 3.x support eventually. You are free to use VGPU if you prefer.
