### ISSUE TITLE
add64 overflow calculation whether mistake？

### ISSUE THREAD

**Issue by acbbghhgf** [ptitSeb/box64#67]
```C
static inline uint64_t add64(x64emu_t *emu, uint64_t d, uint64_t s)
{
	emu->res.u64 = d + s;
	emu->op1.u64 = d;
	emu->op2.u64 = s;
	emu->df = d_add64;
    return emu->res.u64;
}
```
(x64primop.h)

Here, the result of adding two 64 bits is stored in type of Uint64_t,  The most significant overflow result is lost in this Uint64_t type.

Is that right?

**Comment by ptitSeb** [comment]
Yes it is. The Carry is computed based on `d` and `s` in that case.

**Comment by ptitSeb** [comment]
Can I close the ticket now?

**Comment by rajdakin** [comment]
Closing now (no answer since last request).
