### ISSUE TITLE
Error installing intel dpc++ compiler on linux (QT)

### ISSUE THREAD

**Issue by turbobuilt** [ptitSeb/box64#675]
I'm trying to install intels dpcpp++ compiler downloaded from here:
https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#dpcpplibrary

Unfortunately I get an error with QT.  Any idea what's up or how to fix?  Thanks so much for the help!

box64 l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline.sh 

Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on unknown aarch64 cpu with 2 Cores
Params database has 22 entries
Box64 with Dynarec v0.2.3 900f3877 built on Mar 22 2023 07:33:12
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 47 Env var
Looking for l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline.sh
Not an ELF file (sign=#!/b)
Error: reading elf header of /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline.sh, try to launch natively instead
Extract l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline to /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline...
[##########################################################################################################################################]
Extract l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline completed!
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on unknown aarch64 cpu with 2 Cores
Params database has 22 entries
Box64 with Dynarec v0.2.3 900f3877 built on Mar 22 2023 07:33:12
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 47 Env var
Looking for /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/bootstrapper
Rename process to "bootstrapper"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/lib/libQt6Core5Compat.so.6
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/lib/libQt6Widgets.so.6
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/lib/libQt6Network.so.6
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/lib/libQt6Gui.so.6
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/lib/libQt6DBus.so.6
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/lib/libQt6Core.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libxkbcommon.so.0
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/plugins/platforms/libqxcb.so
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/plugins/platforms/../../lib/libQt6XcbQpa.so.6
Using native(wrapped) libxkbcommon-x11.so.0
Using native(wrapped) libxcb-icccm.so.4
Using native(wrapped) libxcb-image.so.0
Using native(wrapped) libxcb-keysyms.so.1
Using native(wrapped) libxcb-randr.so.0
Using native(wrapped) libxcb-render-util.so.0
Using native(wrapped) libxcb-shm.so.0
Using native(wrapped) libxcb-sync.so.1
Using native(wrapped) libxcb-xfixes.so.0
Using native(wrapped) libxcb-render.so.0
Using native(wrapped) libxcb-shape.so.0
Using native(wrapped) libxcb-xkb.so.1
Using native(wrapped) libxcb.so.1
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/lib/libxcb-xinput.so.0
Using native(wrapped) libXau.so.6
Using emulated /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/plugins/imageformats/libqgif.so
Error: PltResolver: Symbol xcb_xfixes_set_cursor_name(ver 0: xcb_xfixes_set_cursor_name) not found, cannot apply R_X86_64_JUMP_SLOT 0xffff7e5cf358 (0xffff7e35cd26) in /home/parallels/Downloads/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline/plugins/platforms/../../lib/libQt6XcbQpa.so.6
Sigfault/Segbus while quitting, exiting silently

**Comment by ptitSeb** [comment]
Ok, I have added the missing function. You can update box64 and try again.
