### ISSUE TITLE
[RPi4] Cannot get symbol in libicu

### ISSUE THREAD

**Issue by DevilBlackDeath** [ptitSeb/box64#690]
I tried to run ScourgeBringer and got a couple of symbols not found in the executable but most notably one in libicu. Based on what I read in other issues, I assume this is a symbol that's not wrapped yet but I'm not 100% sure.

This is all using the native Linux Steam version of ScourgeBringer, using Goldberg Emulator to disable the Steam API. The Goldberg Emulator I have confirmed to be working on multiple games that require Steam already including Jumpjet Rex and Chasm. Running on Raspberry Pi 4 4GB with latest Raspbian bullseye 64 bit, all packages up-to-date. I DID have to compile my own libicu as earlier logs reported box64 looking for v72 of the libs, which is not the one in Raspbian official packages (fairly unsurprising as I've had so many issues with raspbian libraries not being up to date with upstream x86/64 debian).

The two other missing symbols at the beginning I have no idea whether they play into the game crashing though.

Here's the log :
[scourgebringer.txt](https://github.com/ptitSeb/box64/files/11210581/scourgebringer.txt)

**Comment by DevilBlackDeath** [comment]
Well that was fast :) 
On Raspbian x64, v67.1-7 is reported as being used by apt ;)

**Comment by ptitSeb** [comment]
Ok, I have added support for icu 67 (same as 72)

**Comment by DevilBlackDeath** [comment]
Just tried it, now box64 unfortunately complains about "u_strcpy_72" (which I assume would translate to u_strcpy_67 for icu67, which was easily confirmed by running the game with the default library from the package manager).

**Comment by ptitSeb** [comment]
Ok, function added.

**Comment by ksco** [comment]
You can try to add the missing functions by yourself and PR it back. ;) It will be faster if you do it locally. See this blog post for how library wrapping works: https://box86.org/2021/08/a-deep-dive-into-library-wrapping/

**Comment by DevilBlackDeath** [comment]
Yeah I was thinking about that ! Don't know about faster considering the time it takes to build box64 on the pi :P But at least I won't bother ptitSeb for every little missing wrappers for libicu !

**Comment by ptitSeb** [comment]
> Huh I wonder if there'd be a way on my part to let the application run further and let me know all missing symbols from that library cause now it's "u_astrcpy_72" (or 67).
> 
> Isn't there a way using BOX64 command line variables to for the application to keep executing and report all missing symbols even if it would normally cause a crash ?

Not really. and because it's dynamic symbol grabbed with dlsym certainly, but only when needed, there isn't much you can do. Usualy a `BOX64_DLSYM_ERROR=1` would help, but not here it seems.

**Comment by DevilBlackDeath** [comment]
> > Huh I wonder if there'd be a way on my part to let the application run further and let me know all missing symbols from that library cause now it's "u_astrcpy_72" (or 67).
> > Isn't there a way using BOX64 command line variables to for the application to keep executing and report all missing symbols even if it would normally cause a crash ?
> 
> Not really. and because it's dynamic symbol grabbed with dlsym certainly, but only when needed, there isn't much you can do. Usualy a `BOX64_DLSYM_ERROR=1` would help, but not here it seems.

Meaning it could very well be loading all symbols and I wouldn't know it until the end... Well I'll at least give it a shot.

**Comment by ksco** [comment]
It's not gonna be loading all symbols, it'll just load symbols that the program needs.

**Comment by DevilBlackDeath** [comment]
Circumvented so far using Wine. The game runs great on Wine even on a Pi 4 so I doubt performances would be an issue. Aside from the minor issue I mentioned of Wine failing half its execution the game runs really great so I'm closing the issue for now.

Will reopen once I get around to wrapping the missing functions but there's no point in leaving a hanging issue open when it has a workaround and is not actively being worked on (and I'm not about to request every function the game lists as missing as I think there's probably more pressing matters on your end).
