### ISSUE TITLE
[RPi4] BotVice - missing libssl symbol

### ISSUE THREAD

**Issue by DevilBlackDeath** [ptitSeb/box64#691]
While running BotVice, it would seem libssl is missing the 'SSL_load_error_strings'.

Run under the same circumstances as ScourgeBringer. While I've SSL_load_error_strings in the past it's the first time it's a showstopper.

[botvice.txt](https://github.com/ptitSeb/box64/files/11212040/botvice.txt)
Edit : Similar issue running Nuclear Throne with box86. This may come from the Goldberg emulator when games require specific Steam functions. If that is the case however I feel like wrapping this function would probably be beneficial. This is the best way to run Linux-native Steam games on ARM-based devices, especially low-end ones where you actively don't want the Steam client running in background.

here is the end of the BOX64_LOG=2 log (I can upload the whole thing if needed) :
[botvice2.txt](https://github.com/ptitSeb/box64/files/11212185/botvice2.txt)

Edit 2: Just to further confirm, box86 suffers from the same missing wrapped function in libssl. Should I create another issue for box86 or should I consider that any missing function for either one will be wrapped for the other as well when creating an issue ?

After looking at libssl's wrapping, load_error_strings seems to be wrapped, so I'm not sure about why this happens. I'll compile an up-to-date libssl and try again !

**Comment by DevilBlackDeath** [comment]
Ok so after rereading the log it seems the function is not found in my libssl but I have no idea why... Building libssl from the openssl repo  can only create versions 1.1 and 3 which don't create the correct files (I have tried creating a symlink with the correct name and adding its path to LD_LIBRARY_PATH, didn't work either).

**Comment by DevilBlackDeath** [comment]
It would seem some GameMaker games have issues, even though a lot work too. Unfortunately they crash without box64 giving a message (other than the libSSL one but I doubt it's crashing it, as other games and app keep running even with that function missing). Most failing games can be run through wine to go around the issue (Bot Vice being seemingly the only exception, but I'll look for the exact reason later). Feel free to close the issue if the log or base issue have nothing helpful for you anymore !

**Comment by ptitSeb** [comment]
Nucleat Throne should work with box86. I have tried it already. But the linux version that came from itch.io was not working (not working an on x86 pc, not only with box86).
For Bot Vice, I have no idea, I never tried it, and I'm not sure I have a copy of this somewhere to try it out.

**Comment by DevilBlackDeath** [comment]
> Nucleat Throne should work with box86. I have tried it already. But the linux version that came from itch.io was not working (not working an on x86 pc, not only with box86). For Bot Vice, I have no idea, I never tried it, and I'm not sure I have a copy of this somewhere to try it out.

Even with box86 on aarch 64 ? My copy is from Steam though I haven't tested it on x86 Linux proper. Maybe both Linux native versions have the same issue, worth a try looking at it. I'll give Bot Vice a try at the same time.
