### ISSUE TITLE
Some problems of R_RIP assignment

### ISSUE THREAD

**Issue by Mr-HappyLI** [ptitSeb/box64#72]
x64run.c ==>
...
case FF:
...
    case 4:
        R_RIP = (uintptr_t)getAlternate((void*)ED->q[0]);
        STEP
        break;
    case 5:
        if(nextop>0xc0){
 ...   
        }else {
            R_RIP = ED->q[0];
            R_CS = (ED+1)->word[0];
 ...

Why the first ‘R_ RIP = (uintptr_t)getAlternate((void*)ED->q[0]);’ and second ‘R_RIP = ED->q[0];’？
I think the second place should be ‘R_RIP = (uintptr_t)getAlternate((void*)ED->q[0]);’, right?

**Comment by ptitSeb** [comment]
yes, but a check on CS should be done, not that I expect CS to change (and it will probably not work if it does). That opcode should not be used often (if used at all), but I'll make the change.

**Comment by Mr-HappyLI** [comment]
OK,thanks.
