### ISSUE TITLE
On an ARM64 phone, when running wine64 cmd with Box64, it can enter the command line normally but will automatically exit after a while.

### ISSUE THREAD

**Issue by szllzs** [ptitSeb/box64#728]
this is full trace.log
[trace.log](https://github.com/ptitSeb/box64/files/11302846/trace.log)

**Comment by ptitSeb** [comment]
I don't see anything on this log. It seems to just exited normaly.
Did you built box64 with `BAD_SIGNAL`? It's important on Termux.

**Comment by szllzs** [comment]
> I don't see anything on this log. It seems to just exited normaly. Did you built box64 with `BAD_SIGNAL`? It's important on Termux.

I'm going to give it a try. thanks

**Comment by szllzs** [comment]
[log_file_nodyn.txt](https://github.com/ptitSeb/box64/files/11421945/log_file_nodyn.txt)
Hi, I'm trying to add BAD_ SIGNAL, no effect. Later, I prohibited dynamic recompilation and found a segment error in box64, with the log on top
