### ISSUE TITLE
Life is Strange (Unimplemented Opcode (1C) 64 41 F7 51 04 44 89 7C 24 4C 48 B9 79 35 14)

### ISSUE THREAD

**Issue by Firlaev-Hans** [ptitSeb/box64#73]
The Feral Interactive Linux port of Life is Strange 1 doesn't launch and produces this log:
[log.txt](https://github.com/ptitSeb/box64/files/6884584/log.txt)

**Comment by Firlaev-Hans** [comment]
Now there's no "Unimplemented Opcode" message anymore and this window appears, so that's progress:
![LiS_JetsonNano_UnsupportedGPU](https://user-images.githubusercontent.com/61254500/127295081-f85c5fad-6d0e-4e37-a6e8-30e395ae8c46.png)
But clicking any of the buttons just makes the window disappear and nothing happens, and the nothing more is printed to the terminal.
I'm running this on a NVIDIA Jetson Nano, whose GPU should definitely be able to run the game. But it seems like some OpenGL functions needed by the game are not wrapped yet or something like that.
New log: [log.txt](https://github.com/ptitSeb/box64/files/6891687/log.txt)

**Comment by ptitSeb** [comment]
Yes, according to the log, I need to wrap many new OpenGL functions... I'll work on that later.

**Comment by Firlaev-Hans** [comment]
The behavior has not changed. These are the remaining warnings:
```
Warning, function SSL_library_init not found in lib libssl.so.1
Warning, function SSL_library_init not found in lib libssl.so.1
Warning, function SSL_library_init not found in lib libssl.so.1
Warning, function sk_new_null not found in lib libcrypto.so.1
Warning, function sk_new_null not found in lib libcrypto.so.1
Warning, function sk_new_null not found in lib libcrypto.so.1
Warning, function sk_push not found in lib libcrypto.so.1
Warning, function sk_push not found in lib libcrypto.so.1
Warning, function sk_push not found in lib libcrypto.so.1
LifeIsStrange: crash reporter initialised with path "/home/firlaev-hans/.local/share/feral-interactive/Life Is Strange/crashes"
Warning, call to __cxa_thread_atexit_impl(0x65f470, 0xa06a3188, 0x34bbee8) ignored
Warning, call to __cxa_thread_atexit_impl(0x65e370, 0xa06a3178, 0x34bbee8) ignored
Using emulated ../lib/x86_64/libsteam_api.so
Error: Symbol canonicalize_file_name not found, cannot apply R_X86_64_JUMP_SLOT @0x7f5adf2a10 (0xf8fd6) in ../lib/x86_64/libsteam_api.so
Warning: Weak Symbol __gmon_start__ not found, cannot apply R_X86_64_JUMP_SLOT @0x7f5adf7e30 (0x103816)
Error: relocating Plt symbols in elf libsteam_api.so
Error initializing needed lib libsteam_api.so
Warning: Cannot dlopen("libsteam_api.so"/0x25780d1, 2)
Using native(wrapped) libGL.so.1
Warning, no wrapper for glMultiDrawElementsIndirectBindlessNV
Warning, call to __cxa_thread_atexit_impl(0x65f470, 0x7f50001a88, 0x34bbee8) ignored
Warning, call to __cxa_thread_atexit_impl(0x65e370, 0x7f50001a78, 0x34bbee8) ignored
Warning, no wrapper for glMultiDrawElementsIndirectBindlessNV
Warning, call to __cxa_thread_atexit_impl(0x8e11e0, 0xa0cd55b8, 0x34bbee8) ignored
Warning, call to __cxa_thread_atexit_impl(0x8e11e0, 0xa0cd5588, 0x34bbee8) ignored
```
The process still hangs after clicking continue or anything else. I'm not certain that the missing OpenGL functions are actually the cause.

**Comment by ptitSeb** [comment]
Probably not, but I'll still add them.
You may need to switch to emulated for `libssl.so.1` and `libcrypto.so.1`. Use `BOX86_EMULATED_LIB=libssl.so.1:libcrypto.so.1`
Also maybe add `libcurl.so.4` in the list. You'll need the x86 version of them in the game folder or it will fallback to wrapped native version.

**Comment by Firlaev-Hans** [comment]
That environment variable (I assume you meant `BOX64_EMULATED_LIBS`) didn't seem to help, the process still hung (I let it sit there for several minutes knowing how slow loading times in box86/64 can be)

However with these latest commits we're back to a segfault and no GPU warning window:
```
Warning, call to __cxa_thread_atexit_impl(0x65f470, 0x87566968, 0x34bbee8) ignored
Warning, call to __cxa_thread_atexit_impl(0x65e370, 0x87566958, 0x34bbee8) ignored
Using emulated ../lib/x86_64/libsteam_api.so
Warning: Weak Symbol __gmon_start__ not found, cannot apply R_X86_64_JUMP_SLOT @0x7f612d4e30 (0x103816)
13733|SIGSEGV @0x6498a60c (???(/usr/local/bin/box64/0x6498a60c)) (x64pc=0x7f60e28380/../lib/x86_64/libsteam_api.so:"???", rsp=0x7f8eb07db0, stack=0x7f8e309000:0x7f8eb09000 own=(nil) fp=0x868d5310), for accessing 0x103816 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=0x23cecd0
13733|Double SIGSEGV (code=1, pc=0x6498a60c, addr=0x103816)!
```
Although I'm not sure if this is a regression and we're crashing BEFORE the GPU warning, or if the GPU warning simply no longer appears because all the missing GL extensions are wrapped now.

**Comment by ptitSeb** [comment]
All extensions are wrapped, I assume the gl warning is gone?

can you do `addr2line -e /usr/local/bin/box64 -a 0x6498a60c`

**Comment by Firlaev-Hans** [comment]
Yeah as I said there is no longer a graphics driver warning or missing GL function.
```
0x000000006498a60c
/home/firlaev-hans/git/box64/src/dynarec/dynarec_arm64_functions.c:337
```

**Comment by Firlaev-Hans** [comment]
Actually, nevermind. The crash is obviously dynarec related, so I just tried it without it.
Without the dynarec, the graphics warning window still appears, and now we get a bit further when clicking continue:
[log.txt](https://github.com/ptitSeb/box64/files/6893674/log.txt)
And after that I still get some more stuff in the terminal that isn't redirected to the log:
```
[0728/155438:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[0728/155439:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/firlaev-hans/.pki/nssdb): NSS error code: -8023
[0728/155439:ERROR:nss_util.cc(207)] Error initializing NSS without a persistent database: NSS error code: -8023
[0728/155439:FATAL:nss_util.cc(209)] nss_error=-8023, os_error=0
Segmentation fault (core dumped)
[0728/155451:ERROR:nss_util.cc(981)] Failed to load NSS libraries.
[0728/155451:ERROR:zygote_linux.cc(585)] write: Broken pipe
[0728/155452:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1
```
We're getting closer to seeing the launcher I think.

**Comment by Firlaev-Hans** [comment]
The dynarec doesn't segfault anymore and gets just as far as the interpreter. In other words, the launcher still doesn't open.
BUT: I copied the preferences file from my main PC to the Jetson Nano where I disabled "Always show this config menu" to bypass the launcher. Lo and behold, the game works fine:
![LiS_JetsonNano_Working_FPSCounter](https://user-images.githubusercontent.com/61254500/127345053-d749285f-9a33-4333-b359-cc85efcac8a2.png)
Performance isn't great on 1280x800 low settings, but it is heavily CPU limited three cores are used 100% and the remaining one 85%ish. That was to be expected from the Jetson Nano I guess, as this is a 2015 Unreal Engine 3 game.
Anyways, the launcher problem is not fixed but at least there's a workaround to get in-game.

**Comment by ptitSeb** [comment]
I think the launcher use Chrome (or libecf, which is chrome too). box64 (and box86) have issues with chrome for now....

Glad to see it working yes :) (I should finish that one, only done 1st episode and barely started the 2nd one).
You can use `BOX64_DYNAREC_LOG=1` to see if there are some missing opcode on the dynarec.

**Comment by ptitSeb** [comment]
Can I close the ticket? Chromium issue is something else I think.
