### ISSUE TITLE
GOG Installer stopped working

### ISSUE THREAD

**Issue by ksco** [ptitSeb/box64#740]
```
Collecting info for this system...
Operating system: linux
CPU Arch: x86_64
trying mojosetup in bin/linux/x86_64
USING en_US
Dynarec for RISC-V PageSize:4096 Running on unknown riscv64 cpu with 4 Cores
Params database has 25 entries
Box64 with Dynarec v0.2.3 922e5beb built on Apr 17 2023 15:40:30
BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/
BOX64_PATH: ./:bin/
Counted 32 Env var
Looking for /tmp/selfgz395716368/bin/linux/x86_64/mojosetup
Rename process to "mojosetup"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
NOTICE: scripts/mojosetup_init.lua:148: <eof> expected near 'end'
[hit enter]
```

**Comment by ptitSeb** [comment]
I reproduce that also on ARM64 machine. It seems to be an issue with load/unload of libs (I guess). I'll debug that tomorrow.

**Comment by ksco** [comment]
Last week I tried it was working well, so something recently introduced this issue.

**Comment by ksco** [comment]
Interesting. If you run it from a different directory than where the GOG install script sits, it works fine.

**Comment by ksco** [comment]
Is this fixed on ARM64? I haven't figured out what the cause is in RV64, but it seems not related to box64.

**Comment by ptitSeb** [comment]
I could run GOG installer on ARM64 yes. But I'm not sure we had the exact same issue.

**Comment by ksco** [comment]
Can you run the installer from the current folder? e.g. `cd Downloads && ./some_gog_installer.sh`. I have to run it with `Downloads/some_gog_installer.sh`, the former way will cause an error.

**Comment by ptitSeb** [comment]
I run installer with `BOX64_BASH=~/git/box64/tests/bash box64 ./some_installer.sh` on my side, to use x86_64 bash and box64

**Comment by ksco** [comment]
Yes, I'm assuming we are in an x86_64 bash above. Anyway, if this works on ARM64, can you try it on VF2 then? Don't know if it's something wrong with my environment.

**Comment by ptitSeb** [comment]
I just tried on RV64 with ftl installer, from the download folder, and it works fine. I launched the gtk2 installer with no issue (still a bit slow tho).
