### ISSUE TITLE
Running Bastion on VisionFive 2

### ISSUE THREAD

**Issue by ksco** [ptitSeb/box64#748]
Running Bastion on VisionFive 2 (using gl4es and emulated SDL2), the game screen is tilted 45 degrees. I read on this [post](https://magazine.odroid.com/article/playing-modern-fna-games-on-the-odroid-platform/) that gl4es supports running Bastion, so I'm guessing it might be a box64 issue. I don't currently have x86-64 Linux with a monitor available, so no way to verify for now.

![IMG_4978](https://user-images.githubusercontent.com/15257961/235280434-d73b8e8c-d82f-411a-87b9-6a4360af8e1e.jpg)

**Comment by ptitSeb** [comment]
Wow, that is really odd!
Yeah, gl4es should support bastion (but I haven't tried it for a long time). I need to check on an ARM device if it runs fine also.

**Comment by xctan** [comment]
Tested and have the same issue in qemu-user. By bisecting commits, the culprit is https://github.com/ptitSeb/box64/commit/93abd016 and I plan to fix it.

**Comment by xctan** [comment]
Detailed examination reveils that this game is using x87 FSIN and FCOS to calculate sin() and cos(). FSTP 
is used to retrieve the result from x87 regs, which is implemented in the above commit and happens to trigger a bug in JIT'ed trigonometric functions, so everything coincidentally rotates 45 degrees.

**Comment by ptitSeb** [comment]
Ok, I found some issue with a few x87 helper function. I haven't tested Bastion yet, but I guess it should help. Can you try with latest sources?

**Comment by ksco** [comment]
Wow, nice. I’m still on my vacation, I’ll try it later today.

**Comment by xctan** [comment]
@ptitSeb, Bastion now works without rotation.

**Comment by ksco** [comment]
Does the gameplay works also? It segfaulted with some errors directly displayed on the game window before the fix.

**Comment by xctan** [comment]
Gameplay works at around 14 fps.

**Comment by ksco** [comment]
Great, I’ll try on VF2 later. And we’re now have another test target, seems a lot of opcodes are missing for this game.

**Comment by ksco** [comment]
It works on VF2 also (gameplay fps is under 10), but in full-screen mode, the screen will jump and flicker, not sure what the issue is.

**Comment by ptitSeb** [comment]
It can be a gl4es issue.

**Comment by ksco** [comment]
> It can be a gl4es issue.

Yeah, probably. @xctan did you try full-screen on your qemu-user setup? Is it function well?

**Comment by xctan** [comment]
This game runs in full-screen (by default) without any glitch on my setup.

**Comment by ksco** [comment]
Then it probably is a gl4es issue.
