### ISSUE TITLE
Wine broken after last commits

### ISSUE THREAD

**Issue by Ilya114** [ptitSeb/box64#754]
Hi, I has collect box64 in 30 April 2023, Wine 7.20 working fine. Today, I collect Box64 and Wine won't working now. Disks not showing, If I try to recreate prefix Wine showing: `wine: could not load kernel32.dll, status c0000135`. Last commits has broke Wine? 
Hardware: POCO X3 Pro, Snapdragon 860, 6/128, Arrow OS 13, (Android 13, Box64 launching in Termux proot environment), Box64 compiled with BAD_SIGNAL

**Comment by Ilya114** [comment]
> Can you try to `git bisect` the issue to find the actual commit that broken it

I'm a didn't using this command nothing, so can make error
![Screenshot_20230504-082218_Termux_1](https://user-images.githubusercontent.com/93242944/236118443-d8ab589c-824d-4ce9-9945-5cdad14d3c0e.png)

**Comment by Ilya114** [comment]
> Box64 compiled with BAD_SIGNAL

Ah, I forgot add this to compile script but even with this, still same problems

**Comment by ptitSeb** [comment]
to use git bisect, you need to define the interval of version were it's bad and good.
So
`git checkout main`
to go to latest sources and 
`git bisect bad`
because it's now broken
then
`git checkout 464d868af5439ea9f6e6e0db2d97b62add8e219b`
That's a checkout from 29th of April, so I assume it was working then
`git checkout good`
And now, git will automaticaly select a new commit. Just build and test, then use `git bisect good` or `git bisect bad` if it works or not, and git will automaticaly select the next checkout until the 1st bad commit is found (it will be printed on the conolse).
Then you can use `git bisect reset` to finish bissecting
(note that you canot use the git bisect command from the `build` directory, you need to be at the root of box64 folder)

**Comment by ptitSeb** [comment]
I tried to reproduce the issue on my side, but it worked fine.
I use Wine 8.1 tkg
Using a new wineprefix I launched:
`WINEPREFIX=~/.wine_new wine64 explorer`
The wineprefix gots created and Explorer launched, and I could see `C:` and `Z:`

**Comment by Ilya114** [comment]
> I use Wine 8.1 tkg

Try this: https://github.com/Kron4ek/Wine-Builds/releases/download/7.20/wine-7.20-amd64.tar.xz

**Comment by Ilya114** [comment]
> to use git bisect, you need to define the interval of version were it's bad and good. So `git checkout main` to go to latest sources and `git bisect bad` because it's now broken then `git checkout 464d868af5439ea9f6e6e0db2d97b62add8e219b` That's a checkout from 29th of April, so I assume it was working then `git checkout good` And now, git will automaticaly select a new commit. Just build and test, then use `git bisect good` or `git bisect bad` if it works or not, and git will automaticaly select the next checkout until the 1st bad commit is found (it will be printed on the conolse). Then you can use `git bisect reset` to finish bissecting (note that you canot use the git bisect command from the `build` directory, you need to be at the root of box64 folder)
> 
> (The BAD_SIGNAL might help a lot with all the other games that were failing)

Hm, after compile from 29 April I still have `c0000135`, but when I using clean rootfs with 30 April Box64 all working fine. When compiling new box64 all builds are broke

**Comment by ptitSeb** [comment]
What commit works ad what commit doesn't work for you?

As I can't reproduce on my side, I need you to help me narrrow down what could be the cause of this.

**Comment by Ilya114** [comment]
> What commit works ad what commit doesn't work for you?
> 
> As I can't reproduce on my side, I need you to help me narrrow down what could be the cause of this.

April 30, I think I was collecting this box64: https://github.com/ptitSeb/box64/tree/31a6f5c4e32b267bad84057f3b53ad87a53c049c
----
I just checked on clean rootfs, everything works with the current branch. But for some reason, when I try to build to update on the currently configured rootfs, Wine does not work. I don't want to rebuild Mesa, reinstall dependencies. I can send you logs if you need

**Comment by ptitSeb** [comment]
So, this commit 31a6f5c4e32b267bad84057f3b53ad87a53c049c is working fine for you. But not the nexts ones?
It's very trange, there isn't much changes in the next commit tbh
Most are touching RV64 build wich should have 0 impact on you side.
The only few that might changes things are:
c983418cb3a1a711013bc8026ac9ecd309092233 (adding 1 function to libicu)
cbf71f678aea5ebb463daded486a45a267647be2 (change log level if stdout is redirected)
494f054ef4d94210c07ca046e049900f507b4ac5 (adding 1 opcode to dynarec, could be this one maybe)
3a4d58f114a2f030f0937abae4c0ef7ec882641a (changing malloc_hack_2 behaviour, that should not change anything for wine)
60d2efc74b4fe9d9dc907726040ea780bda4247f (rolling back previous change)

Can you try those commit and see if they work or not on your side?

**Comment by Ilya114** [comment]
> [c983418](https://github.com/ptitSeb/box64/commit/c983418cb3a1a711013bc8026ac9ecd309092233) (adding 1 function to libicu)

Disks not showing. I will try `make uninstall` before next compile

**Comment by ptitSeb** [comment]
The libicu one? that's so strange!

can you get me logs when running with `BOX64_DLSYM_ERROR=1`
I will need the full log.

**Comment by Ilya114** [comment]
> 

Now Wine not starting

[log.txt](https://github.com/ptitSeb/box64/files/11396351/log.txt)

**Comment by ptitSeb** [comment]
using `BOX64_DLSYM_ERROR=1 wine64 explorer` is not working?

**Comment by Ilya114** [comment]
> using `BOX64_DLSYM_ERROR=1 wine64 explorer` is not working?

Nope, here is full log:
[log.txt](https://github.com/ptitSeb/box64/files/11396664/log.txt)

**Comment by ptitSeb** [comment]
There seems to be an segfault happening: `002c:err:virtual:virtual_setup_exception nested exception on signal stack in thread 002c addr 0x102044d87 stack 0x67fef590`
But no idea were.
Can you add `BOX64_SHOWSEGV=1` and try again?

**Comment by Ilya114** [comment]
[log.txt](https://github.com/ptitSeb/box64/files/11396859/log.txt)

**Comment by Ilya114** [comment]
> But no idea were.

So I was most likely left without new Box64 assemblies(

**Comment by Ilya114** [comment]
> Don't rebuild box64 and do `addr2line -e box64 -a 0x349eb8e0` (not sure where is the binary, so might need to adjust the path)

Don`t rebuild mean use current build or from 30 april?

**Comment by Ilya114** [comment]
![Screenshot_20230504-143037_Termux_1](https://user-images.githubusercontent.com/93242944/236191755-be9fb643-1b25-41d1-ad43-c6771e09e02f.png)

**Comment by ptitSeb** [comment]
> Don`t rebuild mean use current build or from 30 april?

Use the build from the last log. This is the address of the segfault, and it's inside box64, so want to see where that error comes from.

**Comment by Ilya114** [comment]
> Use the build from the last log. This is the address of the segfault, and it's inside box64, so want to see where that error comes from.

Well, I pushed above

**Comment by ptitSeb** [comment]
That's from the same build that generated the last log.txt?

**Comment by ptitSeb** [comment]
that still makes no sense. I don't understand what's going on, because box64stack as nothing to do with BOX64_DLSYM_ERROR flag.

Lets try something else: run explorer with something like:
```
BOX64_DLSYM_ERROR=1 BOX64_SHOWSEGV=1 BOX64_SHOWBT=1 BOX64_LOG=1 BOX64_TRACE_FILE=~/log-%pid.txt wine64 explorer
```
That will generate a few log-XXX.txt file in your home with logs per process.

**Comment by Ilya114** [comment]
[log-28471.txt](https://github.com/ptitSeb/box64/files/11397020/log-28471.txt)
[log-28471-1.txt](https://github.com/ptitSeb/box64/files/11397022/log-28471-1.txt)
[log-28470.txt](https://github.com/ptitSeb/box64/files/11397023/log-28470.txt)
[log-28469.txt](https://github.com/ptitSeb/box64/files/11397024/log-28469.txt)
[log-28460.txt](https://github.com/ptitSeb/box64/files/11397025/log-28460.txt)
[log-28460-1.txt](https://github.com/ptitSeb/box64/files/11397026/log-28460-1.txt)
[log-28442.txt](https://github.com/ptitSeb/box64/files/11397027/log-28442.txt)
[log-28442-1.txt](https://github.com/ptitSeb/box64/files/11397028/log-28442-1.txt)

**Comment by ksco** [comment]
Irrelevant:

> addr2line -e box64 -a 0x349eb8e0

Wow, this can be useful! @ptitSeb  Please consider writing a post on how to debug box64.

**Comment by ptitSeb** [comment]
@Ilya114 remove the logs files from your home (to not mix with the new one) and try again but without the `BOX64_DLSYM_ERROR=1` flag.

**Comment by Ilya114** [comment]
[log-29495.txt](https://github.com/ptitSeb/box64/files/11397146/log-29495.txt)
[log-29495-1.txt](https://github.com/ptitSeb/box64/files/11397147/log-29495-1.txt)
[log-29494.txt](https://github.com/ptitSeb/box64/files/11397148/log-29494.txt)
[log-29493.txt](https://github.com/ptitSeb/box64/files/11397149/log-29493.txt)
[log-29484.txt](https://github.com/ptitSeb/box64/files/11397150/log-29484.txt)
[log-29484-1.txt](https://github.com/ptitSeb/box64/files/11397151/log-29484-1.txt)
[log-29466.txt](https://github.com/ptitSeb/box64/files/11397152/log-29466.txt)
[log-29466-1.txt](https://github.com/ptitSeb/box64/files/11397153/log-29466-1.txt)

**Comment by Ilya114** [comment]
> (to not mix with the new one)

Already removed before try

**Comment by Ilya114** [comment]
> Does this file `/root/wine-amd64/lib/wine/x86_64-unix/wineboot.so` exist on your side?

No, but how its worked without it on previous box64 builds?

**Comment by ptitSeb** [comment]
I'm still trying to understand what is happening.
Can you do the log thing with a working build?

**Comment by ptitSeb** [comment]
I think the build that fail doesn't have Dynarec enabled. Can  you double check that?

**Comment by Ilya114** [comment]
> I think the build that fail doesn't have Dynarec enabled. Can you double check that?

Ohhh, I thought -DARM_DYNAREC=ON inclueded in standard config, no, it`s not included

**Comment by Ilya114** [comment]
> BAD_SIGNAL

I never understood what it is. Btw, in Wine have some issues: GOG installers not work, Unity games crashing

**Comment by Ilya114** [comment]
![Screenshot_20230504-155641_Termux_X11](https://user-images.githubusercontent.com/93242944/236211195-87045d70-7b41-4360-b89c-459447b7c7d1.png)

It works

**Comment by ptitSeb** [comment]
> > BAD_SIGNAL
> 
> I never understood what it is. Btw, in Wine have some issues: GOG installers not work, Unity games crashing. You are know about this problems?

No, I'm not aware of those issue. On my side, on Debian and other linux system, GOG Installer works fine, and most Unity3D games too.

For GOG Installers, make sure you have `BOX64_BASH` setup correctly, and launch the installer with `box64 ./gog_install.sh` You need to use "box64" prefix here to let box64 load x86_64 bash to run the install shellscript.
Also, for GOG Installer, it's better to have arm64 gtk2 libs installed, to get the graphic installer (but texmode, using ncurses or just nothing should works too).

For Unit3D games, you need a `BAD_SIGNAL` build of box64. Termux doesn't handle signal in a 100% correct way compare to pure linux (probably because it cannot do that due to Android limitation), so with a `BAD_SIGNAL` build, when a signal occurs, there are some addition test to compensate for the signal not being 100% exact. It important for anything that have a JIT/Dynarec, like C#/Mono games, Java games, or Unit3D games (that use C#). Without it, the memory protection will not be handled correctly, and you'll get crash very quickly while the game load.

**Comment by Ilya114** [comment]
> No, I'm not aware of those issue. On my side, on Debian and other linux system, GOG Installer works fine, and most Unity3D games too.

Strange, [here](https://www.youtube.com/watch?v=FyvIZeKhJH8) you can see what it crashing in Wine

**Comment by ptitSeb** [comment]
But is that with a `BAD_SIGNAL` build of box64?

**Comment by Ilya114** [comment]
> But is that with a `BAD_SIGNAL` build of box64?

Yeah, from 30 April

**Comment by Ilya114** [comment]
> It's only Windows Unity3D games or Linux Unity3D games too?

I have to check and I will tell you in a new issue

**Comment by Ilya114** [comment]
> I have to check and I will tell you in a new issue

Have `shm_semaphores_init: semctl init error: Invalid argument - trying again`

**Comment by ptitSeb** [comment]
the semctl init issue might be a proot issue indeed. I'll check GOG Installer and Windows Unity3D games later

**Comment by ptitSeb** [comment]
So, I use "Absolute Drift" that I have on GOG to test. I took the Windows installer and could not install it (it hang with nothing happening).
It's fixed now. Take latest box86 (installer are 32bits apps  it seems) and it should install now. I did got a few error message at the end, but the program was installed correctly.
The game didn't launched when choosing "launch game" from the installer.
But launching it from command line, with `wine64` it launched and worked correctly.

**Comment by Ilya114** [comment]
> It's fixed now. Take latest box86

Yeah, it's work, thanks.
<details>

![Screenshot_20230505-083844_Termux_X11](https://user-images.githubusercontent.com/93242944/236384547-3fe7c0b1-6e6e-45a7-bab2-e4c7a2ee9c9c.png)
<details>

**Comment by Ilya114** [comment]
@ptitSeb what about Unity3D games in Wine?

**Comment by ptitSeb** [comment]
Absolute Drift is a Unity3D game. It's working fine on side. I also tried a few other small Unity3D Windows games and they were working fine for me.
