### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by zqpvr** [ptitSeb/box64#760]
user@host:~/Downloads/linux-x86_64$ ./SuperHaxagon 
Debug level is 1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096 Running on Cortex-A57 with 4 Cores
Params database has 25 entries
Box64 with Dynarec v0.2.3 464d868a built on Apr 30 2023 08:09:12
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 67 Env var
BOX64 try to Preload libgtk3-nocsd.so.0 
Looking for ./SuperHaxagon
Rename process to "SuperHaxagon"
Error loading needed lib libgtk3-nocsd.so.0
Warning, cannot pre-load of libgtk3-nocsd.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libsfml-graphics.so.2.5
Using emulated /usr/lib/x86_64-linux-gnu/libsfml-window.so.2.5
Using emulated /usr/lib/x86_64-linux-gnu/libsfml-audio.so.2.5
Using emulated /usr/lib/x86_64-linux-gnu/libsfml-system.so.2.5
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) libresolv.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXrender.so.1
Using native(wrapped) libudev.so.1

Using native(wrapped) libopenal.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2
Using native(wrapped) libvorbisfile.so.3
Using native(wrapped) libvorbis.so.0
Using native(wrapped) libogg.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libFLAC.so.12
Using emulated /usr/lib/x86_64-linux-gnu/libmvec.so.1
13078|0x7f840c2779: Unimplemented Opcode (37 31 00 00) C5 F9 EF C0 41 56 48 8D 3D 8A 8D FF FF 41 55
13078|0x7f84159a03: Unimplemented Opcode (E5 34 00 00) C5 FC 28 05 75 DD F8 FF 4C 89 EF C5 FC 28 0D
FillBlock at 0x58a0 triggered a segfault, cancelling
13078|SIGSEGV @0x34bbe024 (???(./SuperHaxagon+0x34bbe024)) (x64pc=0x58a0/???:"???", rsp=0x1007fede8, stack=0x100000000:0x100800000 own=(nil) fp=0x1007fedf0), for accessing 0x58a0 (code=1/prot=87), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000000000000000 RSP-0x18:0x0000000000000000 RSP-0x10:0x0000000000000000 RSP-0x08:0x00000001007fedf0
RSP+0x00:0x00000000000300c0 RSP+0x08:0x0000000000000000 RSP+0x10:0x0000000000000001 RSP+0x18:0x00000001007ff13a
RAX:0x0000000000000000 RCX:0x0000000000000000 RDX:0x00000001007fee10 RBX:0x0000000000000000 
RSP:0x00000001007fede8 RBP:0x00000001007fedf0 RSI:0x00000001007fee00 RDI:0x0000000000000001 
 R8:0x0000007f84428a70  R9:0x0000007f83fd9e98 R10:0x0000007f83fe6780 R11:0x0000000000000091 
R12:0x0000007f84060c60 R13:0x0000007f8415cee8 R14:0x0000000000000000 R15:0x0000000000000000 
Segmentation fault (core dumped)

**Comment by ptitSeb** [comment]
These are AVX opcodes. It is not supported for now on box64.
