### ISSUE TITLE
Running Blue Revolver on VF2 leads to OOM

### ISSUE THREAD

**Issue by ksco** [ptitSeb/box64#763]
Reproduce:

1. Download `[experimental] bluerevolver_v051_demo_linux.tar.gz` from https://woofycakes.itch.io/blue-revolver-v05
2. Uncompress it and run `box64 bin/love64 bin/game.love` (with gl4es and emulated SDL)

The game seems running fine, but memory usage will grow at a rate of 1GB/s until it gets killed. I already tried `BOX64_DYNAREC=0`, no help.

@xctan has run it on a native machine, and the memory usage is normal.

**Comment by ptitSeb** [comment]
interresting. I'll check, thanks for the details.

**Comment by xctan** [comment]
I tried this game with 0e14d42dcfc308fe011066c01394d72cbc8ee009 in qemu, the game crashed after entering gameplay (always press z without selecting other options), and the memory footprint was kept below 1 GB.
![image](https://user-images.githubusercontent.com/29012383/236412293-9e6e92ca-d31b-4638-b1a5-b6c491fbd894.png)

**Comment by ksco** [comment]
https://github.com/ptitSeb/box64/commit/0e14d42dcfc308fe011066c01394d72cbc8ee009 is two more commits away from the latest main, I've tried, also leads to OOM. So not the last two commits, but QEMU and SBC do behave inconsistently on this...

**Comment by ptitSeb** [comment]
Not sure on RV64 as I haven't tried yet, but I fixed all issues running this game on ARM64. It's a bit slowish when lots of action is occuring, but I haven't analysed what is happening yet.

**Comment by ksco** [comment]
I'll check that later today.

**Comment by ksco** [comment]
Seems it will report this error as soon as a bullet hits a target, looks like an opcode bug.

**Comment by ptitSeb** [comment]
Yeah, I don't have this on ARM64, it works fine. I played a couple of time and there was no errors.

**Comment by ksco** [comment]
Ok, I'll try fix the opcode bug.

**Comment by xctan** [comment]
I found this bug after running the game half an hour under cosim. The rounding mode should apply to the raw value, not the absolute one.

**Comment by ksco** [comment]
Cosim is awesome!

**Comment by ptitSeb** [comment]
That's strange, I think I saw that before, but it was ok because the sign bit was copied after the conversion.

**Comment by xctan** [comment]
And if the player is not shooting, the game runs at ~12 fps with much less danmaku.

**Comment by ptitSeb** [comment]
No, it should be closed. The performance issue is something completly different.
It something that you can also see, more or less, with other JIT based engined, like Mono/Unity3D (with Terraria or Broforce for example).
The solution is not clear yet, nor is the root cause of the slowdown...
