### ISSUE TITLE
Factorio: Unimplemented Opcode (02) 64 66 89 3C 25 D8 FF FF FF BF B0 C2 B4 01 64

### ISSUE THREAD

**Issue by Kirfkin** [ptitSeb/box64#77]
As per the title, I received an unimplemented Opcode error upon trying to save a game.

```
118546|0x1b48c05: Unimplemented Opcode (02) 64 66 89 3C 25 D8 FF FF FF BF B0 C2 B4 01 64
Library libc.so.6 (0x7b9546e0) needs 0x7d284770, but it was not found. Ignoring.
Library ld-linux-x86-64.so.2 (0x7b9549a0) needs 0x7d284770, but it was not found. Ignoring.
Library libpthread.so.0 (0x7b954500) needs 0x7d284770, but it was not found. Ignoring.
Library libm.so.6 (0x7b954320) needs 0x7d284770, but it was not found. Ignoring.
Library libdl.so.2 (0x7b954070) needs 0x7d284770, but it was not found. Ignoring.
Library libXext.so.6 (0x7b92c140) needs 0x7c347690, but it was not found. Ignoring.
Library libXext.so.6 (0x7b92c140) needs 0x7c344500, but it was not found. Ignoring.
Library libX11.so.6 (0x7b9265f0) needs 0x7c347690, but it was not found. Ignoring.
Library libX11.so.6 (0x7b9265f0) needs 0x7c344500, but it was not found. Ignoring.
Stop waiting for remaining thread 118550
Stop waiting for remaining thread 118551
Stop waiting for remaining thread 118552
Stop waiting for remaining thread 118553
Stop waiting for remaining thread 118554
Stop waiting for remaining thread 118555
Stop waiting for remaining thread 118556
Stop waiting for remaining thread 118557
Stop waiting for remaining thread 118560
Stop waiting for remaining thread 118599
Stop waiting for remaining thread 119263
Stop waiting for remaining thread 119264
Stop waiting for remaining thread 119265
Stop waiting for remaining thread 119266
Stop waiting for remaining thread 119267
Stop waiting for remaining thread 119268
Stop waiting for remaining thread 119269
119266|Double SIGSEGV (code=1, pc=0x648f4ce8, addr=0x48)!
119264|Double SIGSEGV (code=1, pc=0x648f4ce8, addr=0x48)!
```
That's from the Terminal. I can try to get you something better, log wise, if you tell me how.

EDIT:
For those curious, Factorio does work pretty well with some config changes, on the Pinebook Pro. I think most of hte issues -- other than saving because of the opcode issue -- are related to the Panfrost driver.

**Comment by Kirfkin** [comment]
I'll try to test this soon. Currently I'm just using the Manjaro ARM repository build, but I'll try to give the repo a build at some point this week to verify the fix.

Thanks for your hard work.

**Comment by ptitSeb** [comment]
Latest Factorio start for me on my Odroid N2, but I wrong graphics. I suspect it's a Panfrost issue and not box64, so it would be nice if youc an confirm/infirm that.

**Comment by Kirfkin** [comment]
Yea, the graphics issue is definitely a panfrost related issue. Let me pull out a few config options you should change that I believe resolve the worse of the issues:

`texture-compression-level=none`
I'm pretty sure that panfrost can't handle the texture compression well. Disabling it leads to minimal graphical issues when displayed.
`skip-vram-detection=true`
I'm not actually positive this does much, but since I know it detects the VRAM as 0, I decided it was probably worth trying.
`max-texture-size=256`
I did this because there's no compression, so I wanted to minimize the potential memory usage.
`texture-streaming=false`
This is another one that might be able to be set to true; I don't remember 100% if it resolved an issue or if it's something I changed during a test and forgot to log information about.

`legacy-gpu-no-mipmaps=true`
This setting resolved some weird behavior with blue textures; there's a small chance it could have been something else, but it certainly doesn't hurt to have it on.

`custom-mipmap-workaround=true`
As above, I enabled this to try to help resolve some of the weird texture and animation issues.

`buffer-rename-workaround=true`
I haven't actually yet verified if this one is necessary, but it doesn't hurt graphically to set it to true.

Otherwise, all other graphical settings are suggested to be as low as possible, or where you feel you get a comfortable frame rate. CPU and memory usage are relatively minimal, and it's definitely panfrost's performance holding it back. BOX64 is awesome.

![image](https://user-images.githubusercontent.com/15023742/127783917-98f146c2-b78d-491f-8a4a-5adf043efc11.png)

![image](https://user-images.githubusercontent.com/15023742/127783923-968d1893-075e-4fcb-b9e4-36e2c93275a9.png)
This image shows the most significant extent of the "ugliness" in textures with my settings. You'll be missing some particle effects and shadows behave poorly; but nothing is game breaking at this point.


Just to reiterate though: This is from the version before the fix you implemented. The missing Opcode prevented manual saves. To play the game, I just set the autosave interval to 2 minutes. So the graphical issues absolutely should not be related to Box64. Really impressive work, @ptitSeb .

**Comment by Kirfkin** [comment]
I can confirm this is fixed. Good work.
