### ISSUE TITLE
Valheim server crashes soon after start

### ISSUE THREAD

**Issue by genekellyjr** [ptitSeb/box64#770]
Valheim server crashes with

```
Thread 0xffff3c1c2020 may have been prematurely finalized
Setting up 2 worker threads for Enlighten.
  Thread -> id: fffefe7fe020 -> priority: 1 
  Thread -> id: fffefdffd020 -> priority: 1 
05/07/2023 16:15:13: Steam manager on destroy
```

It used to work on v0.2.2 so I'm guessing it was a Valheim update? I keep Valheim updated to latest release (and validated). The thread /#s change so I'm not sure how to get more info out of it.

These symbols are missing at the start:
```
Error: Symbol __atomic_load not found, cannot apply R_X86_64_JUMP_SLOT @0xffff77fea150 (0x971876) in /home/valheim/valheim_server/valheim_server_Data/Plugins/libparty.so
Error: Symbol __atomic_exchange not found, cannot apply R_X86_64_JUMP_SLOT @0xffff77fea158 (0x971886) in /home/valheim/valheim_server/valheim_server_Data/Plugins/libparty.so
Error: relocating Plt symbols in elf libparty.so
```

But I'm not sure they're essential and not sure if they were missing before Valheim updated.

Log output:
https://pastebin.com/vK64R6eP

Log err output:
https://pastebin.com/ZRxLY6Pt

This is installed on an Oracle AMPERE ARM instance. Also tested with latest commits (Box64 with Dynarec v0.2.3 0a558652 built on May  6 2023 21:34:16) and it didn't fix it. Box64 is built with `cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo`.

Let me know if there's something I'm missing or something I can do to get more useful info out of the crash! Thanks

**Comment by ksco** [comment]
Yes, they look essential, and they need to be properly wrapped.

**Comment by ptitSeb** [comment]
Those 2 symbols are already wrapped.
You use latest sources of box64 right?
