### ISSUE TITLE
Box64 BOX64_DYNAREC_BIGBLOCK=0

### ISSUE THREAD

**Issue by Sparda991** [ptitSeb/box64#783]
Hello. Do you know why BOX64_DYNAREC_BIGBLOCK=0 doesnt work on box64? I use box64droid for android and that variable just doesntnwork, drives go missing when using it. On box86 works with no issues tho.

**Comment by ptitSeb** [comment]
No, I don't know why.
I don't reproduce on my linux dev. machine. At least not with a already created WINEPREFIX. Maybe it's the prefix creation that fails?

BIGBLOCKS control how big the Dynarec blocks will be. The bigger they are, the more optimized the generated code will be, but that will also memory consuption bigger, bigger part of the code might end up in several Dynablocks.

the BIGBLOCKS=0 select the smallest size, and should not have any negative impact in stability. There must be something wrong in the dynarec cache managment of box64. I'm currently working on fixing an issue on RV64 that also impact the Dynarec Cache Managment, so it might be linked. We'll see once I fix the issue.

**Comment by Sparda991** [comment]
> No, I don't know why. I don't reproduce on my linux dev. machine. At least not with a already created WINEPREFIX. Maybe it's the prefix creation that fails?
> 
> BIGBLOCKS control how big the Dynarec blocks will be. The bigger they are, the more optimized the generated code will be, but that will also memory consuption bigger, bigger part of the code might end up in several Dynablocks.
> 
> the BIGBLOCKS=0 select the smallest size, and should not have any negative impact in stability. There must be something wrong in the dynarec cache managment of box64. I'm currently working on fixing an issue on RV64 that also impact the Dynarec Cache Managment, so it might be linked. We'll see once I fix the issue.

Thank you man. I updated box64 and BIGBLOCK finally works.THANKS A LOT!!!

**Comment by jserv** [comment]
Is it time to close this issue?

**Comment by LukeShortCloud** [comment]
Yes, this can be closed as completed.
