### ISSUE TITLE
Wrapping fopencookie

### ISSUE THREAD

**Issue by ksco** [ptitSeb/box64#787]
This function is used by [an old game](https://www.gog.com/zh/game/beneath_a_steel_sky) running on ScummVM, and it takes a struct `cookie_io_functions_t` as an argument.

```
typedef struct {
   cookie_read_function_t  *read;
   cookie_write_function_t *write;
   cookie_seek_function_t  *seek;
   cookie_close_function_t *close;
} cookie_io_functions_t;

FILE *fopencookie(void *restrict cookie, const char *restrict mode,
                  cookie_io_functions_t io_funcs);
```
IIUC, A struct of this size will be directly passed through the stack, and it needs to be reconstructed on the fly when calling the native libs. The callback functions also need to be properly wrapped (i.e. `GOM`). Wrapper infra doesn't have support for this kind of function it seems.

> A simple program for testing this function: https://ksco.cool/SAi4

**Comment by ptitSeb** [comment]
Mmmm, I need to think about this, but a signature like "pFEppV" should work. You than create 
```
EXPORT void* my_fopencookie(x64emu_t* emu, vpod* cookie, void* mode, my_cookie_io_function_t* s)
```
That should work, as `V` will gives a pointer to pointing at the stack directly.

**Comment by ksco** [comment]
Oh! Indeed! Let me try it.
