### ISSUE TITLE
Stranded Deep (Box64, Wine 8.0 Proton) 

### ISSUE THREAD

**Issue by Luihart** [ptitSeb/box64#791]
### Description
Stranded Deep, using Direct3D rendering by DXVK, using Box64 on Android (Box64Droid by Ilya).

Crashes on proot whether using DirectX11 or OpenGL renderer, when ingame. (Unity Banner Error)

On Chroot however it Boots ingame and you can Play the first plane Crash scene.

### Tested on
Proot:
Asus Rog Phone 3 8/256GB, Snapdragon 865, Android 12

Chroot:
Poco F3 8/256GB, Snapdragon 870, Android 13

### Status
None reported

**Current behavior:**
This issue occurs especially on Unity Games only.

### Screenshots
![Screenshot_20230517-131637039](https://github.com/ptitSeb/box86-compatibility-list/assets/97235637/263ee3a6-c44d-4ee0-ba10-9fcd889ce055)

### Additional Information
Player and player-prev Log attached

[Player.log](https://github.com/ptitSeb/box86-compatibility-list/files/11497567/Player.log)
[Player-prev.log](https://github.com/ptitSeb/box86-compatibility-list/files/11497575/Player-prev.log)

Previous conversation:
ptitseb:
Does this log is with BOX64_SHOWSEGV=1 env. var.? It seems not, there is no box64 logs there.

Me:
OK sorry, i will Transfer this over, and delete it Here.
To the Log Thing:
Well if there are no box64 logs then that means that the BOX64_LOG or BOX64_SHOWSEGV or both don't work. He has them enabled and He ran the games. Weird
![Screenshot_20230517-140157284](https://github.com/ptitSeb/box64/assets/97235637/391559f0-e262-438b-9293-dfccbe5a7366)

**Comment by ptitSeb** [comment]
Yeah, I still don't see anything anything, like if the signal handler was no installed at all on the proot.
I need to check what are the restriction of proot in termux...

**Comment by JohnGodgames** [comment]
Maybe it helps, but I've tried to start game with command line argument -force-gfx-direct (Force single threaded rendering) and game goes to ingame without crash (no root or BOX64_DYNAREC_BIGBLOCK=0).The same thing works for other games as well.
https://docs.unity3d.com/Manual/PlayerCommandLineArguments.html

**Comment by Luihart** [comment]
> Maybe it helps, but I've tried to start game with command line argument -force-gfx-direct (Force single threaded rendering) and game goes to ingame without crash (no root or BOX64_DYNAREC_BIGBLOCK=0).The same thing works for other games as well. https://docs.unity3d.com/Manual/PlayerCommandLineArguments.html

Thx i can confirm it works!!!
