### ISSUE TITLE
Error: PltResolver: Symbol vwprintf(ver 5: vwprintf@GLIBC_2.2.5) not found, cannot apply R_X86_64_JUMP_SLOT 0x11c6b10 (0x85de36)

### ISSUE THREAD

**Issue by vcanosa** [ptitSeb/box64#793]
I'm running a X86_64 application in Ubuntu and got this error message:
Using native(wrapped) libpthread.so.0
Using native(wrapped) libusb-1.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated libboost_filesystem.so.1.69.0
Using emulated libboost_chrono.so.1.69.0
Using emulated libboost_thread.so.1.69.0
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Error: PltResolver: Symbol vwprintf(ver 5: vwprintf@GLIBC_2.2.5) not found, cannot apply R_X86_64_JUMP_SLOT 0x11c6b10 (0x85de36)

**Comment by ksco** [comment]
This symbol needs to be wrapped to work, I’ll try to add it later.

**Comment by ksco** [comment]
Also, what program are you running, is it public available?

**Comment by ksco** [comment]
I wrapped `vwprintf` in the above PR, wait for it gets merged, then try again.

**Comment by LukeShortCloud** [comment]
The requested functions have been wrapped. Closing as resolved.
