### ISSUE TITLE
ubiorbitapi_r2.dll Support? Box64, Wine 8.0 Proton, Android

### ISSUE THREAD

**Issue by Luihart** [ptitSeb/box64#795]
### Description
Ubisoft Games, which require Game Launcher, doesnt work. However this Problem didnt exist in Exagear at all. Also using non pirated Software and installing ubi Connect Launcher result in Same Error with "a debugger has been found running on your system"

Using Box64Droid by Ilya for Android

### Tested on
Chroot:
Poco F3 8/256GB, Snapdragon 870, Android 13

### Status
None reported

**Current behavior:**
This issue occurs especially on Ubisoft Games with old Ubi Game launcher

### Screenshots
![Screenshot_2023-05-21-05-37-59-435_com termux x11](https://github.com/ptitSeb/box64/assets/97235637/a5363d8e-2165-49e7-a4a4-be268fefb808)

### Additional Information
Game used: Splinter Cell Conviction V1.0

**Comment by lexGg** [comment]
resolved ????? how

**Comment by ptitSeb** [comment]
this should have been solved, I hadded some anti-debugging feature in box86 & box64 a while ago.

**Comment by ptitSeb** [comment]
Can yo try again with latest version of box86+box64? It should be fixed now.

**Comment by LukeShortCloud** [comment]
Closing as resolved.
