### ISSUE TITLE
CCS studio dependancy check failed due to 32 bit Libraries

### ISSUE THREAD

**Issue by dev-rvk** [ptitSeb/box64#825]
Hey!
I tried installing Code Composer Studio on Ubuntu VM with the host as macOS.
It requires me to install the following libraries:
`sudo apt install libc6-i386 libusb-0.1-4 libgconf-2-4 libncurses5 libpython2.7 libtinfo5`

`libc6-i386` in particular is giving error, can't you please explain where I am going wrong? or is the app itself is not supported?

Link to dependency website : https://software-dl.ti.com/ccs/esd/documents/ccsv12_linux_host_support.html

Screenshot of dependency check screen:
<img width="792" alt="Screenshot 2023-06-07 at 12 53 05 PM" src="https://github.com/ptitSeb/box64/assets/66343753/c41fe5f6-3a6b-4325-84a8-defd9a71a6bd">

**Comment by ptitSeb** [comment]
Box64 only support 32bits code in Wine/WOW64. This app doesn't seems compatible as it rely on 32bits linux libs.
It would need box86 to work, but that's not an option on an M1, as 32bits is not supported.

**Comment by LukeShortCloud** [comment]
We recommend using Wine WoW64 builds from here with Box64 for the best results: https://github.com/Kron4ek/Wine-Builds/releases

If you have any further issues with that, please feel free to open a new GitHub Issue. Closing as resolved.
