### ISSUE TITLE
Error loading go binary

### ISSUE THREAD

**Issue by zalexdev** [ptitSeb/box64#83]
root@kali:/routerscan-console# **BOX64_LD_LIBRARY_PATH=. ./box64 routerscan scan --target 192.168.1.1:80 **
Box64 with Dynarec v0.1.3 4d9559f built on Aug  9 2021 22:41:35
BOX64_LD_LIBRARY_PATH: ./
Using default BOX64_PATH: ./:bin/
Counted 34 Env var
Looking for routerscan
argv[1]="scan"
argv[2]="--target"
argv[3]="192.168.1.1:80"
Using native(wrapped) libpthread.so.0
Using emulated liblibrouter.so
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libcrypto.so.1
Using native(wrapped) libdl.so.2
fatal: morestack on g0
**Then in the loop:**
"BOX64: Warning, calling Signal function handler SIG_IGN"

**Files:** (Last release) https://github.com/dilap54/RouterScan-console

System: **debian arm64**

**Comment by LukeShortCloud** [comment]
I believe there are still some lingering issues with Go binaries. For example, here's the Box64 output of running a simple program called [task](https://github.com/go-task/task). The program does not get far enough to fully load.

[go-task-box64.log](https://github.com/user-attachments/files/18214144/go-task-box64.log)

**Comment by ksco** [comment]
Note that Go is almost always static-linked while Box64 depends on some dynamic linking mechanisms to work properly, which will probably never change.

**Comment by LukeShortCloud** [comment]
I retested with FEX and they appear to support statically linked programs. The `task` binary worked. I guess we can recommend Box users to use QEMU (slow) or FEX (fast) for those applications.

**Comment by ptitSeb** [comment]
Of course FEX and QEMU support staticaly linked program. Because libc is emulated, so that doesn't change much.
But box64 is different on that aspect, as it wraps libc and all other libs. Not wrapping libc would means that most of the other mapping would imply not work, becasue the other libs also rely on libc...

**Comment by LukeShortCloud** [comment]
Since Box64 will not be supporting statically linked binaries, I'll close this as not planned.
