### ISSUE TITLE
Cant run any app with box64 - ArchLinuxARM

### ISSUE THREAD

**Issue by IsaacMvmv** [ptitSeb/box64#85]
I have a Pi4, arch linux arm installed, updated.

Uname -a:
```
Linux custom-pi 5.10.52-6-ARCH #1 SMP PREEMPT Tue Aug 3 18:19:31 UTC 2021 aarch64 GNU/Linux
```
For example, Untitled Goose Game (64bit unity game which has a linux edition)
run.sh:
```#!/usr/bin/env bash

# Move to the game directory
cd "$(dirname "$(realpath "$0")")" || exit

# Run the game
exec box64 ./"Untitled Goose Game" "$@"
```
Output:
```Box64 with Dynarec v0.1.3 4d9559f built on Aug  8 2021 19:29:11
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 38 Env var
Looking for ./Untitled Goose Game
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXss.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libudev.so.1
Set current directory to /home/pi/Untitled Goose Game
Found path: /home/pi/Untitled Goose Game/Untitled Goose Game
Error loading needed lib /home/pi/Untitled Goose Game/Untitled Goose Game_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
Warning: Cannot dlopen("/home/pi/Untitled Goose Game/Untitled Goose Game_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so"/0x7f88c9f030, 2)
Unable to load mono library from /home/pi/Untitled Goose Game/Untitled Goose Game_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
Failed to load mono
Stop waiting for remaining thread 1890

```

Any unity game gives same error.

Also  Garrys Mod linux compilation doesnt work 

start.sh

```#!/usr/bin/env bash

scriptdir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

cd "${scriptdir}"/game || exit 1

"${scriptdir}"/steam-runtime/run.sh ./hl2.sh -game garrysmod
```
hl2.sh:
```GAMEROOT=$(cd "${0%/*}" && echo $PWD)/bin/linux64
export LD_LIBRARY_PATH="${GAMEROOT}":$LD_LIBRARY_PATH
unset LD_PRELOAD
GAMEEXE=gmod

ulimit -n 2048

# enable nVidia threaded optimizations
export __GL_THREADED_OPTIMIZATIONS=1

# and launch the game
cd "$GAMEROOT"

# Enable path match if we are running with loose files
if [ -f pathmatch.inf ]; then
        export ENABLE_PATHMATCH=1
fi

# Do the following for strace:
#       GAME_DEBUGGER="strace -f -o strace.log"
# Do the following for tcmalloc
#   LD_PRELOAD=../src/thirdparty/gperftools-2.0/.libs/libtcmalloc_debug.so:$LD_PRELOAD

STATUS=42
while [ $STATUS -eq 42 ]; do
        if [ "${GAME_DEBUGGER}" == "gdb" ] || [ "${GAME_DEBUGGER}" == "cgdb" ]; then
                ARGSFILE=$(mktemp $USER.hl2.gdb.XXXX)
                echo b main > "$ARGSFILE"

                # Set the LD_PRELOAD varname in the debugger, and unset the global version. This makes it so that
                #   gameoverlayrenderer.so and the other preload objects aren't loaded in our debugger's process.
                echo set env LD_PRELOAD=$LD_PRELOAD >> "$ARGSFILE"
                echo show env LD_PRELOAD >> "$ARGSFILE"
                unset LD_PRELOAD

                echo run $@ >> "$ARGSFILE"
                echo show args >> "$ARGSFILE"
                ${GAME_DEBUGGER} box64 "${GAMEROOT}"/${GAMEEXE} -x "$ARGSFILE"
                rm "$ARGSFILE"
        else
        exec ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
        fi
        STATUS=$?
done
exit $STATUS
```
Output:
```ox64 with Dynarec v0.1.3 4d9559f built on Aug  8 2021 19:29:11
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 40 Env var
Looking for /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/gmod
argv[1]="-game"
argv[2]="garrysmod"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libtier0_client.so
Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libvstdlib_client.so
Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libsteam_api.so
Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libtogl_client.so
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Warning: Weak Symbol _ITM_memcpyRtWn not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd2040 (0x89086)
Warning: Weak Symbol _ITM_RU1 not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd2570 (0x89ae6)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd2928 (0x8a256)
Warning: Weak Symbol _ITM_RU8 not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd2d08 (0x8aa16)
Warning: Weak Symbol _ITM_memcpyRnWt not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd3090 (0x8b126)
Warning: Weak Symbol _ZGTtnam not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd3678 (0x8bcf6)
Error: Global Symbol daylight not found, cannot apply R_X86_64_GLOB_DAT @0x7fa7031ef0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libtier0_client.so
Warning: Weak Symbol __gmon_start__ not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa6ae2eb0 (0xef726)
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310b60 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310cd0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310d00 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310de0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310eb0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310f20 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310f40 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310f60 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73113f0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311410 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73114d0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73114f0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311580 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73115a0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311720 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311740 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311760 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311860 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311890 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310cc0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310cf0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310dd0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310e80 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310e90 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310ea0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73113a0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73113e0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73114c0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311570 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311710 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311850 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311880 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: Symbol _ZTVN10__cxxabiv121__vmi_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310ee0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
Error: relocating symbols in elf launcher_client.so
Error initializing needed lib launcher_client.so
Warning: Cannot dlopen("launcher_client.so"/0x400ead, 2)
Failed to load the launcher (Cannot dlopen("launcher_client.so"/0x400ead, 2)
)
2378|SIGSEGV @0x648d947c (???(/usr/local/bin/box64/0x648d947c)) (x64pc=0x7be7/???:"???", rsp=0x7fa81b3828, stack=0x7fa79b4000:0x7fa81b4000 own=(nil) fp=0x7fa81b3830), for accessing 0x7be6 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=0x1
```

Different games, different errors, but Im searching the guilty part and a fix to it.

Thanks

output

**Comment by Bhood23** [comment]
> > For example, Untitled Goose Game (64bit unity game which has a linux edition)
> > run.sh:
> > Output:
> > ```
> > Error loading needed lib /home/pi/Untitled Goose Game/Untitled Goose Game_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
> > Warning: Cannot dlopen("/home/pi/Untitled Goose Game/Untitled Goose Game_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so"/0x7f88c9f030, 2)
> > Unable to load mono library from /home/pi/Untitled Goose Game/Untitled Goose Game_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
> > Failed to load mono
> > Stop waiting for remaining thread 1890
> > ```
> 
> I don't see any reason why that lib is not loaded. Does the file exist and is a correct file?
> 
> > Any unity game gives same error.
> 
> I can play a few Unity3D games on Pi4 (on PiOS 64bits), like "Quiet City" or "Hollow Knight", but I need ` MESA_GL_VERSION_OVERRIDE=3.2` because OpenGL 3.2+ is needed for most of them.
> 
> > Also Garrys Mod linux compilation doesnt work
> > start.sh
> > ```
> > 
> > scriptdir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
> > 
> > cd "${scriptdir}"/game || exit 1
> > 
> > "${scriptdir}"/steam-runtime/run.sh ./hl2.sh -game garrysmod
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > hl2.sh:
> > ```
> > export LD_LIBRARY_PATH="${GAMEROOT}":$LD_LIBRARY_PATH
> > unset LD_PRELOAD
> > GAMEEXE=gmod
> > 
> > ulimit -n 2048
> > 
> > # enable nVidia threaded optimizations
> > export __GL_THREADED_OPTIMIZATIONS=1
> > 
> > # and launch the game
> > cd "$GAMEROOT"
> > 
> > # Enable path match if we are running with loose files
> > if [ -f pathmatch.inf ]; then
> >         export ENABLE_PATHMATCH=1
> > fi
> > 
> > # Do the following for strace:
> > #       GAME_DEBUGGER="strace -f -o strace.log"
> > # Do the following for tcmalloc
> > #   LD_PRELOAD=../src/thirdparty/gperftools-2.0/.libs/libtcmalloc_debug.so:$LD_PRELOAD
> > 
> > STATUS=42
> > while [ $STATUS -eq 42 ]; do
> >         if [ "${GAME_DEBUGGER}" == "gdb" ] || [ "${GAME_DEBUGGER}" == "cgdb" ]; then
> >                 ARGSFILE=$(mktemp $USER.hl2.gdb.XXXX)
> >                 echo b main > "$ARGSFILE"
> > 
> >                 # Set the LD_PRELOAD varname in the debugger, and unset the global version. This makes it so that
> >                 #   gameoverlayrenderer.so and the other preload objects aren't loaded in our debugger's process.
> >                 echo set env LD_PRELOAD=$LD_PRELOAD >> "$ARGSFILE"
> >                 echo show env LD_PRELOAD >> "$ARGSFILE"
> >                 unset LD_PRELOAD
> > 
> >                 echo run $@ >> "$ARGSFILE"
> >                 echo show args >> "$ARGSFILE"
> >                 ${GAME_DEBUGGER} box64 "${GAMEROOT}"/${GAMEEXE} -x "$ARGSFILE"
> >                 rm "$ARGSFILE"
> >         else
> >         exec ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
> >         fi
> >         STATUS=$?
> > done
> > exit $STATUS
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Output:
> > ```
> > Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
> > Using default BOX64_PATH: ./:bin/
> > Counted 40 Env var
> > Looking for /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/gmod
> > argv[1]="-game"
> > argv[2]="garrysmod"
> > Using native(wrapped) libdl.so.2
> > Using native(wrapped) libpthread.so.0
> > Using native(wrapped) libc.so.6
> > Using native(wrapped) ld-linux-x86-64.so.2
> > Using native(wrapped) librt.so.1
> > Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libtier0_client.so
> > Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libvstdlib_client.so
> > Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libsteam_api.so
> > Using emulated /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libtogl_client.so
> > Using native(wrapped) libSDL2-2.0.so.0
> > Using native(wrapped) libm.so.6
> > Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
> > Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
> > Warning: Weak Symbol _ITM_memcpyRtWn not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd2040 (0x89086)
> > Warning: Weak Symbol _ITM_RU1 not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd2570 (0x89ae6)
> > Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd2928 (0x8a256)
> > Warning: Weak Symbol _ITM_RU8 not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd2d08 (0x8aa16)
> > Warning: Weak Symbol _ITM_memcpyRnWt not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd3090 (0x8b126)
> > Warning: Weak Symbol _ZGTtnam not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa5bd3678 (0x8bcf6)
> > Error: Global Symbol daylight not found, cannot apply R_X86_64_GLOB_DAT @0x7fa7031ef0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/libtier0_client.so
> > Warning: Weak Symbol __gmon_start__ not found, cannot apply R_X86_64_JUMP_SLOT @0x7fa6ae2eb0 (0xef726)
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310b60 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310cd0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310d00 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310de0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310eb0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310f20 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310f40 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310f60 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73113f0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311410 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73114d0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73114f0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311580 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73115a0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311720 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311740 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311760 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311860 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv120__si_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311890 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310cc0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310cf0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310dd0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310e80 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310e90 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310ea0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73113a0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73113e0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa73114c0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311570 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311710 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311850 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv117__class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7311880 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: Symbol _ZTVN10__cxxabiv121__vmi_class_type_infoE not found, cannot apply R_X86_64_64 @0x7fa7310ee0 ((nil)) in /run/media/pi/2TB/gomos/linux/GarrysMod/game/bin/linux64/launcher_client.so
> > Error: relocating symbols in elf launcher_client.so
> > Error initializing needed lib launcher_client.so
> > Warning: Cannot dlopen("launcher_client.so"/0x400ead, 2)
> > Failed to load the launcher (Cannot dlopen("launcher_client.so"/0x400ead, 2)
> > )
> > 2378|SIGSEGV @0x648d947c (???(/usr/local/bin/box64/0x648d947c)) (x64pc=0x7be7/???:"???", rsp=0x7fa81b3828, stack=0x7fa79b4000:0x7fa81b4000 own=(nil) fp=0x7fa81b3830), for accessing 0x7be6 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=0x1
> > ```
> 
> Gary's mod, I need to retry. This looks like some mix between libstdc++ and libcxx, not sure....
> 
> There are many games that works on box64: FTL, Into The Breach, SuperMeatBoy, SuperHexagon, WorldOfGoo, Shovel Knight, to name just a few...

Found Any Fix For GMOD

**Comment by IsaacMvmv** [comment]
Try with la test box64, maybe It will work

**Comment by Bhood23** [comment]
> Try with latest box64, maybe It will work
Okey dokey thx

**Comment by ptitSeb** [comment]
I'm closing this ticket. Open a new one if you have other issues.
