### ISSUE TITLE
Illegal Opcode 0x20ffe8: FF FF 41 00 00 00

### ISSUE THREAD

**Issue by Shatur** [ptitSeb/box64#860]
I trying to run a free game [Street Fighter™ X Mega Man™](https://megaman.capcom.com/sfxmm/sfxmm_dl_uk.html)

I use wine-staging 8.11 that I downloaded from the ArchLinux repo from [here](https://archlinux.org/packages/multilib/x86_64/wine-staging/download/).

I run it as usual: `box64 path/to/wine SFXMMv2_EU.exe`.
 
Full output:
[log.txt](https://github.com/ptitSeb/box64/files/11859394/log.txt)

I use box64 compiled from source a few weeks ago.

**Comment by ptitSeb** [comment]
You are using Experimental WOW64 support. It was added to box64 yesterday basicaly!

Not sure if it's a box64 issue or a Wine issue at that point. Did you tried that game on an x86_64 machine with the same wine?

**Comment by Shatur** [comment]
> You are using Experimental WOW64 support. It was added to box64 yesterday basicaly! So you need a box64 build today (really).

Okay, will rebuild and report you back :)

> Not sure if it's a box64 issue or a Wine issue at that point. Did you tried that game on an x86_64 machine with the same wine?

Yes, the game runs on my PC with exact the same wine binary.

**Comment by Shatur** [comment]
Recompiled - having the same error :(
```
box64 --version
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096 Running on Cortex-A53 Cortex-A72 with 6 Cores
Params database has 24 entries
Box64 with Dynarec v0.2.3 770cba7e built on Jun 25 2023 10:43:27
```

**Comment by ptitSeb** [comment]
Well, I'll check on my side and see if I reproduce the issue.

**Comment by ptitSeb** [comment]
I reproduce an issue. So I'll debug on my side

**Comment by Shatur** [comment]
I see that you pushed a fix. Should I try it?

**Comment by ptitSeb** [comment]
You can, but it's still not working for me. I get a dialog box that some value is not defined, then I have a black fullscreen and it just exit.
It progressed, but not working yet.
But you can try of course, you might have a different outcome.

**Comment by Shatur** [comment]
> It's exactly the same behavior on native AMD64 Linux and Wine 8.10

It runs on my AMD64 PC with the exact binaries. Try the wine version from the description of the issue.

**Comment by ptitSeb** [comment]
I don't understand.
The wine in the link is a regular 32bits+64bits version of Wine, but built agaisnt a very recent glibc. It doesn't use WOW64 but regular box86 to launch 32bits games (and fails on my side because of many __XXX64 missing symbols in box86).
This is not consistant with the log.txt from the same post.

**Comment by Shatur** [comment]
> The wine in the link is a regular 32bits+64bits version of Wine, but built agaisnt a very recent glibc.

Yes, it's because it's from ArchLinux repo. My Phone runs ArchLinux too, but aarch64 version. The log I generated was from `box64 path/to/wine SFXMMv2_EU.exe` with wine from ArchLinux AMD64 repo.
Let me try to rebuild box64 with the fix and try again.

**Comment by ptitSeb** [comment]
Mmmm, on my side it never tries WOW64, probably because i386 arch is supported?

**Comment by Shatur** [comment]
> probably because i386 arch is supported?

Do you mean supported on my Phone? It shouldn't, I use PinePhone Pro with RK3399S.

Okay, I tried with the latest change and I have the exact same error. Here is what I did.
1. Recompiled the box64 at https://github.com/ptitSeb/box64/commit/7e514ce4bd3a255ef7555f4867659e9c41d0719b.
```bash
shatur@pinephone-pro /m/S/G/Street Fighter X Mega Man> box64 --version
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096 Running on Cortex-A53 Cortex-A72 with 6 Cores
Params database has 24 entries
Box64 with Dynarec v0.2.3 7e514ce4 built on Jun 26 2023 15:40:45
```

2. Downloaded the wine from ArchLinux repo.
3. Copied it to the game folder and renamed `usr` folder to `wine`.
4. Then I executed the following command:
```bash
box64 wine/bin/wine64 SFXMMv2_EU.exe &> log.txt
```
It produced the following log with the same error: 
[log.txt](https://github.com/ptitSeb/box64/files/11871591/log.txt)
Am I doing something wrong?

On my PC I can run the game with this wine without box64.

**Comment by ptitSeb** [comment]
> > probably because i386 arch is supported?
> 
> Do you mean supported on my Phone? It shouldn't, I use PinePhone Pro with RK3399S.
> 

No, I meant on my system. This wine doesn't try to use wow64 on my system but just launch i386 wine directly, so I never have that:
```
0110:err:environ:init_peb starting L"D:\\Games\\Street Fighter X Mega Man\\SFXMMv2_EU.exe" in experimental wow64 mode
```
on my side.

Maybe your AMD64 System have i386 libs? do you see that experimental wow64  message on your amd64 machine when you run that game?

**Comment by ptitSeb** [comment]
also also, box64 is not compatible yet with AVX or SSE4.2. I don't know what compilation options your wine have, but it might be incompatible with box64 cpu emulation.

**Comment by Shatur** [comment]
> Maybe your AMD64 System have i386 libs? do you see that experimental wow64 message on your amd64 machine when you run that game?

Oh, got it. No, I don't see this message and I do have i386 libs. Here is the log, I run the game and exit it normally (looks like it crashes at the end :smile:): 
[log.txt](https://github.com/ptitSeb/box64/files/11871854/log.txt)
But on my phone I don't have armv7 libs. I assume that this is the issue?

> also also, box64 is not compatible yet with AVX or SSE4.2. I don't know what compilation options your wine have, but it might be incompatible with box64 cpu emulation.

Nothing like this, compiled as usual:
https://gitlab.archlinux.org/archlinux/packaging/packages/wine-staging/-/blob/main/PKGBUILD#L115

**Comment by Shatur** [comment]
So my issue is that I trying to run i386 binary using Box64?

**Comment by ksco** [comment]
You need to use Wine with WOW64 support, which allows you to run Win32 apps without armhf and box86. You can compile it yourself or download it from https://github.com/Pi-Apps-Coders/files/releases

**Comment by ptitSeb** [comment]
> So my issue is that I trying to run i386 binary using wine64 with Box64 and it triggers experimental wow64 mode that is incompatible with Box64?

WOW64 is in the work on box64, and it's beggining to be compatible. There are still some issues to iron out.

Your version of wine is a bit strange to me, as it seems to automaticaly select to use experimental wow64 if i386 is not supported. Other build I have used just have the experimental WOW64 support, or i386, never both... All my systems have i386 supports with box86, so I'm unable to test your issue with you version of wine.
Anyway, if you don't have the experimental wow64 message on your PC, that means you are using plain i386 binaries.
So that test doesn't count. I'll stick to the other wine binary (that have only wow64) for testing and it seems WOW64 is not yet compatible with this game.

**Comment by Shatur** [comment]
Thank you all a lot for the explanations!
Sounds reasonable to me. Just tired wine 8.11 from https://github.com/Pi-Apps-Coders/files/releases that have only WOW64 support on my PC and the game crashes.

Closing this issue because the game can't run because of Wine. Yes, `Illegal Opcode` comes from box64, but looks like it happens only the version of wine from my distro that supports WOW64 and i386.
