### ISSUE TITLE
Unimplemented 32bits Opcode (00 83 C4 0C) 66 60 9C 58 8B C8 35 00 00 04 00 50 9D 9C 58

### ISSUE THREAD

**Issue by DevikinD** [ptitSeb/box64#865]
I am trying to run 32bit game on box64 with dynarec and got `10472|0x495e27: Unimplemented 32bits Opcode (00 83 C4 0C) 66 60 9C 58 8B C8 35 00 00 04 00 50 9D 9C 58
Sigfault/Segbus while quitting, exiting silently`

I used Debian proot on termux and 
wine from here: [wine-8.11](https://github.com/Pi-Apps-Coders/files/releases/download/large-files/wine-8.11.tar.gz) 

Here full log with BOX64_LOG=1
[dynarec_log.txt](https://github.com/ptitSeb/box64/files/11860758/dynarec_log.txt)

Log with dynarec off
[dynarecoff_log.txt](https://github.com/ptitSeb/box64/files/11860760/dynarecoff_log.txt)

**Comment by ptitSeb** [comment]
I have added the missing opcode, you can update and try again.

**Comment by DevikinD** [comment]
> I have added the missing opcode, you can update and try again.

ok thanks to add opcode.
i am trying again but the game wont launch,
with dynarec game mem usage on taskmanager is 0 but the process not crash and with dynarec off mem usage is not 0 but freeze, the process is not crash too.

Here log with dynarec on
[log.txt](https://github.com/ptitSeb/box64/files/11872708/log.txt)
Log with dynarec off
[log1.txt](https://github.com/ptitSeb/box64/files/11872720/log1.txt)

idk if it box64 issue or wine

**Comment by DevikinD** [comment]
Do I have to close this issue? Since the new problem is not related to the opcode

**Comment by ptitSeb** [comment]
A new ticket would be nice yes, different problem, diffeent ticket...
