### ISSUE TITLE
Universe Sandbox 2

### ISSUE THREAD

**Issue by Grima04** [ptitSeb/box64#87]
When running the Linux version of Universe Sandbox 2 with box64, the game crashes during the loading screen due to missing symbols.
I have attached a log taken with `BOX64_DLSYM_ERROR=1` below:
[UniverseSandbox2.log](https://github.com/ptitSeb/box64/files/6971457/UniverseSandbox2.log)

**Comment by ptitSeb** [comment]
I don't see any missing symbol in the log.
Is not easy to catch a missing symbol there, because for X11, symbol are searched in each X11 related lib open (by the program, not by box64). So you can see many "Symbol not found" for the same symbol until it is finaly found in some lib.

Did you found a missing symbol?

**Comment by Grima04** [comment]
Thanks for the explanation, I think that I misinterpreted the "Symbol not found" errors as missing symbol errors but it looks like they were indeed only temporary errors until the symbols were found in another lib. I haven't seen any missing symbols elsewhere in the log.
I have also made a log with `BOX64_LOG=2` since the default logging level doesn't give any useful information about the crash (just the message `Aborted (core dumped)`):
[US2.log](https://github.com/ptitSeb/box64/files/6977477/US2.log)
Hopefully it contains some useful information.
Is there something else I could do to provide more information on the crash?

**Comment by Grima04** [comment]
I have tested the game again with box64 v0.1.5 46f71f3 on my Jetson Xavier NX. 
The Linux version unfortunately still crashes during the loading screen but the Windows version (using DX11) is now able to go ingame using Wine 6.0 from PlayOnLinux. Getting ingame is unfortunately a matter of luck, the game still freezes or crashes very often during the loading screen but when it manages to load properly, it seems to run quite stable.
Currently, there also seems to be a problem with the keyboard and mouse input since it stops working after a while, making the game unplayable but other than that, I haven't noticed any issues.
![Screenshot from 2021-10-05 22-58-38](https://user-images.githubusercontent.com/22496380/136104499-f4b9ccd5-dd5d-4404-9a57-9be701f65894.png)

![Screenshot from 2021-10-05 23-00-28](https://user-images.githubusercontent.com/22496380/136104541-8d8acd77-cbaa-4d76-96a1-cef8ba20fc61.png)
Performance wise, it doesn't run very well (around 5 to 10 FPS) but I guess that a lot of performance is lost due to WineD3D being used. I also tried to force the game to use OpenGL but it doesn't recognize any graphics adapter in that mode, so we are currently limited to DX11.
Overall, this is some really good progress though and it is even more impressive when considering that the game is running through Wine using DX11.

**Comment by Grima04** [comment]
I have also tested the game with ExaGear from Huawei (another x86_64 emulator) and on there the same temperature bug appeared, so I looked on the Steam forums and apparently some people seem to have the same bug on real x86_64 hardware on Linux. The fix that was recommended in the forums was to disable VSYNC and it worked, now the planets have their normal temperature. So the problem isn't on box64's end after all, I am sorry for the false alarm.
The graphics bugs with the orbits were also present on ExaGear (with virgl for GPU acceleration), so it seems to be a bug in the Nvidia drivers but to be sure, we would need a test on another GPU.
Here is how it looks with VSYNC disabled:
![Screenshot from 2021-10-31 14-53-26](https://user-images.githubusercontent.com/22496380/139589612-4be35d2b-e37d-43a6-be20-5077ddb52630.png)

The crashes on startup are still an issue though, so it would be interesting to look into why Goldberg causes crashes on box64.

**Comment by ptitSeb** [comment]
Oh, nice! So it's just a vsynch issue?! How strange the side effect change temperature of the planets!

For the crashes, I have made somes fixes in box86 (expecially the ones on LOCK prefixes) that I have to port to box64 that may help.

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
@Grima04 If you are still having issues with Universe Sandbox 2, feel free to re-open this GitHub Issue. Everything appears to be implemented. Closing as resolved.
