### ISSUE TITLE
Unimplemented 32bits Opcode (C7 B6 6C 00) 64 67 8B 16 2C 00 8B 04 82 C3 90 53 81 C4 F8

### ISSUE THREAD

**Issue by DevikinD** [ptitSeb/box64#870]
More 32bit games need opcode.

with / without dynarec same result
`19646|0x401145: Unimplemented 32bits Opcode (C7 B6 6C 00) 64 67 8B 16 2C 00 8B 04 82 C3 90 53 81 C4 F8
Sigfault/Segbus while quitting, exiting silently`
full [log](https://github.com/ptitSeb/box64/files/11874001/logs.txt)

**Comment by ptitSeb** [comment]
I have added that opcode, you can try again with latest box64.
