### ISSUE TITLE
[32BITS] Windows Steam stuck on the "Updating Steam" phase

### ISSUE THREAD

**Issue by ksco** [ptitSeb/box64#873]
Happens both on ARM64 and RV64.

![image](https://github.com/ptitSeb/box64/assets/15257961/700749eb-4089-41dd-b5aa-85b32f829019)
> Native (top), box64 (bottom)

**Comment by ptitSeb** [comment]
It does download and install now for me. But it doesn't start after the update: it complains that the `steamclient.dll`, 32bits lib, cannot be load for some reason. No idea if this is supposed to work on Wow64 at this stage.

**Comment by ksco** [comment]
No, it's not supported right now, if it starts to download, this issue can be closed. 🎉

**Comment by ksco** [comment]
So it's a lack-of-opcode error? :O I don't recall seeing any "Unimplemented opcode" back then.

**Comment by ptitSeb** [comment]
because `SteamSetup.exe` launch `steam.exe` redirecting everything to oblivion. I launched "C:\Program Files (x86)\Steam\steam.exe" directly to see the missing opcode on my side.
Try again your side, it might work now, even on RV64 :)

**Comment by ksco** [comment]
Sure, I'll try a bit later.

**Comment by agrecascino** [comment]
> No, it's not supported right now, if it starts to download, this issue can be closed. tada
Hmm? Steam runs fine under wine 8.10 on wow64 for me on amd64.

**Comment by ksco** [comment]
> > No, it's not supported right now, if it starts to download, this issue can be closed. tada
> 
> Hmm? Steam runs fine under wine 8.10 on wow64 for me on amd64.

Huh, is your wine built with the experimental wow64 mode on?

**Comment by agrecascino** [comment]
> > > No, it's not supported right now, if it starts to download, this issue can be closed. tada
> > 
> > 
> > Hmm? Steam runs fine under wine 8.10 on wow64 for me on amd64.
> 
> Huh, is your wine built with the experimental wow64 mode on? The last time I checked, it does not work for me.

Yes! At very least, it doesn't fail with this issue... Have you tried installing with OS version set to windows 7?

**Comment by ksco** [comment]
> Have you tried installing with OS version set to windows 7?

No, I haven't tried that, I won't be able to try it until late next month, but I will. :(

**Comment by ksco** [comment]
steam.exe is still not working, but that's another issue. closing this one.
