### ISSUE TITLE
Unimplemented OpCode: 151763|0x7f9f07d3da: Unimplemented Opcode (FF) F0 0F C0 03 4C 8D BD 51 01 00 00 84 C0 74 67

### ISSUE THREAD

**Issue by rafael2k** [ptitSeb/box64#874]
I'm getting this message in from proprietary 64 bit software for Linux:
151763|0x7f9f07d3da: Unimplemented Opcode (FF) F0 0F C0 03 4C 8D BD 51 01 00 00 84 C0 74 67

**Comment by rafael2k** [comment]
The same software, but the decoder binary, issues the same opcode:
371510|0x7fb12c4bea: Unimplemented Opcode (FF) F0 0F C0 03 4C 8D BD 51 01 00 00 84 C0 74 67

**Comment by ptitSeb** [comment]
It's a leggit opcode: `lock xadd byte ptr ds:[rbx], al`, I need to add it.

**Comment by rafael2k** [comment]
Thanks PtitSeb. Btw, do you use some tool to translate the opcode to human readable assembly (like you just did)?

**Comment by ptitSeb** [comment]
> Thanks PtitSeb. Btw, do you use some tool to translate the opcode to human readable assembly (like you just did)?

Yes, I use `ZydisInfo`, comes with `libZydis` that is an optionnal dependancy of box86/box64.

**Comment by rafael2k** [comment]
Thanks! Did not know about Zydis.

**Comment by rafael2k** [comment]
ufff, my bad, sorry, the box64 package was from 2021 and I did not realized. I'll retest with trunk.

**Comment by rafael2k** [comment]
It worked! Sorry the noise... and thanks for ZydisInfo information!
