### ISSUE TITLE
[32BITS] I don't think It seems to four IA-32 instructions(daa, das, aaa and aas) for 32bits mode be implemented.

### ISSUE THREAD

**Issue by hiroki-repo** [ptitSeb/box64#876]
Why you didn't implement 4 BCD x86 instructions(daa[0x27], das[0x2f], aaa[0x37], aas[0x3f])?
I wonder if you planning to implement these IA-32 instructions. Because These opcodes are implemented at box86 and other i386 code emulators and I think It's used to BCD operation in classical PC games or tools.

**Comment by ptitSeb** [comment]
I didn't implemented them because I have not run into games that use them. I tend to implemented stuff "as needed",

**Comment by hiroki-repo** [comment]
I understand why you don't implemented these instructions right now.
