### ISSUE TITLE
DYNAREC makes factorio headless server boot slow and not work

### ISSUE THREAD

**Issue by arb103** [ptitSeb/box64#881]
### Environment
Device: Raspberry Pi 4 Model B
OS: Debian GNU/Linux 11 (bullseye) aarch64
Box64 version: Box64 with Dynarec v0.2.3 a6b231ce built on Jul 10 2023 18:19:54
Factorio headless server version: 1.1.80

### Description
When running factorio headless server, turning dynarec on will make it fail

### Reproduction
Case 1
1. Download https://www.factorio.com/get-download/1.1.80/headless/linux64 and extract it
2. Run `BOX64_DYNAREC=1 box64 bin/x64/factorio --start-server map.zip` (map attached for convenience of not having to make a savefile yourself) [map.zip](https://github.com/ptitSeb/box64/files/12034082/map.zip)
3. Observe as it very slowly boots up and finally crashes

Case 2
1. Run `BOX64_DYNAREC=0 box64 bin/x64/factorio --start-server map.zip`
2. Observe as it boots very fast and works, although incredibly slow

### Logs
attached are logs of trying to run factorio headless server with DYNAREC=1 and DYNAREC=0
[fail.log](https://github.com/ptitSeb/box64/files/12034051/fail.log)
[success.log](https://github.com/ptitSeb/box64/files/12034052/success.log)

**Comment by ptitSeb** [comment]
Thanks for the detailled steps. I can reproduce the issue and will work on a fix.

**Comment by ptitSeb** [comment]
Ok, I think I found and fixed the issue. Can you update box64 and try again?

**Comment by arb103** [comment]
Thanks for the fast response, I can confirm that as of 88a59b44 this works with version 1.1.80 of the game as well as just released version 1.1.87
The game server boots very fast and runs very smooth on a new map, this can be marked as solved
Once again, thank you very much

**Comment by ptitSeb** [comment]
Cool :)

Thansk for the feedback, closing the ticket.
