### ISSUE TITLE
[32BITS]box64 wow64 wine 8.11 refreshProtection no Permission

### ISSUE THREAD

**Issue by szllzs** [ptitSeb/box64#883]
box64(master 0713 arrch64 linux/gnu)
BOX64_DYNAREC=1 is bad, BOX64_DYNAREC=0 is ok
refreshProtection(0x57150010): 0x57150000/0x7 (ret=-1/权限不够)
Strange SIGSEGV with Access error on 0x57150010 for 0x57150010, db=0x72e9a2b0d8, prot=0x7 (old_addr=(nil))
refreshProtection(0x57150010): 0x57150000/0x7 (ret=-1/权限不够)
refreshProtection(0x57150010): 0x57150000/0x7 (ret=-1/权限不够)
Strange SIGSEGV with Access error on 0x57150010 for 0x57150010, db=0x72e9a2b0d8, prot=0x7 (old_addr=0x57150010)
27709|SIGSEGV @0x57150010 (???(0x57150010)) (
x64pc=0x102b05610/home/Wine/x86_64/lib/wine/x86_64-unix/winex11.so:"/home/Wine/x86_64/lib/wine/x86_64-unix/winex11.so/X11DRV_XF86VM_Init",
 rsp=0x10250dc28, stack=0x101810000:0x102010000 own=(nil) fp=0x5710cbc0), 
 for accessing 0x57150010 (code=2/prot=7), db=0x72e9a2b0d8(0x57150010:0x57153368/0x102b05610:
 0x102b057c6/home/Wine/x86_64/lib/wine/x86_64-unix/winex11.so/X11DRV_XF86VM_Init:clean, 
 hash:45563dd4/45563dd4) handler=0x10204be60
RAX:0x0000000102ac9990 RCX:0x0000000000000001 RDX:0x0000000102b07fe0 RBX:0x0000000102b160d1 
RSP:0x000000010250dc28 RBP:0x000000005710cbc0 RSI:0x0000000102b315b0 RDI:0x000000010250dba0 
 R8:0x0000000102b07b7d  R9:0x000000007ffc3363 R10:0x0000000102b17656 R11:0x000000007ffc3353 
R12:0x0000000102b314d0 R13:0x0000000000000006 R14:0x0000000102b16099 R15:0x0000000000000020 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b GS:0x0043 FS:0x0053 
RSP-0x20:0x0000000102b314d0 RSP-0x18:0x0000000000000006 RSP-0x10:0x0000000102b16099 RSP-0x08:0x0000000000000020
RSP+0x00:0x0000000102af7560 RSP+0x08:0x000000010250dca0 RSP+0x10:0x000000010250dc5c RSP+0x18:0x00000000570e8710
Sigactionhanlder for signal #11 called (jump to 0x10204be60/???(0x10204be60))
27709|signal #11 function handler 0x10204be60 called, RSP=0x7ffcfba8

**Comment by ptitSeb** [comment]
Is the issue fixed from some previous push?

**Comment by szllzs** [comment]
> Is the issue fixed from some previous push?

I changed the environment, recompiled the latest box64, and that's ok

**Comment by ptitSeb** [comment]
Ok, great :)
