### ISSUE TITLE
Steam on wine wow64 fails with unknown opcode.

### ISSUE THREAD

**Issue by agrecascino** [ptitSeb/box64#887]
Getting a 
`[2023-07-17 09:21:57] Startup - updater built Mar 24 2023 10:11:41
[2023-07-17 09:21:57] Startup - Steam Client launched with: "C:\Steam\steam.exe"
23324|0x40a912: Unimplemented 32bits Opcode (0F 73 F4 17) 0F D4 C3 0F 6F D9 0F 73 D1 04 0F EF EE 0F EF
`
Which apparently corresponds to paddq?

**Comment by ptitSeb** [comment]
Ok, I'll add it

**Comment by agrecascino** [comment]
Alright, steam starts now,  got a 
26874|0x415023: Unimplemented 32bits Opcode (90 0F 6E 12) 0F F4 D0 8D 52 04 0F D4 CA 0F 7E 08 83 E9 01
in my terminal but everything is still running afaict. It's worth noting that we're stuck where ksco was 2 weeks ago again, but it seems to be failing because networking doesn't seem to work on wow64 wine under box64 at all(can't connect to ut99 servers, can't connect to tribes servers, can't ping, etc).

**Comment by agrecascino** [comment]
Closing because this particular issue is resolved.
