### ISSUE TITLE
Missing opcode in Counter-Strike: Source

### ISSUE THREAD

**Issue by agrecascino** [ptitSeb/box64#892]
22656|0x69487722: Unimplemented Opcode (8B 44 24 74) 67 0F 11 03 48 89 44 24 44 48 8B 54 24 40 89
Which is movups according to zydisinfo

**Comment by agrecascino** [comment]
Fixed

**Comment by ptitSeb** [comment]
So CS:Source is working?

**Comment by agrecascino** [comment]
![image](https://github.com/ptitSeb/box64/assets/9344554/c228ae50-3831-4fea-ae5e-9abce44e2fdb)
