### ISSUE TITLE
SIGSEGV libc6

### ISSUE THREAD

**Issue by fengxue-jrql** [ptitSeb/box64#893]
26706|SIGSEGV @0x749e6aa450 (???(/lib/aarch64-linux-gnu/libc.so.6+0x749e6aa450)) (x64pc=(nil)/???:"???", rsp=0x102000000, stack=0x101800000:0x102000000 own=0x101800000 fp=(nil)), for accessing (nil) (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RAX:0x0000000000000000 RCX:0x0000000000000000 RDX:0x0000000000000000 RBX:0x0000000000000000
RSP:0x0000000102000000 RBP:0x0000000000000000 RSI:0x0000000000000000 RDI:0x0000000000000000
 R8:0x0000000000000000  R9:0x0000000000000000 R10:0x0000000000000000 R11:0x0000000000000000
R12:0x0000000000000000 R13:0x0000000000000000 R14:0x0000000000000000 R15:0x0000000000000000
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b GS:0x0043 FS:0x0053
Segmentation fault

**Comment by ptitSeb** [comment]
I'm going to need much more info than just that.

**Comment by ptitSeb** [comment]
closing, lack of any information to do anything here.
