### ISSUE TITLE
X Error of failed request:  GLXBadFBConfig

### ISSUE THREAD

**Issue by Shatur** [ptitSeb/box64#898]
I trying to run a free game [Street Fighter™ X Mega Man™](https://megaman.capcom.com/sfxmm/sfxmm_dl_uk.html). I already tried it before in #860 the game didn't work with Wine 8.11.

But the game now works with Wine 8.12, I tested it on my PC. I downloaded Wine from https://github.com/Pi-Apps-Coders/files/releases and used the same binary on my PinePhone Pro.

I run it as usual: `box64 path/to/wine SFXMMv2_EU.exe`.
But have the error mentioned in the title. 
Full output: [log.txt](https://github.com/ptitSeb/box64/files/12123096/log.txt)

I use box64 compiled from 51cbb7e1fb6efc6e74c04d7d31dc05f074646771.

**Comment by theofficialgman** [comment]
Tested on wine 8.13 (from my build on Pi-Apps-Coders, I build the release you use) on Nvidia Jetson Orin Nano and this works. Orin nano has full OpenGL 4.6 and Vulkan 1.3 and is ARM64

So either it was fixed in Wine 8.13 or this is an issue with your hardware/drivers

**Comment by Shatur** [comment]
I also tried it with 8.13, same issue :(
Are you using Wayland?

**Comment by theofficialgman** [comment]
No, using xorg. Wayland is still a mess on Nvidia Tegra.

I do get stuck in the game on an orange screen shortly after the title screen

**Comment by theofficialgman** [comment]
the game is still running because if I press ESC I get a "do you want to exit" prompt in game.
likely a wine issue

**Comment by theofficialgman** [comment]
tested on my x86_64 PC (amd gpu, mesa drivers) and am getting stuck in similar places in game. so its pretty buggy still

**Comment by Shatur** [comment]
Right, can confirm the same behavior on my PC.
But I have the mentioned error in the title with other games. For example, The Simpsons Hit and Run results in the same error.

**Comment by theofficialgman** [comment]
like I said this is probably your hardware/drivers
```
0024:err:system:NtUserChangeDisplaySettings Changing (null) display settings returned -2.
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  1907
  Current serial number in output stream:  1907
```
panfrost (MESA drivers for Mali GPUs like in your pinephone pro) still has pretty poor support and buggy GL/GLES and almost non-existant vulkan support

it will get better but takes time.

**Comment by Shatur** [comment]
Hmm... I've run some games through wine32 from a chroot. I can also many some native games.
This line look suspicious: `Changing (null) display settings returned -2.` It should be the number of server. Maybe it have something to do with Wayland support... Okay, I probably should close it since I'm not sure if it's related to box64.
