### ISSUE TITLE
Unimplemented Opcode  C5 F1 62 C8

### ISSUE THREAD

**Issue by wwlwwlwwlwwl** [ptitSeb/box64#899]
Try using latest box64 and wine play [Pathfinder](https://steamdb.info/app/1184370/) 
the game stuck on loading. 
```
30290|0x127fc5d15: Unimplemented Opcode (83 C4 58 C3) C5 F1 62 C8 C5 D1 EF ED C5 F9 7E C8 C5 F9 7E
01cc:err:sync:RtlpWaitForCriticalSection section 0000000127743F28 (null) wait timed out in thread 01cc, blocked by 01c4, retrying (60 sec)
```

**Comment by ptitSeb** [comment]
This is an AVX opcode, not supported yet on box64.

**Comment by LukeShortCloud** [comment]
@wwlwwlwwlwwl AVX is now supported by Box64. Let us know if you have any further issues with the latest version. Closing as resolved.
