### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by Pythonic456** [ptitSeb/box64#91]
Steam on a Pi 4, aarch64 chroot of RPi OS.
```root@rpios64bit:~# su pi
pi@rpios64bit:/root $ cd
pi@rpios64bit:~ $ steam
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1:i386 needs to be installed
Package libc6:i386 needs to be installed
xterm: cannot load font "-Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1"
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
Running Steam on debian 10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Error: You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
Can't find 'steam-runtime-check-requirements', continuing anyway
WARNING: Using default/fallback debugger launch
/home/pi/.local/share/Steam/ubuntu12_32/steam
/home/pi/.local/share/Steam/steam.sh: line 770: /home/pi/.local/share/Steam/ubuntu12_32/steam: No such file or directory
pi@rpios64bit:~ $ 
```
When running Steam, a window opens about here > `Pins up-to-date!`
![2021-08-13-214938_3200x1200_scrot](https://user-images.githubusercontent.com/56113118/129417269-673e5a80-9cd1-4e90-9777-ab578b077b49.png)
Steam crashes right after you press enter in ^.

Fresh install of Steam + RPi OS 32-bit.

Thanks for your help!

**Comment by ptitSeb** [comment]
use `STEAMOS=1` to avoid the libc message.
Steam is an hybrid 32bits / 64bits application. You need box86 for it to work (and the 64bits part isn't working right for now).

**Comment by Pythonic456** [comment]
Ok, thanks. Is there any way I could get steam to run?

**Comment by FalcoGer** [comment]
I'm having trouble running steamcmd. I want a 64 bit game server (7d2d) but steamcmd only runs on box86, which itself requires a 32bit chroot. So I can't have box64 and box86 in the same chroot to run steamcmd.

In the 32 bit chroot i can't download the server, because steamcmd complains about it.
in the 64 bit chroot i can't run steamcmd because I can't run box86 there.

I'm stuck.
Then again my Pi would probably cry until it catches fire if I actually tried to run a 7d2d server on it...

**Comment by Pythonic456** [comment]
@FalcoGer You _could_ install 32-bit and 64-bit libs, in a 64-bit chroot, I have done this before to run box86 and box64 together.

**Comment by FalcoGer** [comment]
> @FalcoGer You _could_ install 32-bit and 64-bit libs, in a 64-bit chroot, I have done this before to run box86 and box64 together.

But I can't compile box86 on an 64 bit host... how did you make that work?

**Comment by Pythonic456** [comment]
32-bit instruction set can be used on a 64-bit host system, as 64-bit has the same instructions as 32-bit (with a few more).

**Comment by ptitSeb** [comment]
you need to use an OS with mutlarch support, like armbian / RPiOS64bits maybe? And then follow the "Build on 64bits OS" of box86.

**Comment by FalcoGer** [comment]
> 
> 
> you need to use an OS with mutlarch support, like armbian / RPiOS64bits maybe? And then follow the "Build on 64bits OS" of box86.

I'm running ubuntu 64bit. and I really, really, really don't feel like setting everything up again with a new OS. Over the course of years I set up lots of services on the thing and it's practically running my home network now as well as mail, web, backup and cloud as well as other things.

It seems like ubuntu has multiarch support from what I've read, I'll try and figure it out.

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
Both Box64 and Box86 are required to run Steam. It appears that all of the issues in this thread have been addressed. Closing as resolved.
