### ISSUE TITLE
Unimplemented Opcode (21 9B 4D 92) D4 19 87 9D 4A 60 B4 78 24 9A E8 ED A5 3F FE (WoW 9.2.0)

### ISSUE THREAD

**Issue by Retloldin** [ptitSeb/box64#913]
Hi! 
I'm trying to run World of Warcraft on the Nintendo Switch and got this error when I got to the Shadowlands client (9.2.0):
6745|0x1402b6a6a: Unimplemented Opcode (21 9B 4D 92) D4 19 87 9D 4A 60 B4 78 24 9A E8 ED A5 3F FE

I'm trying to run the client with Wine 8.13 and DXVK 1.10.3 on the latest version of BOX64:
`Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096 Running on Cortex-A57 with 4 Cores
Params database has 24 entries
Box64 with Dynarec v0.2.3 f5fadea3 built on Jul 29 2023 06:34:00`

Full log: [error_box64.log](https://github.com/ptitSeb/box64/files/12206928/error_box64.log)

**Comment by ptitSeb** [comment]
This is not a valid opcode, so something else is happening before crashing there.

**Comment by LukeShortCloud** [comment]
World of Warcraft has been reported as working on the Nintendo Switch earlier this year.

https://www.youtube.com/watch?v=_EsrgW0xW9Q

Closing as resolved.

**Comment by jhinzuo** [comment]
World of Warcraft _ Warlord of Draenor (6.x) does work. The problem exists in any version after legion (7.X).  And OP did state it is about other versions as these all dont work on box64 but do work on traditional wine so it is definitely a box64 bug. Also the Game never posts any logs so I am not sure how I would continue to debug this. Also the current versions have that issue also games like Overwatch fail with the same Game Initialization I error. When using proton I managed to get Game Initialization failed U but no logs even with trace version.

**Comment by LukeShortCloud** [comment]
@jhinzuo Thank you for the report. Please open up a new GitHub Issue as that is a different problem than what was originally reported here.
