### ISSUE TITLE
Problems running 64-bit GameMaker Games with Box64!

### ISSUE THREAD

**Issue by PrideToons** [ptitSeb/box64#915]
I'm having problems running 64-bit GameMaker Games with Box64. I tried booting up Ultionus with Box64 and ran into the following error message.
afro@odroidn2:~/Downloads/Games/Ultionus_RC6_1.0a_Ubuntu_NoSteam$ ./Ultionus
./Ultionus: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

Next I tried replacing the libraries with x86_64 Libraries but it still didn't work.

afro@odroidn2:~/Downloads/Games/Ultionus_RC6_1.0a_Ubuntu_NoSteam$ cd lib
afro@odroidn2:~/Downloads/Games/Ultionus_RC6_1.0a_Ubuntu_NoSteam/lib$ file libssl.so.1.1
libssl.so.1.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=fafbcd649ee8bebf399fa6151848563980be2136, stripped
afro@odroidn2:~/Downloads/Games/Ultionus_RC6_1.0a_Ubuntu_NoSteam/lib$ file libcrypto.so.1.1
libcrypto.so.1.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=5ea903d6cb5a6287eb5079545cd7be149e19f5bf, stripped

Lastly I tried aarch64 libraries, but unfortunately I'm still running into the same problem.
afro@odroidn2:~/Downloads/Games/Ultionus_RC6_1.0a_Ubuntu_NoSteam/lib$

**Comment by ptitSeb** [comment]
This should be fixed with this commit 81e8ce495273834ccec0f8ae26ee88f776fbeac1
you can update box64 and try again.

**Comment by LukeShortCloud** [comment]
This should be resolved now. Closing.
