### ISSUE TITLE
Dynarec Issue At Building (Native Termux)

### ISSUE THREAD

**Issue by mcagabe19** [ptitSeb/box64#917]
I know it's impossible to build box(86/64) in native termux but can't we give a shot for that?

* CMake Flags
-DBAD_SIGNAL=ON -DARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=gcc-9 -DARM_DYNAREC=ON -DCMAKE_SYSTEM_PROCESSOR=aarch64
* The Error
![Screenshot_20230801_140442_Termux](https://github.com/ptitSeb/box64/assets/82843871/eeffd787-a238-4548-8c99-bd143625ce49)
* Termux Info
![Screenshot_20230801_140755_Termux](https://github.com/ptitSeb/box64/assets/82843871/651cffd2-c3ad-4acc-8cda-f0a31d6c8fcc)
* GCC Info
![Screenshot_20230801_140853_Termux](https://github.com/ptitSeb/box64/assets/82843871/1617625e-dd15-48fb-bfa4-8ee72ccf2bc9)

**Comment by ptitSeb** [comment]
Do you know C?

I don't develop on Termux, so I cannot test or do anything, but I can accept Pull request with fixes.

If you have the correct name of the structure or alternate include file with some unique define macro name, it should be easy to `#ifdef ` a solution there.

**Comment by Heasterian** [comment]
https://github.com/Pipetto-crypto/box64 Looks like this fork is mostly working with Termux as build target (in this case just called Android). It's missing one linker flag in CMakeList.txt
With `-lexecinfo` it should compile fine, but I'm not sure if it's wise to keep it in main box64 repo as "correct" way of building it is by using Termux builder docker image or building it directly in Termux.

**Comment by mcagabe19** [comment]
> https://github.com/Pipetto-crypto/box64 Looks like this fork is mostly working with Termux as build target (in this case just called Android). It's missing one linker flag in CMakeList.txt With `-lexecinfo` it should compile fine, but I'm not sure if it's wise to keep it in main box64 repo as "correct" way of building it is by using Termux builder docker image or building it directly in Termux.

I got these errors so still impossible...
```
/data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/emu/x64syscall.c.o: in function `x64Syscall':
/data/data/com.termux/files/home/box64/src/emu/x64syscall.c:676:(.text+0x700): undefined reference to `my_epoll_wait'
/data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/emu/x64syscall.c.o: in function `my_syscall':
/data/data/com.termux/files/home/box64/src/emu/x64syscall.c:940:(.text+0xfb0): undefined reference to `my_epoll_wait'
/data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/libtools/signals.c.o: in function `my_box64signalhandler':
/data/data/com.termux/files/home/box64/src/libtools/signals.c:1204:(.text+0x1a9c): undefined reference to `backtrace'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/libtools/signals.c:1205:(.text+0x1aac): undefined reference to `backtrace_symbols'
/data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/tools/rcfile.c.o: in function `LoadRCFile':
/data/data/com.termux/files/home/box64/src/tools/rcfile.c:352:(.text+0xc28): undefined reference to `shm_open'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/tools/rcfile.c:354:(.text+0xc38): undefined reference to `shm_unlink'
/data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/wrapped/wrappedlibc.c.o: in function `my_open':
/data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1702:(.text+0x55ac): undefined reference to `shm_open'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1704:(.text+0x55bc): undefined reference to `shm_unlink'
/data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/wrapped/wrappedlibc.c.o: in function `my_open64':
/data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1779:(.text+0x572c): undefined reference to `shm_open'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1781:(.text+0x573c): undefined reference to `shm_unlink'
/data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/wrapped/wrappedlibc.c.o: in function `my_fopen':
/data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1811:(.text+0x58a4): undefined reference to `shm_open'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1813:(.text+0x58b4): undefined reference to `shm_unlink'
/data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/wrapped/wrappedlibc.c.o: in function `my_fopen64':
/data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1839:(.text+0x59c0): undefined reference to `shm_open'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1841:(.text+0x59d0): undefined reference to `shm_unlink'
```

**Comment by Heasterian** [comment]
> > https://github.com/Pipetto-crypto/box64 Looks like this fork is mostly working with Termux as build target (in this case just called Android). It's missing one linker flag in CMakeList.txt With `-lexecinfo` it should compile fine, but I'm not sure if it's wise to keep it in main box64 repo as "correct" way of building it is by using Termux builder docker image or building it directly in Termux.
> 
> I got these errors so still impossible...
> 
> ```
> /data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/emu/x64syscall.c.o: in function `x64Syscall':
> /data/data/com.termux/files/home/box64/src/emu/x64syscall.c:676:(.text+0x700): undefined reference to `my_epoll_wait'
> /data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/emu/x64syscall.c.o: in function `my_syscall':
> /data/data/com.termux/files/home/box64/src/emu/x64syscall.c:940:(.text+0xfb0): undefined reference to `my_epoll_wait'
> /data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/libtools/signals.c.o: in function `my_box64signalhandler':
> /data/data/com.termux/files/home/box64/src/libtools/signals.c:1204:(.text+0x1a9c): undefined reference to `backtrace'
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/libtools/signals.c:1205:(.text+0x1aac): undefined reference to `backtrace_symbols'
> /data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/tools/rcfile.c.o: in function `LoadRCFile':
> /data/data/com.termux/files/home/box64/src/tools/rcfile.c:352:(.text+0xc28): undefined reference to `shm_open'
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/tools/rcfile.c:354:(.text+0xc38): undefined reference to `shm_unlink'
> /data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/wrapped/wrappedlibc.c.o: in function `my_open':
> /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1702:(.text+0x55ac): undefined reference to `shm_open'
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1704:(.text+0x55bc): undefined reference to `shm_unlink'
> /data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/wrapped/wrappedlibc.c.o: in function `my_open64':
> /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1779:(.text+0x572c): undefined reference to `shm_open'
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1781:(.text+0x573c): undefined reference to `shm_unlink'
> /data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/wrapped/wrappedlibc.c.o: in function `my_fopen':
> /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1811:(.text+0x58a4): undefined reference to `shm_open'
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1813:(.text+0x58b4): undefined reference to `shm_unlink'
> /data/data/com.termux/files/usr/bin/ld: CMakeFiles/box64.dir/src/wrapped/wrappedlibc.c.o: in function `my_fopen64':
> /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1839:(.text+0x59c0): undefined reference to `shm_open'
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/box64/src/wrapped/wrappedlibc.c:1841:(.text+0x59d0): undefined reference to `shm_unlink'
> ```

You are missing some packages specific to Termux like for example libandroid-shmem. Run `apt install *libandroid*` and it should install most of them and build fine.

**Comment by Heasterian** [comment]
You are still missing `libandroid-shmem`. Did you used termux-packages setup-termux script? https://github.com/termux/termux-packages/blob/master/scripts/setup-termux.sh

If you didn't, you should dig in into it's wiki and building scripts as they have a lot of changes that aren't normal in normal Linux environment.

**Comment by mcagabe19** [comment]
@Heasterian now I got
```
"./box64": error: Android 5.0 and later only support position-independent executables (-fPIE).
```

**Comment by mcagabe19** [comment]
finally builded box64 in android!! thanks @Heasterian

**Comment by Creeper-xie** [comment]
> @Heasterian now I got
> 
> ```
> "./box64": error: Android 5.0 and later only support position-independent executables (-fPIE).
> ```
> 
> I think I needed add/use -fPIC

I refer to this issue and encountered the same problem, and I am stuck on this step. How did you solve it.
