### ISSUE TITLE
Unsupported Syscalls collection

### ISSUE THREAD

**Issue by zhangjing-GitHub-Code** [ptitSeb/box64#918]
As the topic

cur my uns syscall:
```
0000|2023-08-02 21:18:05 [I] launcher Error: Unsupported Syscall 0x3Bh (59)
```
`Error: Unsupported Syscall 0x10Ch (268)`
### And A question:
~and it uses go, saying errorno 2 when reading not existed files~
The program will `segment fault`/`exit`, and when i run it repeatly it final shows file read err, will it exit too fast by processing by box64?

**Comment by ptitSeb** [comment]
Ok, syscall has been added.

**Comment by zhangjing-GitHub-Code** [comment]
Well you may pin this issue,
and/or add link ro readme?

**Comment by ptitSeb** [comment]
Why? I don't understand. Adding syscall is not that common.

**Comment by ptitSeb** [comment]
Can this ticket be closed now?

**Comment by ptitSeb** [comment]
closing. Feel free to create a new ticket if you have more syscalls to add.
