### ISSUE TITLE
libgtk-x11-2.0.so.0 - missing, but it's right there!

### ISSUE THREAD

**Issue by mentaluproar** [ptitSeb/box64#92]
I'm trying to run zandronum. Box86 wants libgtk-x11-2.0.so.0.  Google says it's a part of libgtk2.0-0.  I fetch it and put it an a folder called missinglibs, export the environment variable saying to look there for it.  Box64 starts up, sees the folder, does not see the lib.  what can I do?

**Comment by ptitSeb** [comment]
is it for box86 or box64?

for box64, gtk is not wrapped, so you need to put the x86_64 version of the libs in the folder (use `file` on the lib to check the architecture).
for box86, gtk is wrapped, so simply install gtk using `apt` or whetever your package manager is.

(side note, you can build zandronum from source also, I have a repo with a ARM compatible build, but it will be the version 3.1 alpha ).

**Comment by mentaluproar** [comment]
Wait, you got the client to build for arm or the server? I know the server works on arm but last I checked the client won’t work on arm.

**Comment by ptitSeb** [comment]
GTK is wrapped now, you can retry

**Comment by rajdakin** [comment]
Closing now (no reply since last request).
