### ISSUE TITLE
arc4random symbol missing

### ISSUE THREAD

**Issue by cidkidnix** [ptitSeb/box64#932]
`arc4random` is missing it's wrapper, this symbol is from `libbsd`. I can attempt to add it if pointed in the correct direction, thanks!

**Comment by ptitSeb** [comment]
libbsd is not wrapped, so I don't understand why the symbol would be missing.

**Comment by ptitSeb** [comment]
Can you re-formulate the issue, or close the ticket if you solve it @cidkidnix
