### ISSUE TITLE
Astroneer: Cursor problem

### ISSUE THREAD

**Issue by olegos2** [ptitSeb/box64#955]
Astroneer has a bug where cursor/pointer is moving but you can't click or highlight anything

**Comment by ptitSeb** [comment]
I don't have the game on my steam collection, but it might be an issue with a specific version of SDL2 used by the game. You should create a profile for the game in ` ~/.box64rc`  and set ` BOX64_PREFER_EMULATED=1`  to try use emulated libs.

**Comment by LukeShortCloud** [comment]
@olegos2 If you're still having issues with the mouse cursor in Astroneer with emulated libraries, please let us know.
