### ISSUE TITLE
libGLEW and libformw

### ISSUE THREAD

**Issue by ScottFreeCode** [ptitSeb/box64#956]
I am getting these errors trying to run an x64 program on Arch Linux ARM (64):

> Error loading needed lib libGLEW.so.2.2
…
Using native(wrapped) libncursesw.so.6
Using native(wrapped) libtinfo.so.6
Error loading needed lib libformw.so.6
…
Error loading one of needed lib
Error initializing needed lib libgraphics.so
Error loading one of needed lib

(libgraphics appears to be getting emulated from the program's provided libgraphics.so; not certain if that matters here but included it for completeness of the errors.)

I've tried a bunch of the troubleshooting BOX64_ variables but haven't gotten any info on _why_ these couldn't be loaded.

libGLEW.so.2.2 and libformw.so.6 are in my /lib folder.

**Comment by ScottFreeCode** [comment]
My best guess on GLEW is that it simply isn't wrapped and I need to install the x64 version of GLEW instead of the aarch64 (ARM 64) version. But let me know if there's a way to confirm that, short of trying it. (I am looking into whether I can override the architecture and package location and install the x64 Arch Linux package to some local folder that could be used with this program only.)

**Comment by ScottFreeCode** [comment]
According to pacman, the libformw library is part of ncurses. ncurses appears to be wrapped. So what's missing?

I had a passing thought that the w might stand for "Wayland" (other libs loaded by this program include X11, so that might be an issue…?) but then I remembered that ncurses is for the terminal, so I'm hoping that's not it.

**Comment by ptitSeb** [comment]
Yes, exactly
libGLEW is not wrapped (and not planning to wrap it as there is a lot of version, it would be cumbersome to wrap).

For libformw.so.6, the ".5" version is wrapped, also libncurses.so.6 is wrapped, but not libformw.so.6... I can add it, copy libformw.so.5, should work fine.

**Comment by ptitSeb** [comment]
Done, I added libformw.so.6 wrapping (copy/paste of libformw.so.5 for now, but that should work fine)

**Comment by ScottFreeCode** [comment]
Thanks!!

Feel free to close this issue out if you prefer, otherwise I'll close it once I confirm I've got this working. (I have a good lead on how to have pacman use an alternative config to install packages for another architecture into a sandboxed location, so, I should be able to install the x64 version of GLEW; I only need to be wait on the AUR package repository getting the latest version of box64.)

**Comment by ptitSeb** [comment]
I'll wait until you confirm it works.

**Comment by ScottFreeCode** [comment]
Turns out that the AUR package box64-git, although it lists its version as 0.2.2, actually pulls down the latest main branch commit. And the fix works!

Thanks again!
