### ISSUE TITLE
SteamVr not running

### ISSUE THREAD

**Issue by Abhinav0002** [ptitSeb/box64#957]
I am running Steam on Debian 12 - ARM Linux using Box64
Encountering an issue on running SteamVR:

SteamVR setup is incomplete, some features might be missing. See /tmp/SteamVRLauncherSetup.log for details.

on inspection of the logs:

Error: **getcap** is required to complete the SteamVR setup.

**Comment by ptitSeb** [comment]
I don't have any hardware to test SteamVR.

about that `getcap` requirement, is that some missing wrapped lib symbols or some program missing? If it's getcap the program, just install the aarch64 one and it will be executed.

I'll probably needs logs to understand what is going on here.

**Comment by Abhinav0002** [comment]
Also is there any way that an application running on box64 can access a USB camera when connected to my host system.

**Comment by ptitSeb** [comment]
apps running with box64 can use libusb, so they should be able to access usb port yes.

**Comment by ptitSeb** [comment]
Use `BOX64_DLSYM_ERROR=1` and see if there are some  missing dlsym function.

**Comment by Abhinav0002** [comment]
Getting these lines:

4167|Call to dlsym(0xb, "XF86VidModeSwitchToMode")(nil)
Call to dlsym(libXss.so.1, "XF86VidModeSwitchToMode") Symbol not found


4167|Call to dlsym(0x5, "_XcursorImageLoadCursor")(nil)
Call to dlsym(libX11.so.6, "_XcursorImageLoadCursor") Symbol not found


Similar to these getting many more

**Comment by Abhinav0002** [comment]
Sure, any other issues ?

**Comment by ptitSeb** [comment]
Did you see some other Symbol not found or some issue to load some libs?

**Comment by Abhinav0002** [comment]
None whatsoever,  any idea if I can add a specific library to box64 libs ?

**Comment by ptitSeb** [comment]
> None whatsoever, any idea if I can add a specific library to box64 libs ?

I'm not sure what do you mean with that.
But if the program doesn't complain about any missing library, and if no library are not found on `dlopen()` calls, there is nothing to add.

**Comment by Abhinav0002** [comment]
The isse that I am facing right now with this is that box64 is not able to load a librealsense.so file

In logs when I checked, the error was: 

Error loading needed lib librealsense2.so
Warning: Cannot dlopen("librealsense2.so/0x550c5590",101)

> I ran a build of Unity that uses a RealSense D435i but on running it via box64, it is not accessing the realsense, any fixes for it ?

**Comment by ptitSeb** [comment]
Ah ok. then, it's like for native program: libs will be serched in `LD_LIBRARY_PATH` and a few system path. Box64 will also looks at the binary folder and in `BOX64_LD_LIBRARY_PATH`.

So look for this lib and make sure it's referenced in the `LD_LIBRARY_PATH`. But assuming this is running from Steam, the `LD_LIBRARY_PATH` should already be setup correctly, unless you are running frm command line directly.

**Comment by Abhinav0002** [comment]
> Ah ok. then, it's like for native program: libs will be serched in `LD_LIBRARY_PATH` and a few system path. Box64 will also looks at the binary folder and in `BOX64_LD_LIBRARY_PATH`.
> 
> So look for this lib and make sure it's referenced in the `LD_LIBRARY_PATH`. But assuming this is running from Steam, the `LD_LIBRARY_PATH` should already be setup correctly, unless you are running frm command line directly.

Right now I am not configuring Steam but running an x86_64 Unity app on ARM Linux using BOX64

**Comment by ptitSeb** [comment]
> > Ah ok. then, it's like for native program: libs will be serched in `LD_LIBRARY_PATH` and a few system path. Box64 will also looks at the binary folder and in `BOX64_LD_LIBRARY_PATH`.
> > So look for this lib and make sure it's referenced in the `LD_LIBRARY_PATH`. But assuming this is running from Steam, the `LD_LIBRARY_PATH` should already be setup correctly, unless you are running frm command line directly.
> 
> Right now I am not configuring Steam but running an x86_64 Unity app on ARM Linux using BOX64

Well, it would be the same on native x86_64: it would not work because the libs would not be found. You need to setup `LD_LIBRARY_PATH` env. var. as Steam do, to get all the needed libs.

**Comment by Abhinav0002** [comment]
Any way we can optimize an app  running on box64 with DYNAREC off as with it on, app is not running

**Comment by ptitSeb** [comment]
> Any way we can optimize an app running on box64 with DYNAREC off as with it on, app is not running

Not really. Best way is to fix Dynarec, as it should work the same as the interpreter.
