### ISSUE TITLE
Zoom Problems

### ISSUE THREAD

**Issue by BusinessKid** [ptitSeb/box64#960]
This is not a code issue, but a more far reaching one. The ram element is mainly bizarre QT libs that you have to emulate.

I have box64 for running Zoom-x86_64. The size is increasing exponentially.  The ram element is mainly bizarre QT libs that you have to emulate. So you are going to have to be more economic with memory. Let me give you some versions and figures 
Zoom-5.9.6 took 55MB of disk space. Then Zoom set a threshold at 5.10.3, and I had to update.
Zoom-5.10.7 took 120MB of space. I got this running by installing a 2GB swap file. Startup time was 2 full minutes until things appeared. It ran on the 4GB ram & most of the 2GB of swap with all 4 cores working hard.

Now Zoom have set a new threshold of 5.14.? I downloaded for my pc and got 5.15.10. That takes up 654MB of disk space :-O!

**Comment by ptitSeb** [comment]
Is that with current box64? Zoom takes like 5GB of RAM to run?

**Comment by BusinessKid** [comment]
Box64 is from about 6 months back. The problem isn't box64 as much as Zoom.  They are adding features that nobody I know uses, and extra bloat almost beyond belief. Linux now is in step with windows releases. 

So box64 has to prepare to emulate a much bigger feature set, and that's what's eating the ram  My current zoom on the RazPi doesn't work with a 1GB swap. M y 2G of swap is actually 2GB, but my 4G of ram is only 3.7GB:-(. It's the 1000 / 1024 thing that all ram suppliers do. And kernel caches aren't counted in free.

Now with Zoom-5.10.7, Archive size = 120MB and start time=120 seconds before you know it hasn't crashed. When you multiply that archive size by 4½, what's the ram usage and startup time going to be like? And then will I be running out of swap 100% of the time? It's not going to be practical.

The 8 core, 8GB sbcs based on the RK3588 might do it. The Orange Pi & Rock Pi are two I know of. But unless you can find some way of
1. Only emulating libraries that are being used, or
2. Minimizing ram usage in some way I haven't thought of  

Boxes like my 4G RazPi won't be able to run Zoom. 

I'm not updating to Zoom-5.14.6 or whatever their min spec is. Because box64 is a very memory-intensive process for my little sbc.

**Comment by BusinessKid** [comment]
I have Zoom recent version (5.16.x) running. It's using 4G of ram, and swap (4G),  and struggling in an "Out of resources" mode. I'd have a BSoD in windows. I'll try upping the swap tomorrow, but it's academic really. The disk usage of the Zoom installation indicates the problem
5.9.x=55MB
5.10.7 = 120MB 
5.16.10=654MB!!
And most of that is for uncommonly used features, whiteboards, texts, fancy share options

**Comment by ptitSeb** [comment]
Note that, lately on box64, I have added a "SAVE_MEM" build configure option, enabled with PI and RK3399 build, that might save a bit of memory. Not sure if you tried with/without it to see if it makes a difference, but it migh help a bit...

**Comment by BusinessKid** [comment]
That "SAVE_MEM" feature looks promising. My box64 version is old.  I've only just updated my RazPi, because the extra slarm64 programs in the repo are compiled with slarm64-current, and my glibc was too old, so all the repo programs would puke. It was using ≥250% CPU in umpteen processes at a minimum

Zoom-5.15.10 uses the 4GB of ram and 4.5GB of swap, which would probably increase in a meeting. Zoom keep incrementing the required version - I now require version 5-12.2 :-(. As zoom runs, the Pi backs off the ram and increases the swap, presumably for caching. That means the latest version will not run in 8G of ram alone.

I'm going to close this issue. I haven't a camera or Mic on my RazPi, but it's interesting for you. I have tablets, & my mobile which can do zoom easily. I'll give up on the RazPi. The problem is Zoom's extra (unneccessary) features are very rarely used, but are emulated. So they're terribly expensive on  ram, which is wasted. What's probably needed is a feature to emulate a lib only when it's called. I don't know if there's source available for all the nutty Qt libs they use. If so, they could be compiled for aarch64.  That would make life easier.
