### ISSUE TITLE
SDL_VIDEODRIVER=wayland not working on Bookworm Raspberry (was ut2004 wayland crash)

### ISSUE THREAD

**Issue by Roburetto** [ptitSeb/box64#961]
A standard ut2004 installation seems to be working fine with both x11 and wayland.

Once you start adding maps, textures and stuff a difference nevertheless shows up.

While x11 works, wayland is now failing (full log attached):

```
Using native(wrapped) openal.so
4646|SIGSEGV @0x7fad81e640 (???(0x7fad81e640)) (x64pc=0xaedc6f//home/pi/games/ut2004/System/ut2004-bin-linux-amd64:"/home/pi/games/ut2004/System/ut2004-bin-linux-amd64/_Z11appFromAnsiPKcPwi + 65", rsp=0x1007fb990, stack=0x100000000:0x100800000 own=(nil) fp=0x62d08a40), for accessing 0x200000 (code=1/prot=0), db=0x7fad851fc0(0x7fad81e5d8:0x7fad81e720/0xaedc51:0xaedca0//home/pi/games/ut2004/System/ut2004-bin-linux-amd64/_Z11appFromAnsiPKcPwi + 65:clean, hash:f27d686e/f27d686e) handler=0xb29b30
RAX:0x0000000001697f80 RCX:0x0000000000000000 RDX:0x0000000000000000 RBX:0x0000000000000400 
RSP:0x00000001007fb990 RBP:0x0000000000000000 RSI:0x0000000001697f80 RDI:0x0000000000000006 
 R8:0x00000000000003ff  R9:0x0000000000000012 R10:0x0000000000000097 R11:0x0000000000630585 
R12:0x0000000000200000 R13:0x0000000000000258 R14:0x0000000000000001 R15:0x0000000063fbcbf0 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053 
RSP-0x20:0x000000005f9eaec0 RSP-0x18:0x000000005f090b60 RSP-0x10:0x0000000000000000 RSP-0x08:0x0000000000aedca5
RSP+0x00:0x0000000062d08a40 RSP+0x08:0x0000000000000320 RSP+0x10:0x0000000000000004 RSP+0x18:0x0000000062d08a40
Signal: SIGSEGV [segmentation fault]
Aborting.

AL lib: (EE) alc_cleanup: 2 devices not closed
```
[box64_log_wayland_crash.txt](https://github.com/ptitSeb/box64/files/12500831/box64_log_wayland_crash.txt)

**Comment by Roburetto** [comment]
Today I came to the conclusion that by removing "export GALLIUM_HUD=fps" the problem does not occur.

pi@pi:~/games/ut2004/System $ export BOX64_PREFER_WRAPPED=1
pi@pi:~/games/ut2004/System $ export SDL_VIDEODRIVER=wayland
pi@pi:~/games/ut2004/System $ export GALLIUM_HUD=fps
pi@pi:~/games/ut2004/System $ ./ut2004-bin-linux-amd64

**Comment by ptitSeb** [comment]
Oh, ok, simple enough...
You can try mangohud instead maybe, if you really want fps counters.

**Comment by Roburetto** [comment]
Here we go again. On most recent Raspberry Pi OS (Debian Bookworm based) SDL_VIDEODRIVER=wayland does not work. Complains about no available video device...

**Comment by ptitSeb** [comment]
Why is that a box64 issue? Arne't you using a wrapped SDL here?

**Comment by Roburetto** [comment]
Bear with my ignorance. I was under the belief that BOX64_PREFER_WRAPPED=1 meant BOX64 would use it's own supplied SDL...

**Comment by ptitSeb** [comment]
Box doesn't supply any libs. They can be "wrapped": so coming from you system directly, or "emulated", and that would be an x86_64 version, most probably coming from the game.

With `BOX64_PREFER_WRAPPED`, libs from your system will be used if possible. So the SDL comes from your system (unless it's not installed and it will fallback to emulated if present). Look at the initialisation of the game to see if SDL is wrapped or emulated.

**Comment by Roburetto** [comment]
Thanks a lot for your feedback.  If I figured this more accurately:
- "wrapping" roughly means running the lib in the "native, ARM world" (implying arm64 SDL 1.2 support for wayland should be present)
- "emulation" roughly means running the lib in it's original Architecture (implying the presence of the amd64 SDL1.2 lib either supplied by the game or by adding the amd64 architecture lib :amd64)

As for the first, I have sdl12-compat ("it provides a binary and source compatible API for programs written against SDL 1.2, but it uses SDL 2.0 behind the scenes"). This might be the problem with wayland...

I will try do do some some further testing.

**Comment by ptitSeb** [comment]
Yes, exactly.

**Comment by Roburetto** [comment]
Ok. I have sorted it.

It turned out I add both  libsdl1.2-compat (SDL 1.2 using 2.0 - location: /usr/lib/aarch64-linux-gnu/sdl12-compat/libSDL-1.2.so.0) and libsdl1.2debian (installed as a dependency from box86 from PiApps - location: /usr/lib/aarch64-linux-gnu/libSDL-1.2.so.0).

 libsdl1.2-compat -> does support wayland
 libsdl1.2debian -> does not support wayland

By default libsdl1.2debian is picked, so prior to running box64 you need to tell you prefer libsdl1.2-compat: 
export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/sdl12-compat

A few sidenotes:
- export GALLIUM_HUD=fps+cpu is now working with Wayland (the first issue I talked about when starting this thread)
- FPS wise, I still do not see performance improves in wayland over x11
- in Bookworm there are now two alternative ways to run SDL 1.2 using SDL 2 (two implementations of libsdl1.2-compat) :
      - libsdl1.2-compat
      - libsdl1.2-compat-shim (this is a full replacement and seems to be the way forward)
