### ISSUE TITLE
no wrapper for vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR

### ISSUE THREAD

**Issue by wwlwwlwwlwwl** [ptitSeb/box64#963]
on latest box64 and dxvk on turnip adreno 740
run cubemap, show these warning, and nothing happending.
```
Warning, no wrapper for vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR
```

**Comment by ptitSeb** [comment]
Ok, I have added the extension (on box86 too, just in case)

**Comment by ptitSeb** [comment]
Is it working now? can the ticket be closed?

**Comment by wwlwwlwwlwwl** [comment]
now is work now! thanks
