### ISSUE TITLE
Virtual machine detection in need for speed the run 

### ISSUE THREAD

**Issue by WILLIAM20302** [ptitSeb/box64#966]
I cannot play the game and others like genshin impact and CSGO

**Comment by shenmo7192** [comment]
Newest build fix this problem
https://cdn.d.store.deepinos.org.cn/aarch64-store/depends/box8664/box64_0.2.5_plus_20230902_arm64.deb

**Comment by ptitSeb** [comment]
@WILLIAM20302 is the issue still present with latest box64?

**Comment by WILLIAM20302** [comment]
> Can you provide more information? What are the specs of the device you're trying to run this on, and do you have any logs you can provide?



> Can you provide more information? What are the specs of the device you're trying to run this on, and do you have any logs you can provide?

Motorola Moto g71
Snapdragon 695 6gb ram Android 12

**Comment by LukeShortCloud** [comment]
Closing as resolved.
