### ISSUE TITLE
 [32BITS] F2 AF unimplemented in dynarec

### ISSUE THREAD

**Issue by AndreRH** [ptitSeb/box64#975]
Hi,

Found with Project Hangover running VARA.exe.
0024:err:box64dynarec:FillBlock64 Warning, null-sized dynarec block (00000000732C7FCE)

offending address in msvbvm60.dll:
732c7fce: f2 af                        	repne		scasl	%es:(%edi), %eax

**Comment by ptitSeb** [comment]
Ok, I have aded the opcode to the arm64 dynarec.

**Comment by AndreRH** [comment]
Thanks!
