### ISSUE TITLE
Ark Server will not start

### ISSUE THREAD

**Issue by KilianBogus** [ptitSeb/box64#976]
Hello, my Ark server will not start
[Log.txt](https://github.com/ptitSeb/box64/files/12589107/Log.txt)

**Comment by ptitSeb** [comment]
That doesn't looks like a box64 issue.

It looks for steam and it's not running, and it tries to use 127.0.0.1:7777 and it's not possible.

**Comment by KilianBogus** [comment]
Why is this not possible?

**Comment by ptitSeb** [comment]
I don't know. It's a system issue. You would have the same issue if the app was native and run without box64.

**Comment by ptitSeb** [comment]
No idea. You should follow tuto about Ark Server.

**Comment by LukeShortCloud** [comment]
Since this is not a Box64 issue, we're going to close this.
