### ISSUE TITLE
android build segmentation fault

### ISSUE THREAD

**Issue by szllzs** [ptitSeb/box64#979]
![Screenshot_2023-09-15-07-31-37-20_84d3000e3f4017145260f7618db1d683](https://github.com/ptitSeb/box64/assets/13085785/bd55cc36-d42c-4e76-a466-70b08780aaed)

termux arm64 run box64 stable reproduction

**Comment by szllzs** [comment]
android 12 
box64 master

**Comment by ptitSeb** [comment]
Ok, thanks for the backtrace. I'll think of something to workaround the issue.
