### ISSUE TITLE
something up with glibc

### ISSUE THREAD

**Issue by Jacobw1oo** [ptitSeb/box64#980]
command: box64_log=2 box86 steam,  
23622|0x101846a08: Calling sigprocmask (/lib/aarch64-linux-gnu/libc.so.6)(0x2, 0x10213E260, 0x0, ...) => return 0x0

 ...  =>PltResolver: Addr=0x35ed03a0, Slot=189 Return=0x10183115e: elf is /usr/local/bin/bash_AMD64 (VerSym=0x1d7ea)
            Apply Global R_X86_64_JUMP_SLOT 0x101924600 with sym=exit(ver 2: exit@GLIBC_2.2.5) (0x10182ec06 -> 0xb0780 / box64) return 0x0

23622|0x10183115e: Calling my_exit (/usr/local/bin/bash_AMD64)(0x1, 0x10213E260, 0x0, ...)

**Comment by ptitSeb** [comment]
I don't see anything wrong here. `bash_AMD64` is just quiting.

Side note: I don't think renaming x86_64 bash to `bash_AMD64` is a good idea. I should keep it's original name `bash` (just put it in `/usr/lib/x86_64-linux-gnu` maybe if you want.
