### ISSUE TITLE
6343|0x10224c04a: Unimplemented Opcode (00 00 74 08) 65 8E 24 25 38 03 00 00 F7 C2 48 00 00 00 75

### ISSUE THREAD

**Issue by theofficialgman** [ptitSeb/box64#982]
using wine-8.16 with the new WOW64 mode now I get `6343|0x10224c04a: Unimplemented Opcode (00 00 74 08) 65 8E 24 25 38 03 00 00 F7 C2 48 00 00 00 75` when running an application that previously worked.

**Comment by ptitSeb** [comment]
Ok, I have added to opcode.
