### ISSUE TITLE
0.2.0->0.2.4 breaks glmark2

### ISSUE THREAD

**Issue by iv-m** [ptitSeb/box64#984]
I'm trying to test my freshly build box64 0.2.4 on riscv64 with glmark2, and it fails:

```
Dynarec for RISC-V With extension: I M A F D C PageSize:4096 Running on Unknown CPU with 4 Cores
Params database has 25 entries
Box64 with Dynarec v0.2.4  built on Aug 21 2023 13:46:23
BOX64_LD_LIBRARY_PATH: /home/user/hsh-x86_64/chroot/usr/lib64/
Using default BOX64_PATH: ./:bin/
Counted 65 Env var
Looking for /home/user/tests/glmark2/glmark2
argv[1]="--fullscreen"
argv[2]="--annotate"
Rename process to "glmark2"
Using emulated /home/user/hsh-x86_64/chroot/usr/lib64/libjpeg.so.62
Using native(wrapped) libpng16.so.16
Using native(wrapped) libX11.so.6
Using emulated /home/user/hsh-x86_64/chroot/usr/lib64/libstdc++.so.6
Using native(wrapped) libm.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Warning: Global Symbol _ZN9__gnu_cxx21zoneinfo_dir_overrideEv not found, cannot apply R_X86_64_GLOB_DAT @0x102402250 ((nil)) in /home/user/hsh-x86_64/chroot/usr/lib64/libstdc++.so.6
Error: PltResolver: Symbol dlopen(ver 14: dlopen@GLIBC_2.34) not found, cannot apply R_X86_64_JUMP_SLOT 0x101889d60 (0x101809716) in /home/user/tests/glmark2/glmark2
```

With older box64 0.2.0, the same command and binaries  work just fine.

**Comment by ksco** [comment]
Does `box64 ./glmark2 --version` works?

**Comment by ptitSeb** [comment]
It's probably some dependancies in a wrapped lib that is missing `libdl`, or I should just force `libdl` to be used all the time when `libc` is used...

**Comment by iv-m** [comment]
> It's probably some dependancies in a wrapped lib that is missing `libdl`, or I should just force `libdl` to be used all the time when `libc` is used...

Well, probably... 

Since glibc 2.34 (AFAIR), `libdl` is just a stub and all the useful things like `dlopen` are in the libc itself:

```
# readelf -s /lib64/libc.so.6 | grep dlopen
   743: 000000000006c1c2   114 FUNC    GLOBAL DEFAULT   13 dlopen@GLIBC_2.27
   745: 000000000006c1c2   114 FUNC    GLOBAL DEFAULT   13 dlopen@@GLIBC_2.34
```

So, recently build software does not have to link with libdl and probably does not -- especially when build with `--as-needed`. The `glmark` binary I'm trying does not have `libdl` as `needed` library.

**Comment by iv-m** [comment]
> Does `box64 ./glmark2 --version` works?

`box64 ./glmark2 --help` works.

**Comment by ptitSeb** [comment]
I pushed a fix, it should work fine now.

**Comment by LukeShortCloud** [comment]
Closing as resolved.
