### ISSUE TITLE
[32 BIT] Issues with GTA IV and Max Payne 3 when using the dynarec and Wine with WoW64

### ISSUE THREAD

**Issue by Grima04** [ptitSeb/box64#985]
I have tested Grand Theft Auto IV and Max Payne 3 (both are 32 bit games) on my Nvidia Jetson Xavier NX using Wine 8.16 staging (from Kron4ek) with WoW64 enabled.
When running both games with the dynamic recompiler of box64 enabled, there are issues which make both games unplayable. 
Grand Theft Auto IV gets stuck at the disclaimer screen and doesn't progress any further.
Max Payne 3 gets to the main menu but progressing any further is impossible, since either the menu buttons are invisible or the entire menu screen just appears black while the game doesn't react to any keyboard or mouse input. Furthermore, there are also some audio glitches causing random garbled sound output or loud beeping noises.
When using BOX64_DYNAREC=0 to disable the dynarec, both games work as expected and get ingame without any issues, although performance levels are extremely low due to the much slower interpreter.
I have attached some screenshots below to show what it looks like.

![Screenshot from 2023-09-22 01-34-45](https://github.com/ptitSeb/box64/assets/22496380/23550dbf-f5be-4f8d-8658-599a652db992)
GTA IV gets stuck here when using the dynarec.

![Screenshot from 2023-09-22 01-33-07](https://github.com/ptitSeb/box64/assets/22496380/c6c1b0eb-b4ff-4329-8c9b-8b1cbf98c725)
Max Payne 3 at the main menu with dynarec enabled.

![Screenshot from 2023-09-21 16-44-55](https://github.com/ptitSeb/box64/assets/22496380/4436314f-f438-4b10-94ff-280700649190)
GTA IV ingame using the interpreter.

![Screenshot from 2023-09-21 19-13-31](https://github.com/ptitSeb/box64/assets/22496380/27c70f88-c46a-4031-867b-4a7745cef5f7)
Max Payne 3 at the main menu using the interpreter.

**Comment by Grima04** [comment]
I have messed around with some box64 environment variables to see if the games need more accurate emulation in some areas.
After trying some dynarec options, I came across the BOX64_DYNAREC_X87DOUBLE variable. When set, both games no longer experience audio issues and get to the menus just fine, so it looks like accurate x87 emulation using double is needed for both GTA IV and Max Payne 3.
There are still issues though, since GTA IV crashes or freezes after the loading screen when using the dynarec.
Max Payne 3 gets stuck on the loading screen and the graphics start to completely freak out after a few seconds (it looks like vertex explosions) and the game remains in this infinite glitched loading screen until it is killed via the terminal.


![Screenshot from 2023-10-01 16-49-41](https://github.com/ptitSeb/box64/assets/22496380/51745398-93a7-45a6-80c1-c5280816ebdf)
When getting to this screen, GTA IV crashes or freezes. Additionally, the DXVK HUD also glitches out on the last frame before the game freezes.


![Screenshot from 2023-10-01 18-15-54](https://github.com/ptitSeb/box64/assets/22496380/8a32d1f0-9394-4a1e-b2ba-aa44577782cb)
![Screenshot from 2023-10-01 18-18-21](https://github.com/ptitSeb/box64/assets/22496380/448a47a1-0798-4590-8394-d7d15b3e6b57)
![Screenshot from 2023-10-01 18-15-28](https://github.com/ptitSeb/box64/assets/22496380/32fdc6f1-ae80-4154-99e0-5cbcc28ae3b1)
This is how the loading screen of Max Payne 3 looks like after it starts glitching out. The DXVK HUD also breaks here as soon as the graphic errors start appearing.

**Comment by Grima04** [comment]
The recent x87 fixes/improvements seem to have resolved the problems that both games were having. GTAIV and Max Payne 3 are now working as expected and BOX64_DYNAREC_X87DOUBLE=1 also doesn't seem to be required anymore, so I think that I can close this issue now.

**Comment by ptitSeb** [comment]
Ahn that's some great news! I don't own those games so cannot test myself.

**Comment by OpomboMORTO** [comment]
@Grima04 qDoes not support alsa I wanted to talk to you, do you happen to have discord or Telegram?
