### ISSUE TITLE
Teamspeak3Client on Pi4 fails to run

### ISSUE THREAD

**Issue by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [ptitSeb/box64#986]
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 27 entries
Box64 with Dynarec v0.2.5 4b6cec84 built on Sep 23 2023 17:27:15
Counted 52 Env var
BOX64 LIB PATH: ./:./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
Looking for ./ts3client_linux_amd64
Rename process to "ts3client_linux_amd64"
Using emulated libquazip.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libm.so.6
Using emulated libQt5Core.so.5
Using emulated libQt5Gui.so.5
Using emulated libQt5Network.so.5
Using emulated libQt5Widgets.so.5
Using emulated libQt5Sql.so.5
Using emulated libQt5WebEngineCore.so.5
Using emulated libQt5WebEngineWidgets.so.5
Using emulated libQt5WebChannel.so.5
Using emulated libQt5WebSockets.so.5
Using emulated libQt5Svg.so.5
Using native(wrapped) libresolv.so.2
Using emulated libc++.so.1
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libgthread-2.0.so.0
Using native(wrapped) libatomic.so.1
Using emulated libunwind.so.1
Using native(wrapped) libGL.so.1
Using emulated libQt5Quick.so.5
Using emulated libQt5QmlModels.so.5
Using emulated libQt5Qml.so.5
Using native(wrapped) libnss3.so
Using native(wrapped) libnssutil3.so
Using native(wrapped) libsmime3.so
Using native(wrapped) libplds4.so
Using native(wrapped) libplc4.so
Using native(wrapped) libnspr4.so
Error loading needed lib libevent-2.1.so.7
Using native(wrapped) libX11.so.6
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXdamage.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXtst.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libexpat.so.1
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libxkbcommon.so.0
Using native(wrapped) libdbus-1.so.3
Using native(wrapped) libpci.so.3
Using native(wrapped) libasound.so.2
Using native(wrapped) libz.so.1
Using native(wrapped) libxml2.so.2
Using native(wrapped) libxslt.so.1
Error loading needed lib liblcms2.so.2
Error loading one of needed lib
Error initializing needed lib libQt5WebEngineCore.so.5
Using emulated libQt5PrintSupport.so.5
Using emulated libQt5QuickWidgets.so.5
Warning: Global Symbol OPENSSL_memory_alloc not found, cannot apply R_X86_64_GLOB_DAT @0x10ada6b90 ((nil)) in libQt5WebEngineCore.so.5
Warning: Global Symbol OPENSSL_memory_free not found, cannot apply R_X86_64_GLOB_DAT @0x10ada6b98 ((nil)) in libQt5WebEngineCore.so.5
Warning: Global Symbol sdallocx not found, cannot apply R_X86_64_GLOB_DAT @0x10ada6ba0 ((nil)) in libQt5WebEngineCore.so.5
Warning: Global Symbol OPENSSL_memory_get_size not found, cannot apply R_X86_64_GLOB_DAT @0x10ada6ba8 ((nil)) in libQt5WebEngineCore.so.5
Error: Symbol cmsDeleteTransform not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada93d0 (0x703c066) in libQt5WebEngineCore.so.5
Error: Symbol cmsOpenProfileFromMem not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada93d8 (0x703c076) in libQt5WebEngineCore.so.5
Error: Symbol cmsCreate_sRGBProfile not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada93e0 (0x703c086) in libQt5WebEngineCore.so.5
Error: Symbol cmsGetColorSpace not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada93e8 (0x703c096) in libQt5WebEngineCore.so.5
Error: Symbol cmsChannelsOf not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada93f0 (0x703c0a6) in libQt5WebEngineCore.so.5
Error: Symbol cmsCreateTransform not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada93f8 (0x703c0b6) in libQt5WebEngineCore.so.5
Error: Symbol cmsCloseProfile not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada9400 (0x703c0c6) in libQt5WebEngineCore.so.5
Error: Symbol cmsDoTransform not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada9408 (0x703c0d6) in libQt5WebEngineCore.so.5
Error: Symbol event_del not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada96c8 (0x703c656) in libQt5WebEngineCore.so.5
Error: Symbol event_base_new not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada96d0 (0x703c666) in libQt5WebEngineCore.so.5
Error: Symbol event_set not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada96d8 (0x703c676) in libQt5WebEngineCore.so.5
Error: Symbol event_base_set not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada96e0 (0x703c686) in libQt5WebEngineCore.so.5
Error: Symbol event_add not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada96e8 (0x703c696) in libQt5WebEngineCore.so.5
Error: Symbol event_base_free not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada96f0 (0x703c6a6) in libQt5WebEngineCore.so.5
Error: Symbol event_get_fd not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada96f8 (0x703c6b6) in libQt5WebEngineCore.so.5
Error: Symbol event_base_loop not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada9700 (0x703c6c6) in libQt5WebEngineCore.so.5
Error: Symbol event_base_loopbreak not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada9708 (0x703c6d6) in libQt5WebEngineCore.so.5
Warning: Weak Symbol OPENSSL_memory_alloc not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada99f8 (0x703ccb6)
Warning: Weak Symbol OPENSSL_memory_free not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada9a00 (0x703ccc6)
Warning: Weak Symbol sdallocx not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada9a08 (0x703ccd6)
Warning: Weak Symbol OPENSSL_memory_get_size not found, cannot apply R_X86_64_JUMP_SLOT @0x10ada9a10 (0x703cce6)
Error: relocating Plt symbols in elf libQt5WebEngineCore.so.5
Error initializing needed lib libQt5WebEngineCore.so.5
Error loading one of needed lib
Error initializing needed lib libQt5WebEngineWidgets.so.5
Error loading one of needed lib
Error: loading needed libs in elf /home/r/Downloads/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64

**Comment by ptitSeb** [comment]
Ah, new missing symbols.
Is that was the latest version of the client?

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
Yessir straight from the source typa shid, it canhas to be was the LATEST!

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
HAVE YOU MADEINGTON THE DOING OF DA SYMBOLS!?!?!! ME SIR IS IN THE RUSHINGTON OF.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
has you been adderington of the symbols?

**Comment by ptitSeb** [comment]
No, not yet. I'll try this week.

**Comment by ptitSeb** [comment]
Ok, so it was 2 library that was not wrapped. I wrapped them and now ts3 is starting (you might need to install libxcb-xinerama0 )
It seems to crash when exiting, but that's something else.

**Comment by LukeShortCloud** [comment]
@zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z The original functions that needed to be wrapped have been wrapped. If you're still running into more errors with the latest versions of Box64 and Teamspeak, please feel free to open a new GitHub Issue. Closing as resolved.
