### ISSUE TITLE
box64 on m2 mac running asahi ubuntu pagesize error

### ISSUE THREAD

**Issue by thescribbler479** [ptitSeb/box64#990]
i recently installed asahi ubuntu, a fork of asahi linux that runs ubuntu rather than arch, onto my m2 macbook air. i installed box64 through pi-apps and attempted to run an x86-64 .deb, but was given an error i havent seen before. its not an issue with this deb because i tried box64 on other debs and got the same error. this was the output of the console after trying to run the deb:

Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:16384 Running on Blizzard-M2 Avalanche-M2 with 8 Cores
Params database has 27 entries
Box64 with Dynarec v0.2.5 bf6c6498 built on Sep 24 2023 06:16:36
Error: PageSize configuration is wrong: configured with 4096, but got 16384
[the output ends there]

if anyone knows what this means or how to fix it i would really appreciate it, as no one else seems to have this issue. thanks.

edit: i also tried installing box64 through the premade deb method from the compiling readme, and was given the same error.

**Comment by MonsieurRoZz** [comment]
Asahi switched to 16k page size in August.

getconf PAGE_SIZE

**Comment by ptitSeb** [comment]
You need to build box64 with 16k Page. Use the "M1" profile and build from scratch or use `ccmake` to alter configuration.

**Comment by theofficialgman** [comment]
> asahi ubuntu

since when is there an asahi ubuntu?

@thescribbler479  can you please report the output of 
```bash
~/pi-apps/api get_device_info
echo "CHIP: $CHIP"
echo "model: $model"
```

this output is necessary to do device detection.
idk what to expect for the M2 devices since the public asahi devicetree documentation doesn't list its model number

**Comment by theofficialgman** [comment]
@ptitSeb slightly unrelated to the current convo but box86 does not have such pagesize config options.
are binary builds of box86 compatible with multiple pagesizes or does box86 only work on 4K pages and is expected to not work on Asahi with 16K pages?

**Comment by ksco** [comment]
Box86 needs to run in a 32-bit environment, and Apple Silicon dropped 32-bit support since A11.

**Comment by theofficialgman** [comment]
> Box86 needs to run in a 32-bit environment, and Apple Silicon dropped 32-bit support since A11.

Gotcha so it won't work on apple silicon macs regardless. But that doesn't answer the question of box86 pagesize support.

**Comment by theofficialgman** [comment]
@ptitSeb you should be able to close. I added a generic arm 16K pagesize build to pi-apps automated apt repo builder and associated install script.
CC: @thescribbler479 

also thanks to @MonsieurRz who linked how to check pagesize from userspace.

**Comment by ptitSeb** [comment]
Ah, nice! thnaks :)
